(function () {
  "use strict";

  const Shared=window.WeishanCommerceShadowContractValidation,Recommendation=window.WeishanRecommendationPackage,RecommendationValidation=window.WeishanRecommendationValidation,Types=window.WeishanRecommendationEngineTypes;
  function fail(code){Shared.fail(code);}function text(value){return Shared.text(value);}function exact(value,keys){return Shared.exact(value,keys);}function enumValue(values,value){return values.indexOf(value)>=0;}
  function request(input){return Recommendation.createRecommendationRequest(input);}function candidate(input){return Recommendation.validateRecommendationCandidate(input);}function risk(input){return Recommendation.validateRecommendationRisk(input);}function result(input){return Recommendation.validateRecommendationResult(input);}
  function reason(input){const value=Shared.safeClone(input),keys=Types.INTERFACES.recommendationEngineReason.required;if(!exact(value,keys)||!text(value.reasonId)||!text(value.candidateId)||!enumValue(Types.ENUMS.REASON_TYPE,value.reasonType)||!enumValue(Recommendation.PACKAGE.enums.EVIDENCE_TYPE,value.evidenceType)||!text(value.summary)||!Array.isArray(value.limitations)||!enumValue(Recommendation.PACKAGE.enums.CONFIDENCE,value.confidence))fail("invalid_recommendation_engine_reason");return Shared.freeze(value);}
  function dependencies(input){if(!input||typeof input.clock!=="function"||typeof input.idGenerator!=="function")fail("invalid_recommendation_engine_dependencies");return input;}
  function envelope(input){const value=Shared.safeClone(input),keys=Types.INTERFACES.recommendationEngineResultEnvelope.required;if(!exact(value,keys)||value.schemaVersion!==Types.CONTRACT_VERSION||!text(value.engineResultId)||!text(value.requestId)||!enumValue(Types.ENUMS.ENGINE_STATUS,value.engineStatus)||!Array.isArray(value.analysisCategories)||!value.analysisCategories.every(function(item){return enumValue(Types.ENUMS.ANALYSIS_CATEGORY,item);})||!Array.isArray(value.reasons)||!Array.isArray(value.risks)||!value.evidenceSummary||typeof value.evidenceSummary!=="object"||!value.comparisonSummary||typeof value.comparisonSummary!=="object"||!Array.isArray(value.limitations)||!Array.isArray(value.warnings)||value.userDecisionRequired!==true||value.executed!==false||value.productionAffected!==false||!text(value.createdAt))fail("invalid_recommendation_engine_envelope");value.recommendationResult=result(value.recommendationResult);if(value.recommendationResult.requestId!==value.requestId)fail("recommendation_result_request_mismatch");value.reasons=value.reasons.map(reason);value.risks=value.risks.map(risk);return Shared.freeze(value);}
  function compatibility(version){return Shared.compatibility(version,Types.CONTRACT_VERSION);}
  window.WeishanRecommendationEngineValidation=Object.freeze({fail,text,exact,request,candidate,risk,result,reason,dependencies,envelope,compatibility,freeze:Shared.freeze,safeClone:Shared.safeClone});
})();
