(function () {
  "use strict";

  const V=window.WeishanPriceNormalizationValidation,Types=window.WeishanPriceNormalizationTypes;
  function add(values,value){if(values.indexOf(value)<0)values.push(value);}
  function authorityLevel(state){return {REFERENCE:"REFERENCE_ONLY",ESTIMATED:"ESTIMATED_ONLY",CACHED:"CACHED_QUOTE",LIVE_QUOTE:"TRACEABLE_QUOTE",STALE_QUOTE:"TRACEABLE_QUOTE",FINAL_CHECKOUT:"EXTERNAL_FINAL_CHECKOUT",UNKNOWN:"UNKNOWN"}[state];}
  function freshness(authority){if(authority.priceState==="STALE_QUOTE")return "STALE";if(authority.priceState==="CACHED")return "CACHED";if(authority.priceState==="LIVE_QUOTE")return "CURRENT";return authority.timestamp.freshness==="KNOWN"?"CURRENT":"UNKNOWN";}
  function normalizePrice(authorityInput,dependencies){const authority=V.authority(authorityInput),deps=V.dependencies(dependencies),unknown=["AMOUNT","SHIPPING","BAGGAGE"],estimated=[],limitations=["NO_AMOUNT_VALUE_IN_PRICE_AUTHORITY","NO_CURRENCY_CONVERSION"],warnings=[];if(authority.evidence.taxStatus==="UNKNOWN")add(unknown,"TAX");if(authority.evidence.feeStatus==="UNKNOWN")add(unknown,"FEE");if(authority.priceState==="ESTIMATED")estimated.push("AMOUNT");if(authority.priceState==="STALE_QUOTE")limitations.push("QUOTE_FRESHNESS_STALE");if(authority.priceState==="FINAL_CHECKOUT")limitations.push("EXTERNAL_PLATFORM_REMAINS_FINAL_AUTHORITY");if(authority.currency!=="UNKNOWN")warnings.push("CROSS_CURRENCY_NOT_COMPARABLE_WITHOUT_RATE_EVIDENCE");if(authority.evidence.traceability!=="TRACEABLE")limitations.push("EVIDENCE_NOT_FULLY_TRACEABLE");const readiness=authority.priceState==="UNKNOWN"?"BLOCKED":authority.priceState==="STALE_QUOTE"?"NOT_READY":"PARTIAL",normalizationId=deps.idGenerator(),createdAt=deps.clock();if(!V.text(normalizationId)||!V.text(createdAt))V.fail("invalid_price_normalization_identity");return V.normalizedPrice({schemaVersion:Types.CONTRACT_VERSION,normalizationId:normalizationId,authorityId:authority.authorityId,domain:"UNKNOWN",currency:authority.currency,amountState:authority.priceState==="ESTIMATED"?"ESTIMATED":"UNKNOWN",taxState:authority.evidence.taxStatus,feeState:authority.evidence.feeStatus,shippingState:"UNKNOWN",baggageState:"UNKNOWN",knownComponents:[],unknownComponents:unknown,estimatedComponents:estimated,authorityLevel:authorityLevel(authority.priceState),confidence:authority.confidence,freshnessState:freshness(authority),limitations:limitations,warnings:warnings,comparisonReadiness:readiness,createdAt:createdAt,executed:false,productionAffected:false});}
  window.WeishanPriceNormalizationCore=Object.freeze({normalizePrice});
})();
