(function(){
  const plans = [
  {
    "plan_id": "CN_PERSONAL_20GB",
    "plan_name": "中国区个人云 20GB",
    "plan_type": "personal_cloud",
    "region": "CN",
    "storage_quota_gb": 20,
    "member_limit": 0,
    "monthly_price": 15,
    "yearly_price": 128,
    "currency": "CNY",
    "is_active": true,
    "sort_order": 10,
    "description": "个人入门云存储套餐"
  },
  {
    "plan_id": "CN_PERSONAL_300GB",
    "plan_name": "中国区个人云 300GB",
    "plan_type": "personal_cloud",
    "region": "CN",
    "storage_quota_gb": 300,
    "member_limit": 0,
    "monthly_price": 39,
    "yearly_price": 399,
    "currency": "CNY",
    "is_active": true,
    "sort_order": 20,
    "description": "适合日常办公、多设备同步、资料备份"
  },
  {
    "plan_id": "CN_PERSONAL_1TB",
    "plan_name": "中国区个人云 1TB",
    "plan_type": "personal_cloud",
    "region": "CN",
    "storage_quota_gb": 1024,
    "member_limit": 0,
    "monthly_price": 99,
    "yearly_price": 999,
    "currency": "CNY",
    "is_active": true,
    "sort_order": 30,
    "description": "适合重度个人用户和长期文件整理"
  },
  {
    "plan_id": "CN_PERSONAL_5TB",
    "plan_name": "中国区个人云 5TB",
    "plan_type": "personal_cloud",
    "region": "CN",
    "storage_quota_gb": 5120,
    "member_limit": 0,
    "monthly_price": 399,
    "yearly_price": 3999,
    "currency": "CNY",
    "is_active": true,
    "sort_order": 40,
    "description": "适合大容量资料、设计素材、项目文件"
  },
  {
    "plan_id": "CN_PERSONAL_10TB",
    "plan_name": "中国区个人云 10TB",
    "plan_type": "personal_cloud",
    "region": "CN",
    "storage_quota_gb": 10240,
    "member_limit": 0,
    "monthly_price": 699,
    "yearly_price": 6999,
    "currency": "CNY",
    "is_active": true,
    "sort_order": 50,
    "description": "适合企业级个人用户或大容量长期存储"
  },
  {
    "plan_id": "GLOBAL_PERSONAL_20GB",
    "plan_name": "海外个人云 20GB",
    "plan_type": "personal_cloud",
    "region": "GLOBAL",
    "storage_quota_gb": 20,
    "member_limit": 0,
    "monthly_price": 2.99,
    "yearly_price": 25.99,
    "currency": "USD",
    "is_active": true,
    "sort_order": 110,
    "description": "适合轻度备份、文档、提示词和少量图片"
  },
  {
    "plan_id": "GLOBAL_PERSONAL_300GB",
    "plan_name": "海外个人云 300GB",
    "plan_type": "personal_cloud",
    "region": "GLOBAL",
    "storage_quota_gb": 300,
    "member_limit": 0,
    "monthly_price": 5.99,
    "yearly_price": 59.99,
    "currency": "USD",
    "is_active": true,
    "sort_order": 120,
    "description": "适合日常办公、多设备同步和附件保存"
  },
  {
    "plan_id": "GLOBAL_PERSONAL_1TB",
    "plan_name": "海外个人云 1TB",
    "plan_type": "personal_cloud",
    "region": "GLOBAL",
    "storage_quota_gb": 1024,
    "member_limit": 0,
    "monthly_price": 14.99,
    "yearly_price": 149.99,
    "currency": "USD",
    "is_active": true,
    "sort_order": 130,
    "description": "适合内容创作、项目文件和长期资料整理"
  },
  {
    "plan_id": "GLOBAL_PERSONAL_5TB",
    "plan_name": "海外个人云 5TB",
    "plan_type": "personal_cloud",
    "region": "GLOBAL",
    "storage_quota_gb": 5120,
    "member_limit": 0,
    "monthly_price": 56.99,
    "yearly_price": 569.99,
    "currency": "USD",
    "is_active": true,
    "sort_order": 140,
    "description": "适合工作室、小团队素材库和大容量归档"
  },
  {
    "plan_id": "GLOBAL_PERSONAL_10TB",
    "plan_name": "海外个人云 10TB",
    "plan_type": "personal_cloud",
    "region": "GLOBAL",
    "storage_quota_gb": 10240,
    "member_limit": 0,
    "monthly_price": 99.99,
    "yearly_price": 999.99,
    "currency": "USD",
    "is_active": true,
    "sort_order": 150,
    "description": "适合企业级文件、海量资料和长期存储"
  },
  {
    "plan_id": "CN_ENTERPRISE_BASIC",
    "plan_name": "中国区企业基础版",
    "plan_type": "enterprise",
    "region": "CN",
    "storage_quota_gb": 300,
    "member_limit": 5,
    "monthly_price": 299,
    "yearly_price": 2999,
    "currency": "CNY",
    "is_active": true,
    "sort_order": 210,
    "description": "适合小团队使用，包含企业空间、成员管理、项目共享和300GB企业云空间，最多5名成员"
  },
  {
    "plan_id": "CN_ENTERPRISE_STANDARD",
    "plan_name": "中国区企业标准版",
    "plan_type": "enterprise",
    "region": "CN",
    "storage_quota_gb": 1024,
    "member_limit": 20,
    "monthly_price": 699,
    "yearly_price": 6999,
    "currency": "CNY",
    "is_active": true,
    "sort_order": 220,
    "description": "适合成长型团队，包含项目协作、权限管理和1TB企业云空间，最多20名成员"
  },
  {
    "plan_id": "CN_ENTERPRISE_PRO",
    "plan_name": "中国区企业高级版",
    "plan_type": "enterprise",
    "region": "CN",
    "storage_quota_gb": 5120,
    "member_limit": 50,
    "monthly_price": 1999,
    "yearly_price": 19999,
    "currency": "CNY",
    "is_active": true,
    "sort_order": 230,
    "description": "适合中大型团队，包含高级权限、自有云接入和5TB企业云空间，最多50名成员"
  },
  {
    "plan_id": "GLOBAL_ENTERPRISE_BASIC",
    "plan_name": "Global Enterprise Basic",
    "plan_type": "enterprise",
    "region": "GLOBAL",
    "storage_quota_gb": 300,
    "member_limit": 5,
    "monthly_price": 49,
    "yearly_price": 499,
    "currency": "USD",
    "is_active": true,
    "sort_order": 310,
    "description": "For small teams, includes team workspace, member management, project sharing, and 300GB cloud storage, up to 5 members"
  },
  {
    "plan_id": "GLOBAL_ENTERPRISE_STANDARD",
    "plan_name": "Global Enterprise Standard",
    "plan_type": "enterprise",
    "region": "GLOBAL",
    "storage_quota_gb": 1024,
    "member_limit": 20,
    "monthly_price": 99,
    "yearly_price": 999,
    "currency": "USD",
    "is_active": true,
    "sort_order": 320,
    "description": "For growing teams, includes project collaboration, permission management, and 1TB cloud storage, up to 20 members"
  },
  {
    "plan_id": "GLOBAL_ENTERPRISE_PRO",
    "plan_name": "Global Enterprise Pro",
    "plan_type": "enterprise",
    "region": "GLOBAL",
    "storage_quota_gb": 5120,
    "member_limit": 50,
    "monthly_price": 299,
    "yearly_price": 2999,
    "currency": "USD",
    "is_active": true,
    "sort_order": 330,
    "description": "For larger teams, includes advanced permissions, own-cloud connection, and 5TB cloud storage, up to 50 members"
  }
];
  function all(){ return plans.slice().sort((a,b) => a.sort_order - b.sort_order); }
  function get(id){ return all().find(p => p.plan_id === id) || null; }
  function byType(type){ return all().filter(p => p.plan_type === type); }
  window.PlansData = { all, get, byType };
})();
