(function(){
  function title(){ return window.I18n.t(window.WeishanRouter.current()); }
  function accountLabel(){ const a=window.AccountApi.current(); return a.loggedIn ? window.AccountApi.publicName(a) : window.I18n.t("loginRegister"); }
  function html(){ return `<header class="topbar"><div><h1>${title()}</h1><p>${window.I18n.t("topbarSubtitle")}</p></div><div class="top-actions"><select id="langSelect" class="select-small"><option value="zh">中文</option><option value="en">English</option></select><span class="small green" aria-label="${window.I18n.t("localFirstMode")}">${window.I18n.t("localFirstMode")}</span><button class="small" id="settingsBtn">${window.I18n.t("settingsButton")}</button><button class="small" id="accountBtn">${accountLabel()}</button><button class="small" id="logoutBtn" style="${window.AccountApi.current().loggedIn?'':'display:none'}">${window.I18n.t("logout")}</button><button class="small primary" id="mailBtn">${window.I18n.t("mailButton")}</button></div></header>`; }
  function bind(){ const lang=document.getElementById("langSelect"); lang.value=window.I18n.getLang(); lang.addEventListener("change", e => window.I18n.setLang(e.target.value)); document.getElementById("settingsBtn").addEventListener("click",()=>window.WeishanRouter.setRoute("settings")); document.getElementById("accountBtn").addEventListener("click",()=>window.WeishanRouter.setRoute("settings")); document.getElementById("mailBtn").addEventListener("click",()=>window.WeishanRouter.setRoute("mail")); document.getElementById("logoutBtn").addEventListener("click",()=>{ window.AccountApi.logout(); window.WeishanRouter.refresh(); }); }
  function mount(root){ root.querySelector(".main").insertAdjacentHTML("afterbegin", html()); bind(); }
  function refresh(){ const old=document.querySelector(".topbar"); if(!old) return; const parent=old.parentElement; old.remove(); parent.insertAdjacentHTML("afterbegin", html()); bind(); }
  window.Topbar = { mount, refresh };
})();
