const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");
const root = path.join(__dirname, "../../apps/desktop/src/renderer/core");
const windowRef = {}; windowRef.window = windowRef;
const context = vm.createContext({ window:windowRef, Set, Number, Object, Array, String, Boolean, RegExp, Math });
[
  "globalCommerceInputGuard.js", "globalDecisionEvidenceConfidence.js", "globalDecisionEvidence.js", "globalDecisionEvidenceClassifier.js", "globalDecisionChange.js", "globalDecisionLifecycle.js", "globalDecisionScenario.js", "globalDecisionAssumption.js", "globalDecisionImpact.js", "globalDecisionTradeoff.js", "globalDecisionSimulation.js", "globalDecisionRiskCoverage.js", "globalDecisionAlternative.js", "globalDecisionConstraint.js", "globalDecisionConfidence.js", "globalDecisionWarning.js", "globalDecisionQuality.js", "globalDecisionTimelineCompare.js", "globalDecisionStability.js", "globalDecisionEvolution.js", "globalDecisionAdaptation.js"
].forEach((file) => vm.runInContext(fs.readFileSync(path.join(root, file), "utf8"), context));
const evidenceClassifier = windowRef.WeishanGlobalDecisionEvidenceClassifier;
const evidenceApi = windowRef.WeishanGlobalDecisionEvidence;
const changeApi = windowRef.WeishanGlobalDecisionChange;
const lifecycle = windowRef.WeishanGlobalDecisionLifecycle;
const stabilityApi = windowRef.WeishanGlobalDecisionStability;
const adaptationApi = windowRef.WeishanGlobalDecisionAdaptation;
const previous = Object.freeze({ facts:["Original total cost."], analysis:["Original analysis."], risks:["Original availability risk."], alternatives:["Original option B."], recommendation:{ recommendation:"OPTION_A" }, confidence:"MEDIUM", constraints:{ goal:"BEST_VALUE" }, limitations:["Offline information only."] });
const current = Object.freeze({ facts:["Updated total cost."], analysis:["Updated analysis."], risks:["Updated availability risk."], alternatives:["Updated option B."], recommendation:{ recommendation:"OPTION_B" }, confidence:"MEDIUM", constraints:{ goal:"LOWEST_RISK" }, limitations:["Offline information only."] });
const previousEvidence = evidenceClassifier.classifyDecisionEvidence({ facts:["Original total cost."], userInputs:[], assumptions:["Original dates."], analysisBasis:["Original comparison."], limitations:["Offline information only."] }).evidence;
const currentEvidence = evidenceClassifier.classifyDecisionEvidence({ facts:["Updated total cost."], userInputs:[], assumptions:["Updated dates."], analysisBasis:["Updated comparison."], limitations:["Offline information only."] }).evidence;
const change = changeApi.compareDecisionChangesWithEvidence({ previous, current, previousEvidence, currentEvidence });
assert.equal(change.success, true);
assert.equal(change.evidenceRequired, true);
assert.equal(change.categories.includes("FACT_CHANGED"), true);
assert.equal(change.categories.includes("CONSTRAINT_CHANGED"), true);
assert.equal(change.categories.includes("RISK_CHANGED"), true);
assert.equal(change.categories.includes("OPTION_CHANGED"), true);
assert.equal(change.categories.includes("EVIDENCE_CHANGED"), true);
assert.equal(change.changes.every((item) => item.evidence.length > 0), true);
assert.equal(changeApi.compareDecisionChangesWithEvidence({ previous, current, previousEvidence:["not evidence"], currentEvidence }).success, false);
assert.equal(stabilityApi.assessDecisionStability({ changes:change }).stability.status, "CHANGED");
assert.equal(stabilityApi.assessDecisionStability({ changes:{ status:"INSUFFICIENT_INFORMATION" } }).stability.status, "UNCERTAIN");
const scenario = { scenarioId:"OPTION_B", title:"Updated option B", assumptions:["The user-provided dates remain applicable."], impacts:{ cost:["Cost uses the updated user-provided figure."], time:["Time uses the stated schedule."], risk:["Risk uses disclosed policy information."], convenience:["Convenience uses the supplied route."], longTerm:["Long-term impact depends on stated usage."] }, advantages:["Updated comparison supports this option."], risks:["Availability may change."], limitations:["No live provider check."], tradeoffs:["Lower risk can reduce flexibility."] };
const simulation = windowRef.WeishanGlobalDecisionSimulation.simulateDecisionScenarios({ domain:"FINANCE", userTriggered:true, scenarios:[scenario] });
assert.equal(simulation.success, true);
const result = adaptationApi.runDecisionAdaptation({ previousDecision:previous, currentDecision:current, currentContext:{ question:"Please reassess this decision.", constraints:{ goal:"LOWEST_RISK" } }, previousEvidence, currentEvidence, simulation, userTriggered:true });
assert.equal(result.success, true);
assert.equal(result.adaptation.userTriggered, true);
assert.equal(result.adaptation.automaticChangeDetection, false);
assert.equal(result.adaptation.automaticRefresh, false);
assert.equal(result.adaptation.automaticReminder, false);
assert.equal(result.adaptation.report.userDecisionRequired, true);
assert.equal(result.adaptation.report.currentEvidence.length, currentEvidence.length);
assert.equal(result.adaptation.stability.evaluatesDecisionCorrectness, false);
assert.equal(result.adaptation.report.simulation[0].returnPrediction, false);
assert.equal(adaptationApi.runDecisionAdaptation(Object.assign({}, { previousDecision:previous, currentDecision:current, currentContext:{ question:"Please reassess this decision.", constraints:{ goal:"LOWEST_RISK" } }, previousEvidence, currentEvidence, simulation }, { userTriggered:false })).success, false);
const evidenceVersion = evidenceApi.createEvidenceVersion({ versionId:"evidence-v2", previousEvidence, currentEvidence, userTriggered:true });
assert.equal(evidenceVersion.success, true);
assert.equal(evidenceVersion.version.overwritesPrevious, false);
const decisionVersion = lifecycle.createDecisionVersion({ versionId:"decision-v2", previousArtifact:{ id:"v1" }, updatedArtifact:{ id:"v2" }, updateSummary:"User requested a new comparison.", userTriggered:true });
const archive = lifecycle.appendDecisionArchiveVersion({ archive:[{ versionId:"decision-v1" }], version:decisionVersion.version, userTriggered:true });
assert.equal(archive.success, true);
assert.equal(archive.archive.length, 2);
assert.equal(archive.overwritesPrevious, false);
assert.equal(lifecycle.appendDecisionArchiveVersion({ archive:[], version:decisionVersion.version, userTriggered:false }).success, false);
const inputText = JSON.stringify({ previous, current, previousEvidence, currentEvidence, simulation }); adaptationApi.runDecisionAdaptation({ previousDecision:previous, currentDecision:current, currentContext:{ question:"Please reassess this decision.", constraints:{ goal:"LOWEST_RISK" } }, previousEvidence, currentEvidence, simulation, userTriggered:true }); assert.equal(JSON.stringify({ previous, current, previousEvidence, currentEvidence, simulation }), inputText);
for (let index = 0; index < 20; index += 1) assert.deepEqual(JSON.parse(JSON.stringify(adaptationApi.runDecisionAdaptation({ previousDecision:previous, currentDecision:current, currentContext:{ question:"Please reassess this decision.", constraints:{ goal:"LOWEST_RISK" } }, previousEvidence, currentEvidence, simulation, userTriggered:true }))), JSON.parse(JSON.stringify(result)));
console.log("GLOBAL_DECISION_EVOLUTION PASS");
