const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");
const root = path.join(__dirname, "../../apps/desktop/src/renderer/core");
const windowRef = {}; windowRef.window = windowRef;
const context = vm.createContext({ window:windowRef, Set, Number, Object, Array, String, Boolean, RegExp, Math });
[
  "globalCommerceInputGuard.js", "globalDecisionEvidenceConfidence.js", "globalDecisionEvidence.js", "globalDecisionEvidenceClassifier.js", "globalDecisionExplanation.js", "globalDecisionScenario.js", "globalDecisionAssumption.js", "globalDecisionImpact.js", "globalDecisionTradeoff.js", "globalDecisionSimulation.js"
].forEach((file) => vm.runInContext(fs.readFileSync(path.join(root, file), "utf8"), context));
const evidenceApi = windowRef.WeishanGlobalDecisionEvidence;
const classifier = windowRef.WeishanGlobalDecisionEvidenceClassifier;
const confidence = windowRef.WeishanGlobalDecisionEvidenceConfidence;
const explanation = windowRef.WeishanGlobalDecisionExplanation;
const simulationApi = windowRef.WeishanGlobalDecisionSimulation;
const classified = classifier.classifyDecisionEvidence({ facts:["The user supplied the total cost."], userInputs:["The user's budget is fixed."], assumptions:["The stated dates remain applicable."], analysisBasis:["The supplied total cost was compared."], limitations:["Live availability was not checked."] });
assert.equal(classified.success, true);
assert.deepEqual(JSON.parse(JSON.stringify(classified.evidence.map((item) => item.type))), ["FACT", "USER_INPUT", "ASSUMPTION", "ANALYSIS_BASIS", "LIMITATION"]);
assert.equal(classified.analysisPresentedAsFact, false);
assert.equal(classified.automaticSourceCollection, false);
assert.equal(classified.evidence[3].source, "OFFLINE_CALCULATION");
assert.equal(classified.evidence[3].type, "ANALYSIS_BASIS");
assert.equal(confidence.assessEvidenceConfidence({ type:"ASSUMPTION", limitations:[], completeness:true }).confidence.level, "LOW");
assert.equal(confidence.assessEvidenceConfidence({ type:"FACT", limitations:[], completeness:true }).confidence.falsePrecision, false);
const scenario = { scenarioId:"OPTION_A", title:"Option A", assumptions:["The supplied time window remains applicable."], impacts:{ cost:["Cost reflects the user-provided estimate."], time:["Time reflects the supplied schedule."], risk:["Policy details may vary."], convenience:["One connection is included."], longTerm:["Long-term impact depends on the stated usage period."] }, advantages:["Lower supplied total cost."], risks:["Availability may change."], limitations:["No live provider check."], tradeoffs:["Less flexibility may reduce cost."] };
const simulated = simulationApi.simulateDecisionScenarios({ domain:"FINANCE", userTriggered:true, scenarios:[scenario] });
assert.equal(simulated.success, true);
const simulationEvidence = evidenceApi.createSimulationEvidence(simulated.simulations[0]);
assert.equal(simulationEvidence.success, true);
assert.equal(simulationEvidence.simulationEvidence.hiddenSimulationPremise, false);
assert.equal(simulationEvidence.simulationEvidence.prediction, false);
assert.deepEqual(JSON.parse(JSON.stringify(simulationEvidence.simulationEvidence.assumptions)), ["The supplied time window remains applicable."]);
const v4 = simulationApi.createDecisionReportV4({ report:{ facts:["User-provided fact."], analysis:["User-provided analysis."], recommendation:"Review the supplied options.", risks:["Availability may change."], limitations:["Offline information only."], confidence:"MEDIUM" }, simulation:simulated });
const v5 = evidenceApi.createDecisionReportV5({ report:v4.report, evidence:classified.evidence });
assert.equal(v5.success, true);
assert.equal(v5.report.evidence.length, 5);
assert.equal(v5.report.userDecisionRequired, true);
assert.equal(v5.report.evidence.some((item) => item.type === "ANALYSIS_BASIS" && item.source === "OFFLINE_CALCULATION"), true);
assert.equal(evidenceApi.createDecisionReportV5({ report:v4.report, evidence:[{ type:"FACT", source:"OFFLINE_CALCULATION", statement:"Spoofed", confidence:"HIGH", limitations:[], userProvided:true }] }).success, false);
assert.equal(classifier.createEvidenceSummary([{ type:"FACT", source:"OFFLINE_CALCULATION", statement:"Spoofed", confidence:"HIGH", limitations:[], userProvided:true }]).success, false);
const upgraded = explanation.createDecisionExplanationWithEvidence({ explanation:{ recommendationReason:"The supplied evidence supports reviewing this option.", keyAdvantages:["A stated advantage."], keyRisks:["A stated limitation."], alternatives:["Option B"], confidence:"MEDIUM", explanationType:"EVIDENCE_BASED_OFFLINE" }, evidence:classified.evidence });
assert.equal(upgraded.success, true);
assert.equal(upgraded.explanation.evidenceSummary.authoritative, false);
assert.deepEqual(JSON.parse(JSON.stringify(upgraded.explanation.evidenceSummary.unknown)), ["Live availability was not checked."]);
assert.equal(evidenceApi.createDecisionEvidence({ type:"ANALYSIS_BASIS", source:"USER_PROVIDED", statement:"Blocked", limitations:[], userProvided:false, completeness:true }).success, false);
assert.equal(classifier.classifyDecisionEvidence({ facts:["x"], userInputs:[], assumptions:[], analysisBasis:[], limitations:[], token:"blocked" }).success, false);
const getterInput = { facts:["x"], userInputs:[], assumptions:[], analysisBasis:[], limitations:[] };
Object.defineProperty(getterInput, "extra", { get() { return "blocked"; } });
assert.equal(classifier.classifyDecisionEvidence(getterInput).success, false);
const inputText = JSON.stringify(classified); classifier.createEvidenceSummary(classified.evidence); assert.equal(JSON.stringify(classified), inputText);
for (let index = 0; index < 20; index += 1) assert.deepEqual(JSON.parse(JSON.stringify(evidenceApi.createDecisionReportV5({ report:v4.report, evidence:classified.evidence }))), JSON.parse(JSON.stringify(v5)));
console.log("GLOBAL_DECISION_EVIDENCE PASS");
