const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");
const windowRef = {}; windowRef.window = windowRef;
const context = vm.createContext({ window:windowRef, Set, Number, Object, Array, String, Boolean, RegExp, Math });
["globalCommerceInputGuard.js", "globalDecisionFinanceAdapter.js"].forEach((file) => vm.runInContext(fs.readFileSync(path.join(__dirname, "../../apps/desktop/src/renderer/core", file), "utf8"), context));
const finance = windowRef.WeishanGlobalDecisionFinanceAdapter;
const input = { facts:["User-provided instrument information."], analysis:["Information is organized for comparison."], risks:["Market outcomes are uncertain."], alternatives:["Option B", "Option C"], confidence:"LOW", limitations:["Offline information only; not investment advice."] };
const result = finance.createFinanceDecisionReport(input);
assert.equal(result.success, true);
assert.equal(result.report.domain, "FINANCE");
assert.equal(result.report.recommendation.recommendation, "REVIEW_FINANCIAL_OPTIONS");
assert.equal(result.report.recommendation.whyRecommended.includes("not investment advice"), true);
assert.equal(result.report.userDecisionRequired, true);
assert.equal(finance.createFinanceDecisionReport(Object.assign({}, input, { accountId:"blocked" })).success, false);
assert.equal(finance.createFinanceDecisionReport(Object.assign({}, input, { confidence:"LOW", risks:[] })).success, false);
const text = JSON.stringify(input); finance.createFinanceDecisionReport(input); assert.equal(JSON.stringify(input), text);
for (let index = 0; index < 20; index += 1) assert.deepEqual(JSON.parse(JSON.stringify(finance.createFinanceDecisionReport(input))), JSON.parse(JSON.stringify(result)));
console.log("GLOBAL_DECISION_FINANCE PASS");
