const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");
const root = path.join(__dirname, "../../apps/desktop/src/renderer/core");
const windowRef = {}; windowRef.window = windowRef;
const context = vm.createContext({ window:windowRef, Set, Number, Object, Array, String, Boolean, RegExp, Math });
[
  "globalCommerceInputGuard.js", "globalDecisionDomainRegistry.js", "globalDecisionDomainAdapter.js", "globalDecisionTravelAdapter.js", "globalDecisionFinanceAdapter.js", "globalDecisionQuery.js", "globalDecisionIntent.js", "globalDecisionClarification.js", "globalDecisionEntryRouter.js", "globalDecisionStarter.js", "globalDecisionOrchestrator.js", "globalDecisionFirstFlow.js"
].forEach((file) => vm.runInContext(fs.readFileSync(path.join(root, file), "utf8"), context));
const queryApi = windowRef.WeishanGlobalDecisionQuery;
const intentApi = windowRef.WeishanGlobalDecisionIntent;
const router = windowRef.WeishanGlobalDecisionEntryRouter;
const starter = windowRef.WeishanGlobalDecisionStarter;
const flow = windowRef.WeishanGlobalDecisionFirstFlow;
const query = queryApi.createDecisionQuery({ question:"Tokyo hotels: which option should I compare?", constraints:{ budget:"user-provided" } });
assert.equal(query.success, true);
assert.deepEqual(JSON.parse(JSON.stringify(query.query.domainCandidate)), ["TRAVEL"]);
assert.equal(query.query.userInformationInferred, false);
assert.equal(intentApi.understandDecisionIntent("Tokyo hotels: which option should I compare?").intent, "COMPARISON");
assert.equal(intentApi.understandDecisionIntent("What did I decide before?").intent, "REVIEW");
assert.equal(starter.listDecisionStarters().purchaseInducementEnabled, false);
const selectionRequired = router.routeDecisionEntry({ question:"Tokyo hotels: which option should I compare?", userTriggered:true });
assert.equal(selectionRequired.success, true);
assert.equal(selectionRequired.route.state, "DOMAIN_SELECTION_REQUIRED");
const route = router.routeDecisionEntry({ question:"Tokyo hotels: which option should I compare?", constraints:{ budget:"user-provided", time:"user-provided", preference:"user-provided" }, selectedDomain:"TRAVEL", userTriggered:true });
assert.equal(route.success, true);
assert.equal(route.route.state, "ORCHESTRATOR_USER_ACTION_REQUIRED");
assert.equal(route.route.orchestratorExecutionEnabled, false);
assert.equal(route.route.archiveCreated, false);
const first = flow.createFirstDecisionFlow({ question:"Tokyo hotels: which option should I compare?", constraints:{ budget:"user-provided", time:"user-provided", preference:"user-provided" }, selectedDomain:"TRAVEL", userTriggered:true, decisionInput:{ travelType:"HOTEL", facts:["User-provided total cost."], analysis:["User-provided convenience information."], risks:["Cancellation details are limited."], alternatives:["Option B", "Option C"], confidence:"MEDIUM", limitations:["Offline information only."] } });
assert.equal(first.success, true);
assert.equal(first.flow.report.domain, "TRAVEL");
assert.equal(first.flow.report.userDecisionRequired, true);
assert.equal(first.flow.archiveCreated, false);
assert.equal(router.continueDecisionAssistant({ userTriggered:false }).success, false);
assert.equal(queryApi.createDecisionQuery({ question:"Which computer suits me?", accountId:"blocked" }).success, false);
const text = JSON.stringify(query); queryApi.createDecisionQuery({ question:"Tokyo hotels: which option should I compare?", constraints:{ budget:"user-provided" } }); assert.equal(JSON.stringify(query), text);
for (let index = 0; index < 20; index += 1) assert.deepEqual(JSON.parse(JSON.stringify(flow.createFirstDecisionFlow({ question:"Tokyo hotels: which option should I compare?", constraints:{ budget:"user-provided", time:"user-provided", preference:"user-provided" }, selectedDomain:"TRAVEL", userTriggered:true, decisionInput:{ travelType:"HOTEL", facts:["User-provided total cost."], analysis:["User-provided convenience information."], risks:["Cancellation details are limited."], alternatives:["Option B", "Option C"], confidence:"MEDIUM", limitations:["Offline information only."] } }))), JSON.parse(JSON.stringify(first)));
console.log("GLOBAL_DECISION_ENTRY PASS");
