const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");
const root = path.join(__dirname, "../../apps/desktop/src/renderer/core");
const windowRef = {}; windowRef.window = windowRef;
const context = vm.createContext({ window:windowRef, Set, Number, Object, Array, String, Boolean, RegExp, Math });
["globalCommerceInputGuard.js", "globalDecisionChange.js", "globalDecisionLifecycle.js", "globalDecisionReview.js", "globalDecisionFreshness.js"].forEach((file) => vm.runInContext(fs.readFileSync(path.join(root, file), "utf8"), context));
const lifecycleApi = windowRef.WeishanGlobalDecisionLifecycle;
const reviewApi = windowRef.WeishanGlobalDecisionReview;
const changeApi = windowRef.WeishanGlobalDecisionChange;
const freshnessApi = windowRef.WeishanGlobalDecisionFreshness;
const created = lifecycleApi.createDecisionLifecycle({ lifecycleId:"life-1", memoryId:"memory-1", domain:"COMMERCE" });
assert.equal(created.success, true);
assert.equal(created.lifecycle.state, "CREATED");
assert.equal(created.lifecycle.automaticTransitionEnabled, false);
const active = lifecycleApi.transitionDecisionLifecycle({ lifecycle:created.lifecycle, nextState:"ACTIVE", userTriggered:true });
const updated = lifecycleApi.transitionDecisionLifecycle({ lifecycle:active.lifecycle, nextState:"UPDATED", userTriggered:true });
const reviewed = lifecycleApi.transitionDecisionLifecycle({ lifecycle:updated.lifecycle, nextState:"REVIEWED", userTriggered:true });
const completed = lifecycleApi.transitionDecisionLifecycle({ lifecycle:reviewed.lifecycle, nextState:"COMPLETED", userTriggered:true });
const archived = lifecycleApi.transitionDecisionLifecycle({ lifecycle:completed.lifecycle, nextState:"ARCHIVED", userTriggered:true });
assert.equal(archived.lifecycle.state, "ARCHIVED");
assert.equal(lifecycleApi.transitionDecisionLifecycle({ lifecycle:created.lifecycle, nextState:"COMPLETED", userTriggered:true }).success, false);
assert.equal(lifecycleApi.transitionDecisionLifecycle({ lifecycle:created.lifecycle, nextState:"ACTIVE", userTriggered:false }).success, false);
const previous = { facts:[{ code:"PRICE" }], risks:[{ type:"PRICE_RISK" }], recommendation:{ recommendation:"old" }, confidence:"MEDIUM", limitations:["Offline"] };
const current = { facts:[{ code:"PRICE_NEW" }], risks:[{ type:"RISK_NEW" }], recommendation:{ recommendation:"new" }, confidence:"LOW", limitations:["Offline", "Limited"] };
const change = changeApi.compareDecisionChanges({ previous, current });
assert.deepEqual(JSON.parse(JSON.stringify(change.categories)), ["FACT_CHANGED", "RISK_CHANGED", "OPTION_CHANGED"]);
assert.deepEqual(JSON.parse(JSON.stringify(changeApi.compareDecisionChanges({ previous:{}, current:{} }).categories)), ["INSUFFICIENT_INFORMATION"]);
const review = reviewApi.createDecisionReview({ memoryId:"memory-1", originalDecision:previous, currentDecision:current, currentContext:{ businessType:"COMMERCE" }, userTriggered:true });
assert.equal(review.success, true);
assert.equal(review.review.changedFacts, true);
assert.equal(review.review.changedRisks, true);
assert.equal(review.review.changedRecommendation, true);
assert.equal(review.review.userDecisionRequired, true);
const fresh = freshnessApi.checkDecisionFreshness({ memoryId:"memory-1", userRequested:true, declaredState:"MAY_NEED_REVIEW", reason:"User requested a review." });
assert.equal(fresh.success, true);
assert.equal(fresh.freshness.automaticExpirationEnabled, false);
assert.equal(freshnessApi.checkDecisionFreshness({ memoryId:"memory-1", userRequested:false, declaredState:"CURRENT", reason:"x" }).success, false);
const version = lifecycleApi.createDecisionVersion({ versionId:"version-2", previousArtifact:previous, updatedArtifact:current, updateSummary:"User updated conditions.", userTriggered:true });
assert.equal(version.success, true);
assert.equal(version.version.overwritesPrevious, false);
const timeline = lifecycleApi.appendDecisionTimelineEvent({ timeline:[], eventId:"event-1", eventType:"VIEW", memoryId:"memory-1", userTriggered:true });
assert.equal(timeline.success, true);
assert.equal(timeline.timeline[0].observedBehavior, false);
assert.equal(lifecycleApi.appendDecisionTimelineEvent({ timeline:[], eventId:"event-2", eventType:"VIEW", memoryId:"memory-1", userTriggered:false }).success, false);
const source = JSON.stringify(previous); reviewApi.createDecisionReview({ memoryId:"memory-1", originalDecision:previous, currentDecision:current, userTriggered:true }); assert.equal(JSON.stringify(previous), source);
for (let index = 0; index < 20; index += 1) assert.deepEqual(JSON.parse(JSON.stringify(lifecycleApi.createDecisionLifecycle({ lifecycleId:"life-1", memoryId:"memory-1", domain:"COMMERCE" }))), JSON.parse(JSON.stringify(created)));
console.log("GLOBAL_DECISION_LIFECYCLE PASS");
