const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");
const root = path.join(__dirname, "../../apps/desktop/src/renderer/core");
const windowRef = {}; windowRef.window = windowRef;
const context = vm.createContext({ window:windowRef, Set, Number, Object, Array, String, Boolean, RegExp, Math });
[
  "globalCommerceInputGuard.js", "globalDecisionTravelAdapter.js", "globalDecisionSummary.js", "globalDecisionComparisonView.js", "globalDecisionExplainability.js", "globalDecisionShareArtifact.js", "globalDecisionFeedback.js", "globalDecisionExperience.js"
].forEach((file) => vm.runInContext(fs.readFileSync(path.join(root, file), "utf8"), context));
const travel = windowRef.WeishanGlobalDecisionTravelAdapter;
const summary = windowRef.WeishanGlobalDecisionSummary;
const comparison = windowRef.WeishanGlobalDecisionComparisonView;
const explainability = windowRef.WeishanGlobalDecisionExplainability;
const share = windowRef.WeishanGlobalDecisionShareArtifact;
const feedback = windowRef.WeishanGlobalDecisionFeedback;
const experienceApi = windowRef.WeishanGlobalDecisionExperience;
const report = travel.createTravelDecisionReport({ travelType:"HOTEL", facts:["Total cost was provided by the user."], analysis:["Convenience information was provided by the user."], risks:["Cancellation details are limited."], alternatives:["Option B", "Option C"], confidence:"MEDIUM", limitations:["Offline information only."] }).report;
const summaryResult = summary.createDecisionSummary(report);
assert.equal(summaryResult.success, true);
assert.equal(summaryResult.summary.oneLineConclusion.includes("Based on"), true);
assert.equal(summaryResult.summary.primaryRisks.length, 1);
const comparisonResult = comparison.createDecisionComparisonView([{ label:"A", price:100, value:["Convenient"], risks:["Risk A"], limitations:["Offline"] }, { label:"B", price:90, value:["Flexible"], risks:["Risk B"], limitations:["Offline"] }, { label:"C", price:95, value:["Stable"], risks:["Risk C"], limitations:["Offline"] }]);
assert.equal(comparisonResult.success, true);
assert.equal(comparisonResult.comparison.priceOnlyRanking, false);
assert.equal(comparisonResult.comparison.options.length, 3);
const quality = explainability.evaluateDecisionExplainability(report);
assert.equal(quality.success, true);
assert.equal(quality.explainability.recommendationScore, false);
assert.equal(quality.explainability.measures.risksDisclosed, true);
const experience = experienceApi.createDecisionExperience({ decisionReport:report });
assert.equal(experience.success, true);
assert.equal(experience.experience.shareable, false);
assert.equal(experience.experience.automaticGrowthEnabled, false);
assert.equal(experience.experience.userDecisionRequired, true);
const shared = share.createDecisionShareArtifact({ title:"Why I reviewed this hotel", report });
assert.equal(shared.success, true);
assert.equal(shared.artifact.shareable, false);
assert.equal(shared.artifact.requiresExplicitUserAction, true);
assert.equal(shared.artifact.socialTrackingEnabled, false);
const template = share.createAnonymousDecisionTemplate({ question:"How should I compare hotels?", summary:"Compare evidence and risk.", analysis:["Use disclosed limitations."] });
assert.equal(template.success, true);
assert.equal(template.template.anonymous, true);
assert.equal(template.template.includesArchive, false);
assert.equal(feedback.createDecisionFeedback({ response:"HELPFUL" }).feedback.trackingEnabled, false);
assert.equal(feedback.createDecisionFeedback({ response:"NOT_HELPFUL", accountId:"blocked" }).success, false);
assert.equal(share.createDecisionShareArtifact({ title:"x", report:Object.assign({}, report, { token:"blocked" }) }).success, false);
const text = JSON.stringify(report); experienceApi.createDecisionExperience({ decisionReport:report }); assert.equal(JSON.stringify(report), text);
for (let index = 0; index < 20; index += 1) assert.deepEqual(JSON.parse(JSON.stringify(experienceApi.createDecisionExperience({ decisionReport:report }))), JSON.parse(JSON.stringify(experience)));
console.log("GLOBAL_DECISION_EXPERIENCE PASS");
