const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");
const root = path.join(__dirname, "../../apps/desktop/src/renderer/core");
const windowRef = {}; windowRef.window = windowRef;
const context = vm.createContext({ window:windowRef, Set, Number, Object, Array, String, Boolean, RegExp, Math });
["globalCommerceInputGuard.js", "globalDecisionTemplate.js", "globalDecisionKnowledgeShare.js", "globalDecisionPattern.js", "globalDecisionFeedback.js"].forEach((file) => vm.runInContext(fs.readFileSync(path.join(root, file), "utf8"), context));
const templateApi = windowRef.WeishanGlobalDecisionTemplate;
const shareApi = windowRef.WeishanGlobalDecisionKnowledgeShare;
const patternApi = windowRef.WeishanGlobalDecisionPattern;
const feedbackApi = windowRef.WeishanGlobalDecisionFeedback;
const templateInput = { templateId:"hotel-selection-v1", title:"Hotel selection", templateType:"HOTEL_SELECTION", questionStructure:"What matters for this stay?", comparisonDimensions:["total cost", "location"], riskDimensions:["cancellation", "availability"], analysisFramework:["facts", "risks", "alternatives"], authorDisclosure:{ identity:"Verified template contributor", interestDisclosure:"No commercial relationship declared." } };
const template = templateApi.createDecisionTemplate(templateInput);
assert.equal(template.success, true);
assert.equal(template.template.containsPersonalData, false);
assert.equal(template.template.rankingInfluenceEnabled, false);
assert.equal(template.template.providerInfluenceEnabled, false);
assert.equal(templateApi.createDecisionTemplate(Object.assign({}, templateInput, { accountId:"blocked" })).success, false);
const share = shareApi.createAnonymousKnowledgeShare({ shareId:"knowledge-1", title:"How to compare Tokyo hotels", knowledge:{ question:"How should I compare hotels?", method:"Compare cost, policy, and risks.", analysis:["Review cancellation limitations."] }, userConsent:true });
assert.equal(share.success, true);
assert.equal(share.share.visibility, "PRIVATE");
assert.equal(share.share.authorizedByUser, true);
assert.equal(share.share.automaticPublication, false);
assert.equal(share.share.socialTrackingEnabled, false);
assert.equal(shareApi.createAnonymousKnowledgeShare({ shareId:"x", title:"x", knowledge:{ question:"x", method:"x", analysis:[] }, userConsent:false }).success, false);
assert.deepEqual(JSON.parse(JSON.stringify(patternApi.listDecisionPatterns().map((item) => item.patternId))), ["PRICE_NOT_BEST", "TOTAL_COST", "RISK_REWARD", "LONG_TERM_VALUE"]);
assert.equal(patternApi.findDecisionPattern("PRICE_NOT_BEST").pattern.personalLearningEnabled, false);
assert.equal(patternApi.findDecisionPattern("UNKNOWN").code, "DECISION_PATTERN_NOT_FOUND");
const feedback = feedbackApi.createDecisionFeedback({ response:"HELPFUL", comment:"Clear risk explanation." });
assert.equal(feedback.success, true);
assert.equal(feedback.feedback.trackingEnabled, false);
assert.equal(feedback.feedback.analyticsEnabled, false);
assert.equal(feedback.feedback.profileUseEnabled, false);
const text = JSON.stringify(templateInput); templateApi.createDecisionTemplate(templateInput); assert.equal(JSON.stringify(templateInput), text);
for (let index = 0; index < 20; index += 1) assert.deepEqual(JSON.parse(JSON.stringify(templateApi.createDecisionTemplate(templateInput))), JSON.parse(JSON.stringify(template)));
console.log("GLOBAL_DECISION_ECOSYSTEM PASS");
