const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");

const root = path.join(__dirname, "../../apps/desktop/src/renderer/core");
const windowRef = {};
windowRef.window = windowRef;
const context = vm.createContext({ window:windowRef, Set, Number, Object, Array, String, Boolean, RegExp, Math });
["globalCommerceInputGuard.js", "globalDecisionMemoryArtifact.js", "globalDecisionMemory.js"].forEach((file) => vm.runInContext(fs.readFileSync(path.join(root, file), "utf8"), context));
const memoryApi = windowRef.WeishanGlobalDecisionMemory;
const artifactApi = windowRef.WeishanGlobalDecisionMemoryArtifact;
const artifactInput = { question:"Which hotel option should I review?", facts:[{ code:"TOTAL_COST" }], analysis:[{ code:"OFFLINE_ANALYSIS" }], recommendation:{ recommendation:"hotel-a", whyRecommended:"Declared evidence supports it.", advantages:["Declared availability"], risks:["Evidence remains limited."], alternatives:["hotel-b"], confidence:"MEDIUM" }, risks:[{ type:"DATA_LIMITATION", reason:"Evidence remains limited." }], alternatives:["hotel-b", "hotel-c"], confidence:"MEDIUM" };
const artifact = artifactApi.createDecisionMemoryArtifact(artifactInput);
assert.equal(artifact.success, true);
assert.equal(artifact.artifact.offline, true);
assert.equal(artifact.artifact.immutable, true);
assert.equal(artifactApi.createDecisionMemoryArtifact(Object.assign({}, artifactInput, { token:"blocked" })).success, false);
const input = { memoryId:"memory-hotel-1", title:"Tokyo hotel comparison", domain:"COMMERCE", summary:"A user-saved offline hotel comparison.", memoryType:"COMPARISON_RECORD", decisionArtifact:artifactInput };
const created = memoryApi.createDecisionMemory(input);
assert.equal(created.success, true);
assert.equal(created.memory.createdByUser, true);
assert.equal(created.memory.trackingEnabled, false);
assert.equal(created.memory.storage, "CALLER_MANAGED_OFFLINE");
assert.equal(Object.prototype.hasOwnProperty.call(created.memory, "accountId"), false);
assert.equal(memoryApi.createDecisionMemory(Object.assign({}, input, { deviceId:"blocked" })).success, false);
let collection = memoryApi.saveDecisionMemory([], input);
assert.equal(collection.success, true);
assert.equal(collection.memories.length, 1);
assert.equal(memoryApi.saveDecisionMemory(collection.memories, input).code, "DECISION_MEMORY_DUPLICATE");
const continued = memoryApi.continueDecision(collection.memories, "memory-hotel-1");
assert.equal(continued.success, true);
assert.equal(continued.continuation.recalculationRequested, false);
assert.equal(continued.continuation.decisionArtifact.question, artifactInput.question);
const deleted = memoryApi.deleteDecisionMemory(collection.memories, "memory-hotel-1");
assert.equal(deleted.success, true);
assert.equal(deleted.memories.length, 0);
assert.equal(memoryApi.continueDecision(deleted.memories, "memory-hotel-1").code, "DECISION_MEMORY_NOT_FOUND");
assert.equal(memoryApi.deleteDecisionMemory(deleted.memories, "memory-hotel-1").code, "DECISION_MEMORY_NOT_FOUND");
const before = JSON.stringify(input);
memoryApi.createDecisionMemory(input);
assert.equal(JSON.stringify(input), before);
created.memory.title = "changed";
assert.equal(memoryApi.createDecisionMemory(input).memory.title, "Tokyo hotel comparison");
for (let index = 0; index < 20; index += 1) assert.deepEqual(JSON.parse(JSON.stringify(memoryApi.createDecisionMemory(input))), JSON.parse(JSON.stringify(created)));
const getterInput = {};
Object.defineProperty(getterInput, "memoryId", { get() { throw new Error("getter must not execute"); } });
assert.equal(memoryApi.createDecisionMemory(getterInput).success, false);
console.log("GLOBAL_DECISION_MEMORY PASS");
