const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");
const windowRef = {}; windowRef.window = windowRef;
const context = vm.createContext({ window:windowRef, Set, Number, Object, Array, String, Boolean, RegExp, Math });
["globalCommerceInputGuard.js", "globalDecisionTravelAdapter.js"].forEach((file) => vm.runInContext(fs.readFileSync(path.join(__dirname, "../../apps/desktop/src/renderer/core", file), "utf8"), context));
const travel = windowRef.WeishanGlobalDecisionTravelAdapter;
const input = { travelType:"HOTEL", facts:["User-provided total cost."], analysis:["User-provided convenience evidence."], risks:["Cancellation details are limited."], alternatives:["Option B", "Option C"], confidence:"MEDIUM", limitations:["Offline information only."] };
const result = travel.createTravelDecisionReport(input);
assert.equal(result.success, true);
assert.equal(result.report.domain, "TRAVEL");
assert.equal(result.report.recommendation.recommendation, "REVIEW_TRAVEL_OPTIONS");
assert.equal(result.report.userDecisionRequired, true);
assert.equal(travel.createTravelDecisionReport(Object.assign({}, input, { bookingUrl:"blocked" })).success, false);
assert.equal(travel.createTravelDecisionReport(Object.assign({}, input, { confidence:"LOW", risks:[] })).success, false);
const text = JSON.stringify(input); travel.createTravelDecisionReport(input); assert.equal(JSON.stringify(input), text);
for (let index = 0; index < 20; index += 1) assert.deepEqual(JSON.parse(JSON.stringify(travel.createTravelDecisionReport(input))), JSON.parse(JSON.stringify(result)));
console.log("GLOBAL_DECISION_TRAVEL PASS");
