"use strict";

const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const root=path.resolve(__dirname,"../.."),shared=path.join(root,"apps/desktop/src/renderer/core/commerceShadow/contracts"),priceContracts=path.join(root,"apps/desktop/src/renderer/core/commerceShadow/price/contracts"),normalization=path.join(root,"apps/desktop/src/renderer/core/commerceShadow/price/normalization"),recommendation=path.join(root,"apps/desktop/src/renderer/core/commerceShadow/recommendation"),sharedFiles=["sharedCommerceContractTypes.js","sharedCommerceContractValidation.js","sharedCommerceContracts.js","sharedCommerceContractPackage.js"],authorityFiles=["priceAuthorityTypes.js","priceAuthorityValidation.js","priceAuthorityContracts.js","priceAuthorityPackage.js"],normalizationFiles=["priceNormalizationTypes.js","priceNormalizationValidation.js","priceNormalizationCore.js","priceNormalizationPackage.js"],recommendationFiles=["recommendationTypes.js","recommendationValidation.js","recommendationContracts.js","recommendationPackage.js"],tests=[];let assertions=0;
function equal(a,b,m){assertions++;assert.equal(a,b,m);}function truth(a,m){assertions++;assert.ok(a,m);}function throws(f,m){assertions++;assert.throws(f,m);}function test(name,run){tests.push({name,run});}function load(){const w={};w.window=w;const c=vm.createContext({window:w});sharedFiles.forEach(f=>vm.runInContext(fs.readFileSync(path.join(shared,f),"utf8"),c,{filename:f}));authorityFiles.forEach(f=>vm.runInContext(fs.readFileSync(path.join(priceContracts,f),"utf8"),c,{filename:f}));normalizationFiles.forEach(f=>vm.runInContext(fs.readFileSync(path.join(normalization,f),"utf8"),c,{filename:f}));recommendationFiles.forEach(f=>vm.runInContext(fs.readFileSync(path.join(recommendation,f),"utf8"),c,{filename:f}));return w.WeishanRecommendationPackage;}function deps(){let n=0;return{clock:()=>"2026-08-02T00:00:00.000Z",idGenerator:()=>"recommendation-"+(++n)};}function reference(n){return{normalizationId:"normalization-"+n,authorityId:"authority-"+n,currency:"UNKNOWN",comparisonReadiness:"BLOCKED"};}function request(extra){return Object.assign({schemaVersion:"P8_RECOMMENDATION_V1",requestId:"request-1",domain:"PRODUCT",marketContextId:"market-1",normalizedPrices:[],userPreferences:[],constraints:[],comparisonMode:"UNKNOWN",requestedGoal:"UNKNOWN",limitations:["NO_PRICE_EVIDENCE"]},extra||{});}function candidate(n,extra){return Object.assign({candidateId:"candidate-"+n,sourceReference:"UNKNOWN",normalizedPriceReference:reference(n),providerReference:"UNKNOWN",availabilityState:"UNKNOWN",advantages:[],disadvantages:[],risks:[],confidence:"UNKNOWN",evidenceState:"UNKNOWN",limitations:["MISSING_EVIDENCE"],selectionStatus:"UNKNOWN"},extra||{});}
// Group 1: Contract schema.
test("creates immutable request and an empty non-generated result",()=>{const api=load(),r=api.createRecommendationRequest(request()),result=api.createEmptyRecommendationResult(r,deps());equal(r.requestId,"request-1");truth(Object.isFrozen(r));equal(result.status,"NO_RECOMMENDATION_GENERATED");equal(result.userDecisionRequired,true);equal(result.executed,false);equal(result.productionAffected,false);truth(result.limitations.includes("CONTRACT_ONLY_NO_RECOMMENDATION_GENERATED"));});
test("supports every requested goal and comparison mode as neutral metadata",()=>{const api=load();["LOWEST_COST","BEST_VALUE","MOST_CONVENIENT","MOST_RELIABLE","FASTEST","USER_DEFINED","UNKNOWN"].forEach(goal=>{const value=api.createRecommendationRequest(request({requestedGoal:goal}));equal(value.requestedGoal,goal);});["PRICE_ONLY","TOTAL_COST","QUALITY_BALANCE","RISK_AWARE","USER_PRIORITY","UNKNOWN"].forEach(mode=>equal(api.createRecommendationRequest(request({comparisonMode:mode})).comparisonMode,mode));});
// Group 2: Candidate structure.
test("preserves empty unknown and multiple candidates without selecting a winner",()=>{const api=load(),empty=api.createEmptyRecommendationResult(request(),deps()),unknown=api.validateRecommendationCandidate(candidate(1)),multiple=[candidate(1),candidate(2,{selectionStatus:"CONSIDER"}),candidate(3,{selectionStatus:"NOT_READY"})].map(api.validateRecommendationCandidate);equal(empty.candidates.length,0);equal(unknown.selectionStatus,"UNKNOWN");equal(multiple.length,3);multiple.forEach(value=>truth(["UNKNOWN","CONSIDER","NOT_READY"].includes(value.selectionStatus)));truth(multiple.every(value=>!Object.prototype.hasOwnProperty.call(value,"winner")));});
test("validates price comparison and user preference metadata without inferring value",()=>{const api=load(),r=api.createRecommendationRequest(request({normalizedPrices:[reference(1),reference(2)],userPreferences:["DIRECT_ROUTE"],constraints:["NO_AUTOMATIC_PURCHASE"]}));equal(r.normalizedPrices.length,2);equal(r.normalizedPrices[0].comparisonReadiness,"BLOCKED");equal(r.userPreferences[0],"DIRECT_ROUTE");equal(r.constraints[0],"NO_AUTOMATIC_PURCHASE");});
// Group 3: Evidence preservation.
test("preserves factors risks and explanation evidence classification",()=>{const api=load(),factor=api.validateRecommendationFactor({factorType:"PRICE",valueState:"UNKNOWN",evidenceType:"FACT",confidence:"LOW",explanation:"Missing total",limitations:["NO_AMOUNT"]}),risk=api.validateRecommendationRisk({riskType:"PRICE_CHANGE",valueState:"UNKNOWN",evidenceType:"ASSUMPTION",confidence:"LOW",explanation:"May change",limitations:["UNVERIFIED"]}),referenceValue=api.validateRecommendationExplanationReference({referenceId:"evidence-1",evidenceType:"UNKNOWN",limitations:["MISSING"]});equal(factor.evidenceType,"FACT");equal(risk.evidenceType,"ASSUMPTION");equal(referenceValue.evidenceType,"UNKNOWN");truth(Object.isFrozen(factor));truth(Object.isFrozen(risk));});
test("rejects missing evidence and invalid unknown fields",()=>{const api=load();throws(()=>api.validateRecommendationCandidate(candidate(1,{evidenceState:"OTHER"})));throws(()=>api.validateRecommendationFactor({factorType:"PRICE",valueState:"UNKNOWN",evidenceType:"UNKNOWN",confidence:"UNKNOWN",explanation:"x",limitations:[],extra:"x"}));throws(()=>api.createRecommendationRequest(request({normalizedPrices:[Object.assign(reference(1),{extra:"x"})]})));});
// Group 4: Security rejection.
test("rejects sensitive getters functions symbols cycles and prototype pollution",()=>{const api=load(),base=request(),getter=request(),cycle=request();Object.defineProperty(getter,"requestId",{get(){return"x";},enumerable:true});cycle.self=cycle;[Object.assign(request(),{token:"x"}),getter,Object.assign(request(),{domain:()=>"PRODUCT"}),Object.assign(request(),{domain:Symbol("x")}),cycle,JSON.parse('{"__proto__":{"polluted":true}}')].forEach(value=>throws(()=>api.createRecommendationRequest(value)));});
test("deep freezes outputs and preserves source inputs",()=>{const api=load(),source=request({normalizedPrices:[reference(1)]}),value=api.createRecommendationRequest(source);source.normalizedPrices[0].currency="USD";equal(value.normalizedPrices[0].currency,"UNKNOWN");truth(Object.isFrozen(value));truth(Object.isFrozen(value.normalizedPrices));throws(()=>{value.requestId="other";});});
// Group 5: Determinism and compatibility.
test("is deterministic with injected result dependencies",()=>{const api=load(),a=api.createEmptyRecommendationResult(request({normalizedPrices:[reference(1)]}),deps()),b=api.createEmptyRecommendationResult(request({normalizedPrices:[reference(1)]}),deps());assertions++;assert.deepEqual(JSON.parse(JSON.stringify(a)),JSON.parse(JSON.stringify(b)));});
test("keeps forward versions under review and execution closed",()=>{const api=load();equal(api.assessCompatibility("P8_RECOMMENDATION_V1").status,"BACKWARD_COMPATIBLE");equal(api.assessCompatibility("P8_RECOMMENDATION_V2").status,"FORWARD_REVIEW_REQUIRED");equal(api.PACKAGE.executionGate,"CLOSED");equal(api.PACKAGE.authorizesExecution,false);equal(api.PACKAGE.recommendationGeneration,false);equal(api.PACKAGE.ranking,false);equal(api.PACKAGE.providerSelection,false);equal(api.PACKAGE.userAction,false);});
test("is isolated from AI ranking provider purchase redirect UI and persistence",()=>{const source=recommendationFiles.map(f=>fs.readFileSync(path.join(recommendation,f),"utf8")).join("\n");["fetch(","XMLHttpRequest","require(","electron","CommandApi","ProviderDiscovery","rankCandidates","LLM","prompt","checkout","booking","redirect","localStorage","navigator.geolocation","Date.now","Math.random"].forEach(token=>equal(source.includes(token),false,token));});
tests.forEach(({run})=>run());console.log("P8_WP008_RECOMMENDATION_CONTRACT PASS "+tests.length+" tests "+assertions+" assertions");
