"use strict";

const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const root=path.resolve(__dirname,"../.."),shared=path.join(root,"apps/desktop/src/renderer/core/commerceShadow/contracts"),price=path.join(root,"apps/desktop/src/renderer/core/commerceShadow/price/contracts"),sharedFiles=["sharedCommerceContractTypes.js","sharedCommerceContractValidation.js","sharedCommerceContracts.js","sharedCommerceContractPackage.js"],priceFiles=["priceAuthorityTypes.js","priceAuthorityValidation.js","priceAuthorityContracts.js","priceAuthorityPackage.js"],tests=[];
function test(name,run){tests.push({name,run});}function load(){const w={};w.window=w;const c=vm.createContext({window:w});sharedFiles.forEach(f=>vm.runInContext(fs.readFileSync(path.join(shared,f),"utf8"),c,{filename:f}));priceFiles.forEach(f=>vm.runInContext(fs.readFileSync(path.join(price,f),"utf8"),c,{filename:f}));return w.WeishanPriceAuthorityPackage;}function deps(){let n=0;return{clock:()=>"2026-08-02T00:00:00.000Z",idGenerator:()=>"authority-"+(++n)};}
test("defines every approved price state without generating a price",()=>{const api=load(),states=JSON.parse(JSON.stringify(api.PACKAGE.enums.PRICE_STATE));assert.deepEqual(states,["REFERENCE","ESTIMATED","CACHED","LIVE_QUOTE","STALE_QUOTE","FINAL_CHECKOUT","UNKNOWN"]);const value=api.createUnknownPriceAuthority(deps());assert.equal(Object.prototype.hasOwnProperty.call(value,"amount"),false);assert.equal(value.priceState,"UNKNOWN");});
test("creates an explicit unknown authority boundary",()=>{const api=load(),value=api.createUnknownPriceAuthority(deps());assert.equal(value.evidence.source,"UNKNOWN");assert.equal(value.timestamp.capturedAt,"UNKNOWN");assert.equal(value.expiration.expiresAt,"UNKNOWN");assert.equal(value.confidence,"UNKNOWN");assert.equal(value.currency,"UNKNOWN");assert.ok(value.limitations.includes("EXTERNAL_CHECKOUT_REMAINS_FINAL_AUTHORITY"));assert.ok(value.unknownFields.includes("amount"));});
test("deeply freezes defensively copied authority metadata",()=>{const api=load(),value=api.createUnknownPriceAuthority(deps());assert.equal(Object.isFrozen(value),true);assert.equal(Object.isFrozen(value.evidence),true);assert.equal(Object.isFrozen(value.unknownFields),true);assert.throws(()=>{value.priceState="LIVE_QUOTE";});});
test("validates complete schema and rejects unknown or malformed fields",()=>{const api=load(),value=api.createUnknownPriceAuthority(deps());assert.deepEqual(JSON.parse(JSON.stringify(api.validatePriceAuthority(value))),JSON.parse(JSON.stringify(value)));[Object.assign({},value,{extra:"x"}),Object.assign({},value,{priceState:"OTHER"}),Object.assign({},value,{executionGate:"OPEN"}),Object.assign({},value,{currency:""})].forEach(input=>assert.throws(()=>api.validatePriceAuthority(input)));});
test("rejects sensitive executable cyclic and prototype-polluted values",()=>{const api=load(),value=api.createUnknownPriceAuthority(deps()),getter=JSON.parse(JSON.stringify(value)),cycle=JSON.parse(JSON.stringify(value));Object.defineProperty(getter,"authorityId",{get(){return"x";},enumerable:true});cycle.self=cycle;[Object.assign({},value,{token:"x"}),getter,Object.assign({},value,{currency:()=>"USD"}),Object.assign({},value,{currency:Symbol("x")}),cycle,JSON.parse('{"__proto__":{"polluted":true}}')].forEach(input=>assert.throws(()=>api.validatePriceAuthority(input)));});
test("is deterministic with injected identities and clocks",()=>{const api=load(),a=api.createUnknownPriceAuthority(deps()),b=api.createUnknownPriceAuthority(deps());assert.deepEqual(JSON.parse(JSON.stringify(a)),JSON.parse(JSON.stringify(b)));});
test("keeps forward versions under review and current version compatible",()=>{const api=load();assert.equal(api.assessCompatibility("P8_PRICE_AUTHORITY_V1").status,"BACKWARD_COMPATIBLE");assert.equal(api.assessCompatibility("P8_PRICE_AUTHORITY_V2").status,"FORWARD_REVIEW_REQUIRED");});
test("contains no price engine provider network search or runtime capability",()=>{const source=priceFiles.map(f=>fs.readFileSync(path.join(price,f),"utf8")).join("\n");["fetch(","XMLHttpRequest","require(","electron","CommandApi","ProviderDiscovery","searchProvider","priceQuote","checkout","localStorage","navigator.geolocation"].forEach(token=>assert.equal(source.includes(token),false,token));});
test("keeps package execution closed",()=>{const api=load();assert.equal(api.PACKAGE.executionGate,"CLOSED");assert.equal(api.PACKAGE.authorizesExecution,false);assert.equal(api.PACKAGE.priceEngine,false);assert.equal(api.PACKAGE.providerAccess,false);assert.equal(api.PACKAGE.networkAccess,false);});
tests.forEach(({run})=>run());console.log("P8_WP006_PRICE_AUTHORITY_CONTRACT PASS "+tests.length);
