"use strict";

const assert = require("node:assert/strict"), fs = require("node:fs"), path = require("node:path"), vm = require("node:vm");
const root = path.resolve(__dirname, "../.."), directory = path.join(root, "apps/desktop/src/renderer/core/commerceShadow/contracts");
const files = ["sharedCommerceContractTypes.js", "sharedCommerceContractValidation.js", "sharedCommerceContracts.js", "sharedCommerceContractPackage.js"], cases = [];
function test(name, run) { cases.push({name, run}); }
function load() { const windowRef = {}; windowRef.window = windowRef; const context = vm.createContext({window:windowRef}); files.forEach((file) => vm.runInContext(fs.readFileSync(path.join(directory, file), "utf8"), context, {filename:file})); return windowRef.WeishanSharedCommerceContractPackage; }
function request() { return {contractVersion:"P8_SHARED_CONTRACT_V1",requestId:"request-1",userGoal:"Compare flights",marketContext:{market:"UNKNOWN",status:"UNKNOWN"},constraints:{items:["FLEXIBLE"],unknowns:["DATE"]},userDecisionRequired:true,executionGate:"CLOSED",authorizesExecution:false}; }
function result() { return {contractVersion:"P8_SHARED_CONTRACT_V1",resultId:"result-1",status:"PARTIAL",facts:["PRICE_UNKNOWN"],evidence:["UNKNOWN"],priceState:"UNKNOWN",recommendationCategory:"UNKNOWN",explanationCategories:["WHY","UNKNOWN"],confidence:"LOW",unknowns:["TAX"],userDecisionRequired:true,executionGate:"CLOSED",authorizesExecution:false}; }
function failure() { return {contractVersion:"P8_SHARED_CONTRACT_V1",failureId:"failure-1",status:"FAILED",category:"AUTHORITY",code:"MISSING_EVIDENCE",message:"Evidence is missing",retryable:false,limitations:["UNKNOWN"],userDecisionRequired:true,executionGate:"CLOSED",authorizesExecution:false}; }
// Group 1: schema validation and unknown handling.
test("creates strict request, result, failure, and response DTOs", () => { const api=load(), a=api.createRequest(request()), b=api.createResult(result()), c=api.createFailure(failure()), d=api.createResponse({contractVersion:"P8_SHARED_CONTRACT_V1",requestId:"request-1",status:"FAILED",result:null,failure:c,userDecisionRequired:true,executionGate:"CLOSED",authorizesExecution:false}); assert.equal(a.requestId,"request-1"); assert.equal(b.priceState,"UNKNOWN"); assert.equal(c.category,"AUTHORITY"); assert.equal(d.failure.code,"MISSING_EVIDENCE"); });
test("rejects unknown DTO fields and open execution", () => { const api=load(); assert.throws(() => api.createRequest(Object.assign(request(),{futureField:true})),/invalid_request_contract/); assert.throws(() => api.createRequest(Object.assign(request(),{executionGate:"OPEN"})),/invalid_request_contract/); assert.throws(() => api.createResponse({contractVersion:"P8_SHARED_CONTRACT_V1",requestId:"request-1",status:"FAILED",result:null,failure:{},userDecisionRequired:true,executionGate:"CLOSED",authorizesExecution:false}),/invalid_failure_contract/); });
test("rejects secret-like, accessor, function, symbol, circular, and polluted inputs", () => { const api=load(), getter=request(), circular=request(); Object.defineProperty(getter,"userGoal",{get(){return "x";},enumerable:true}); circular.constraints.self=circular; [Object.assign(request(),{apiKey:"x"}),getter,Object.assign(request(),{userGoal:()=>"x"}),Object.assign(request(),{userGoal:Symbol("x")}),circular,JSON.parse('{"__proto__":{"polluted":true}}')].forEach((value) => assert.throws(() => api.createRequest(value))); });
// Group 2: serialization and determinism.
test("serializes into JSON-safe immutable data", () => { const api=load(), value=api.createResult(result()); assert.deepEqual(JSON.parse(JSON.stringify(value)),JSON.parse(JSON.stringify(result()))); });
test("returns deterministic output for identical input", () => { const api=load(); assert.deepEqual(JSON.parse(JSON.stringify(api.createRequest(request()))),JSON.parse(JSON.stringify(api.createRequest(request())))); });
// Group 3: deep immutability and input isolation.
test("deep-freezes contracts without mutating inputs", () => { const api=load(), input=result(), value=api.createResult(input); input.unknowns.push("CURRENCY"); assert.equal(value.unknowns.length,1); assert.equal(Object.isFrozen(value),true); assert.equal(Object.isFrozen(value.unknowns),true); });
test("exposes a frozen non-runtime package", () => { const api=load(); assert.equal(Object.isFrozen(api.PACKAGE),true); assert.equal(api.PACKAGE.executionGate,"CLOSED"); assert.equal(api.PACKAGE.authorizesExecution,false); assert.equal(api.PACKAGE.runtimeImplemented,false); });
// Group 4: backward and forward compatibility.
test("accepts only the current identical contract version as backward compatible", () => { const status=load().assessCompatibility("P8_SHARED_CONTRACT_V1"); assert.equal(status.backwardCompatible,true); assert.equal(status.status,"BACKWARD_COMPATIBLE"); });
test("requires review instead of interpreting an unknown future version", () => { const status=load().assessCompatibility("P8_SHARED_CONTRACT_V2"); assert.equal(status.forwardCompatible,false); assert.equal(status.status,"FORWARD_REVIEW_REQUIRED"); });
// Group 5: package isolation and contract inventory.
test("contains all required shared enums and interface definitions", () => { const api=load(), enums=api.PACKAGE.enums; ["STATUS","CONFIDENCE","EVIDENCE","PRICE_STATE","RECOMMENDATION_CATEGORY","EXPLANATION_CATEGORY","FAILURE_CATEGORY"].forEach((key) => assert.ok(Array.isArray(enums[key]))); ["request","result","failure","response"].forEach((key) => assert.equal(api.PACKAGE.contracts[key].immutable,true)); });
test("has no production or network import surface", () => { const source=files.map((file) => fs.readFileSync(path.join(directory,file),"utf8")).join("\n"); ["require(","fetch(","XMLHttpRequest","electron","CommandApi","Provider","Scheduler","Workspace"].forEach((token) => assert.equal(source.includes(token),false,token)); });
cases.forEach(({run}) => run()); console.log("P8_WP001_SHARED_CONTRACT_ALIGNMENT PASS "+cases.length);
