"use strict";

const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const root=path.resolve(__dirname,"../.."),shared=path.join(root,"apps/desktop/src/renderer/core/commerceShadow/contracts"),priceContracts=path.join(root,"apps/desktop/src/renderer/core/commerceShadow/price/contracts"),normalization=path.join(root,"apps/desktop/src/renderer/core/commerceShadow/price/normalization"),recommendation=path.join(root,"apps/desktop/src/renderer/core/commerceShadow/recommendation"),engine=path.join(recommendation,"engine"),sharedFiles=["sharedCommerceContractTypes.js","sharedCommerceContractValidation.js","sharedCommerceContracts.js","sharedCommerceContractPackage.js"],authorityFiles=["priceAuthorityTypes.js","priceAuthorityValidation.js","priceAuthorityContracts.js","priceAuthorityPackage.js"],normalizationFiles=["priceNormalizationTypes.js","priceNormalizationValidation.js","priceNormalizationCore.js","priceNormalizationPackage.js"],recommendationFiles=["recommendationTypes.js","recommendationValidation.js","recommendationContracts.js","recommendationPackage.js"],engineFiles=["recommendationEngineTypes.js","recommendationEngineValidation.js","recommendationEngineCore.js","recommendationEnginePackage.js"],tests=[];let assertions=0;
function equal(a,b,m){assertions++;assert.equal(a,b,m);}function truth(a,m){assertions++;assert.ok(a,m);}function throws(f,m){assertions++;assert.throws(f,m);}function test(name,run){tests.push({name,run});}function load(){const w={};w.window=w;const c=vm.createContext({window:w});sharedFiles.forEach(f=>vm.runInContext(fs.readFileSync(path.join(shared,f),"utf8"),c,{filename:f}));authorityFiles.forEach(f=>vm.runInContext(fs.readFileSync(path.join(priceContracts,f),"utf8"),c,{filename:f}));normalizationFiles.forEach(f=>vm.runInContext(fs.readFileSync(path.join(normalization,f),"utf8"),c,{filename:f}));recommendationFiles.forEach(f=>vm.runInContext(fs.readFileSync(path.join(recommendation,f),"utf8"),c,{filename:f}));engineFiles.forEach(f=>vm.runInContext(fs.readFileSync(path.join(engine,f),"utf8"),c,{filename:f}));return w;}function deps(){let n=0;return{clock:()=>"2026-08-02T00:00:00.000Z",idGenerator:()=>"engine-"+(++n)};}function request(extra){return Object.assign({schemaVersion:"P8_RECOMMENDATION_V1",requestId:"request-1",domain:"PRODUCT",marketContextId:"market-1",normalizedPrices:[],userPreferences:[],constraints:[],comparisonMode:"RISK_AWARE",requestedGoal:"MOST_RELIABLE",limitations:[]},extra||{});}function candidate(id,extra){return Object.assign({candidateId:id,sourceReference:"UNKNOWN",normalizedPriceReference:{normalizationId:"norm-"+id,authorityId:"authority-"+id,currency:"USD",comparisonReadiness:"READY"},providerReference:"UNKNOWN",availabilityState:"AVAILABLE",advantages:[],disadvantages:[],risks:[],confidence:"MEDIUM",evidenceState:"FACT",limitations:[],selectionStatus:"CONSIDER"},extra||{});}function output(req,candidates){const w=load();return w.WeishanRecommendationEnginePackage.generateRecommendationEnvelope(req||request(),candidates||[],deps());}
// Group 1: Recommendation generation.
test("generates a valid unchanged WP008 result inside the engine envelope",()=>{const w=load(),input=request(),items=[candidate("a")],value=w.WeishanRecommendationEnginePackage.generateRecommendationEnvelope(input,items,deps()),checked=w.WeishanRecommendationPackage.validateRecommendationResult(value.recommendationResult);assertions++;assert.deepEqual(JSON.parse(JSON.stringify(checked)),JSON.parse(JSON.stringify(value.recommendationResult)));equal(value.engineStatus,"GENERATED");equal(value.userDecisionRequired,true);equal(value.executed,false);equal(value.productionAffected,false);truth(!Object.prototype.hasOwnProperty.call(value.recommendationResult.candidates[0],"analysisCategory"));});
test("supports explicit user preference match without winner semantics",()=>{const value=output(request({userPreferences:["a"]}),[candidate("a"),candidate("b")]);truth(value.reasons.some(item=>item.reasonType==="USER_PREFERENCE_MATCH"));truth(value.reasons.every(item=>item.summary!=="BEST"));truth(value.recommendationResult.candidates.every(item=>!Object.prototype.hasOwnProperty.call(item,"winner")));equal(value.recommendationResult.status,"PENDING_USER_DECISION");});
test("represents empty candidates as no recommendation",()=>{const value=output(request(),[]);equal(value.engineStatus,"NO_RECOMMENDATION");truth(value.analysisCategories.includes("NO_RECOMMENDATION"));equal(value.recommendationResult.status,"NO_RECOMMENDATION_GENERATED");equal(value.reasons.length,0);});
// Group 2: Comparison readiness.
test("represents readiness, insufficient evidence, and blocked candidates without mapping selection status",()=>{const ready=output(request(),[candidate("a")]),insufficient=output(request(),[candidate("b",{normalizedPriceReference:{normalizationId:"n",authorityId:"a",currency:"USD",comparisonReadiness:"BLOCKED"}})]),blocked=output(request(),[candidate("c",{selectionStatus:"BLOCKED"})]);truth(ready.analysisCategories.includes("SUPPORTED"));equal(insufficient.engineStatus,"INSUFFICIENT_EVIDENCE");truth(insufficient.analysisCategories.includes("INSUFFICIENT_EVIDENCE"));equal(blocked.engineStatus,"BLOCKED");equal(blocked.recommendationResult.candidates[0].selectionStatus,"BLOCKED");});
test("marks currency mismatch not comparable and propagates risk",()=>{const value=output(request(),[candidate("a"),candidate("b",{normalizedPriceReference:{normalizationId:"n-b",authorityId:"a-b",currency:"EUR",comparisonReadiness:"READY"}})]);equal(value.engineStatus,"NOT_COMPARABLE");truth(value.analysisCategories.includes("NOT_COMPARABLE"));truth(value.risks.some(item=>item.riskType==="CURRENCY_NOT_COMPARABLE"));truth(value.warnings.includes("CURRENCY_NOT_COMPARABLE"));});
// Group 3: Evidence propagation.
test("propagates unknown evidence fees availability and stale risks",()=>{const value=output(request(),[candidate("a",{evidenceState:"UNKNOWN",availabilityState:"UNKNOWN",limitations:["UNKNOWN_FEES","STALE_QUOTE"]})]);equal(value.engineStatus,"INSUFFICIENT_EVIDENCE");["LIMITED_EVIDENCE","UNKNOWN_AVAILABILITY","UNKNOWN_FEES","STALE_QUOTE"].forEach(type=>truth(value.risks.some(item=>item.riskType===type),type));truth(value.reasons.every(item=>item.confidence==="MEDIUM"||item.confidence==="UNKNOWN"));});
test("preserves evidence-backed reasons and bounded confidence",()=>{const value=output(request({userPreferences:["a"]}),[candidate("a",{confidence:"LOW"})]),reason=value.reasons[0];equal(reason.evidenceType,"FACT");equal(reason.confidence,"LOW");equal(reason.reasonType,"USER_PREFERENCE_MATCH");truth(reason.limitations.length>0);});
// Group 4: Security rejection.
test("rejects accessors functions symbols cycles prototype pollution and sensitive fields",()=>{const w=load(),d=deps(),base=request(),getter=request(),cycle=request();Object.defineProperty(getter,"requestId",{get(){return"x";},enumerable:true});cycle.self=cycle;[Object.assign(request(),{token:"x"}),getter,Object.assign(request(),{domain:()=>"PRODUCT"}),Object.assign(request(),{domain:Symbol("x")}),cycle,JSON.parse('{"__proto__":{"polluted":true}}')].forEach(value=>throws(()=>w.WeishanRecommendationEnginePackage.generateRecommendationEnvelope(value,[],d)));});
test("returns immutable output and does not mutate candidates",()=>{const items=[candidate("a")],value=output(request(),items);items[0].confidence="HIGH";equal(value.recommendationResult.candidates[0].confidence,"MEDIUM");truth(Object.isFrozen(value));truth(Object.isFrozen(value.recommendationResult));truth(Object.isFrozen(value.reasons));throws(()=>{value.engineStatus="FAILED";});});
// Group 5: Determinism.
test("is deterministic across ready unknown blocked and empty scenarios",()=>{[[request(),[candidate("a")]],[request(),[candidate("a",{evidenceState:"UNKNOWN"})]],[request(),[candidate("a",{selectionStatus:"BLOCKED"})]],[request(),[]]].forEach(pair=>{const a=output(pair[0],pair[1]),b=output(pair[0],pair[1]);assertions++;assert.deepEqual(JSON.parse(JSON.stringify(a)),JSON.parse(JSON.stringify(b)));});});
test("keeps engine compatibility and execution boundary closed",()=>{const w=load(),api=w.WeishanRecommendationEnginePackage;equal(api.assessCompatibility("P8_RECOMMENDATION_ENGINE_V1").status,"BACKWARD_COMPATIBLE");equal(api.assessCompatibility("P8_RECOMMENDATION_ENGINE_V2").status,"FORWARD_REVIEW_REQUIRED");equal(api.PACKAGE.executionGate,"CLOSED");equal(api.PACKAGE.authorizesExecution,false);equal(api.PACKAGE.providerInvocation,false);equal(api.PACKAGE.automaticSelection,false);equal(api.PACKAGE.ranking,false);equal(api.PACKAGE.externalAI,false);});
test("is isolated from provider network purchase redirect UI LLM and nondeterminism",()=>{const source=engineFiles.map(f=>fs.readFileSync(path.join(engine,f),"utf8")).join("\n");["fetch(","XMLHttpRequest","require(","electron","CommandApi","ProviderDiscovery","checkout","booking","payment","redirect","prompt","LLM","localStorage","navigator.geolocation","Date.now","Math.random"].forEach(token=>equal(source.includes(token),false,token));});
tests.forEach(({run})=>run());console.log("P8_WP009_RECOMMENDATION_SHADOW_ENGINE PASS "+tests.length+" tests "+assertions+" assertions");
