"use strict";

const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const root=path.resolve(__dirname,"../.."),shared=path.join(root,"apps/desktop/src/renderer/core/commerceShadow/contracts"),market=path.join(root,"apps/desktop/src/renderer/core/commerceShadow/market"),resolver=path.join(root,"apps/desktop/src/renderer/core/commerceShadow/marketResolver"),sharedFiles=["sharedCommerceContractTypes.js","sharedCommerceContractValidation.js","sharedCommerceContracts.js","sharedCommerceContractPackage.js"],marketFiles=["marketContextTypes.js","marketContextValidation.js","marketContextContracts.js","marketContextPackage.js"],resolverFiles=["marketResolverTypes.js","marketResolverValidation.js","marketResolverCore.js","marketResolverPackage.js"],tests=[];let assertions=0;
function equal(a,b,m){assertions++;assert.equal(a,b,m);}function truth(a,m){assertions++;assert.ok(a,m);}function throws(f,m){assertions++;assert.throws(f,m);}function test(name,run){tests.push({name,run});}
function load(){const w={};w.window=w;const c=vm.createContext({window:w});sharedFiles.forEach(f=>vm.runInContext(fs.readFileSync(path.join(shared,f),"utf8"),c,{filename:f}));marketFiles.forEach(f=>vm.runInContext(fs.readFileSync(path.join(market,f),"utf8"),c,{filename:f}));resolverFiles.forEach(f=>vm.runInContext(fs.readFileSync(path.join(resolver,f),"utf8"),c,{filename:f}));return w;}
function deps(){let n=0;return{clock:()=>"2026-08-02T00:00:00.000Z",idGenerator:()=>"resolution-"+(++n)};}function loc(country,source,region,city){return{country,region:region||"UNKNOWN",city:city||"UNKNOWN",postalCode:"UNKNOWN",source:source||"TASK_DESTINATION"};}
function input(extra){return Object.assign({domain:"PRODUCT",accountCountry:loc("CN","USER_DEFAULT"),savedDestination:null,temporaryOverride:null,taskDestination:loc("JP"),hotelDestination:null,flightOrigin:null,flightDestination:null,paymentRegion:loc("CN","USER_DEFAULT"),preference:{userDefaultMarket:loc("CN","USER_DEFAULT"),systemLocaleHint:loc("US","SYSTEM_LOCALE_HINT"),requestedCurrency:"JPY",language:"en"},overrideStatus:"NONE"},extra||{});}function result(extra){const w=load(),context=w.WeishanMarketContextPackage.createMarketContext(input(extra),deps());return w.WeishanMarketResolverPackage.resolveMarket(context,deps());}
// Group 1: precedence resolution.
test("resolves every approved source deterministically",()=>{const scenarios=[{extra:{temporaryOverride:loc("US","USER_TEMPORARY_OVERRIDE"),overrideStatus:"ACTIVE"},source:"USER_TEMPORARY_OVERRIDE",country:"US"},{extra:{},source:"TASK_DESTINATION",country:"JP"},{extra:{taskDestination:null,savedDestination:loc("DE","SAVED_DESTINATION")},source:"SAVED_DESTINATION",country:"DE"},{extra:{taskDestination:null,preference:{userDefaultMarket:loc("GB","USER_DEFAULT"),systemLocaleHint:loc("US","SYSTEM_LOCALE_HINT"),requestedCurrency:"GBP",language:"en"}},source:"USER_DEFAULT",country:"GB"},{extra:{taskDestination:null,preference:{userDefaultMarket:loc("UNKNOWN","UNKNOWN"),systemLocaleHint:loc("US","SYSTEM_LOCALE_HINT"),requestedCurrency:"USD",language:"en"}},source:"SYSTEM_LOCALE_HINT",country:"US"},{extra:{taskDestination:null,preference:{userDefaultMarket:loc("UNKNOWN","UNKNOWN"),systemLocaleHint:loc("UNKNOWN","UNKNOWN"),requestedCurrency:"UNKNOWN",language:"UNKNOWN"}},source:"UNKNOWN",country:"UNKNOWN"}];scenarios.forEach(s=>{const r=result(s.extra);equal(r.selectionSource,s.source);equal(r.resolvedCountry,s.country);equal(r.executed,false);equal(r.productionAffected,false);truth(Object.isFrozen(r));});});
test("records ignored lower priority sources without changing winning source",()=>{["USER_TEMPORARY_OVERRIDE","TASK_DESTINATION","SAVED_DESTINATION","USER_DEFAULT","SYSTEM_LOCALE_HINT"].forEach((source,index)=>{const extras=[{temporaryOverride:loc("US","USER_TEMPORARY_OVERRIDE"),overrideStatus:"CONFIRMED"},{},{taskDestination:null,savedDestination:loc("DE","SAVED_DESTINATION")},{taskDestination:null,preference:{userDefaultMarket:loc("GB","USER_DEFAULT"),systemLocaleHint:loc("US","SYSTEM_LOCALE_HINT"),requestedCurrency:"GBP",language:"en"}},{taskDestination:null,preference:{userDefaultMarket:loc("UNKNOWN","UNKNOWN"),systemLocaleHint:loc("US","SYSTEM_LOCALE_HINT"),requestedCurrency:"USD",language:"en"}}][index],r=result(extras);equal(r.explanation.winningSource,source);truth(r.explanation.ignoredLowerPrioritySources.length>0);});});
// Group 2: domain-specific resolution.
test("preserves distinct flight origin and destination",()=>{for(let i=0;i<20;i++){const r=result({domain:"FLIGHT",taskDestination:null,flightOrigin:loc(i%2?"CN":"US"),flightDestination:loc(i%2?"JP":"GB", "TASK_DESTINATION","Tokyo","Tokyo")});equal(r.status,"RESOLVED");equal(r.resolvedCountry,i%2?"JP":"GB");equal(r.requiresUserConfirmation,false);}});
test("uses hotel destination and product delivery destination",()=>{for(let i=0;i<20;i++){const hotel=result({domain:"HOTEL",taskDestination:null,hotelDestination:loc(i%2?"JP":"DE","TASK_DESTINATION","Tokyo","Tokyo")}),product=result({domain:"PRODUCT",taskDestination:loc(i%2?"US":"GB")});equal(hotel.resolvedCountry,i%2?"JP":"DE");equal(hotel.status,"RESOLVED");equal(product.resolvedCountry,i%2?"US":"GB");equal(product.status,"RESOLVED");}});
test("keeps payment region and requested currency independent",()=>{for(let i=0;i<12;i++){const r=result({paymentRegion:loc("CN","USER_DEFAULT"),preference:{userDefaultMarket:loc("CN","USER_DEFAULT"),systemLocaleHint:loc("US","SYSTEM_LOCALE_HINT"),requestedCurrency:i%2?"USD":"JPY",language:"en"}});equal(r.resolvedCountry,"JP");equal(r.resolvedCurrency,i%2?"USD":"JPY");truth(r.warnings.includes("PAYMENT_REGION_DIFFERS_FROM_TARGET_MARKET"));}});
// Group 3: conflict and ambiguity.
test("requires confirmation for every documented ambiguity",()=>{const cases=[{domain:"FLIGHT",taskDestination:null,flightOrigin:null,flightDestination:loc("JP")},{domain:"FLIGHT",taskDestination:null,flightOrigin:loc("CN"),flightDestination:null},{domain:"HOTEL",taskDestination:null,hotelDestination:loc("JP")},{domain:"FLIGHT",taskDestination:null,flightOrigin:loc("CN"),flightDestination:loc("JP")}];cases.forEach((value,index)=>{const r=result(value);if(index===3){equal(r.status,"AMBIGUOUS");}else truth(["AMBIGUOUS","UNKNOWN"].includes(r.status));equal(r.requiresUserConfirmation,true);truth(r.limitations.length>0);});});
test("returns conflicted results rather than selecting an unsafe winner",()=>{for(let i=0;i<10;i++){const w=load(),context=w.WeishanMarketContextPackage.createMarketContext(input({domain:"FLIGHT",taskDestination:null,flightOrigin:loc("JP"),flightDestination:loc("JP", "TASK_DESTINATION","Tokyo","Tokyo")}),deps()),r=w.WeishanMarketResolverPackage.resolveMarket(context,deps());equal(r.status,"CONFLICTED");equal(r.requiresUserConfirmation,true);truth(r.conflicts.includes("FLIGHT_ORIGIN_DESTINATION_NOT_DISTINCT"));}});
test("rejects malformed contexts and unsupported domains safely",()=>{const w=load(),good=w.WeishanMarketContextPackage.createMarketContext(input(),deps()),bad=JSON.parse(JSON.stringify(good));bad.domain="OTHER";throws(()=>w.WeishanMarketResolverPackage.resolveMarket(bad,deps()));const unknown=result({domain:"UNKNOWN",taskDestination:null});equal(unknown.status,"INVALID");truth(unknown.limitations.includes("UNSUPPORTED_DOMAIN"));});
test("marks contradictory market and country fields as conflicted",()=>{const w=load(),context=w.WeishanMarketContextPackage.createMarketContext(input(),deps()),contradictory=JSON.parse(JSON.stringify(context));contradictory.targetMarket="US";const r=w.WeishanMarketResolverPackage.resolveMarket(contradictory,deps());equal(r.status,"CONFLICTED");equal(r.requiresUserConfirmation,true);truth(r.conflicts.includes("MARKET_COUNTRY_CONTRADICTION"));});
// Group 4: security and immutability.
test("rejects sensitive values, accessors, functions, symbols, circular references, and unsafe prototypes",()=>{const w=load(),good=w.WeishanMarketContextPackage.createMarketContext(input(),deps()),getter=JSON.parse(JSON.stringify(good)),circular=JSON.parse(JSON.stringify(good));Object.defineProperty(getter,"contextId",{get(){return"x";},enumerable:true});circular.self=circular;[Object.assign({},good,{token:"x"}),getter,Object.assign({},good,{domain:()=>"PRODUCT"}),Object.assign({},good,{domain:Symbol("x")}),circular,JSON.parse('{"__proto__":{"polluted":true}}')].forEach(value=>throws(()=>w.WeishanMarketResolverPackage.resolveMarket(value,deps())));});
test("defensively copies and freezes every result boundary",()=>{const w=load(),context=w.WeishanMarketContextPackage.createMarketContext(input(),deps()),mutable=JSON.parse(JSON.stringify(context)),r=w.WeishanMarketResolverPackage.resolveMarket(mutable,deps());mutable.targetCountry="US";equal(r.resolvedCountry,"JP");truth(Object.isFrozen(r));truth(Object.isFrozen(r.explanation));throws(()=>{r.status="INVALID";});});
// Group 5: determinism and compatibility.
test("is structurally deterministic across 20 injected scenario pairs",()=>{for(let i=0;i<20;i++){const extra=i%2?{taskDestination:loc("JP")}:{taskDestination:null,preference:{userDefaultMarket:loc("UNKNOWN","UNKNOWN"),systemLocaleHint:loc("US","SYSTEM_LOCALE_HINT"),requestedCurrency:"USD",language:"en"}},a=result(extra),b=result(extra);assertions++;assert.deepEqual(JSON.parse(JSON.stringify(a)),JSON.parse(JSON.stringify(b)));}});
test("preserves closed execution boundaries and compatibility review",()=>{const w=load(),api=w.WeishanMarketResolverPackage,compat=api.assessCompatibility("P8_MARKET_RESOLVER_V2");equal(api.PACKAGE.executionGate,"CLOSED");equal(api.PACKAGE.authorizesExecution,false);equal(api.PACKAGE.executed,false);equal(api.PACKAGE.productionAffected,false);equal(compat.status,"FORWARD_REVIEW_REQUIRED");});
test("has no production, location, network, provider, persistence, or UI integration",()=>{const source=resolverFiles.map(f=>fs.readFileSync(path.join(resolver,f),"utf8")).join("\n");["fetch(","XMLHttpRequest","require(","electron","CommandApi","navigator.geolocation","localStorage","sessionStorage","indexedDB","fs.","ipc","ProviderRegistry","ProviderDiscovery"].forEach(token=>equal(source.includes(token),false,token));});
tests.forEach(({run})=>run());truth(assertions>=120,"meaningful assertion threshold");console.log("P8_WP003_MARKET_RESOLVER_SHADOW PASS "+tests.length+" tests "+assertions+" assertions");
