"use strict";

const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const root=path.resolve(__dirname,"../.."),shared=path.join(root,"apps/desktop/src/renderer/core/commerceShadow/contracts"),registry=path.join(root,"apps/desktop/src/renderer/core/commerceShadow/providerRegistry"),sharedFiles=["sharedCommerceContractTypes.js","sharedCommerceContractValidation.js","sharedCommerceContracts.js","sharedCommerceContractPackage.js"],registryFiles=["providerRegistryTypes.js","providerRegistryValidation.js","providerRegistryContracts.js","providerRegistryPackage.js"],tests=[];
function test(name,run){tests.push({name,run});}function load(){const w={};w.window=w;const c=vm.createContext({window:w});sharedFiles.forEach(f=>vm.runInContext(fs.readFileSync(path.join(shared,f),"utf8"),c,{filename:f}));registryFiles.forEach(f=>vm.runInContext(fs.readFileSync(path.join(registry,f),"utf8"),c,{filename:f}));return w.WeishanProviderRegistryPackage;}function deps(){let id=0;return{clock:()=>"2026-08-02T00:00:00.000Z",idGenerator:()=>"registry-"+(++id)};}
test("creates a default-deny empty registry",()=>{const api=load(),value=api.createDefaultProviderRegistry(deps());assert.equal(value.status,"NOT_REGISTERED");assert.deepEqual(JSON.parse(JSON.stringify(value.providers)),[]);assert.equal(value.executionGate,"CLOSED");assert.equal(value.authorizesExecution,false);assert.equal(value.executed,false);assert.equal(value.productionAffected,false);});
test("creates only the neutral unregistered descriptor",()=>{const api=load(),value=api.createDefaultProviderDescriptor(deps());assert.equal(value.providerId,"NOT_REGISTERED");assert.equal(value.providerType,"UNKNOWN");assert.equal(value.evidenceStatus,"UNKNOWN");assert.equal(value.approvalStatus,"NOT_APPROVED");assert.equal(value.availabilityStatus,"UNAVAILABLE");assert.deepEqual(JSON.parse(JSON.stringify(value.supportedMarkets)),[]);assert.deepEqual(JSON.parse(JSON.stringify(value.supportedDomains)),[]);});
test("keeps every default capability and coverage value non-activating",()=>{const api=load(),capability=api.defaultCapability(),coverage=api.defaultCoverage(),status=api.defaultStatus();Object.values(JSON.parse(JSON.stringify(capability))).forEach(value=>assert.equal(value,"UNKNOWN"));Object.values(JSON.parse(JSON.stringify(coverage))).forEach(value=>assert.deepEqual(value,[]));assert.deepEqual(JSON.parse(JSON.stringify(status)),{evidenceStatus:"UNKNOWN",approvalStatus:"NOT_APPROVED",availabilityStatus:"UNAVAILABLE"});});
test("validates only the neutral descriptor",()=>{const api=load(),value=api.createDefaultProviderDescriptor(deps()),checked=api.validateProviderDescriptor(value);assert.deepEqual(JSON.parse(JSON.stringify(checked)),JSON.parse(JSON.stringify(value)));[Object.assign({},value,{providerId:"REAL_PROVIDER"}),Object.assign({},value,{approvalStatus:"APPROVED"}),Object.assign({},value,{availabilityStatus:"AVAILABLE"}),Object.assign({},value,{supportedCountries:["US"]})].forEach(input=>assert.throws(()=>api.validateProviderDescriptor(input)));});
test("rejects sensitive and executable values",()=>{const api=load(),value=api.createDefaultProviderDescriptor(deps()),getter=JSON.parse(JSON.stringify(value)),circular=JSON.parse(JSON.stringify(value));Object.defineProperty(getter,"providerId",{get(){return"NOT_REGISTERED";},enumerable:true});circular.self=circular;[Object.assign({},value,{token:"x"}),getter,Object.assign({},value,{version:()=>"x"}),Object.assign({},value,{version:Symbol("x")}),circular,JSON.parse('{"__proto__":{"polluted":true}}')].forEach(input=>assert.throws(()=>api.validateProviderDescriptor(input)));});
test("returns deeply immutable defensive copies",()=>{const api=load(),source=api.createDefaultProviderDescriptor(deps()),copy=api.validateProviderDescriptor(JSON.parse(JSON.stringify(source)));assert.equal(Object.isFrozen(copy),true);assert.equal(Object.isFrozen(copy.capabilityDeclaration),true);assert.throws(()=>{copy.providerId="OTHER";});});
test("is deterministic with injected dependencies",()=>{const api=load(),a=api.createDefaultProviderRegistry(deps()),b=api.createDefaultProviderRegistry(deps()),da=api.createDefaultProviderDescriptor(deps()),db=api.createDefaultProviderDescriptor(deps());assert.deepEqual(JSON.parse(JSON.stringify(a)),JSON.parse(JSON.stringify(b)));assert.deepEqual(JSON.parse(JSON.stringify(da)),JSON.parse(JSON.stringify(db)));});
test("requires review for unknown contract versions",()=>{const api=load();assert.equal(api.assessCompatibility("P8_PROVIDER_REGISTRY_V1").status,"BACKWARD_COMPATIBLE");assert.equal(api.assessCompatibility("P8_PROVIDER_REGISTRY_V2").status,"FORWARD_REVIEW_REQUIRED");});
test("contains no registry activation, production import, discovery, network, or persistence capability",()=>{const source=registryFiles.map(f=>fs.readFileSync(path.join(registry,f),"utf8")).join("\n");["fetch(","XMLHttpRequest","require(","electron","CommandApi","navigator.geolocation","localStorage","sessionStorage","indexedDB","ProviderDiscovery","Registry.activate","apiKey"].forEach(token=>assert.equal(source.includes(token),false,token));});
test("keeps the package closed and does not expose a registration operation",()=>{const api=load();assert.equal(api.PACKAGE.executionGate,"CLOSED");assert.equal(api.PACKAGE.authorizesExecution,false);assert.equal(api.PACKAGE.registryActivation,false);assert.equal(api.PACKAGE.providerRegistration,false);assert.equal(Object.prototype.hasOwnProperty.call(api,"registerProvider"),false);});
tests.forEach(({run})=>run());console.log("P8_WP004_PROVIDER_REGISTRY_CONTRACT PASS "+tests.length);
