"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm"),root=path.resolve(__dirname,"../.."),base=path.join(root,"apps/desktop/src/renderer/core/commerceShadow");
const groups=[["contracts",["sharedCommerceContractTypes.js","sharedCommerceContractValidation.js","sharedCommerceContracts.js","sharedCommerceContractPackage.js"]],["price/contracts",["priceAuthorityTypes.js","priceAuthorityValidation.js","priceAuthorityContracts.js","priceAuthorityPackage.js"]],["price/normalization",["priceNormalizationTypes.js","priceNormalizationValidation.js","priceNormalizationCore.js","priceNormalizationPackage.js"]],["recommendation",["recommendationTypes.js","recommendationValidation.js","recommendationContracts.js","recommendationPackage.js"]],["recommendation/engine",["recommendationEngineTypes.js","recommendationEngineValidation.js","recommendationEngineCore.js","recommendationEnginePackage.js"]],["explanation",["explanationTypes.js","explanationValidation.js","explanationContracts.js","explanationPackage.js"]],["explanation/engine",["explanationEngineTypes.js","explanationEngineValidation.js","explanationEngineCore.js","explanationEnginePackage.js"]]];
function load(){const w={};w.window=w;const c=vm.createContext({window:w});groups.forEach(g=>g[1].forEach(f=>vm.runInContext(fs.readFileSync(path.join(base,g[0],f),"utf8"),c)));return w;}
function deps(){let n=0;return{clock:()=>"2026-08-02T00:00:00.000Z",idGenerator:()=>"id-"+(++n)};}
function request(language){return{schemaVersion:"P8_EXPLANATION_V1",explanationRequestId:"request-1",recommendationEngineResultId:"id-2",recommendationResultReference:{resultId:"result-1"},requestedLanguage:language||"en",requestedDetailLevel:"STANDARD",requestedSections:["SUMMARY","RISKS"],audienceContext:{mode:"USER"},limitations:[],createdAt:"time"};}
function result(w){const d=deps(),engine=w.WeishanRecommendationEnginePackage.generateRecommendationEnvelope({schemaVersion:"P8_RECOMMENDATION_V1",requestId:"r",domain:"PRODUCT",marketContextId:"m",normalizedPrices:[],userPreferences:[],constraints:[],comparisonMode:"UNKNOWN",requestedGoal:"UNKNOWN",limitations:[]},[],d);return w.WeishanExplanationPackage.createExplanationResult({explanationRequestId:"request-1",recommendationEngineResultId:engine.engineResultId,recommendationEngineEnvelope:engine,sections:[{sectionId:"risk",sectionType:"RISKS",claimReferences:[],evidenceReferences:[],riskReferences:[],assumptionReferences:[],limitationReferences:[],unknownReferences:[],presentationOrder:1,status:"PARTIAL"},{sectionId:"summary",sectionType:"SUMMARY",claimReferences:[],evidenceReferences:[],riskReferences:[],assumptionReferences:[],limitationReferences:[],unknownReferences:[],presentationOrder:0,status:"AVAILABLE"}],claims:[],evidenceReferences:[],assumptions:[],limitations:[],riskReferences:[],unknowns:[]},d);}
const w=load(),r=result(w),api=w.WeishanExplanationEnginePackage,e=api.presentExplanation(request(),r,deps());
assert.equal(e.language,"en");assert.deepEqual(Array.from(e.sectionPresentations,x=>x.sourceReference),["summary","risk"]);assert.deepEqual(JSON.parse(JSON.stringify(e.explanationResult)),JSON.parse(JSON.stringify(r)));assert.equal(e.userDecisionRequired,true);assert.equal(e.executed,false);assert.ok(Object.isFrozen(e));assert.ok(Object.isFrozen(e.explanationResult));assert.equal(api.presentExplanation(request("UNKNOWN"),r,deps()).sectionPresentations[0].text,"SECTION_REVIEW_REQUIRED");assert.equal(api.presentExplanation({...request(),explanationRequestId:"other"},r,deps()).presentationStatus,"FAILED");assert.equal(api.presentExplanation(request(),{...r,explanationRequestId:"other"},deps()).failureCode,"request_result_mismatch");assert.deepEqual(JSON.parse(JSON.stringify(e)),JSON.parse(JSON.stringify(api.presentExplanation(request(),r,deps()))));assert.equal(api.PACKAGE.executionGate,"CLOSED");assert.equal(api.PACKAGE.externalAI,false);
const source=groups[6][1].map(f=>fs.readFileSync(path.join(base,"explanation/engine",f),"utf8")).join("\n");["fetch(","XMLHttpRequest","require(","electron","Provider","Date.now","Math.random","localStorage","navigator."].forEach(token=>assert.equal(source.includes(token),false,token));console.log("P8_WP011_EXPLANATION_SHADOW_ENGINE PASS");
