"use strict";

const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const root=path.resolve(__dirname,"../.."),shared=path.join(root,"apps/desktop/src/renderer/core/commerceShadow/contracts"),market=path.join(root,"apps/desktop/src/renderer/core/commerceShadow/market"),registry=path.join(root,"apps/desktop/src/renderer/core/commerceShadow/providerRegistry"),discovery=path.join(root,"apps/desktop/src/renderer/core/commerceShadow/provider/discovery"),sharedFiles=["sharedCommerceContractTypes.js","sharedCommerceContractValidation.js","sharedCommerceContracts.js","sharedCommerceContractPackage.js"],marketFiles=["marketContextTypes.js","marketContextValidation.js","marketContextContracts.js","marketContextPackage.js"],registryFiles=["providerRegistryTypes.js","providerRegistryValidation.js","providerRegistryContracts.js","providerRegistryPackage.js"],discoveryFiles=["providerDiscoveryTypes.js","providerDiscoveryValidation.js","providerDiscoveryCore.js","providerDiscoveryPackage.js"],tests=[];
function test(name,run){tests.push({name,run});}function load(){const w={};w.window=w;const c=vm.createContext({window:w});sharedFiles.forEach(f=>vm.runInContext(fs.readFileSync(path.join(shared,f),"utf8"),c,{filename:f}));marketFiles.forEach(f=>vm.runInContext(fs.readFileSync(path.join(market,f),"utf8"),c,{filename:f}));registryFiles.forEach(f=>vm.runInContext(fs.readFileSync(path.join(registry,f),"utf8"),c,{filename:f}));discoveryFiles.forEach(f=>vm.runInContext(fs.readFileSync(path.join(discovery,f),"utf8"),c,{filename:f}));return w;}function deps(){let n=0;return{clock:()=>"2026-08-02T00:00:00.000Z",idGenerator:()=>"id-"+(++n)};}function loc(country,source){return{country,region:"UNKNOWN",city:"UNKNOWN",postalCode:"UNKNOWN",source:source||"TASK_DESTINATION"};}function input(extra){return Object.assign({domain:"PRODUCT",accountCountry:loc("CN","USER_DEFAULT"),savedDestination:null,temporaryOverride:null,taskDestination:loc("JP"),hotelDestination:null,flightOrigin:null,flightDestination:null,paymentRegion:loc("CN","USER_DEFAULT"),preference:{userDefaultMarket:loc("CN","USER_DEFAULT"),systemLocaleHint:loc("US","SYSTEM_LOCALE_HINT"),requestedCurrency:"JPY",language:"en"},overrideStatus:"NONE"},extra||{});}function output(extra){const w=load(),d=deps(),context=w.WeishanMarketContextPackage.createMarketContext(input(extra),d),r=w.WeishanProviderRegistryPackage.createDefaultProviderRegistry(d);return w.WeishanProviderDiscoveryPackage.discoverCandidates(context,r,d);}
test("returns no provider for every known explicit market",()=>{[{}, {temporaryOverride:loc("US","USER_TEMPORARY_OVERRIDE"),overrideStatus:"ACTIVE"},{taskDestination:null,savedDestination:loc("DE","SAVED_DESTINATION")}].forEach(extra=>{const value=output(extra);assert.equal(value.status,"NO_PROVIDER");assert.deepEqual(JSON.parse(JSON.stringify(value.candidates)),[]);assert.equal(value.executed,false);assert.equal(value.productionAffected,false);});});
test("keeps locale-only and unknown contexts safely non-executable",()=>{const partial=output({taskDestination:null,preference:{userDefaultMarket:loc("UNKNOWN","UNKNOWN"),systemLocaleHint:loc("US","SYSTEM_LOCALE_HINT"),requestedCurrency:"USD",language:"en"}}),unknown=output({taskDestination:null,preference:{userDefaultMarket:loc("UNKNOWN","UNKNOWN"),systemLocaleHint:loc("UNKNOWN","UNKNOWN"),requestedCurrency:"UNKNOWN",language:"UNKNOWN"}});assert.equal(partial.status,"PARTIAL");assert.equal(unknown.status,"UNKNOWN");assert.deepEqual(JSON.parse(JSON.stringify(partial.candidates)),[]);assert.deepEqual(JSON.parse(JSON.stringify(unknown.candidates)),[]);});
test("blocks unsupported domains and preserves empty candidate ordering",()=>{const value=output({domain:"UNKNOWN",taskDestination:null});assert.equal(value.status,"BLOCKED");assert.ok(value.limitations.includes("UNSUPPORTED_DOMAIN"));assert.deepEqual(JSON.parse(JSON.stringify(value.candidates)),[]);});
test("rejects invalid registry and context contracts",()=>{const w=load(),d=deps(),context=w.WeishanMarketContextPackage.createMarketContext(input(),d),registry=w.WeishanProviderRegistryPackage.createDefaultProviderRegistry(d);assert.throws(()=>w.WeishanProviderDiscoveryPackage.discoverCandidates(Object.assign({},context,{contextId:""}),registry,d));assert.throws(()=>w.WeishanProviderDiscoveryPackage.discoverCandidates(context,Object.assign({},registry,{providers:["x"]}),d));});
test("rejects sensitive executable and cyclic input",()=>{const w=load(),d=deps(),context=w.WeishanMarketContextPackage.createMarketContext(input(),d),registry=w.WeishanProviderRegistryPackage.createDefaultProviderRegistry(d),getter=JSON.parse(JSON.stringify(context)),cycle=JSON.parse(JSON.stringify(registry));Object.defineProperty(getter,"contextId",{get(){return"x";},enumerable:true});cycle.self=cycle;[Object.assign({},context,{token:"x"}),getter,Object.assign({},registry,{status:()=>"NOT_REGISTERED"}),cycle,JSON.parse('{"__proto__":{"polluted":true}}')].forEach(value=>assert.throws(()=>w.WeishanProviderDiscoveryPackage.discoverCandidates(value.providers?context:value,value.providers?value:registry,d)));});
test("is immutable and deterministic with injected dependencies",()=>{const a=output(),b=output();assert.deepEqual(JSON.parse(JSON.stringify(a)),JSON.parse(JSON.stringify(b)));assert.equal(Object.isFrozen(a),true);assert.throws(()=>{a.status="CANDIDATES_FOUND";});});
test("requires compatibility review for a future discovery version",()=>{const w=load();assert.equal(w.WeishanProviderDiscoveryPackage.assessCompatibility("P8_PROVIDER_DISCOVERY_V1").status,"BACKWARD_COMPATIBLE");assert.equal(w.WeishanProviderDiscoveryPackage.assessCompatibility("P8_PROVIDER_DISCOVERY_V2").status,"FORWARD_REVIEW_REQUIRED");});
test("is isolated from provider communication, search, price, booking, UI, and runtime integration",()=>{const source=discoveryFiles.map(f=>fs.readFileSync(path.join(discovery,f),"utf8")).join("\n");["fetch(","XMLHttpRequest","require(","electron","CommandApi","ProviderDiscoveryRuntime","searchProvider","priceQuote","checkout","localStorage","navigator.geolocation"].forEach(token=>assert.equal(source.includes(token),false,token));});
test("keeps execution and candidate activation closed",()=>{const w=load(),api=w.WeishanProviderDiscoveryPackage;assert.equal(api.PACKAGE.executionGate,"CLOSED");assert.equal(api.PACKAGE.authorizesExecution,false);assert.equal(api.PACKAGE.providerCommunication,false);assert.equal(api.PACKAGE.candidateExecution,false);assert.equal(Object.prototype.hasOwnProperty.call(api,"executeCandidate"),false);});
tests.forEach(({run})=>run());console.log("P8_WP005_PROVIDER_DISCOVERY_SHADOW PASS "+tests.length);
