"use strict";

const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const root=path.resolve(__dirname,"../.."),shared=path.join(root,"apps/desktop/src/renderer/core/commerceShadow/contracts"),priceContracts=path.join(root,"apps/desktop/src/renderer/core/commerceShadow/price/contracts"),normalization=path.join(root,"apps/desktop/src/renderer/core/commerceShadow/price/normalization"),sharedFiles=["sharedCommerceContractTypes.js","sharedCommerceContractValidation.js","sharedCommerceContracts.js","sharedCommerceContractPackage.js"],authorityFiles=["priceAuthorityTypes.js","priceAuthorityValidation.js","priceAuthorityContracts.js","priceAuthorityPackage.js"],normalizationFiles=["priceNormalizationTypes.js","priceNormalizationValidation.js","priceNormalizationCore.js","priceNormalizationPackage.js"],tests=[];let assertions=0;
function equal(a,b,m){assertions++;assert.equal(a,b,m);}function truth(a,m){assertions++;assert.ok(a,m);}function throws(f,m){assertions++;assert.throws(f,m);}function test(name,run){tests.push({name,run});}function load(){const w={};w.window=w;const c=vm.createContext({window:w});sharedFiles.forEach(f=>vm.runInContext(fs.readFileSync(path.join(shared,f),"utf8"),c,{filename:f}));authorityFiles.forEach(f=>vm.runInContext(fs.readFileSync(path.join(priceContracts,f),"utf8"),c,{filename:f}));normalizationFiles.forEach(f=>vm.runInContext(fs.readFileSync(path.join(normalization,f),"utf8"),c,{filename:f}));return w;}function deps(){let n=0;return{clock:()=>"2026-08-02T00:00:00.000Z",idGenerator:()=>"id-"+(++n)};}function authority(state,extra){const w=load(),value=w.WeishanPriceAuthorityPackage.createUnknownPriceAuthority(deps());return Object.assign(JSON.parse(JSON.stringify(value)),{priceState:state||"UNKNOWN"},extra||{});}function normalized(state,extra){const w=load(),d=deps(),input=authority(state,extra),validated=w.WeishanPriceAuthorityPackage.validatePriceAuthority(input);return w.WeishanPriceNormalizationPackage.normalizePrice(validated,d);}
// Group 1: Authority state preservation.
test("preserves all seven authority states without creating known money",()=>{const expected={UNKNOWN:"UNKNOWN",REFERENCE:"REFERENCE_ONLY",ESTIMATED:"ESTIMATED_ONLY",CACHED:"CACHED_QUOTE",LIVE_QUOTE:"TRACEABLE_QUOTE",STALE_QUOTE:"TRACEABLE_QUOTE",FINAL_CHECKOUT:"EXTERNAL_FINAL_CHECKOUT"};Object.keys(expected).forEach(state=>{const value=normalized(state);equal(value.authorityLevel,expected[state]);equal(value.amountState,state==="ESTIMATED"?"ESTIMATED":"UNKNOWN");equal(value.knownComponents.length,0);});});
test("preserves cached live stale and final-checkout metadata boundaries",()=>{const cached=normalized("CACHED",{timestamp:{capturedAt:"2026-08-01T00:00:00.000Z",freshness:"KNOWN"}}),live=normalized("LIVE_QUOTE",{evidence:{source:"FIXTURE_ONLY",traceability:"TRACEABLE",taxStatus:"KNOWN",feeStatus:"KNOWN",availabilityStatus:"KNOWN"}}),stale=normalized("STALE_QUOTE"),final=normalized("FINAL_CHECKOUT");equal(cached.freshnessState,"CACHED");equal(live.freshnessState,"CURRENT");equal(stale.freshnessState,"STALE");truth(stale.limitations.includes("QUOTE_FRESHNESS_STALE"));truth(final.limitations.includes("EXTERNAL_PLATFORM_REMAINS_FINAL_AUTHORITY"));});
// Group 2: Normalization rules.
test("normalizes only format metadata and never performs conversion or ranking",()=>{["USD","JPY","EUR","UNKNOWN"].forEach(currency=>{const value=normalized("REFERENCE",{currency:currency});equal(value.currency,currency);equal(value.domain,"UNKNOWN");equal(value.comparisonReadiness,"PARTIAL");equal(value.knownComponents.length,0);if(currency!=="UNKNOWN")truth(value.warnings.includes("CROSS_CURRENCY_NOT_COMPARABLE_WITHOUT_RATE_EVIDENCE"));});});
test("keeps estimated cost fields explicitly estimated",()=>{const value=normalized("ESTIMATED");equal(value.amountState,"ESTIMATED");truth(value.estimatedComponents.includes("AMOUNT"));truth(value.unknownComponents.includes("SHIPPING"));truth(value.unknownComponents.includes("BAGGAGE"));});
// Group 3: Unknown handling.
test("preserves unknown tax fee shipping baggage and amount",()=>{const value=normalized("UNKNOWN");equal(value.taxState,"UNKNOWN");equal(value.feeState,"UNKNOWN");equal(value.shippingState,"UNKNOWN");equal(value.baggageState,"UNKNOWN");["AMOUNT","TAX","FEE","SHIPPING","BAGGAGE"].forEach(component=>truth(value.unknownComponents.includes(component)));equal(value.comparisonReadiness,"BLOCKED");});
test("does not turn incomplete authority evidence into ready comparison",()=>{["REFERENCE","ESTIMATED","CACHED","LIVE_QUOTE","FINAL_CHECKOUT"].forEach(state=>{const value=normalized(state);equal(value.comparisonReadiness,"PARTIAL");truth(value.limitations.includes("NO_AMOUNT_VALUE_IN_PRICE_AUTHORITY"));});equal(normalized("STALE_QUOTE").comparisonReadiness,"NOT_READY");});
// Group 4: Security rejection.
test("rejects getters functions symbols cycles prototype pollution and sensitive fields",()=>{const w=load(),d=deps(),base=w.WeishanPriceAuthorityPackage.createUnknownPriceAuthority(d),getter=JSON.parse(JSON.stringify(base)),cycle=JSON.parse(JSON.stringify(base));Object.defineProperty(getter,"authorityId",{get(){return"x";},enumerable:true});cycle.self=cycle;[Object.assign({},base,{token:"x"}),getter,Object.assign({},base,{currency:()=>"USD"}),Object.assign({},base,{currency:Symbol("x")}),cycle,JSON.parse('{"__proto__":{"polluted":true}}')].forEach(value=>throws(()=>w.WeishanPriceNormalizationPackage.normalizePrice(value,d)));});
test("returns deeply immutable output without mutating authority input",()=>{const w=load(),d=deps(),source=w.WeishanPriceAuthorityPackage.createUnknownPriceAuthority(d),copy=JSON.parse(JSON.stringify(source)),value=w.WeishanPriceNormalizationPackage.normalizePrice(copy,d);copy.currency="USD";equal(value.currency,"UNKNOWN");truth(Object.isFrozen(value));truth(Object.isFrozen(value.unknownComponents));throws(()=>{value.currency="USD";});});
// Group 5: Determinism and compatibility.
test("is deterministic for every price state with injected dependencies",()=>{["UNKNOWN","REFERENCE","ESTIMATED","CACHED","LIVE_QUOTE","STALE_QUOTE","FINAL_CHECKOUT"].forEach(state=>{const a=normalized(state),b=normalized(state);assertions++;assert.deepEqual(JSON.parse(JSON.stringify(a)),JSON.parse(JSON.stringify(b)));});});
test("keeps compatibility review and execution boundary closed",()=>{const w=load(),api=w.WeishanPriceNormalizationPackage;equal(api.assessCompatibility("P8_PRICE_NORMALIZATION_V1").status,"BACKWARD_COMPATIBLE");equal(api.assessCompatibility("P8_PRICE_NORMALIZATION_V2").status,"FORWARD_REVIEW_REQUIRED");equal(api.PACKAGE.executionGate,"CLOSED");equal(api.PACKAGE.authorizesExecution,false);equal(api.PACKAGE.currencyConversion,false);equal(api.PACKAGE.comparisonRanking,false);});
test("is isolated from collection provider network checkout recommendation UI and persistence",()=>{const source=normalizationFiles.map(f=>fs.readFileSync(path.join(normalization,f),"utf8")).join("\n");["fetch(","XMLHttpRequest","require(","electron","CommandApi","ProviderDiscovery","searchProvider","priceQuote","checkout","recommendation","localStorage","navigator.geolocation","Date.now","Math.random"].forEach(token=>equal(source.includes(token),false,token));});
tests.forEach(({run})=>run());truth(assertions>=100,"meaningful assertion threshold");console.log("P8_WP007_PRICE_NORMALIZATION_SHADOW PASS "+tests.length+" tests "+assertions+" assertions");
