"use strict";

const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const root=path.resolve(__dirname,"../.."),shared=path.join(root,"apps/desktop/src/renderer/core/commerceShadow/contracts"),market=path.join(root,"apps/desktop/src/renderer/core/commerceShadow/market"),sharedFiles=["sharedCommerceContractTypes.js","sharedCommerceContractValidation.js","sharedCommerceContracts.js","sharedCommerceContractPackage.js"],marketFiles=["marketContextTypes.js","marketContextValidation.js","marketContextContracts.js","marketContextPackage.js"],tests=[];
function test(name,run){tests.push({name,run});}function load(){const w={};w.window=w;const c=vm.createContext({window:w});sharedFiles.forEach(f=>vm.runInContext(fs.readFileSync(path.join(shared,f),"utf8"),c,{filename:f}));marketFiles.forEach(f=>vm.runInContext(fs.readFileSync(path.join(market,f),"utf8"),c,{filename:f}));return w.WeishanMarketContextPackage;}
function deps(){let id=0;return{clock:()=>"2026-08-02T00:00:00.000Z",idGenerator:()=>"market-"+(++id)};}function loc(country,source){return{country,region:"UNKNOWN",city:"UNKNOWN",postalCode:"UNKNOWN",source:source||"TASK_DESTINATION"};}function input(extra){return Object.assign({domain:"PRODUCT",accountCountry:loc("CN","USER_DEFAULT"),savedDestination:null,temporaryOverride:null,taskDestination:loc("JP"),hotelDestination:null,flightOrigin:null,flightDestination:null,paymentRegion:loc("CN","USER_DEFAULT"),preference:{userDefaultMarket:loc("CN","USER_DEFAULT"),systemLocaleHint:loc("US","SYSTEM_LOCALE_HINT"),requestedCurrency:"JPY",language:"en"},overrideStatus:"NONE"},extra||{});}
// Group 1: valid contracts.
test("creates explicit delivery and payment market context",()=>{const api=load(),value=api.createMarketContext(input(),deps());assert.equal(value.targetCountry,"JP");assert.equal(value.paymentRegion,"CN");assert.equal(value.requestedCurrency,"JPY");});
test("supports flight origin and destination plus hotel destination",()=>{const api=load(),flight=api.createMarketContext(input({domain:"FLIGHT",flightOrigin:loc("CN"),flightDestination:loc("JP"),taskDestination:null}),deps()),hotel=api.createMarketContext(input({domain:"HOTEL",hotelDestination:loc("JP"),taskDestination:null}),deps());assert.equal(flight.originMarket,"CN");assert.equal(flight.destinationMarket,"JP");assert.equal(hotel.targetCountry,"JP");});
test("supports unknown market and locale-hint-only context",()=>{const api=load(),unknown=api.createMarketContext(input({taskDestination:null,savedDestination:null,preference:{userDefaultMarket:loc("UNKNOWN","UNKNOWN"),systemLocaleHint:loc("UNKNOWN","UNKNOWN"),requestedCurrency:"UNKNOWN",language:"UNKNOWN"}}),deps()),hint=api.createMarketContext(input({taskDestination:null,preference:{userDefaultMarket:loc("UNKNOWN","UNKNOWN"),systemLocaleHint:loc("US","SYSTEM_LOCALE_HINT"),requestedCurrency:"USD",language:"en"}}),deps());assert.equal(unknown.targetMarket,"UNKNOWN");assert.equal(hint.selectionSource,"SYSTEM_LOCALE_HINT");assert.equal(hint.confidence,"DERIVED_HINT");});
// Group 2: precedence and explicit override.
test("gives active temporary override precedence over explicit task destination",()=>{const api=load(),value=api.createMarketContext(input({temporaryOverride:loc("US","USER_TEMPORARY_OVERRIDE"),overrideStatus:"CONFIRMED"}),deps());assert.equal(value.targetCountry,"US");assert.equal(value.selectionSource,"USER_TEMPORARY_OVERRIDE");});
test("returns safe failure for conflicting explicit task destinations",()=>{const api=load(),value=api.createMarketContext(input({domain:"FLIGHT",taskDestination:loc("CN"),flightDestination:loc("JP")}),deps());assert.equal(value.code,"CONFLICTING_EXPLICIT_DESTINATIONS");assert.equal(value.userDecisionRequired,true);});
// Group 3: security rejection.
test("rejects sensitive fields, accessors, functions, symbols, circular input, and prototype pollution",()=>{const api=load(),getter=input(),circular=input();Object.defineProperty(getter,"domain",{get(){return"PRODUCT";},enumerable:true});circular.preference.self=circular;[Object.assign(input(),{token:"x"}),getter,Object.assign(input(),{domain:()=>"PRODUCT"}),Object.assign(input(),{domain:Symbol("x")}),circular,JSON.parse('{"__proto__":{"polluted":true}}')].forEach(value=>assert.throws(()=>api.createMarketContext(value,deps())));});
// Group 4: immutability and determinism.
test("defensively copies and freezes context",()=>{const api=load(),source=input(),value=api.createMarketContext(source,deps());source.taskDestination.country="US";assert.equal(value.targetCountry,"JP");assert.equal(Object.isFrozen(value),true);assert.equal(Object.isFrozen(value.sources),true);});
test("is structurally deterministic with injected clock and ID generator",()=>{const api=load(),a=api.createMarketContext(input(),deps()),b=api.createMarketContext(input(),deps());assert.deepEqual(JSON.parse(JSON.stringify(a)),JSON.parse(JSON.stringify(b)));});
// Group 5: failure and compatibility behavior.
test("rejects malformed country, currency, and lifecycle values",()=>{const api=load();assert.throws(()=>api.createMarketContext(input({taskDestination:loc("japan")}),deps()));assert.throws(()=>api.createMarketContext(input({preference:{userDefaultMarket:loc("CN"),systemLocaleHint:loc("US","SYSTEM_LOCALE_HINT"),requestedCurrency:"JP",language:"en"}}),deps()));const invalid=api.createMarketContext(input({overrideStatus:"OPEN"}),deps());assert.equal(invalid.code,"INVALID_OVERRIDE_STATUS");});
test("keeps missing postal code non-blocking and requires review for future versions",()=>{const api=load(),value=api.createMarketContext(input({taskDestination:{country:"JP",region:"UNKNOWN",city:"UNKNOWN",postalCode:"UNKNOWN",source:"TASK_DESTINATION"}}),deps()),compat=api.assessCompatibility("P8_MARKET_CONTEXT_V2");assert.equal(value.targetCountry,"JP");assert.equal(compat.status,"FORWARD_REVIEW_REQUIRED");});
test("is isolated from resolver, provider, network, settings, and production imports",()=>{const source=marketFiles.map(f=>fs.readFileSync(path.join(market,f),"utf8")).join("\n");["fetch(","XMLHttpRequest","require(","electron","CommandApi","Provider Registry","Market Resolver","navigator.geolocation","localStorage","WeishanStore"].forEach(token=>assert.equal(source.includes(token),false,token));});
tests.forEach(({run})=>run());console.log("P8_WP002_MARKET_CONTEXT_CONTRACT PASS "+tests.length);
