const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");
const ROOT = path.resolve(__dirname, "../..");
function load(files) { const window = {}; window.window = window; const context = vm.createContext({ window, console }); for (const file of files) vm.runInContext(fs.readFileSync(path.join(ROOT, file), "utf8"), context, { filename:file }); return window; }
function main() {
  const windowRef = load(["apps/desktop/src/renderer/core/readOnlyQuoteSessionManager.js", "apps/desktop/src/renderer/core/readOnlyQuoteEvidenceSummaryFormatter.js", "apps/desktop/src/renderer/core/readOnlyQuoteDecisionAssistant.js", "apps/desktop/src/renderer/core/readOnlyQuoteCandidateComparisonExplainer.js", "apps/desktop/src/renderer/core/readOnlyQuoteSessionReportCenter.js", "apps/desktop/src/renderer/core/readOnlyQuoteAuditExport.js"]);
  const manager = windowRef.WeishanReadOnlyQuoteSessionManager;
  const api = windowRef.WeishanReadOnlyQuoteAuditExport;
  assert.equal(api.READ_ONLY_QUOTE_AUDIT_EXPORT_VERSION, "4.2.6");
  const session = manager.updateReadOnlyQuoteSession(manager.createReadOnlyQuoteSession({ route:"上海 → 成都" }), { type:"DRY_RUN_COMPLETED", result:{ runId:"r1", dryRunTopCandidates:[{ quoteId:"q1", providerName:"A", totalPrice:930 }], selectedCandidate:{ quoteId:"q1", providerName:"A" } } });
  const model = api.buildReadOnlyQuoteAuditExport({ sessionSummary: manager.buildReadOnlyQuoteSessionSummary(session), dryRunTopCandidates:[{ quoteId:"q1", providerName:"A", totalPrice:930, bookingUrl:"https://blocked.example" }], selectedCandidate:{ quoteId:"q1", providerName:"A" }, runHistorySummary:{ totalRunCount:1 }, quoteDeltaSummary:{ status:"not_enough_history" }, replaySummary:{ status:"unavailable" } });
  assert.equal(model.appVersion, "4.2.6");
  assert.equal(model.exportType, "redacted_json_preview");
  assert.equal(model.generatedAt, null);
  assert.ok(model.sessionSummary);
  assert.equal(model.topCandidates.length, 1);
  assert.ok(model.selectedCandidate);
  assert.ok(model.historySummary);
  assert.ok(model.deltaSummary);
  assert.ok(model.replaySummary);
  assert.ok(model.reportCenterSummary);
  assert.ok(model.userFacingSummary);
  assert.ok(model.safetyReportSummary);
  assert.ok(model.decisionAssistantSummary);
  assert.ok(model.candidateComparisonSummary);
  assert.ok(model.recommendationExplanation);
  assert.ok(Array.isArray(model.decisionSafetyWarnings));
  assert.ok(Array.isArray(model.exportValidationWarnings));
  assert.equal(model.safety.rawResponseIncluded, false);
  assert.equal(model.safety.secretIncluded, false);
  assert.equal(model.safety.bookingUrlIncluded, false);
  assert.equal(model.safety.paymentUrlIncluded, false);
  assert.equal(model.safety.orderUrlIncluded, false);
  assert.equal(model.safety.identityIncluded, false);
  assert.equal(model.caveat.includes("本导出仅为只读候选证据"), true);
  const validation = api.validateReadOnlyQuoteAuditExport(model);
  assert.equal(validation.valid, true);
  assert.equal(api.validateReadOnlyQuoteAuditExport(Object.assign({}, model, { token:"abc" })).valid, false);
  assert.equal(api.validateReadOnlyQuoteAuditExport(Object.assign({}, model, { key:"abc" })).valid, false);
  assert.equal(api.validateReadOnlyQuoteAuditExport(Object.assign({}, model, { secret:"abc" })).valid, false);
  assert.equal(api.validateReadOnlyQuoteAuditExport(Object.assign({}, model, { bookingUrl:"https://blocked.example" })).valid, false);
  assert.equal(api.validateReadOnlyQuoteAuditExport(Object.assign({}, model, { paymentUrl:"https://blocked.example" })).valid, false);
  assert.equal(api.validateReadOnlyQuoteAuditExport(Object.assign({}, model, { orderUrl:"https://blocked.example" })).valid, false);
  assert.equal(api.validateReadOnlyQuoteAuditExport(Object.assign({}, model, { rawResponse:{ ok:false } })).valid, false);
  assert.equal(api.validateReadOnlyQuoteAuditExport(Object.assign({}, model, { reportCenterSummary:{ token:"abc" } })).valid, false);
  const preview = api.buildReadOnlyQuoteAuditExportPreview(session);
  assert.equal(preview.previewLabel, "Redacted JSON Preview");
  assert.equal(preview.fileWrite, false);
  assert.equal(preview.upload, false);
  console.log("READ_ONLY_QUOTE_AUDIT_EXPORT PASS");
}
main();
