;(function () {
  "use strict";
  const READONLY_ADAPTER_CONTRACT_GATE_VERSION = "2.1.47";
  const core = window.WeishanReadOnlyProviderAdapterContract;
  function clone(value) { return JSON.parse(JSON.stringify(value)); }
  const allowedMethods = core ? core.ALLOWED_METHODS.slice() : ["getAdapterMetadata", "validateCredentialScope", "validateReadinessGates", "runOfflineFixtureSearch", "normalizeProviderResult", "validateResultSchema", "attachSourceLabel", "runDryRun"];
  const blockedMethods = core ? core.BLOCKED_METHODS.slice() : ["connect", "fetch", "request", "post", "createOrder", "pay", "checkout", "uploadIdentity", "revealCredential", "exportCredential", "testEndpoint"];
  const commerceReadonlyAdapterContractGateContract = { version:READONLY_ADAPTER_CONTRACT_GATE_VERSION, moduleName:"readonly_adapter_contract_gate", phase:"readonly_adapter_contract_gate", gateStatus:"draft-ready", mode:"offline_fixture_only", adapterExecution:"offline fixture only", realNetwork:"disabled", realEndpoint:"disabled", realProviderSandbox:"disabled", realProviderResult:"disabled", rawPayloadDisplay:"disabled", writeAction:"disabled", redacted:true, display:{ title:"read-only adapter contract gate", establishedLine:"read-only adapter contract gate：draft-ready", statusLine:"status: draft-ready", modeLine:"mode: offline fixture only", adapterExecutionLine:"adapter contract draft-ready", networkLine:"real network disabled", endpointLine:"real endpoint disabled", sandboxLine:"real provider sandbox disabled", providerResultLine:"real provider result disabled", rawPayloadLine:"raw payload display disabled", writeActionLine:"write action disabled", dryRunLine:"offline fixture dry run allowed", noNetworkLine:"不执行真实 network", noEndpointLine:"不调用真实 provider endpoint", noResultLine:"不读取真实 provider result", withheldLine:"当前 price 仍 disabled；当前 availability 仍 disabled；当前 bookingUrl 仍 disabled；rawProviderPayload forbidden", redactedLine:"redacted: true" }, capabilities:{ canShowReadonlyAdapterContractGate:true, canExecuteAdapter:false, canExecuteReadonlyDryRun:true, canUseNetwork:false, canConnectEndpoint:false, canRunRealProviderSandbox:false, canReadRealProviderResult:false, canDisplayRawProviderPayload:false, canDisplayRealPrice:false, canDisplayAvailability:false, canDisplayBookingUrl:false, canCreateBooking:false, canSubmitOrder:false, canCheckout:false, canPay:false, canUploadIdentity:false, canSubmitBankCard:false, canSendRawToken:false, canSendRawApiKey:false } };
  function buildReadonlyAdapterInterfaceDraft(){ return { version:READONLY_ADAPTER_CONTRACT_GATE_VERSION, fields:["adapterId", "providerCategory", "providerName", "mode", "networkPolicy", "credentialPolicy", "endpointPolicy", "resultPolicy", "bookingUrlPolicy", "paymentPolicy", "orderPolicy", "identityUploadPolicy", "redacted: true"], redacted:true }; }
  function buildReadonlyAdapterMethodDraft(){ return { version:READONLY_ADAPTER_CONTRACT_GATE_VERSION, readonlyMethods:allowedMethods.slice(), redacted:true }; }
  function buildReadonlyAdapterForbiddenMethodDraft(){ return { version:READONLY_ADAPTER_CONTRACT_GATE_VERSION, forbiddenMethods:blockedMethods.slice(), redacted:true }; }
  function buildReadonlyAdapterRequestContractDraft(){ return { version:READONLY_ADAPTER_CONTRACT_GATE_VERSION, fields:["query", "providerCategory", "adapterId", "readonlyOnly", "fixtureOnly", "noBooking", "noPayment", "noOrder", "redacted: true"], readonlyOnly:true, noBooking:true, noPayment:true, noOrder:true, redacted:true }; }
  function buildReadonlyAdapterResponseContractDraft(){ return { version:READONLY_ADAPTER_CONTRACT_GATE_VERSION, fields:["resultType", "providerCategory", "adapterId", "sourceLabel", "resultSchemaVersion", "querySummary", "candidateSummary", "fixtureOnly", "realProvider", "realNetwork", "realPrice", "availability", "bookingUrl", "redacted: true"], priceStatus:"disabled", availabilityStatus:"disabled", bookingUrlStatus:"disabled", rawProviderPayloadStatus:"forbidden", redacted:true }; }
  function buildReadonlyAdapterErrorStateDraft(){ return { version:READONLY_ADAPTER_CONTRACT_GATE_VERSION, errorStates:["NETWORK_DISABLED", "ENDPOINT_DISABLED", "CREDENTIAL_METADATA_ONLY", "REAL_PROVIDER_DISABLED", "BOOKING_URL_FORBIDDEN", "WRITE_ACTION_FORBIDDEN"], redacted:true }; }
  function buildReadonlyAdapterContractAuditDraft(){ const audit = core ? core.buildReadOnlyProviderAdapterAuditDraft({ adapterId:"readonly_provider_adapter_contract_v1", providerCategory:"all" }) : { eventType:"READ_ONLY_PROVIDER_ADAPTER_V1_DRAFT", adapterId:"readonly_provider_adapter_contract_v1", providerCategory:"all", mode:"offline_fixture_only", realProviderCallCount:0, networkAttemptCount:0, realCredentialReadCount:0, realEndpointConnectCount:0, realPriceDisplayedCount:0, bookingUrlDisplayedCount:0, paymentAttemptCount:0, orderAttemptCount:0, identityUploadAttemptCount:0, redacted:true }; return { version:READONLY_ADAPTER_CONTRACT_GATE_VERSION, readonlyAdapterContractAuditDraft:audit, redacted:true }; }
  function evaluateReadonlyAdapterContractDraft(){ return { version:READONLY_ADAPTER_CONTRACT_GATE_VERSION, allowed:false, gateStatus:"draft-ready", decision:"no-go", blockedReason:"real_provider_connection_disabled", canExecuteAdapter:false, canExecuteReadonlyDryRun:true, canUseNetwork:false, canConnectEndpoint:false, canDisplayRealPrice:false, canDisplayBookingUrl:false, redacted:true }; }
  function assertReadonlyAdapterContractGateSafe(gate){ const target = gate || commerceReadonlyAdapterContractGateContract; const caps = target.capabilities || {}; ["realNetwork", "realEndpoint", "realProviderSandbox", "realProviderResult", "rawPayloadDisplay", "writeAction"].forEach(function(key){ if (target[key] !== "disabled") throw new Error(key + " must be disabled"); }); ["canUseNetwork", "canConnectEndpoint", "canRunRealProviderSandbox", "canReadRealProviderResult", "canDisplayRawProviderPayload", "canDisplayRealPrice", "canDisplayAvailability", "canDisplayBookingUrl", "canCreateBooking", "canSubmitOrder", "canCheckout", "canPay", "canUploadIdentity", "canSubmitBankCard", "canSendRawToken", "canSendRawApiKey"].forEach(function(key){ if (caps[key] !== false) throw new Error(key + " must stay false"); }); return true; }
  function buildReadonlyAdapterContractGateDisplay(gate){ const base = Object.assign({}, commerceReadonlyAdapterContractGateContract, gate && typeof gate === "object" ? gate : {}); return Object.assign({}, clone(base), { adapterInterfaceDraft:buildReadonlyAdapterInterfaceDraft(), readonlyMethodDraft:buildReadonlyAdapterMethodDraft(), forbiddenMethodDraft:buildReadonlyAdapterForbiddenMethodDraft(), requestContractDraft:buildReadonlyAdapterRequestContractDraft(), responseContractDraft:buildReadonlyAdapterResponseContractDraft(), errorStateDraft:buildReadonlyAdapterErrorStateDraft(), audit:buildReadonlyAdapterContractAuditDraft(), evaluation:evaluateReadonlyAdapterContractDraft() }); }
  window.WeishanCommerceReadonlyAdapterContractGate = { READONLY_ADAPTER_CONTRACT_GATE_VERSION, commerceReadonlyAdapterContractGateContract, buildReadonlyAdapterInterfaceDraft, buildReadonlyAdapterMethodDraft, buildReadonlyAdapterForbiddenMethodDraft, buildReadonlyAdapterRequestContractDraft, buildReadonlyAdapterResponseContractDraft, buildReadonlyAdapterErrorStateDraft, buildReadonlyAdapterContractAuditDraft, evaluateReadonlyAdapterContractDraft, assertReadonlyAdapterContractGateSafe, buildReadonlyAdapterContractGateDisplay };
})();
