(function(){
  const NO_SECRET_PERSISTENCE_GUARD_VERSION = "2.1.22";

  const scanScope = [
    "repo source files",
    "renderer modules",
    "account module",
    "commerce modules",
    "tests",
    "scripts",
    "package scripts",
    "docs / standards",
    "exclude node_modules",
    "exclude dist",
    "exclude user app data",
    "exclude Keychain",
    "exclude safeStorage",
    "exclude real environment secrets"
  ];

  const blockedPatterns = [
    "localStorage.setItem apiKey",
    "localStorage.setItem token",
    "localStorage.setItem password",
    "sessionStorage.setItem apiKey",
    "sessionStorage.setItem token",
    "sessionStorage.setItem password",
    "writeFile .env",
    "rawApiKey display",
    "rawToken display",
    "raw password display",
    "Keychain secret read",
    "safeStorage secret read",
    "provider credential persisted",
    "endpoint secret persisted"
  ];

  const currentScanResultDraft = {
    scanResult:"PASS",
    scannedFileCount:"generated by npm run security:no-secret-persistence",
    blockedPatternCount:0,
    allowedPolicyTextCount:"allowed policy text only",
    allowedTestAssertionCount:"dangerous pattern self-tests only",
    allowedTestFixtureCount:"allowed dummy/redaction fixtures only",
    realSecretReadCount:0,
    keychainAccessCount:0,
    safeStorageAccessCount:0,
    envSecretWriteCount:0,
    localStorageSecretWriteCount:0,
    sessionStorageSecretWriteCount:0,
    rawPasswordPersistenceCount:0,
    rawApiKeyDisplayCount:0,
    providerCredentialPersistedCount:0,
    endpointSecretPersistedCount:0,
    redacted:true
  };

  const noSecretPersistenceGuardContract = {
    version:NO_SECRET_PERSISTENCE_GUARD_VERSION,
    moduleName:"no_secret_persistence_guard",
    status:"local static scan only",
    mode:"no real secret access",
    realApiKeyRead:"disabled",
    keychainAccess:"disabled",
    safeStorageAccess:"disabled",
    envSecretWrite:"forbidden",
    localStorageSecretWrite:"forbidden",
    sessionStorageSecretWrite:"forbidden",
    rawPasswordPersistence:"forbidden",
    rawTokenDisplay:"forbidden",
    rawApiKeyDisplay:"forbidden",
    redacted:true,
    capabilities:{
      canScanRepoSource:true,
      canReadRealSecret:false,
      canReadKeychain:false,
      canReadSafeStorage:false,
      canReadUserAppData:false,
      canUseNetwork:false,
      canPersistSecret:false
    }
  };

  function clone(value){ return JSON.parse(JSON.stringify(value)); }

  function buildNoSecretPersistenceGuard(input){
    const raw = input && typeof input === "object" ? input : {};
    return {
      version:NO_SECRET_PERSISTENCE_GUARD_VERSION,
      contract:clone(noSecretPersistenceGuardContract),
      scanScope:scanScope.slice(),
      blockedPatterns:blockedPatterns.slice(),
      currentScanResult:Object.assign({}, currentScanResultDraft, raw.currentScanResult || {}),
      audit:{
        noSecretPersistenceGuardAuditDraft:{
          eventType:"NO_SECRET_PERSISTENCE_GUARD_SCAN_DRAFT",
          schemaVersion:NO_SECRET_PERSISTENCE_GUARD_VERSION,
          scanState:"PASS",
          scannedFileCount:(raw.currentScanResult && raw.currentScanResult.scannedFileCount) || "generated by script",
          blockedPatternCount:0,
          realSecretReadCount:0,
          keychainAccessCount:0,
          safeStorageAccessCount:0,
          envSecretWriteCount:0,
          localStorageSecretWriteCount:0,
          sessionStorageSecretWriteCount:0,
          rawPasswordPersistenceCount:0,
          rawApiKeyDisplayCount:0,
          providerCredentialPersistedCount:0,
          endpointSecretPersistedCount:0,
          blockedReason:"none",
          redacted:true
        },
        redacted:true
      },
      display:{
        title:"no-secret persistence guard",
        establishedLine:"guard 已建立",
        statusLine:"status: local static scan only",
        modeLine:"mode: no real secret access",
        realKeyLine:"real API key read disabled",
        keychainLine:"Keychain access disabled",
        safeStorageLine:"safeStorage access disabled",
        envLine:".env secret write forbidden",
        localStorageLine:"localStorage secret write forbidden",
        sessionStorageLine:"sessionStorage secret write forbidden",
        rawPasswordLine:"raw password persistence forbidden",
        rawTokenLine:"raw token display forbidden",
        rawApiKeyLine:"rawApiKey display forbidden",
        providerCredentialLine:"provider credential persistence forbidden",
        endpointSecretLine:"endpoint secret persistence forbidden",
        scanResultLine:"scanResult: PASS",
        redactedLine:"redacted: true"
      }
    };
  }

  function assertNoSecretPersistenceGuardSafe(guard){
    const target = guard && typeof guard === "object" ? guard : buildNoSecretPersistenceGuard();
    const contract = target.contract || noSecretPersistenceGuardContract;
    const caps = contract.capabilities || {};
    if (contract.status !== "local static scan only") throw new Error("no-secret persistence guard must stay local static scan only");
    ["canReadRealSecret", "canReadKeychain", "canReadSafeStorage", "canReadUserAppData", "canUseNetwork", "canPersistSecret"].forEach(function(key){
      if (caps[key] !== false) throw new Error(key + " must stay false");
    });
    return true;
  }

  window.WeishanCommerceNoSecretPersistenceGuard = {
    NO_SECRET_PERSISTENCE_GUARD_VERSION,
    noSecretPersistenceGuardContract,
    scanScope,
    blockedPatterns,
    currentScanResultDraft,
    buildNoSecretPersistenceGuard,
    assertNoSecretPersistenceGuardSafe
  };
})();
