;(function () {
  "use strict";

  const CREDENTIAL_CONSENT_SCOPE_GATE_VERSION = "4.1.6";
  const core = window.WeishanCredentialConsentScopeGate;
  function clone(value) { return JSON.parse(JSON.stringify(value)); }
  function fallbackCore() {
    const ALLOWED_SCOPES = ["readonly_search", "readonly_price", "readonly_availability_metadata", "readonly_inventory", "result_analysis", "source_label_display"];
    const FORBIDDEN_SCOPES = ["write_api", "create_order", "payment", "checkout", "booking", "identity_upload", "passport_upload", "bank_card_save", "background_silent_call", "plaintext_key_export", "provider_endpoint_test", "real_network_call"];
    const REQUIRED_CONFIRMATIONS = ["我确认该 API 仅用于只读搜索和价格读取", "我理解 weishan 不会替我付款", "我理解 weishan 不会替我下单", "我理解 weishan 不会上传身份证、护照或银行卡", "我理解最终价格以外部平台页面为准", "我理解当前版本不会连接真实 endpoint", "我理解当前版本不会返回真实价格", "我理解当前版本不会保存或使用真实 API key"];
    return { ALLOWED_SCOPES, FORBIDDEN_SCOPES, REQUIRED_CONFIRMATIONS, buildCredentialConsentScopeGate:function(){ return { version:CREDENTIAL_CONSENT_SCOPE_GATE_VERSION, status:"credential consent gate only", phase:"credential_consent_scope_gate", mode:"no provider connection", consentState:"draft_ready", allowedScopes:ALLOWED_SCOPES, forbiddenScopes:FORBIDDEN_SCOPES, requiredConfirmations:REQUIRED_CONFIRMATIONS, checkedConfirmations:[], checkedConfirmationCount:0, submitRealBindingAllowed:false, finalDecision:"no-go", realProvider:"disabled", realNetwork:"disabled", realEndpoint:"disabled", realPrice:"disabled", bookingUrl:"disabled", payment:"disabled", order:"disabled", identityUpload:"disabled", plaintextKeyExport:"disabled", redacted:true }; }, buildCredentialConsentScopeAuditDraft:function(gate){ return { eventType:"CREDENTIAL_CONSENT_SCOPE_GATE_DRAFT", allowedScopes:gate.allowedScopes || ALLOWED_SCOPES, forbiddenScopes:gate.forbiddenScopes || FORBIDDEN_SCOPES, requiredConfirmations:gate.requiredConfirmations || REQUIRED_CONFIRMATIONS, consentSubmittedCount:0, realCredentialUsedCount:0, providerConnectionCount:0, networkAttemptCount:0, realEndpointConnectCount:0, realPriceDisplayedCount:0, bookingUrlDisplayedCount:0, paymentAttemptCount:0, orderAttemptCount:0, identityUploadAttemptCount:0, redacted:true }; }, assertCredentialConsentScopeGateSafe:function(){ return true; } };
  }
  const api = core || fallbackCore();
  function buildCredentialConsentObjectDraft(){ return { version:CREDENTIAL_CONSENT_SCOPE_GATE_VERSION, fields:["consentId", "providerId", "credentialAlias", "allowedScopes", "forbiddenScopes", "requiredConfirmations", "consentState", "finalDecision", "redacted: true"], redacted:true }; }
  function buildCredentialScopeDraft(){ return { version:CREDENTIAL_CONSENT_SCOPE_GATE_VERSION, credentialScopes:api.ALLOWED_SCOPES.slice(), forbiddenScopes:api.FORBIDDEN_SCOPES.slice(), redacted:true }; }
  function buildCredentialConsentStateDraft(){ return { version:CREDENTIAL_CONSENT_SCOPE_GATE_VERSION, states:["draft_ready", "missing", "submitted_blocked"], submittedCount:0, approvedForFutureReadonlyCount:0, redacted:true }; }
  function buildCredentialPermissionBoundaryDraft(){ return { version:CREDENTIAL_CONSENT_SCOPE_GATE_VERSION, boundaries:api.FORBIDDEN_SCOPES.map(function(scope){ return scope + " forbidden"; }), redacted:true }; }
  function buildCredentialConsentBlockingRulesDraft(){ return { version:CREDENTIAL_CONSENT_SCOPE_GATE_VERSION, blockingRules:["real provider disabled", "real network disabled", "real endpoint disabled", "real price disabled", "bookingUrl disabled", "payment/order disabled", "identity upload disabled", "plaintext key export disabled"], redacted:true }; }
  function buildCredentialConsentScopeAuditDraft(gate){ return { version:CREDENTIAL_CONSENT_SCOPE_GATE_VERSION, credentialConsentScopeAuditDraft:api.buildCredentialConsentScopeAuditDraft(gate || api.buildCredentialConsentScopeGate()), redacted:true }; }
  function evaluateCredentialConsentScopeDraft(gate){ const safe = api.buildCredentialConsentScopeGate(gate); return { version:CREDENTIAL_CONSENT_SCOPE_GATE_VERSION, allowed:false, gateStatus:"draft-ready", decision:"no-go", consentState:safe.consentState, blockedReason:"credential_consent_scope_gate_only", canInputCredential:false, canSaveCredential:false, canReadCredential:false, canTestConnection:false, canUseNetwork:false, redacted:true }; }
  function assertCredentialConsentScopeGateSafe(gate){ return api.assertCredentialConsentScopeGateSafe(gate || api.buildCredentialConsentScopeGate()); }
  function buildCredentialConsentScopeGateDisplay(gate){
    const safe = api.buildCredentialConsentScopeGate(gate);
    const audit = api.buildCredentialConsentScopeAuditDraft(safe);
    return Object.assign({}, clone(safe), { version:CREDENTIAL_CONSENT_SCOPE_GATE_VERSION, moduleName:"credential_consent_scope_gate", gateStatus:"draft-ready", status:"credential consent gate only", mode:"no provider connection", display:{ title:"API 授权范围同意闸门", establishedLine:"credential consent scope gate：draft-ready", statusLine:"status: credential consent gate only", modeLine:"mode: no provider connection", realProviderLine:"real provider disabled", networkLine:"real network disabled", endpointLine:"real endpoint disabled", priceLine:"real price disabled", bookingUrlLine:"bookingUrl disabled", paymentLine:"payment disabled", orderLine:"order disabled", identityLine:"identity upload disabled", plaintextLine:"plaintext key export disabled", redactedLine:"redacted: true" }, consentObjectDraft:buildCredentialConsentObjectDraft(), credentialScopeDraft:buildCredentialScopeDraft(), consentStateDraft:buildCredentialConsentStateDraft(), permissionBoundaries:buildCredentialPermissionBoundaryDraft(), blockingRules:buildCredentialConsentBlockingRulesDraft(), audit:{ credentialConsentScopeAuditDraft:audit }, evaluation:evaluateCredentialConsentScopeDraft(safe), capabilities:{ canShowCredentialConsentScopeGate:true, canToggleTestConfirmations:true, canSubmitRealBinding:false, canInputCredential:false, canSaveCredential:false, canReadCredential:false, canTestConnection:false, canUseNetwork:false, canConnectEndpoint:false, canCreateOrder:false, canPay:false, canUploadIdentity:false } });
  }
  window.WeishanCommerceCredentialConsentScopeGate = { CREDENTIAL_CONSENT_SCOPE_GATE_VERSION, commerceCredentialConsentScopeGateContract:buildCredentialConsentScopeGateDisplay(), buildCredentialConsentObjectDraft, buildCredentialScopeDraft, buildCredentialConsentStateDraft, buildCredentialPermissionBoundaryDraft, buildCredentialConsentBlockingRulesDraft, buildCredentialConsentScopeAuditDraft, evaluateCredentialConsentScopeDraft, assertCredentialConsentScopeGateSafe, buildCredentialConsentScopeGateDisplay };
})();
