;(function () {
  "use strict";

  const FLIGHT_WORKFLOW_RISK_BADGE_BUILDER_VERSION = "2.2.0";
  const BUILDER_NAME = "flight_workflow_risk_badge_builder_v1";
  const FORBIDDEN_TEXT_RE = /https?:\/\/\S+|token|apiKey|secret|password|身份证|护照|银行卡|credential|passport|cardNumber/ig;
  function clone(value) { return value && typeof value === "object" ? JSON.parse(JSON.stringify(value)) : value; }
  function text(value) { return String(value == null ? "" : value).trim(); }
  function obj(value) { return value && typeof value === "object" && !Array.isArray(value) ? value : {}; }
  function safeText(value) { return text(value).replace(FORBIDDEN_TEXT_RE, "redacted"); }
  function safety() { return { bookingUrl:null, payment:false, order:false, ticketing:false, identityUpload:false, secretStored:false, redacted:true }; }
  function badge(badgeId, label, severity) { return { badgeId:badgeId, label:label, severity:severity || "info", redacted:true }; }
  function healthOf(input) { const safe = input && typeof input === "object" ? input : {}; return safe.auditHealth || safe.auditReview && safe.auditReview.auditHealth || safe.auditReviewCenter && safe.auditReviewCenter.auditHealth || {}; }
  function buildFlightWorkflowRiskBadges(input) {
    try {
      const safe = input && typeof input === "object" ? input : {};
      const health = healthOf(safe);
      const preview = safe.safeSessionExportPreview || safe.exportPreview || {};
      const badges = [badge("read_only_safe", "只读安全", "info")];
      if (health.hasConfirmationRequiredActions || safe.requiresConfirmation === true) badges.push(badge("confirmation_required", "需要二次确认", "warning"));
      if (health.hasBlockedActions || health.hasPaymentRisk || health.hasOrderRisk || health.hasTicketingRisk || safe.tradingBlocked === true) badges.push(badge("trading_blocked", "交易动作已阻断", "blocked"));
      if (health.hasSensitiveInputBlocked || health.hasIdentityUploadRisk) badges.push(badge("sensitive_input_blocked", "敏感输入已阻断", "blocked"));
      const checklist = safe.humanReviewChecklistSummary || safe.humanReviewChecklist || {};
      const packet = safe.finalSafeHandoffPacketSummary || safe.finalSafeHandoffPacket || {};
      const policy = safe.handoffPacketPolicyDecision || {};
      const sentinel = safe.safetyRegressionSummary || safe.sentinelReport || {};
      const operator = safe.operatorConsoleSummary || {};
      if (sentinel.status === "pass") badges.push(badge("safety_regression_pass", "安全回归通过", "info"));
      if (sentinel.status === "fail" || sentinel.status === "failed_safe") badges.push(badge("safety_regression_fail", "安全回归失败", "blocked"));
      if (operator.status === "ready") badges.push(badge("operator_console_ready", "运营控制台正常", "info"));
      if (operator.status === "warning" || checklist.status === "needs_review") badges.push(badge("manual_review_required", "需要人工复核", "warning"));
      if (checklist.status === "ready") badges.push(badge("human_review_done", "人工复核完成", "info"));
      if (checklist.status === "needs_review" || packet.status === "needs_review" || policy.status === "needs_review") badges.push(badge("human_review_needed", "仍需复核", "warning"));
      if (packet.status === "ready" && policy.status === "allowed") badges.push(badge("platform_confirmation_ready", "可进入平台确认", "info"));
      if (packet.status === "blocked" || policy.status === "blocked") badges.push(badge("handoff_packet_blocked", "交接包已阻断", "blocked"));
      if (preview.status === "ready" || safe.canPreviewExport === true) badges.push(badge("export_preview", "可预览脱敏摘要", "info"));
      const releaseReadiness = safe.releaseReadinessSummary || safe.releaseReadiness || {};
      const betaReadiness = safe.userFacingBetaReadiness || releaseReadiness.userFacingBetaReadiness || {};
      const copyStatus = safe.copyValidationStatus || releaseReadiness.copyValidationStatus || "";
      if (releaseReadiness.status === "ready" || betaReadiness.safeForUserFacingBeta === true || releaseReadiness.safeForUserFacingBeta === true) {
        badges.push(badge("release_ready", "发布就绪", "info"));
        badges.push(badge("read_only_beta_ready", "只读 Beta 可验收", "info"));
      } else if (releaseReadiness.status === "warning" || betaReadiness.status === "warning") {
        badges.push(badge("release_needs_review", "仍需复核", "warning"));
      } else if (releaseReadiness.status === "blocked" || releaseReadiness.status === "failed_safe" || betaReadiness.status === "blocked") {
        badges.push(badge("release_not_ready", "暂不可验收", "blocked"));
      }
      const beta = safe.betaAcceptanceSummary || releaseReadiness.betaAcceptanceSummary || {};
      const guided = safe.guidedUserTestSummary || releaseReadiness.guidedUserTestSummary || {};
      const feedback = safe.feedbackSanitizerSummary || releaseReadiness.feedbackSanitizerSummary || {};
      if (beta.status === "ready" || releaseReadiness.betaAcceptanceReady === true || safe.betaAcceptanceReady === true) badges.push(badge("beta_acceptance_ready", "Beta 验收可开始", "info"));
      if (guided.status === "in_progress") badges.push(badge("guided_user_test_in_progress", "Beta 验收进行中", "warning"));
      if (guided.status === "completed") badges.push(badge("guided_user_test_completed", "Beta 验收完成", "info"));
      if (feedback.status === "ready" || feedback.status === "redacted") badges.push(badge("feedback_sanitized", "测试反馈已脱敏", "info"));
      const feedbackReview = safe.feedbackReviewSummary || releaseReadiness.feedbackReviewSummary || {};
      const sessionSummary = safe.acceptanceSessionSummary || releaseReadiness.acceptanceSessionSummary || {};
      if (feedbackReview.status === "ready") badges.push(badge("beta_feedback_ready", "测试反馈可用", "info"));
      if (feedbackReview.status === "needs_review") badges.push(badge("beta_feedback_needs_review", "测试反馈需复核", "warning"));
      if (sessionSummary.status === "completed") badges.push(badge("acceptance_session_completed", "验收会话完成", "info"));
      if (sessionSummary.status === "needs_review" || sessionSummary.status === "in_progress") badges.push(badge("acceptance_session_needs_review", "验收仍需复核", "warning"));
      if (feedbackReview.status === "blocked" || sessionSummary.status === "blocked") badges.push(badge("acceptance_session_blocked", "验收已阻断", "blocked"));
      const cohort = safe.betaCohortSummary || releaseReadiness.betaCohortSummary || {};
      const trend = safe.feedbackTrendSummary || releaseReadiness.feedbackTrendSummary || {};
      const cohortHealth = cohort.cohortHealth || {};
      if (cohort.status === "ready" || cohortHealth.safeToExpandBeta === true || trend.recommendation && trend.recommendation.recommendationId === "expand_read_only_beta") badges.push(badge("beta_cohort_expand_ready", "Beta 反馈可扩大测试", "info"));
      if (cohort.status === "needs_more_feedback" || trend.status === "insufficient_data") badges.push(badge("beta_cohort_insufficient", "趋势数据不足", "warning"));
      if (cohort.status === "needs_review" || trend.status === "needs_review") badges.push(badge("beta_cohort_watch", "Beta 反馈仍需观察", "warning"));
      if (cohort.findings && JSON.stringify(cohort.findings).indexOf("安全文案理解不足") >= 0 || trend.trends && trend.trends.safetyCopyTrend === "not_understood") badges.push(badge("beta_safety_copy_low", "安全文案理解不足", "warning"));
      if (cohort.findings && JSON.stringify(cohort.findings).indexOf("可用性反馈偏弱") >= 0 || trend.trends && trend.trends.usabilityTrend === "negative") badges.push(badge("beta_usability_low", "可用性反馈偏弱", "warning"));
      const expansionGate = safe.betaExpansionGateSummary || releaseReadiness.betaExpansionGateSummary || {};
      const publicPilot = safe.publicPilotChecklistSummary || releaseReadiness.publicPilotChecklistSummary || {};
      const pilotReadiness = safe.pilotReadinessSummary || releaseReadiness.pilotReadinessSummary || {};
      const onboarding = safe.pilotOnboardingSummary || releaseReadiness.pilotOnboardingSummary || {};
      const consent = safe.readOnlyConsentSummary || releaseReadiness.readOnlyConsentSummary || {};
      if (expansionGate.status === "approved" || expansionGate.decision && expansionGate.decision.safeToExpandReadOnlyBeta === true) badges.push(badge("beta_expansion_approved", "可以小范围扩大只读测试", "info"));
      if (expansionGate.status === "continue_internal_testing" || publicPilot.status === "needs_internal_testing" || pilotReadiness.status === "needs_internal_testing") badges.push(badge("pilot_continue_internal", "继续内部测试", "warning"));
      if (expansionGate.status === "needs_review" || publicPilot.status === "needs_review" || pilotReadiness.status === "needs_review") badges.push(badge("pilot_needs_review", "仍需复核", "warning"));
      if (expansionGate.status === "blocked" || publicPilot.status === "blocked" || pilotReadiness.status === "blocked") badges.push(badge("pilot_blocked", "暂不可扩大测试", "blocked"));
      if (publicPilot.status === "ready" || publicPilot.readiness && publicPilot.readiness.safeForSmallPublicPilot === true) badges.push(badge("public_pilot_checklist_ready", "试点检查清单通过", "info"));
      if (publicPilot.checklistName || pilotReadiness.viewModelName || expansionGate.gateName) badges.push(badge("public_pilot_read_only", "公开试点仍为只读", "info"));
      if (consent.status === "accepted" || consent.consentSummary && consent.consentSummary.allRequiredAccepted === true) badges.push(badge("pilot_consent_accepted", "已确认只读范围", "info"));
      else if (consent.consentFlowName || onboarding.guardName) badges.push(badge("pilot_consent_required", "仍需确认只读范围", "warning"));
      if (onboarding.status === "allowed" || onboarding.decision && onboarding.decision.canEnterReadOnlyPilot === true) badges.push(badge("pilot_entry_allowed", "可以进入只读试点", "info"));
      if (onboarding.status === "blocked" || onboarding.status === "failed_safe") badges.push(badge("pilot_entry_blocked", "暂不可进入只读试点", "blocked"));
      if (onboarding.guardName || consent.consentFlowName) badges.push(badge("pilot_consent_not_transaction", "只读试点不代表交易授权", "info"));
      const issueIntake = safe.issueIntakeSummary || releaseReadiness.issueIntakeSummary || {};
      const supportFallback = safe.supportFallbackSummary || releaseReadiness.supportFallbackSummary || {};
      const pilotSupport = safe.pilotSupportSummary || releaseReadiness.pilotSupportSummary || {};
      if (issueIntake.status === "ready" || issueIntake.status === "redacted" || pilotSupport.viewModelName) badges.push(badge("pilot_support_redacted", "问题反馈已脱敏", "info"));
      if (supportFallback.status === "ready") badges.push(badge("pilot_support_ready", "支持兜底正常", "info"));
      if (supportFallback.status === "needs_review" || supportFallback.status === "blocked" || issueIntake.status === "blocked") badges.push(badge("pilot_support_internal_review", "需要内部复核", "warning"));
      if (issueIntake.issueCategory === "platform_mismatch") badges.push(badge("pilot_platform_mismatch", "平台核对差异待处理", "warning"));
      if (issueIntake.issueCategory === "safety_copy_unclear") badges.push(badge("pilot_safety_copy_review", "安全文案需优化", "warning"));
      const issueReview = safe.issueReviewSummary || releaseReadiness.issueReviewSummary || {};
      const issueHealth = issueReview.issueHealth || {};
      const supportTriage = safe.supportTriageSummary || releaseReadiness.supportTriageSummary || {};
      const triage = supportTriage.triage || {};
      if (issueReview.status === "ready" || safe.pilotIssueReviewStatus === "ready") badges.push(badge("pilot_issue_review_ready", "问题可用于改进参考", "info"));
      if (issueReview.status === "needs_review" || supportTriage.status === "needs_internal_review" || safe.issueRequiresInternalReview === true || issueHealth.requiresInternalReview === true || triage.requiresInternalReview === true) badges.push(badge("pilot_issue_internal_review", "问题需要内部复核", "warning"));
      if (safe.issueAffectsPilotExpansion === true || issueHealth.affectsPilotExpansion === true || triage.affectsPilotExpansion === true) badges.push(badge("pilot_issue_affects_expansion", "问题影响试点扩大", "warning"));
      if (supportTriage.status === "ready" || triage.triageId) badges.push(badge("pilot_issue_triage_done", "问题分流完成", "info"));
      if (issueReview.status === "blocked" || supportTriage.status === "blocked") badges.push(badge("pilot_issue_blocked", "问题已安全阻断", "blocked"));
      const issuePattern = obj(safe.issuePatternSummary);
      const supportReadiness = obj(safe.supportReadinessSummary);
      const cohortProgress = obj(safe.cohortProgressSummary);
      const trialMilestone = obj(safe.trialMilestoneSummary);
      if (issuePattern.status === "ready" || safe.issuePatternStatus === "ready") badges.push(badge("pilot_issue_pattern_ready", "试点问题趋势正常", "info"));
      if (issuePattern.status === "needs_review" || safe.repeatedIssueRisk === true) badges.push(badge("pilot_issue_pattern_repeated", "发现高频问题", "warning"));
      if (supportReadiness.status === "ready" || safe.supportReadyForPublicPilot === true) badges.push(badge("support_readiness_ready", "支持兜底准备就绪", "info"));
      if (supportReadiness.status === "continue_small_pilot" || safe.supportReadinessStatus === "continue_small_pilot") badges.push(badge("support_readiness_small_pilot", "继续小范围试点", "warning"));
      if (supportReadiness.status === "needs_review" || safe.supportReadinessStatus === "needs_review") badges.push(badge("support_readiness_pause_expansion", "需要暂停扩大测试", "warning"));
      const pilotExitCriteria = obj(safe.pilotExitCriteriaSummary || safe.exitCriteriaSummary);
      const launchCandidateReadiness = obj(safe.launchCandidateReadinessSummary || safe.launchCandidateSummary);
      const freezeGateSummary = obj(safe.freezeGateSummary || safe.launchCandidateFreezeGateSummary);
      const evidenceFreezePackSummary = obj(safe.evidenceFreezePackSummary || safe.freezePackSummary);
      if (pilotExitCriteria.status === "met" || pilotExitCriteria.exitHealth && pilotExitCriteria.exitHealth.readyForLaunchCandidate === true) badges.push(badge("pilot_exit_criteria_met", "试点退出条件已满足", "info"));
      if (pilotExitCriteria.status === "continue_pilot" || safe.pilotExitCriteriaStatus === "continue_pilot") badges.push(badge("pilot_exit_criteria_continue", "继续试点观察", "warning"));
      if (launchCandidateReadiness.status === "ready" || launchCandidateReadiness.launchCandidateReadiness && launchCandidateReadiness.launchCandidateReadiness.safeForReadOnlyLaunchCandidate === true) badges.push(badge("launch_candidate_ready", "只读发布候选已准备", "info"));
      if (launchCandidateReadiness.status === "needs_review" || safe.launchCandidateStatus === "needs_review") badges.push(badge("launch_candidate_review", "发布候选仍需复核", "warning"));
      if (launchCandidateReadiness.status === "blocked" || safe.launchCandidateStatus === "blocked") badges.push(badge("launch_candidate_blocked", "发布候选已阻断", "blocked"));
      if (freezeGateSummary.status === "frozen") badges.push(badge("launch_candidate_frozen", "只读发布候选已冻结", "info"));
      if (freezeGateSummary.status === "ready_to_freeze") badges.push(badge("launch_candidate_ready_to_freeze", "准备冻结只读发布候选", "info"));
      if (freezeGateSummary.status === "needs_review") badges.push(badge("launch_candidate_freeze_review", "冻结仍需复核", "warning"));
      if (freezeGateSummary.status === "blocked") badges.push(badge("launch_candidate_freeze_blocked", "冻结已阻断", "blocked"));
      if (evidenceFreezePackSummary.status === "ready") badges.push(badge("evidence_freeze_pack_ready", "证据冻结包已就绪", "info"));
      if (evidenceFreezePackSummary.status === "needs_review") badges.push(badge("evidence_freeze_pack_review", "证据冻结仍需复核", "warning"));
      if (evidenceFreezePackSummary.status === "blocked") badges.push(badge("evidence_freeze_pack_blocked", "证据冻结包已阻断", "blocked"));
      const rcCandidateReview = obj(safe.rcCandidateReviewSummary);
      const rcEvidenceReview = obj(safe.rcEvidenceReviewSummary);
      const rcRegressionAudit = obj(safe.rcRegressionAuditSummary);
      const releaseRiskLedger = obj(safe.releaseRiskLedgerSummary);
      const rcCopyFinalization = obj(safe.rcCopyFinalizationSummary);
      const safetyDisclosureReview = obj(safe.safetyDisclosureReviewSummary);
      const globalShoppingProductGoalSummary = obj(safe.globalShoppingProductGoalSummary);
      const jumpToPlatformBoundarySummary = obj(safe.jumpToPlatformBoundarySummary);
      const priceSourceNormalizationSummary = obj(safe.priceSourceNormalizationSummary);
      const officialPriceAnchorSummary = obj(safe.officialPriceAnchorSummary);
      const priceCandidateDisplaySummary = obj(safe.priceCandidateDisplaySummary);
      const sameItemMatcherSummary = obj(safe.sameItemMatcherSummary);
      const duplicateCandidateMergerSummary = obj(safe.duplicateCandidateMergerSummary);
      const coveredLowestCandidateBoardSummary = obj(safe.coveredLowestCandidateBoardSummary);
      const externalDeepLinkSafetySummary = obj(safe.externalDeepLinkSafetySummary);
      const searchParameterPrefillSummary = obj(safe.searchParameterPrefillSummary);
      const jumpToPlatformHandoffPreviewSummary = obj(safe.jumpToPlatformHandoffPreviewSummary);
      const sandboxDeepLinkCandidateSummary = obj(safe.sandboxDeepLinkCandidateSummary);
      const platformAvailabilitySummary = obj(safe.platformAvailabilitySummary);
      const partnerLinkPolicySummary = obj(safe.partnerLinkPolicySummary);
      const sandboxHandoffViewModelSummary = obj(safe.sandboxHandoffViewModelSummary);
      const readOnlyProviderSandboxConnectorSummary = obj(safe.readOnlyProviderSandboxConnectorSummary);
      const fixtureReplayConsoleSummary = obj(safe.fixtureReplayConsoleSummary);
      const normalizedPriceCandidateBoardSummary = obj(safe.normalizedPriceCandidateBoardSummary);
      const realProviderSandboxGateSummary = obj(safe.realProviderSandboxGateSummary);
      const providerRequestEnvelopeSummary = obj(safe.providerRequestEnvelopeSummary);
      const providerCallAuditLedgerSummary = obj(safe.providerCallAuditLedgerSummary);
      const providerSandboxReadinessViewModelSummary = obj(safe.providerSandboxReadinessViewModelSummary);
      const providerSandboxDryRunHarnessSummary = obj(safe.providerSandboxDryRunHarnessSummary);
      const firstReadOnlyProviderAdapterShellSummary = obj(safe.firstReadOnlyProviderAdapterShellSummary);
      const providerSandboxSafetyKillSwitchSummary = obj(safe.providerSandboxSafetyKillSwitchSummary);
      const providerSandboxDryRunViewModelSummary = obj(safe.providerSandboxDryRunViewModelSummary);
      const providerAdapterRegistrySummary = obj(safe.providerAdapterRegistrySummary);
      const dryRunProviderResponseNormalizerSummary = obj(safe.dryRunProviderResponseNormalizerSummary);
      const sandboxProviderRunbookSummary = obj(safe.sandboxProviderRunbookSummary);
      const providerAdapterRegistryViewModelSummary = obj(safe.providerAdapterRegistryViewModelSummary);
      const readOnlyProviderSandboxIntegrationGateSummary = obj(safe.readOnlyProviderSandboxIntegrationGateSummary);
      const sandboxPriceCandidateSessionSummary = obj(safe.sandboxPriceCandidateSessionSummary);
      const sandboxPriceCandidateResultBoardSummary = obj(safe.sandboxPriceCandidateResultBoardSummary);
      const legalProviderFixtureSummary = obj(safe.legalProviderFixtureSummary);
      const providerCredentialSafetySummary = obj(safe.providerCredentialSafetySummary);
      const sandboxPriceFeedSummary = obj(safe.sandboxPriceFeedSummary);
      const providerFixtureViewModelSummary = obj(safe.providerFixtureViewModelSummary);
      const sandboxProviderResponseContractSummary = obj(safe.sandboxProviderResponseContractSummary);
      const pricePipelineOrchestratorSummary = obj(safe.pricePipelineOrchestratorSummary);
      const readOnlyCandidateJourneySummary = obj(safe.readOnlyCandidateJourneySummary);
      if (rcCandidateReview.status === "ready_for_review" || safe.safeToStartRcReview === true) badges.push(badge("rc_review_ready", "可以开始 RC 复核", "info"));
      if (rcCandidateReview.status === "evidence_incomplete" || rcEvidenceReview.status === "incomplete") badges.push(badge("rc_review_incomplete", "证据仍需补充", "warning"));
      if (rcCandidateReview.status === "needs_safety_review" || rcEvidenceReview.status === "needs_review") badges.push(badge("rc_review_safety_review", "需要安全复核", "warning"));
      if (rcCandidateReview.status === "blocked" || rcEvidenceReview.status === "blocked") badges.push(badge("rc_review_blocked", "RC 复核已阻断", "blocked"));
      if (rcCandidateReview.consoleName || rcEvidenceReview.checklistName) badges.push(badge("rc_review_read_only_only", "复核不代表交易能力", "info"));
      if (rcRegressionAudit.status === "passed") badges.push(badge("rc_regression_passed", "RC 回归审计通过", "info"));
      if (rcRegressionAudit.status === "needs_review") badges.push(badge("rc_regression_needs_review", "RC 回归仍需复核", "warning"));
      if (releaseRiskLedger.status === "clear") badges.push(badge("release_risk_clear", "暂无阻断风险", "info"));
      if (releaseRiskLedger.status === "open_risks" || releaseRiskLedger.status === "needs_review") badges.push(badge("release_risk_pending", "发布风险待处理", "warning"));
      if (releaseRiskLedger.status === "blocked") badges.push(badge("release_risk_blocked", "发布风险已阻断", "blocked"));
      if (rcCopyFinalization.status === "finalized") badges.push(badge("rc_copy_finalized", "RC 文案可以定稿", "info"));
      if (rcCopyFinalization.status === "needs_review") badges.push(badge("rc_copy_needs_review", "RC 文案仍需复核", "warning"));
      if (safetyDisclosureReview.status === "approved") badges.push(badge("safety_disclosure_approved", "安全披露通过", "info"));
      if (safetyDisclosureReview.status === "needs_review") badges.push(badge("safety_disclosure_needs_review", "安全披露仍需复核", "warning"));
      if (safetyDisclosureReview.status === "blocked") badges.push(badge("safety_disclosure_blocked", "安全披露已阻断", "blocked"));
      if (rcCopyFinalization.finalizationName || safetyDisclosureReview.boardName) badges.push(badge("copy_disclosure_read_only", "文案不代表交易能力", "info"));
      if (globalShoppingProductGoalSummary.status === "aligned") badges.push(badge("global_shopping_goal_aligned", "全球购目标已对齐", "info"));
      if (globalShoppingProductGoalSummary.status === "needs_review") badges.push(badge("global_shopping_goal_review", "全球购目标仍需复核", "warning"));
      if (globalShoppingProductGoalSummary.status === "blocked") badges.push(badge("global_shopping_goal_blocked", "全球购目标已阻断", "blocked"));
      if (jumpToPlatformBoundarySummary.status === "safe") badges.push(badge("jump_boundary_safe", "跳转平台边界安全", "info"));
      if (jumpToPlatformBoundarySummary.status === "needs_review") badges.push(badge("jump_boundary_review", "跳转平台边界仍需复核", "warning"));
      if (jumpToPlatformBoundarySummary.status === "blocked") badges.push(badge("jump_boundary_blocked", "跳转平台边界已阻断", "blocked"));
      if (globalShoppingProductGoalSummary.status || jumpToPlatformBoundarySummary.status) badges.push(badge("user_checkout_on_platform", "用户在平台自行下单", "info"));
      if (globalShoppingProductGoalSummary.status || jumpToPlatformBoundarySummary.status) badges.push(badge("no_lowest_claim", "禁止最低价相关承诺", "warning"));
      if (globalShoppingProductGoalSummary.status || jumpToPlatformBoundarySummary.status) badges.push(badge("no_one_click_order_claim", "禁止自动下单承诺", "warning"));
      if (globalShoppingProductGoalSummary.status || jumpToPlatformBoundarySummary.status) badges.push(badge("jump_not_transaction", "跳转不代表交易能力", "info"));
      if (priceSourceNormalizationSummary.status === "ready") badges.push(badge("price_normalization_ready", "价格归一化结构已准备", "info"));
      if (priceSourceNormalizationSummary.status === "needs_review") badges.push(badge("price_normalization_review", "价格归一化仍需复核", "warning"));
      if (priceSourceNormalizationSummary.status === "blocked") badges.push(badge("price_normalization_blocked", "价格归一化已阻断", "blocked"));
      if (officialPriceAnchorSummary.status === "anchored") badges.push(badge("official_price_anchor_ready", "官方价锚点已建立", "info"));
      if (officialPriceAnchorSummary.status === "missing_official") badges.push(badge("official_price_anchor_missing", "缺少官方价", "warning"));
      if (priceCandidateDisplaySummary.status === "ready") badges.push(badge("covered_lowest_candidate", "已覆盖来源中的较低候选价", "info"));
      if (priceCandidateDisplaySummary.status) badges.push(badge("platform_realtime_price", "价格以平台实时页面为准", "info"));
      if (priceCandidateDisplaySummary.status) badges.push(badge("price_display_not_order", "价格展示不代表下单能力", "info"));
      if (sameItemMatcherSummary.status === "ready") badges.push(badge("same_item_match_ready", "同款候选识别已准备", "info"));
      if (sameItemMatcherSummary.status === "needs_review") badges.push(badge("same_item_match_review", "同款候选识别仍需复核", "warning"));
      if (sameItemMatcherSummary.status === "blocked" || sameItemMatcherSummary.status === "failed_safe") badges.push(badge("same_item_match_blocked", "同款候选识别已阻断", "blocked"));
      if (duplicateCandidateMergerSummary.status === "ready" || duplicateCandidateMergerSummary.status === "merged") badges.push(badge("duplicate_merge_ready", "重复候选合并已准备", "info"));
      if (duplicateCandidateMergerSummary.status === "needs_review") badges.push(badge("duplicate_merge_review", "重复候选合并仍需复核", "warning"));
      if (duplicateCandidateMergerSummary.status === "blocked" || duplicateCandidateMergerSummary.status === "failed_safe") badges.push(badge("duplicate_merge_blocked", "重复候选合并已阻断", "blocked"));
      if (coveredLowestCandidateBoardSummary.status === "ready") badges.push(badge("covered_lowest_board_ready", "已覆盖来源较低候选价已准备", "info"));
      if (coveredLowestCandidateBoardSummary.status === "needs_review") badges.push(badge("covered_lowest_board_review", "已覆盖来源较低候选价仍需复核", "warning"));
      if (coveredLowestCandidateBoardSummary.status === "blocked" || coveredLowestCandidateBoardSummary.status === "failed_safe") badges.push(badge("covered_lowest_board_blocked", "已覆盖来源较低候选价已阻断", "blocked"));
      if (safe.safeToProceedWithDeepLinkSafetyGate === true || coveredLowestCandidateBoardSummary.safeToProceedWithDeepLinkSafetyGate === true) badges.push(badge("deep_link_safety_gate_ready", "跳转前安全门已准备", "info"));
      if (externalDeepLinkSafetySummary.status === "safe") badges.push(badge("external_deep_link_safety_ready", "跳转安全结构已准备", "info"));
      if (externalDeepLinkSafetySummary.status === "needs_review") badges.push(badge("external_deep_link_safety_review", "跳转安全仍需复核", "warning"));
      if (externalDeepLinkSafetySummary.status === "blocked") badges.push(badge("external_deep_link_safety_blocked", "跳转已阻断", "blocked"));
      if (searchParameterPrefillSummary.status === "safe") badges.push(badge("search_prefill_safe", "预填边界安全", "info"));
      if (searchParameterPrefillSummary.status === "needs_review") badges.push(badge("search_prefill_review", "预填边界仍需复核", "warning"));
      if (searchParameterPrefillSummary.status === "blocked") badges.push(badge("search_prefill_blocked", "预填边界已阻断", "blocked"));
      if (jumpToPlatformHandoffPreviewSummary.status === "ready") badges.push(badge("handoff_preview_ready", "跳转至平台查看", "info"));
      if (jumpToPlatformHandoffPreviewSummary.status === "needs_review") badges.push(badge("handoff_preview_review", "跳转预览仍需复核", "warning"));
      if (jumpToPlatformHandoffPreviewSummary.status === "blocked") badges.push(badge("handoff_preview_blocked", "跳转预览已阻断", "blocked"));
      if (jumpToPlatformHandoffPreviewSummary.status) badges.push(badge("handoff_prefill_copy", "可带入搜索条件", "info"));
      if (jumpToPlatformHandoffPreviewSummary.status) badges.push(badge("handoff_self_checkout", "平台自行下单", "info"));
      if (externalDeepLinkSafetySummary.status || searchParameterPrefillSummary.status) badges.push(badge("handoff_no_platform_account_storage", "不保存平台账号", "info"));
      if (externalDeepLinkSafetySummary.status || searchParameterPrefillSummary.status) badges.push(badge("handoff_no_identity_bank_storage", "不保存证件银行卡", "info"));
      if (jumpToPlatformHandoffPreviewSummary.status) badges.push(badge("handoff_preview_not_ordering", "跳转预览不代表下单能力", "warning"));
      if (sandboxDeepLinkCandidateSummary.status === "ready") badges.push(badge("sandbox_deep_link_candidate_ready", "Sandbox 跳转候选已准备", "info"));
      if (sandboxDeepLinkCandidateSummary.status === "needs_review") badges.push(badge("sandbox_deep_link_candidate_review", "Sandbox 跳转候选仍需复核", "warning"));
      if (sandboxDeepLinkCandidateSummary.status === "blocked") badges.push(badge("sandbox_deep_link_candidate_blocked", "Sandbox 跳转候选已阻断", "blocked"));
      if (platformAvailabilitySummary.status === "available") badges.push(badge("platform_availability_ready", "平台候选可展示", "info"));
      if (platformAvailabilitySummary.status === "needs_review") badges.push(badge("platform_availability_review", "平台可用性仍需复核", "warning"));
      if (platformAvailabilitySummary.status === "blocked") badges.push(badge("platform_availability_blocked", "平台可用性已阻断", "blocked"));
      if (partnerLinkPolicySummary.status === "compliant") badges.push(badge("partner_link_policy_ready", "合作链接政策合规", "info"));
      if (partnerLinkPolicySummary.status === "needs_review") badges.push(badge("partner_link_policy_review", "合作链接政策仍需复核", "warning"));
      if (partnerLinkPolicySummary.status === "blocked") badges.push(badge("partner_link_policy_blocked", "合作链接政策已阻断", "blocked"));
      if (partnerLinkPolicySummary.status) badges.push(badge("partner_link_not_lowest", "合作链接不代表最低价", "warning"));
      if (platformAvailabilitySummary.status) badges.push(badge("platform_realtime_truth", "平台页面为实时价格准绳", "info"));
      if (sandboxDeepLinkCandidateSummary.status) badges.push(badge("sandbox_link_no_open", "Sandbox 跳转不打开真实平台", "info"));
      if (platformAvailabilitySummary.status) badges.push(badge("platform_no_endorsement", "平台可用不代表官方背书", "warning"));
      if (readOnlyProviderSandboxConnectorSummary.status === "ready") badges.push(badge("readonly_provider_connector_ready", "只读 Provider Connector 已准备", "info"));
      if (readOnlyProviderSandboxConnectorSummary.status === "needs_review") badges.push(badge("readonly_provider_connector_review", "只读 Provider Connector 仍需复核", "warning"));
      if (readOnlyProviderSandboxConnectorSummary.status === "blocked") badges.push(badge("readonly_provider_connector_blocked", "只读 Provider Connector 已阻断", "blocked"));
      if (fixtureReplayConsoleSummary.status === "ready") badges.push(badge("fixture_replay_ready", "Fixture 回放已准备", "info"));
      if (fixtureReplayConsoleSummary.status === "needs_review") badges.push(badge("fixture_replay_review", "Fixture 回放仍需复核", "warning"));
      if (fixtureReplayConsoleSummary.status === "blocked") badges.push(badge("fixture_replay_blocked", "Fixture 回放已阻断", "blocked"));
      if (normalizedPriceCandidateBoardSummary.status === "ready") badges.push(badge("normalized_price_candidate_board_ready", "归一化价格候选板已准备", "info"));
      if (normalizedPriceCandidateBoardSummary.status === "needs_review") badges.push(badge("normalized_price_candidate_board_review", "归一化价格候选板仍需复核", "warning"));
      if (normalizedPriceCandidateBoardSummary.status === "blocked") badges.push(badge("normalized_price_candidate_board_blocked", "归一化价格候选板已阻断", "blocked"));
      if (realProviderSandboxGateSummary.status === "ready") badges.push(badge("real_provider_sandbox_gate_ready", "真实只读 Provider Sandbox 闸门已准备", "info"));
      if (realProviderSandboxGateSummary.status === "needs_review") badges.push(badge("real_provider_sandbox_gate_review", "真实只读 Provider Sandbox 闸门仍需复核", "warning"));
      if (realProviderSandboxGateSummary.status === "blocked") badges.push(badge("real_provider_sandbox_gate_blocked", "真实只读 Provider Sandbox 闸门已阻断", "blocked"));
      if (providerRequestEnvelopeSummary.status === "ready") badges.push(badge("provider_request_envelope_ready", "Provider 请求封装已准备", "info"));
      if (providerRequestEnvelopeSummary.status === "needs_review") badges.push(badge("provider_request_envelope_review", "Provider 请求封装仍需复核", "warning"));
      if (providerRequestEnvelopeSummary.status === "blocked") badges.push(badge("provider_request_envelope_blocked", "Provider 请求封装已阻断", "blocked"));
      if (providerCallAuditLedgerSummary.status === "ready") badges.push(badge("provider_call_audit_ledger_ready", "Provider 调用审计台账已准备", "info"));
      if (providerCallAuditLedgerSummary.status === "needs_review") badges.push(badge("provider_call_audit_ledger_review", "Provider 调用审计台账仍需复核", "warning"));
      if (providerCallAuditLedgerSummary.status === "blocked") badges.push(badge("provider_call_audit_ledger_blocked", "Provider 调用审计台账已阻断", "blocked"));
      if (providerRequestEnvelopeSummary.status) badges.push(badge("provider_request_envelope_not_send", "请求封装不发送真实请求", "info"));
      if (providerCallAuditLedgerSummary.status) badges.push(badge("provider_call_audit_no_raw_response", "调用审计不保存 raw response", "info"));
      if (providerSandboxReadinessViewModelSummary.status) badges.push(badge("provider_sandbox_readiness_not_real_price", "Sandbox 准备不代表真实价格", "warning"));
      if (providerSandboxReadinessViewModelSummary.status) badges.push(badge("provider_sandbox_readiness_not_ordering", "Sandbox 准备不代表下单能力", "warning"));
      if (providerSandboxDryRunHarnessSummary.status === "ready") badges.push(badge("provider_sandbox_dry_run_ready", "Provider Sandbox 干跑框架已准备", "info"));
      if (providerSandboxDryRunHarnessSummary.status === "needs_review") badges.push(badge("provider_sandbox_dry_run_review", "Provider Sandbox 干跑框架仍需复核", "warning"));
      if (providerSandboxDryRunHarnessSummary.status === "blocked") badges.push(badge("provider_sandbox_dry_run_blocked", "Provider Sandbox 干跑框架已阻断", "blocked"));
      if (firstReadOnlyProviderAdapterShellSummary.status === "ready") badges.push(badge("provider_adapter_shell_ready", "第一个只读 Provider Adapter 外壳已准备", "info"));
      if (firstReadOnlyProviderAdapterShellSummary.status === "needs_review") badges.push(badge("provider_adapter_shell_review", "第一个只读 Provider Adapter 外壳仍需复核", "warning"));
      if (firstReadOnlyProviderAdapterShellSummary.status === "blocked") badges.push(badge("provider_adapter_shell_blocked", "第一个只读 Provider Adapter 外壳已阻断", "blocked"));
      if (providerSandboxSafetyKillSwitchSummary.status === "clear") badges.push(badge("provider_kill_switch_clear", "Provider Sandbox 安全熔断器未触发", "info"));
      if (providerSandboxSafetyKillSwitchSummary.status === "blocked") badges.push(badge("provider_kill_switch_blocked", "安全熔断器阻断真实 provider 风险", "blocked"));
      if (providerSandboxDryRunViewModelSummary.status === "ready") badges.push(badge("provider_dry_run_view_ready", "Provider Sandbox 干跑准备", "info"));
      if (providerSandboxDryRunHarnessSummary.status || firstReadOnlyProviderAdapterShellSummary.status || providerSandboxSafetyKillSwitchSummary.status) badges.push(badge("provider_dry_run_no_request", "干跑不发送真实请求", "info"));
      if (firstReadOnlyProviderAdapterShellSummary.status) badges.push(badge("provider_adapter_no_endpoint", "Adapter 外壳不包含真实 endpoint", "info"));
      if (providerSandboxDryRunViewModelSummary.status) badges.push(badge("provider_dry_run_not_real_price", "干跑不代表真实价格或下单能力", "warning"));
      if (providerAdapterRegistrySummary.status === "ready") badges.push(badge("provider_adapter_registry_ready", "Adapter 注册表已准备", "info"));
      if (providerAdapterRegistrySummary.status === "needs_review") badges.push(badge("provider_adapter_registry_review", "Adapter 注册表仍需复核", "warning"));
      if (providerAdapterRegistrySummary.status === "blocked") badges.push(badge("provider_adapter_registry_blocked", "Adapter 注册表已阻断", "blocked"));
      if (dryRunProviderResponseNormalizerSummary.status === "ready") badges.push(badge("dry_run_response_normalizer_ready", "Dry-run 响应归一化已准备", "info"));
      if (dryRunProviderResponseNormalizerSummary.status === "needs_review") badges.push(badge("dry_run_response_normalizer_review", "Dry-run 响应归一化仍需复核", "warning"));
      if (dryRunProviderResponseNormalizerSummary.status === "blocked") badges.push(badge("dry_run_response_normalizer_blocked", "Dry-run 响应归一化已阻断", "blocked"));
      if (sandboxProviderRunbookSummary.status === "ready") badges.push(badge("sandbox_provider_runbook_ready", "Sandbox Provider 接入手册已准备", "info"));
      if (sandboxProviderRunbookSummary.status === "needs_review") badges.push(badge("sandbox_provider_runbook_review", "Sandbox Provider 接入手册仍需复核", "warning"));
      if (sandboxProviderRunbookSummary.status === "blocked") badges.push(badge("sandbox_provider_runbook_blocked", "Sandbox Provider 接入手册已阻断", "blocked"));
      if (providerAdapterRegistrySummary.status) badges.push(badge("provider_adapter_registry_read_only", "只允许只读 adapter 注册", "info"));
      if (dryRunProviderResponseNormalizerSummary.status) badges.push(badge("dry_run_response_normalizer_no_raw", "不接收 raw provider response", "info"));
      if (sandboxProviderRunbookSummary.status) badges.push(badge("sandbox_provider_runbook_no_execution", "接入手册不执行真实接入", "warning"));
      if (providerAdapterRegistryViewModelSummary.status || providerAdapterRegistrySummary.status) badges.push(badge("provider_adapter_registry_not_connected", "Adapter 注册不代表真实 provider 接通", "warning"));
      if (readOnlyProviderSandboxConnectorSummary.status || fixtureReplayConsoleSummary.status || normalizedPriceCandidateBoardSummary.status) badges.push(badge("fixture_replay_not_real_provider", "Replay 不代表真实 provider 调用", "warning"));
      if (readOnlyProviderSandboxConnectorSummary.status || legalProviderFixtureSummary.status || providerCredentialSafetySummary.status) badges.push(badge("connector_no_prod_key", "Connector 不读取生产密钥", "info"));
      if (readOnlyProviderSandboxIntegrationGateSummary.status === "ready") badges.push(badge("provider_sandbox_integration_gate_ready", "只读 Provider Sandbox 接入闸门已准备", "info"));
      if (readOnlyProviderSandboxIntegrationGateSummary.status === "needs_review") badges.push(badge("provider_sandbox_integration_gate_review", "只读 Provider Sandbox 接入闸门仍需复核", "warning"));
      if (readOnlyProviderSandboxIntegrationGateSummary.status === "blocked") badges.push(badge("provider_sandbox_integration_gate_blocked", "只读 Provider Sandbox 接入闸门已阻断", "blocked"));
      if (sandboxPriceCandidateSessionSummary.status === "ready") badges.push(badge("sandbox_price_candidate_session_ready", "Sandbox 价格候选会话已准备", "info"));
      if (sandboxPriceCandidateSessionSummary.status === "needs_review") badges.push(badge("sandbox_price_candidate_session_review", "Sandbox 价格候选会话仍需复核", "warning"));
      if (sandboxPriceCandidateSessionSummary.status === "blocked") badges.push(badge("sandbox_price_candidate_session_blocked", "Sandbox 价格候选会话已阻断", "blocked"));
      if (sandboxPriceCandidateResultBoardSummary.status === "ready") badges.push(badge("sandbox_price_candidate_result_ready", "Sandbox 价格候选结果已准备", "info"));
      if (sandboxPriceCandidateResultBoardSummary.status === "needs_review") badges.push(badge("sandbox_price_candidate_result_review", "Sandbox 价格候选结果仍需复核", "warning"));
      if (sandboxPriceCandidateResultBoardSummary.status === "blocked") badges.push(badge("sandbox_price_candidate_result_blocked", "Sandbox 价格候选结果已阻断", "blocked"));
      if (sandboxPriceCandidateResultBoardSummary.status || sandboxPriceCandidateSessionSummary.status) badges.push(badge("sandbox_result_not_real_price", "Sandbox 结果不代表真实价格", "warning"));
      if (sandboxPriceCandidateResultBoardSummary.status || sandboxPriceCandidateSessionSummary.status) badges.push(badge("sandbox_result_not_lowest", "候选结果不代表全网最低", "warning"));
      if (sandboxPriceCandidateResultBoardSummary.status || sandboxPriceCandidateSessionSummary.status) badges.push(badge("sandbox_result_not_ordering", "候选结果不代表下单能力", "warning"));
      if (sandboxPriceCandidateResultBoardSummary.status || readOnlyProviderSandboxIntegrationGateSummary.status) badges.push(badge("sandbox_result_platform_truth", "价格以未来平台实时页面为准", "info"));
      if (normalizedPriceCandidateBoardSummary.status || pricePipelineOrchestratorSummary.status) badges.push(badge("normalized_candidate_not_real_price", "归一化候选不代表真实价格", "warning"));
      if (normalizedPriceCandidateBoardSummary.status || readOnlyCandidateJourneySummary.status) badges.push(badge("normalized_candidate_not_ordering", "价格候选板不代表下单能力", "warning"));
      if (sandboxHandoffViewModelSummary.status === "ready") badges.push(badge("sandbox_handoff_ready", "Sandbox 跳转候选与平台可用性已准备", "info"));
      if (legalProviderFixtureSummary.status === "ready") badges.push(badge("legal_provider_fixture_ready", "Provider fixture 已准备", "info"));
      if (legalProviderFixtureSummary.status === "needs_review") badges.push(badge("legal_provider_fixture_review", "Provider fixture 仍需复核", "warning"));
      if (legalProviderFixtureSummary.status === "blocked") badges.push(badge("legal_provider_fixture_blocked", "Provider fixture 已阻断", "blocked"));
      if (providerCredentialSafetySummary.status === "ready") badges.push(badge("provider_credential_safety_ready", "Provider 凭据边界安全", "info"));
      if (providerCredentialSafetySummary.status === "needs_review") badges.push(badge("provider_credential_safety_review", "Provider 凭据边界仍需复核", "warning"));
      if (providerCredentialSafetySummary.status === "blocked") badges.push(badge("provider_credential_safety_blocked", "Provider 凭据边界已阻断", "blocked"));
      if (sandboxPriceFeedSummary.status === "ready") badges.push(badge("sandbox_price_feed_ready", "Sandbox 价格 Feed 已准备", "info"));
      if (sandboxPriceFeedSummary.status === "needs_review") badges.push(badge("sandbox_price_feed_review", "Sandbox 价格 Feed 仍需复核", "warning"));
      if (sandboxPriceFeedSummary.status === "blocked") badges.push(badge("sandbox_price_feed_blocked", "Sandbox 价格 Feed 已阻断", "blocked"));
      if (sandboxProviderResponseContractSummary.status === "ready") badges.push(badge("sandbox_provider_response_contract_ready", "Provider 响应合同已准备", "info"));
      if (sandboxProviderResponseContractSummary.status === "needs_review") badges.push(badge("sandbox_provider_response_contract_review", "Provider 响应合同仍需复核", "warning"));
      if (sandboxProviderResponseContractSummary.status === "blocked") badges.push(badge("sandbox_provider_response_contract_blocked", "Provider 响应合同已阻断", "blocked"));
      if (pricePipelineOrchestratorSummary.status === "ready") badges.push(badge("price_pipeline_ready", "只读价格流水线已准备", "info"));
      if (pricePipelineOrchestratorSummary.status === "needs_review") badges.push(badge("price_pipeline_review", "只读价格流水线仍需复核", "warning"));
      if (pricePipelineOrchestratorSummary.status === "blocked") badges.push(badge("price_pipeline_blocked", "只读价格流水线已阻断", "blocked"));
      if (readOnlyCandidateJourneySummary.status === "ready") badges.push(badge("candidate_journey_ready", "全球购只读候选旅程已准备", "info"));
      if (readOnlyCandidateJourneySummary.status === "needs_review") badges.push(badge("candidate_journey_review", "全球购只读候选旅程仍需复核", "warning"));
      if (readOnlyCandidateJourneySummary.status === "blocked") badges.push(badge("candidate_journey_blocked", "全球购只读候选旅程已阻断", "blocked"));
      if (providerCredentialSafetySummary.status || sandboxPriceFeedSummary.status) badges.push(badge("provider_no_prod_key", "不读取生产密钥", "info"));
      if (legalProviderFixtureSummary.status || providerCredentialSafetySummary.status || sandboxPriceFeedSummary.status) badges.push(badge("provider_no_raw_response", "不保存 raw provider response", "info"));
      if (sandboxPriceFeedSummary.status) badges.push(badge("sandbox_feed_normalization_ready", "Fixture feed 可进入价格归一化", "info"));
      if (providerFixtureViewModelSummary.status || legalProviderFixtureSummary.status) badges.push(badge("provider_fixture_not_real_price", "Provider fixture 不代表真实价格", "warning"));
      if (sandboxProviderResponseContractSummary.status || pricePipelineOrchestratorSummary.status) badges.push(badge("provider_response_not_persisted", "Raw provider response 不持久化", "info"));
      if (pricePipelineOrchestratorSummary.status || readOnlyCandidateJourneySummary.status) badges.push(badge("fixture_enters_candidate_journey", "Fixture 数据进入候选旅程", "info"));
      if (pricePipelineOrchestratorSummary.status) badges.push(badge("price_pipeline_not_real_price", "价格流水线不代表真实价格", "warning"));
      if (readOnlyCandidateJourneySummary.status) badges.push(badge("candidate_journey_not_ordering", "候选旅程不代表下单能力", "warning"));
      if (safe.safeToProceedWithPartnerFixtureAdapter === true || sandboxHandoffViewModelSummary.safeToProceedWithPartnerFixtureAdapter === true) badges.push(badge("partner_fixture_adapter_ready", "合作/联盟链接可继续只读接入", "info"));
      if (safe.safeToProceedWithSandboxCandidateUserPreview === true) badges.push(badge("sandbox_candidate_user_preview_ready", "可继续只读 Sandbox 候选展示", "info"));
      if (cohortProgress.status === "ready" || safe.cohortProgressStatus === "ready") badges.push(badge("cohort_progress_ready", "测试批次进度正常", "info"));
      if (cohortProgress.status === "needs_review" || safe.cohortProgressStatus === "needs_review") badges.push(badge("cohort_progress_in_progress", "测试批次仍在进行", "warning"));
      if (cohortProgress.status === "needs_more_testers" || safe.cohortProgressStatus === "needs_more_testers") badges.push(badge("cohort_progress_needs_more", "仍需更多测试者", "warning"));
      if (trialMilestone.status === "ready" || safe.trialMilestoneStatus === "ready") badges.push(badge("trial_milestone_ready", "下一批测试已准备", "info"));
      if (trialMilestone.status === "needs_review" || safe.trialMilestoneStatus === "needs_review") badges.push(badge("trial_milestone_review", "测试批次仍在进行", "warning"));
      if (trialMilestone.status === "blocked" || safe.trialMilestoneStatus === "blocked") badges.push(badge("trial_milestone_blocked", "测试批次已阻断", "blocked"));
      const rolloutControl = obj(safe.rolloutControlSummary);
      const cohortHealthDashboard = obj(safe.cohortHealthSummary);
      if (rolloutControl.status === "ready" || safe.rolloutDecisionStatus === "ready") badges.push(badge("rollout_control_ready", "发布控制正常", "info"));
      if (obj(rolloutControl.decision).decisionId === "advance_next_cohort") badges.push(badge("rollout_next_cohort_ready", "可以进入下一批只读测试", "info"));
      if (rolloutControl.status === "continue_current_batch" || safe.rolloutDecisionStatus === "continue_current_batch") badges.push(badge("rollout_continue_current", "继续当前小范围试点", "warning"));
      if (rolloutControl.status === "pause_expansion" || safe.rolloutDecisionStatus === "pause_expansion") badges.push(badge("rollout_pause_expansion", "暂停扩大测试", "warning"));
      if (rolloutControl.status === "blocked") badges.push(badge("rollout_blocked", "发布控制已阻断", "blocked"));
      if (cohortHealthDashboard.status === "healthy" || safe.cohortHealthStatus === "healthy") badges.push(badge("cohort_health_healthy", "批次健康", "info"));
      if (cohortHealthDashboard.status === "needs_review" || safe.cohortHealthStatus === "needs_review") badges.push(badge("cohort_health_review", "批次需要复核", "warning"));
      if (cohortHealthDashboard.status === "blocked") badges.push(badge("cohort_health_blocked", "批次已阻断", "blocked"));
      const pilotOpsSummary = safe.pilotOpsSummary || safe.readOnlyPilotOpsSummary || {};
      const nextCohortDecision = safe.nextCohortDecisionSummary || safe.nextCohortDecisionBoard || {};
      if (pilotOpsSummary.status === "healthy" || safe.pilotOpsStatus === "healthy") badges.push(badge("pilot_ops_healthy", "试点运行健康", "info"));
      if (pilotOpsSummary.status === "continue_current_batch" || safe.pilotOpsStatus === "continue_current_batch") badges.push(badge("pilot_ops_continue_current", "继续当前批次", "warning"));
      if (pilotOpsSummary.status === "pause_expansion" || safe.pilotOpsStatus === "pause_expansion") badges.push(badge("pilot_ops_pause_expansion", "暂停扩大测试", "warning"));
      if (pilotOpsSummary.status === "needs_review" || safe.pilotOpsStatus === "needs_review") badges.push(badge("pilot_ops_needs_review", "运营需要复核", "warning"));
      if (pilotOpsSummary.status === "blocked" || safe.pilotOpsStatus === "blocked") badges.push(badge("pilot_ops_blocked", "试点运营已阻断", "blocked"));
      if (obj(nextCohortDecision.decision).decisionId === "advance_next_cohort" || nextCohortDecision.status === "advance") badges.push(badge("next_cohort_advance", "下一批可推进", "info"));
      if (nextCohortDecision.status === "continue_current" || safe.nextCohortDecisionStatus === "continue_current") badges.push(badge("next_cohort_continue", "继续当前批次", "warning"));
      if (nextCohortDecision.status === "pause" || safe.nextCohortDecisionStatus === "pause") badges.push(badge("next_cohort_pause", "暂停扩大测试", "warning"));
      if (nextCohortDecision.status === "needs_review" || safe.nextCohortDecisionStatus === "needs_review") badges.push(badge("next_cohort_needs_review", "运营需要复核", "warning"));
      if (nextCohortDecision.status === "blocked" || safe.nextCohortDecisionStatus === "blocked") badges.push(badge("next_cohort_blocked", "试点运营已阻断", "blocked"));
      if (beta.status === "blocked" || guided.status === "blocked" || guided.status === "failed_safe") badges.push(badge("beta_acceptance_blocked", "Beta 验收被阻断", "blocked"));
      if (copyStatus === "pass" || releaseReadiness.copyValidationStatus === "pass") badges.push(badge("safety_copy_unified", "安全文案已统一", "info"));
      badges.push(badge("not_exportable", "不可导出", "warning"));
      return clone({ builderName:BUILDER_NAME, appVersion:FLIGHT_WORKFLOW_RISK_BADGE_BUILDER_VERSION, status:health.overall === "blocked" ? "blocked" : "ready", badges:badges, summaryLabel:summarizeFlightWorkflowRiskBadges(badges).summaryLabel, safety:safety(), bookingUrl:null, redacted:true });
    } catch (error) {
      return clone({ builderName:BUILDER_NAME, appVersion:FLIGHT_WORKFLOW_RISK_BADGE_BUILDER_VERSION, status:"failed_safe", badges:[badge("read_only_safe", "只读安全", "info"), badge("not_exportable", "不可导出", "warning")], summaryLabel:"只读安全 / 不可导出", safety:safety(), bookingUrl:null, redacted:true });
    }
  }
  function summarizeFlightWorkflowRiskBadges(badges) {
    const list = Array.isArray(badges) ? badges : [];
    return clone({ builderName:BUILDER_NAME, appVersion:FLIGHT_WORKFLOW_RISK_BADGE_BUILDER_VERSION, badgeCount:list.length, summaryLabel:list.map(function (item) { return safeText(item && item.label || ""); }).filter(Boolean).join(" / ") || "只读安全", safety:safety(), bookingUrl:null, redacted:true });
  }
  function buildFlightWorkflowRiskBadgeBuilderAuditDraft(input) {
    const model = buildFlightWorkflowRiskBadges(input || {});
    return clone({ eventType:"FLIGHT_WORKFLOW_RISK_BADGE_BUILDER_AUDIT_DRAFT", builderName:BUILDER_NAME, appVersion:FLIGHT_WORKFLOW_RISK_BADGE_BUILDER_VERSION, status:model.status, badgeCount:model.badges.length, summaryLabel:model.summaryLabel, bookingUrl:null, payment:false, order:false, ticketing:false, identityUpload:false, secretStored:false, redacted:true });
  }
  window.WeishanFlightWorkflowRiskBadgeBuilder = { FLIGHT_WORKFLOW_RISK_BADGE_BUILDER_VERSION, BUILDER_NAME, buildFlightWorkflowRiskBadges, summarizeFlightWorkflowRiskBadges, buildFlightWorkflowRiskBadgeBuilderAuditDraft };
})();
