;(function () {
  "use strict";
  const FLIGHT_WORKFLOW_HANDOFF_PACKET_POLICY_GUARD_VERSION = "4.0.9";
  const GUARD_NAME = "flight_workflow_handoff_packet_policy_guard_v1";
  const FORBIDDEN_TEXT_RE = /https?:\/\/\S+|token|apiKey|secret|password|身份证|护照|银行卡|credential|passport|cardNumber/ig;
  function clone(value) { return value && typeof value === "object" ? JSON.parse(JSON.stringify(value)) : value; }
  function text(value) { return String(value == null ? "" : value).trim(); }
  function safeText(value) { return text(value).replace(FORBIDDEN_TEXT_RE, "redacted"); }
  function toArray(value) { return Array.isArray(value) ? value.slice() : []; }
  function safety() { return { bookingUrl:null, checkoutUrl:null, paymentUrl:null, orderUrl:null, canOpenExternalPlatform:false, payment:false, order:false, ticketing:false, identityUpload:false, credentialInput:false, rawResponseStored:false, rawUserTextStored:false, secretStored:false, redacted:true }; }
  function scan(value) { const reasons = []; function add(id){ if (reasons.indexOf(id) < 0) reasons.push(id); } function visit(item, key){ if (item == null) return; const name = String(key || ""); if (/rawProviderResponse|rawResponse|rawPayload|rawText|rawUserText|rawInput/i.test(name) && item) add("raw_content_blocked"); if (/token|apiKey|secret|password|auth/i.test(name) && item) add("secret_blocked"); if (/credential|identity|passport|bank|card|idNumber|passportNumber/i.test(name) && item) add("identity_or_credential_blocked"); if (/bookingUrl|checkoutUrl|paymentUrl|orderUrl/i.test(name) && item !== null && item !== false && item !== "") add("trading_url_blocked"); if (/payment|pay/i.test(name) && item === true) add("payment_blocked"); if (/order|checkout/i.test(name) && item === true) add("order_blocked"); if (/ticketing|issue_ticket/i.test(name) && item === true) add("ticketing_blocked"); if (typeof item === "string" && (/token|apiKey|secret|password|sk-|pk-|live_|prod_|身份证|护照|银行卡|https?:\/\//i.test(item))) add("sensitive_text_blocked"); if (Array.isArray(item)) item.forEach(function (child){ visit(child, name); }); else if (item && typeof item === "object") Object.keys(item).forEach(function (childKey){ visit(item[childKey], childKey); }); } visit(value, ""); return reasons; }
  function buildFlightWorkflowHandoffPacketPolicyDecision(input) { return evaluateFlightWorkflowHandoffPacketPolicy(input); }
  function evaluateFlightWorkflowHandoffPacketPolicy(input) { if (!input || typeof input !== "object" || Array.isArray(input)) return clone({ guardName:GUARD_NAME, appVersion:FLIGHT_WORKFLOW_HANDOFF_PACKET_POLICY_GUARD_VERSION, status:"failed_safe", reason:"malformed_input", blockedReasons:["malformed_input"], policy:{ externalOpenForbiddenByDefault:true, paymentForbidden:true, orderForbidden:true, ticketingForbidden:true, identityInputForbidden:true, rawResponseForbidden:true, secretForbidden:true, redacted:true }, safety:safety(), bookingUrl:null, checkoutUrl:null, paymentUrl:null, orderUrl:null, redacted:true }); const reasons = scan(input); const packet = input.finalSafeHandoffPacketSummary || input.finalSafeHandoffPacket || input; const sentinel = input.safetyRegressionSummary || input.sentinelReport || {}; if (sentinel.status === "fail" || sentinel.status === "failed_safe") reasons.push("safety_regression_failed"); const status = reasons.length ? "blocked" : (packet.status === "ready" ? "allowed" : (packet.status === "blocked" ? "blocked" : "needs_review")); const blockedReasons = reasons.concat(packet.status === "blocked" && reasons.indexOf("handoff_packet_blocked") < 0 ? ["handoff_packet_blocked"] : []); return clone({ guardName:GUARD_NAME, appVersion:FLIGHT_WORKFLOW_HANDOFF_PACKET_POLICY_GUARD_VERSION, status:status, reason:status === "allowed" ? "ready_for_user_confirmed_platform_check" : (status === "needs_review" ? "human_review_required" : "handoff_packet_blocked"), blockedReasons:blockedReasons, policy:{ externalOpenForbiddenByDefault:true, paymentForbidden:true, orderForbidden:true, ticketingForbidden:true, identityInputForbidden:true, rawResponseForbidden:true, secretForbidden:true, downloadForbidden:true, fileWriteForbidden:true, redacted:true }, safety:safety(), bookingUrl:null, checkoutUrl:null, paymentUrl:null, orderUrl:null, canOpenExternalPlatform:false, payment:false, order:false, ticketing:false, identityUpload:false, credentialInput:false, rawResponseStored:false, rawUserTextStored:false, secretStored:false, redacted:true }); }
  function buildFlightWorkflowHandoffPacketPolicyGuardAuditDraft(input) { const decision = evaluateFlightWorkflowHandoffPacketPolicy(input || {}); return clone({ eventType:"FLIGHT_WORKFLOW_HANDOFF_PACKET_POLICY_GUARD_AUDIT_DRAFT", guardName:GUARD_NAME, appVersion:FLIGHT_WORKFLOW_HANDOFF_PACKET_POLICY_GUARD_VERSION, status:decision.status, reason:decision.reason, blockedReasons:toArray(decision.blockedReasons).map(safeText), bookingUrl:null, checkoutUrl:null, paymentUrl:null, orderUrl:null, payment:false, order:false, ticketing:false, identityUpload:false, rawResponseStored:false, rawUserTextStored:false, secretStored:false, redacted:true }); }
  window.WeishanFlightWorkflowHandoffPacketPolicyGuard = { FLIGHT_WORKFLOW_HANDOFF_PACKET_POLICY_GUARD_VERSION, GUARD_NAME, evaluateFlightWorkflowHandoffPacketPolicy, buildFlightWorkflowHandoffPacketPolicyDecision, buildFlightWorkflowHandoffPacketPolicyGuardAuditDraft };
})();
