;(function () {
  "use strict";

  const FLIGHT_WORKFLOW_RISK_BADGE_BUILDER_VERSION = "2.9.0";
  const BUILDER_NAME = "flight_workflow_risk_badge_builder_v1";
  const FORBIDDEN_TEXT_RE = /https?:\/\/\S+|token|apiKey|secret|password|身份证|护照|银行卡|credential|passport|cardNumber/ig;
  function clone(value) { return value && typeof value === "object" ? JSON.parse(JSON.stringify(value)) : value; }
  function text(value) { return String(value == null ? "" : value).trim(); }
  function obj(value) { return value && typeof value === "object" && !Array.isArray(value) ? value : {}; }
  function safeText(value) { return text(value).replace(FORBIDDEN_TEXT_RE, "redacted"); }
  function safety() { return { bookingUrl:null, payment:false, order:false, ticketing:false, identityUpload:false, secretStored:false, redacted:true }; }
  function badge(badgeId, label, severity) { return { badgeId:badgeId, label:label, severity:severity || "info", redacted:true }; }
  function healthOf(input) { const safe = input && typeof input === "object" ? input : {}; return safe.auditHealth || safe.auditReview && safe.auditReview.auditHealth || safe.auditReviewCenter && safe.auditReviewCenter.auditHealth || {}; }
  function buildFlightWorkflowRiskBadges(input) {
    try {
      const safe = input && typeof input === "object" ? input : {};
      const health = healthOf(safe);
      const preview = safe.safeSessionExportPreview || safe.exportPreview || {};
      const badges = [badge("read_only_safe", "只读安全", "info")];
      if (health.hasConfirmationRequiredActions || safe.requiresConfirmation === true) badges.push(badge("confirmation_required", "需要二次确认", "warning"));
      if (health.hasBlockedActions || health.hasPaymentRisk || health.hasOrderRisk || health.hasTicketingRisk || safe.tradingBlocked === true) badges.push(badge("trading_blocked", "交易动作已阻断", "blocked"));
      if (health.hasSensitiveInputBlocked || health.hasIdentityUploadRisk) badges.push(badge("sensitive_input_blocked", "敏感输入已阻断", "blocked"));
      const checklist = safe.humanReviewChecklistSummary || safe.humanReviewChecklist || {};
      const packet = safe.finalSafeHandoffPacketSummary || safe.finalSafeHandoffPacket || {};
      const policy = safe.handoffPacketPolicyDecision || {};
      const sentinel = safe.safetyRegressionSummary || safe.sentinelReport || {};
      const operator = safe.operatorConsoleSummary || {};
      if (sentinel.status === "pass") badges.push(badge("safety_regression_pass", "安全回归通过", "info"));
      if (sentinel.status === "fail" || sentinel.status === "failed_safe") badges.push(badge("safety_regression_fail", "安全回归失败", "blocked"));
      if (operator.status === "ready") badges.push(badge("operator_console_ready", "运营控制台正常", "info"));
      if (operator.status === "warning" || checklist.status === "needs_review") badges.push(badge("manual_review_required", "需要人工复核", "warning"));
      if (checklist.status === "ready") badges.push(badge("human_review_done", "人工复核完成", "info"));
      if (checklist.status === "needs_review" || packet.status === "needs_review" || policy.status === "needs_review") badges.push(badge("human_review_needed", "仍需复核", "warning"));
      if (packet.status === "ready" && policy.status === "allowed") badges.push(badge("platform_confirmation_ready", "可进入平台确认", "info"));
      if (packet.status === "blocked" || policy.status === "blocked") badges.push(badge("handoff_packet_blocked", "交接包已阻断", "blocked"));
      if (preview.status === "ready" || safe.canPreviewExport === true) badges.push(badge("export_preview", "可预览脱敏摘要", "info"));
      const releaseReadiness = safe.releaseReadinessSummary || safe.releaseReadiness || {};
      const betaReadiness = safe.userFacingBetaReadiness || releaseReadiness.userFacingBetaReadiness || {};
      const copyStatus = safe.copyValidationStatus || releaseReadiness.copyValidationStatus || "";
      if (releaseReadiness.status === "ready" || betaReadiness.safeForUserFacingBeta === true || releaseReadiness.safeForUserFacingBeta === true) {
        badges.push(badge("release_ready", "发布就绪", "info"));
        badges.push(badge("read_only_beta_ready", "只读 Beta 可验收", "info"));
      } else if (releaseReadiness.status === "warning" || betaReadiness.status === "warning") {
        badges.push(badge("release_needs_review", "仍需复核", "warning"));
      } else if (releaseReadiness.status === "blocked" || releaseReadiness.status === "failed_safe" || betaReadiness.status === "blocked") {
        badges.push(badge("release_not_ready", "暂不可验收", "blocked"));
      }
      const beta = safe.betaAcceptanceSummary || releaseReadiness.betaAcceptanceSummary || {};
      const guided = safe.guidedUserTestSummary || releaseReadiness.guidedUserTestSummary || {};
      const feedback = safe.feedbackSanitizerSummary || releaseReadiness.feedbackSanitizerSummary || {};
      if (beta.status === "ready" || releaseReadiness.betaAcceptanceReady === true || safe.betaAcceptanceReady === true) badges.push(badge("beta_acceptance_ready", "Beta 验收可开始", "info"));
      if (guided.status === "in_progress") badges.push(badge("guided_user_test_in_progress", "Beta 验收进行中", "warning"));
      if (guided.status === "completed") badges.push(badge("guided_user_test_completed", "Beta 验收完成", "info"));
      if (feedback.status === "ready" || feedback.status === "redacted") badges.push(badge("feedback_sanitized", "测试反馈已脱敏", "info"));
      const feedbackReview = safe.feedbackReviewSummary || releaseReadiness.feedbackReviewSummary || {};
      const sessionSummary = safe.acceptanceSessionSummary || releaseReadiness.acceptanceSessionSummary || {};
      if (feedbackReview.status === "ready") badges.push(badge("beta_feedback_ready", "测试反馈可用", "info"));
      if (feedbackReview.status === "needs_review") badges.push(badge("beta_feedback_needs_review", "测试反馈需复核", "warning"));
      if (sessionSummary.status === "completed") badges.push(badge("acceptance_session_completed", "验收会话完成", "info"));
      if (sessionSummary.status === "needs_review" || sessionSummary.status === "in_progress") badges.push(badge("acceptance_session_needs_review", "验收仍需复核", "warning"));
      if (feedbackReview.status === "blocked" || sessionSummary.status === "blocked") badges.push(badge("acceptance_session_blocked", "验收已阻断", "blocked"));
      const cohort = safe.betaCohortSummary || releaseReadiness.betaCohortSummary || {};
      const trend = safe.feedbackTrendSummary || releaseReadiness.feedbackTrendSummary || {};
      const cohortHealth = cohort.cohortHealth || {};
      if (cohort.status === "ready" || cohortHealth.safeToExpandBeta === true || trend.recommendation && trend.recommendation.recommendationId === "expand_read_only_beta") badges.push(badge("beta_cohort_expand_ready", "Beta 反馈可扩大测试", "info"));
      if (cohort.status === "needs_more_feedback" || trend.status === "insufficient_data") badges.push(badge("beta_cohort_insufficient", "趋势数据不足", "warning"));
      if (cohort.status === "needs_review" || trend.status === "needs_review") badges.push(badge("beta_cohort_watch", "Beta 反馈仍需观察", "warning"));
      if (cohort.findings && JSON.stringify(cohort.findings).indexOf("安全文案理解不足") >= 0 || trend.trends && trend.trends.safetyCopyTrend === "not_understood") badges.push(badge("beta_safety_copy_low", "安全文案理解不足", "warning"));
      if (cohort.findings && JSON.stringify(cohort.findings).indexOf("可用性反馈偏弱") >= 0 || trend.trends && trend.trends.usabilityTrend === "negative") badges.push(badge("beta_usability_low", "可用性反馈偏弱", "warning"));
      const expansionGate = safe.betaExpansionGateSummary || releaseReadiness.betaExpansionGateSummary || {};
      const publicPilot = safe.publicPilotChecklistSummary || releaseReadiness.publicPilotChecklistSummary || {};
      const pilotReadiness = safe.pilotReadinessSummary || releaseReadiness.pilotReadinessSummary || {};
      const onboarding = safe.pilotOnboardingSummary || releaseReadiness.pilotOnboardingSummary || {};
      const consent = safe.readOnlyConsentSummary || releaseReadiness.readOnlyConsentSummary || {};
      if (expansionGate.status === "approved" || expansionGate.decision && expansionGate.decision.safeToExpandReadOnlyBeta === true) badges.push(badge("beta_expansion_approved", "可以小范围扩大只读测试", "info"));
      if (expansionGate.status === "continue_internal_testing" || publicPilot.status === "needs_internal_testing" || pilotReadiness.status === "needs_internal_testing") badges.push(badge("pilot_continue_internal", "继续内部测试", "warning"));
      if (expansionGate.status === "needs_review" || publicPilot.status === "needs_review" || pilotReadiness.status === "needs_review") badges.push(badge("pilot_needs_review", "仍需复核", "warning"));
      if (expansionGate.status === "blocked" || publicPilot.status === "blocked" || pilotReadiness.status === "blocked") badges.push(badge("pilot_blocked", "暂不可扩大测试", "blocked"));
      if (publicPilot.status === "ready" || publicPilot.readiness && publicPilot.readiness.safeForSmallPublicPilot === true) badges.push(badge("public_pilot_checklist_ready", "试点检查清单通过", "info"));
      if (publicPilot.checklistName || pilotReadiness.viewModelName || expansionGate.gateName) badges.push(badge("public_pilot_read_only", "公开试点仍为只读", "info"));
      if (consent.status === "accepted" || consent.consentSummary && consent.consentSummary.allRequiredAccepted === true) badges.push(badge("pilot_consent_accepted", "已确认只读范围", "info"));
      else if (consent.consentFlowName || onboarding.guardName) badges.push(badge("pilot_consent_required", "仍需确认只读范围", "warning"));
      if (onboarding.status === "allowed" || onboarding.decision && onboarding.decision.canEnterReadOnlyPilot === true) badges.push(badge("pilot_entry_allowed", "可以进入只读试点", "info"));
      if (onboarding.status === "blocked" || onboarding.status === "failed_safe") badges.push(badge("pilot_entry_blocked", "暂不可进入只读试点", "blocked"));
      if (onboarding.guardName || consent.consentFlowName) badges.push(badge("pilot_consent_not_transaction", "只读试点不代表交易授权", "info"));
      const issueIntake = safe.issueIntakeSummary || releaseReadiness.issueIntakeSummary || {};
      const supportFallback = safe.supportFallbackSummary || releaseReadiness.supportFallbackSummary || {};
      const pilotSupport = safe.pilotSupportSummary || releaseReadiness.pilotSupportSummary || {};
      if (issueIntake.status === "ready" || issueIntake.status === "redacted" || pilotSupport.viewModelName) badges.push(badge("pilot_support_redacted", "问题反馈已脱敏", "info"));
      if (supportFallback.status === "ready") badges.push(badge("pilot_support_ready", "支持兜底正常", "info"));
      if (supportFallback.status === "needs_review" || supportFallback.status === "blocked" || issueIntake.status === "blocked") badges.push(badge("pilot_support_internal_review", "需要内部复核", "warning"));
      if (issueIntake.issueCategory === "platform_mismatch") badges.push(badge("pilot_platform_mismatch", "平台核对差异待处理", "warning"));
      if (issueIntake.issueCategory === "safety_copy_unclear") badges.push(badge("pilot_safety_copy_review", "安全文案需优化", "warning"));
      const issueReview = safe.issueReviewSummary || releaseReadiness.issueReviewSummary || {};
      const issueHealth = issueReview.issueHealth || {};
      const supportTriage = safe.supportTriageSummary || releaseReadiness.supportTriageSummary || {};
      const triage = supportTriage.triage || {};
      if (issueReview.status === "ready" || safe.pilotIssueReviewStatus === "ready") badges.push(badge("pilot_issue_review_ready", "问题可用于改进参考", "info"));
      if (issueReview.status === "needs_review" || supportTriage.status === "needs_internal_review" || safe.issueRequiresInternalReview === true || issueHealth.requiresInternalReview === true || triage.requiresInternalReview === true) badges.push(badge("pilot_issue_internal_review", "问题需要内部复核", "warning"));
      if (safe.issueAffectsPilotExpansion === true || issueHealth.affectsPilotExpansion === true || triage.affectsPilotExpansion === true) badges.push(badge("pilot_issue_affects_expansion", "问题影响试点扩大", "warning"));
      if (supportTriage.status === "ready" || triage.triageId) badges.push(badge("pilot_issue_triage_done", "问题分流完成", "info"));
      if (issueReview.status === "blocked" || supportTriage.status === "blocked") badges.push(badge("pilot_issue_blocked", "问题已安全阻断", "blocked"));
      const issuePattern = obj(safe.issuePatternSummary);
      const supportReadiness = obj(safe.supportReadinessSummary);
      const cohortProgress = obj(safe.cohortProgressSummary);
      const trialMilestone = obj(safe.trialMilestoneSummary);
      if (issuePattern.status === "ready" || safe.issuePatternStatus === "ready") badges.push(badge("pilot_issue_pattern_ready", "试点问题趋势正常", "info"));
      if (issuePattern.status === "needs_review" || safe.repeatedIssueRisk === true) badges.push(badge("pilot_issue_pattern_repeated", "发现高频问题", "warning"));
      if (supportReadiness.status === "ready" || safe.supportReadyForPublicPilot === true) badges.push(badge("support_readiness_ready", "支持兜底准备就绪", "info"));
      if (supportReadiness.status === "continue_small_pilot" || safe.supportReadinessStatus === "continue_small_pilot") badges.push(badge("support_readiness_small_pilot", "继续小范围试点", "warning"));
      if (supportReadiness.status === "needs_review" || safe.supportReadinessStatus === "needs_review") badges.push(badge("support_readiness_pause_expansion", "需要暂停扩大测试", "warning"));
      const pilotExitCriteria = obj(safe.pilotExitCriteriaSummary || safe.exitCriteriaSummary);
      const launchCandidateReadiness = obj(safe.launchCandidateReadinessSummary || safe.launchCandidateSummary);
      const freezeGateSummary = obj(safe.freezeGateSummary || safe.launchCandidateFreezeGateSummary);
      const evidenceFreezePackSummary = obj(safe.evidenceFreezePackSummary || safe.freezePackSummary);
      if (pilotExitCriteria.status === "met" || pilotExitCriteria.exitHealth && pilotExitCriteria.exitHealth.readyForLaunchCandidate === true) badges.push(badge("pilot_exit_criteria_met", "试点退出条件已满足", "info"));
      if (pilotExitCriteria.status === "continue_pilot" || safe.pilotExitCriteriaStatus === "continue_pilot") badges.push(badge("pilot_exit_criteria_continue", "继续试点观察", "warning"));
      if (launchCandidateReadiness.status === "ready" || launchCandidateReadiness.launchCandidateReadiness && launchCandidateReadiness.launchCandidateReadiness.safeForReadOnlyLaunchCandidate === true) badges.push(badge("launch_candidate_ready", "只读发布候选已准备", "info"));
      if (launchCandidateReadiness.status === "needs_review" || safe.launchCandidateStatus === "needs_review") badges.push(badge("launch_candidate_review", "发布候选仍需复核", "warning"));
      if (launchCandidateReadiness.status === "blocked" || safe.launchCandidateStatus === "blocked") badges.push(badge("launch_candidate_blocked", "发布候选已阻断", "blocked"));
      if (freezeGateSummary.status === "frozen") badges.push(badge("launch_candidate_frozen", "只读发布候选已冻结", "info"));
      if (freezeGateSummary.status === "ready_to_freeze") badges.push(badge("launch_candidate_ready_to_freeze", "准备冻结只读发布候选", "info"));
      if (freezeGateSummary.status === "needs_review") badges.push(badge("launch_candidate_freeze_review", "冻结仍需复核", "warning"));
      if (freezeGateSummary.status === "blocked") badges.push(badge("launch_candidate_freeze_blocked", "冻结已阻断", "blocked"));
      if (evidenceFreezePackSummary.status === "ready") badges.push(badge("evidence_freeze_pack_ready", "证据冻结包已就绪", "info"));
      if (evidenceFreezePackSummary.status === "needs_review") badges.push(badge("evidence_freeze_pack_review", "证据冻结仍需复核", "warning"));
      if (evidenceFreezePackSummary.status === "blocked") badges.push(badge("evidence_freeze_pack_blocked", "证据冻结包已阻断", "blocked"));
      const rcCandidateReview = obj(safe.rcCandidateReviewSummary);
      const rcEvidenceReview = obj(safe.rcEvidenceReviewSummary);
      const rcRegressionAudit = obj(safe.rcRegressionAuditSummary);
      const releaseRiskLedger = obj(safe.releaseRiskLedgerSummary);
      const rcCopyFinalization = obj(safe.rcCopyFinalizationSummary);
      const safetyDisclosureReview = obj(safe.safetyDisclosureReviewSummary);
      const globalShoppingProductGoalSummary = obj(safe.globalShoppingProductGoalSummary);
      const jumpToPlatformBoundarySummary = obj(safe.jumpToPlatformBoundarySummary);
      const priceSourceNormalizationSummary = obj(safe.priceSourceNormalizationSummary);
      const officialPriceAnchorSummary = obj(safe.officialPriceAnchorSummary);
      const priceCandidateDisplaySummary = obj(safe.priceCandidateDisplaySummary);
      const sameItemMatcherSummary = obj(safe.sameItemMatcherSummary);
      const duplicateCandidateMergerSummary = obj(safe.duplicateCandidateMergerSummary);
      const coveredLowestCandidateBoardSummary = obj(safe.coveredLowestCandidateBoardSummary);
      const externalDeepLinkSafetySummary = obj(safe.externalDeepLinkSafetySummary);
      const searchParameterPrefillSummary = obj(safe.searchParameterPrefillSummary);
      const jumpToPlatformHandoffPreviewSummary = obj(safe.jumpToPlatformHandoffPreviewSummary);
      const sandboxDeepLinkCandidateSummary = obj(safe.sandboxDeepLinkCandidateSummary);
      const platformAvailabilitySummary = obj(safe.platformAvailabilitySummary);
      const partnerLinkPolicySummary = obj(safe.partnerLinkPolicySummary);
      const sandboxHandoffViewModelSummary = obj(safe.sandboxHandoffViewModelSummary);
      const readOnlyProviderSandboxConnectorSummary = obj(safe.readOnlyProviderSandboxConnectorSummary);
      const fixtureReplayConsoleSummary = obj(safe.fixtureReplayConsoleSummary);
      const normalizedPriceCandidateBoardSummary = obj(safe.normalizedPriceCandidateBoardSummary);
      const realProviderSandboxGateSummary = obj(safe.realProviderSandboxGateSummary);
      const providerRequestEnvelopeSummary = obj(safe.providerRequestEnvelopeSummary);
      const providerCallAuditLedgerSummary = obj(safe.providerCallAuditLedgerSummary);
      const providerSandboxReadinessViewModelSummary = obj(safe.providerSandboxReadinessViewModelSummary);
      const providerSandboxDryRunHarnessSummary = obj(safe.providerSandboxDryRunHarnessSummary);
      const firstReadOnlyProviderAdapterShellSummary = obj(safe.firstReadOnlyProviderAdapterShellSummary);
      const providerSandboxSafetyKillSwitchSummary = obj(safe.providerSandboxSafetyKillSwitchSummary);
      const providerSandboxDryRunViewModelSummary = obj(safe.providerSandboxDryRunViewModelSummary);
      const providerSandboxReadinessWorkbenchSummary = obj(safe.providerSandboxReadinessWorkbenchSummary);
      const offlineProviderScenarioLabSummary = obj(safe.offlineProviderScenarioLabSummary);
      const readOnlyProviderAdapterSdkSkeletonSummary = obj(safe.readOnlyProviderAdapterSdkSkeletonSummary);
      const manualActivationCommandCenterSummary = obj(safe.manualActivationCommandCenterSummary);
      const providerSandboxMilestoneViewModelSummary = obj(safe.providerSandboxMilestoneViewModelSummary);
      const offlineProviderAdapterContractKitSummary = obj(safe.offlineProviderAdapterContractKitSummary);
      const mockSandboxQaMatrixSummary = obj(safe.mockSandboxQaMatrixSummary);
      const humanActivationRunbookCenterSummary = obj(safe.humanActivationRunbookCenterSummary);
      const providerAdapterComplianceChecklistSummary = obj(safe.providerAdapterComplianceChecklistSummary);
      const providerSandboxReleaseCandidateViewModelSummary = obj(safe.providerSandboxReleaseCandidateViewModelSummary);
      const offlineProviderCertificationCenterSummary = obj(safe.offlineProviderCertificationCenterSummary);
      const mockIntegrationRegressionLabSummary = obj(safe.mockIntegrationRegressionLabSummary);
      const humanApprovalEvidenceBinderSummary = obj(safe.humanApprovalEvidenceBinderSummary);
      const adapterBoundaryLockSummary = obj(safe.adapterBoundaryLockSummary);
      const providerCertificationViewModelSummary = obj(safe.providerCertificationViewModelSummary);
      const providerOfflineReleaseGateSummary = obj(safe.providerOfflineReleaseGateSummary);
      const providerCertificationFreezeLedgerSummary = obj(safe.providerCertificationFreezeLedgerSummary);
      const sandboxActivationReviewPacketSummary = obj(safe.sandboxActivationReviewPacketSummary);
      const adapterBoundaryDiffInspectorSummary = obj(safe.adapterBoundaryDiffInspectorSummary);
      const providerOfflineReleaseViewModelSummary = obj(safe.providerOfflineReleaseViewModelSummary);
      const offlineLaunchDecisionSimulatorSummary = obj(safe.offlineLaunchDecisionSimulatorSummary);
      const sandboxActivationReceiptLedgerSummary = obj(safe.sandboxActivationReceiptLedgerSummary);
      const adapterSecurityRegressionGuardSummary = obj(safe.adapterSecurityRegressionGuardSummary);
      const providerOfflineLaunchChecklistSummary = obj(safe.providerOfflineLaunchChecklistSummary);
      const providerOfflineLaunchViewModelSummary = obj(safe.providerOfflineLaunchViewModelSummary);
      const providerAdapterRegistrySummary = obj(safe.providerAdapterRegistrySummary);
      const dryRunProviderResponseNormalizerSummary = obj(safe.dryRunProviderResponseNormalizerSummary);
      const sandboxProviderRunbookSummary = obj(safe.sandboxProviderRunbookSummary);
      const providerAdapterRegistryViewModelSummary = obj(safe.providerAdapterRegistryViewModelSummary);
      const readOnlyProviderSandboxIntegrationGateSummary = obj(safe.readOnlyProviderSandboxIntegrationGateSummary);
      const sandboxPriceCandidateSessionSummary = obj(safe.sandboxPriceCandidateSessionSummary);
      const sandboxPriceCandidateResultBoardSummary = obj(safe.sandboxPriceCandidateResultBoardSummary);
      const sandboxSessionReplayCenterSummary = obj(safe.sandboxSessionReplayCenterSummary);
      const providerEvidenceTraceSummary = obj(safe.providerEvidenceTraceSummary);
      const candidateConfidenceExplainerSummary = obj(safe.candidateConfidenceExplainerSummary);
      const sandboxReplayViewModelSummary = obj(safe.sandboxReplayViewModelSummary);
      const sandboxCandidateComparisonWorkbenchSummary = obj(safe.sandboxCandidateComparisonWorkbenchSummary);
      const providerEvidenceComparisonMatrixSummary = obj(safe.providerEvidenceComparisonMatrixSummary);
      const readOnlyHandoffReadinessDrillSummary = obj(safe.readOnlyHandoffReadinessDrillSummary);
      const sandboxDecisionReviewViewModelSummary = obj(safe.sandboxDecisionReviewViewModelSummary);
      const readOnlyPlatformHandoffSimulatorSummary = obj(safe.readOnlyPlatformHandoffSimulatorSummary);
      const redactedSearchParameterPackSummary = obj(safe.redactedSearchParameterPackSummary);
      const userConfirmationChecklistSummary = obj(safe.userConfirmationChecklistSummary);
      const platformHandoffSimulationViewModelSummary = obj(safe.platformHandoffSimulationViewModelSummary);
      const legalProviderFixtureSummary = obj(safe.legalProviderFixtureSummary);
      const providerCredentialSafetySummary = obj(safe.providerCredentialSafetySummary);
      const sandboxPriceFeedSummary = obj(safe.sandboxPriceFeedSummary);
      const providerFixtureViewModelSummary = obj(safe.providerFixtureViewModelSummary);
      const sandboxProviderResponseContractSummary = obj(safe.sandboxProviderResponseContractSummary);
      const pricePipelineOrchestratorSummary = obj(safe.pricePipelineOrchestratorSummary);
      const readOnlyCandidateJourneySummary = obj(safe.readOnlyCandidateJourneySummary);
      const userFacingManualReviewFlowSummary = obj(safe.userFacingManualReviewFlowSummary);
      const platformVerificationProgressTrackerSummary = obj(safe.platformVerificationProgressTrackerSummary);
      const safeNextActionPanelSummary = obj(safe.safeNextActionPanelSummary);
      const userManualReviewViewModelSummary = obj(safe.userManualReviewViewModelSummary);
      const manualPlatformVisitPreparationCenterSummary = obj(safe.manualPlatformVisitPreparationCenterSummary);
      const externalPlatformBoundaryBriefSummary = obj(safe.externalPlatformBoundaryBriefSummary);
      const finalUserSafetyChecklistSummary = obj(safe.finalUserSafetyChecklistSummary);
      const platformVisitPreparationViewModelSummary = obj(safe.platformVisitPreparationViewModelSummary);
      const externalPlatformExitRampPreviewSummary = obj(safe.externalPlatformExitRampPreviewSummary);
      const manualVisitSafetyBriefSummary = obj(safe.manualVisitSafetyBriefSummary);
      const readOnlySessionClosurePackSummary = obj(safe.readOnlySessionClosurePackSummary);
      const externalPlatformExitViewModelSummary = obj(safe.externalPlatformExitViewModelSummary);
      const readOnlyCommerceSessionRecapCenterSummary = obj(safe.readOnlyCommerceSessionRecapCenterSummary);
      const userTrustClosureSummarySummary = obj(safe.userTrustClosureSummarySummary);
      const nextFeatureReadinessGateSummary = obj(safe.nextFeatureReadinessGateSummary);
      const commerceSessionRecapViewModelSummary = obj(safe.commerceSessionRecapViewModelSummary);
      const readOnlySandboxProviderIntegrationBlueprintSummary = obj(safe.readOnlySandboxProviderIntegrationBlueprintSummary);
      const credentialIsolationReadinessBoardSummary = obj(safe.credentialIsolationReadinessBoardSummary);
      const providerContractSelectionBoardSummary = obj(safe.providerContractSelectionBoardSummary);
      const sandboxProviderPlanningViewModelSummary = obj(safe.sandboxProviderPlanningViewModelSummary);
      const providerLegalReviewDossierSummary = obj(safe.providerLegalReviewDossierSummary);
      const credentialVaultInterfaceStubSummary = obj(safe.credentialVaultInterfaceStubSummary);
      const sandboxAdapterContractTestbedSummary = obj(safe.sandboxAdapterContractTestbedSummary);
      const providerIntegrationPrepViewModelSummary = obj(safe.providerIntegrationPrepViewModelSummary);
      if (rcCandidateReview.status === "ready_for_review" || safe.safeToStartRcReview === true) badges.push(badge("rc_review_ready", "可以开始 RC 复核", "info"));
      if (rcCandidateReview.status === "evidence_incomplete" || rcEvidenceReview.status === "incomplete") badges.push(badge("rc_review_incomplete", "证据仍需补充", "warning"));
      if (rcCandidateReview.status === "needs_safety_review" || rcEvidenceReview.status === "needs_review") badges.push(badge("rc_review_safety_review", "需要安全复核", "warning"));
      if (rcCandidateReview.status === "blocked" || rcEvidenceReview.status === "blocked") badges.push(badge("rc_review_blocked", "RC 复核已阻断", "blocked"));
      if (rcCandidateReview.consoleName || rcEvidenceReview.checklistName) badges.push(badge("rc_review_read_only_only", "复核不代表交易能力", "info"));
      if (rcRegressionAudit.status === "passed") badges.push(badge("rc_regression_passed", "RC 回归审计通过", "info"));
      if (rcRegressionAudit.status === "needs_review") badges.push(badge("rc_regression_needs_review", "RC 回归仍需复核", "warning"));
      if (releaseRiskLedger.status === "clear") badges.push(badge("release_risk_clear", "暂无阻断风险", "info"));
      if (releaseRiskLedger.status === "open_risks" || releaseRiskLedger.status === "needs_review") badges.push(badge("release_risk_pending", "发布风险待处理", "warning"));
      if (releaseRiskLedger.status === "blocked") badges.push(badge("release_risk_blocked", "发布风险已阻断", "blocked"));
      if (rcCopyFinalization.status === "finalized") badges.push(badge("rc_copy_finalized", "RC 文案可以定稿", "info"));
      if (rcCopyFinalization.status === "needs_review") badges.push(badge("rc_copy_needs_review", "RC 文案仍需复核", "warning"));
      if (safetyDisclosureReview.status === "approved") badges.push(badge("safety_disclosure_approved", "安全披露通过", "info"));
      if (safetyDisclosureReview.status === "needs_review") badges.push(badge("safety_disclosure_needs_review", "安全披露仍需复核", "warning"));
      if (safetyDisclosureReview.status === "blocked") badges.push(badge("safety_disclosure_blocked", "安全披露已阻断", "blocked"));
      if (rcCopyFinalization.finalizationName || safetyDisclosureReview.boardName) badges.push(badge("copy_disclosure_read_only", "文案不代表交易能力", "info"));
      if (globalShoppingProductGoalSummary.status === "aligned") badges.push(badge("global_shopping_goal_aligned", "全球购目标已对齐", "info"));
      if (globalShoppingProductGoalSummary.status === "needs_review") badges.push(badge("global_shopping_goal_review", "全球购目标仍需复核", "warning"));
      if (globalShoppingProductGoalSummary.status === "blocked") badges.push(badge("global_shopping_goal_blocked", "全球购目标已阻断", "blocked"));
      if (jumpToPlatformBoundarySummary.status === "safe") badges.push(badge("jump_boundary_safe", "跳转平台边界安全", "info"));
      if (jumpToPlatformBoundarySummary.status === "needs_review") badges.push(badge("jump_boundary_review", "跳转平台边界仍需复核", "warning"));
      if (jumpToPlatformBoundarySummary.status === "blocked") badges.push(badge("jump_boundary_blocked", "跳转平台边界已阻断", "blocked"));
      if (globalShoppingProductGoalSummary.status || jumpToPlatformBoundarySummary.status) badges.push(badge("user_checkout_on_platform", "用户在平台自行下单", "info"));
      if (globalShoppingProductGoalSummary.status || jumpToPlatformBoundarySummary.status) badges.push(badge("no_lowest_claim", "禁止最低价相关承诺", "warning"));
      if (globalShoppingProductGoalSummary.status || jumpToPlatformBoundarySummary.status) badges.push(badge("no_one_click_order_claim", "禁止自动下单承诺", "warning"));
      if (globalShoppingProductGoalSummary.status || jumpToPlatformBoundarySummary.status) badges.push(badge("jump_not_transaction", "跳转不代表交易能力", "info"));
      if (priceSourceNormalizationSummary.status === "ready") badges.push(badge("price_normalization_ready", "价格归一化结构已准备", "info"));
      if (priceSourceNormalizationSummary.status === "needs_review") badges.push(badge("price_normalization_review", "价格归一化仍需复核", "warning"));
      if (priceSourceNormalizationSummary.status === "blocked") badges.push(badge("price_normalization_blocked", "价格归一化已阻断", "blocked"));
      if (officialPriceAnchorSummary.status === "anchored") badges.push(badge("official_price_anchor_ready", "官方价锚点已建立", "info"));
      if (officialPriceAnchorSummary.status === "missing_official") badges.push(badge("official_price_anchor_missing", "缺少官方价", "warning"));
      if (priceCandidateDisplaySummary.status === "ready") badges.push(badge("covered_lowest_candidate", "已覆盖来源中的较低候选价", "info"));
      if (priceCandidateDisplaySummary.status) badges.push(badge("platform_realtime_price", "价格以平台实时页面为准", "info"));
      if (priceCandidateDisplaySummary.status) badges.push(badge("price_display_not_order", "价格展示不代表下单能力", "info"));
      if (sameItemMatcherSummary.status === "ready") badges.push(badge("same_item_match_ready", "同款候选识别已准备", "info"));
      if (sameItemMatcherSummary.status === "needs_review") badges.push(badge("same_item_match_review", "同款候选识别仍需复核", "warning"));
      if (sameItemMatcherSummary.status === "blocked" || sameItemMatcherSummary.status === "failed_safe") badges.push(badge("same_item_match_blocked", "同款候选识别已阻断", "blocked"));
      if (duplicateCandidateMergerSummary.status === "ready" || duplicateCandidateMergerSummary.status === "merged") badges.push(badge("duplicate_merge_ready", "重复候选合并已准备", "info"));
      if (duplicateCandidateMergerSummary.status === "needs_review") badges.push(badge("duplicate_merge_review", "重复候选合并仍需复核", "warning"));
      if (duplicateCandidateMergerSummary.status === "blocked" || duplicateCandidateMergerSummary.status === "failed_safe") badges.push(badge("duplicate_merge_blocked", "重复候选合并已阻断", "blocked"));
      if (coveredLowestCandidateBoardSummary.status === "ready") badges.push(badge("covered_lowest_board_ready", "已覆盖来源较低候选价已准备", "info"));
      if (coveredLowestCandidateBoardSummary.status === "needs_review") badges.push(badge("covered_lowest_board_review", "已覆盖来源较低候选价仍需复核", "warning"));
      if (coveredLowestCandidateBoardSummary.status === "blocked" || coveredLowestCandidateBoardSummary.status === "failed_safe") badges.push(badge("covered_lowest_board_blocked", "已覆盖来源较低候选价已阻断", "blocked"));
      if (safe.safeToProceedWithDeepLinkSafetyGate === true || coveredLowestCandidateBoardSummary.safeToProceedWithDeepLinkSafetyGate === true) badges.push(badge("deep_link_safety_gate_ready", "跳转前安全门已准备", "info"));
      if (externalDeepLinkSafetySummary.status === "safe") badges.push(badge("external_deep_link_safety_ready", "跳转安全结构已准备", "info"));
      if (externalDeepLinkSafetySummary.status === "needs_review") badges.push(badge("external_deep_link_safety_review", "跳转安全仍需复核", "warning"));
      if (externalDeepLinkSafetySummary.status === "blocked") badges.push(badge("external_deep_link_safety_blocked", "跳转已阻断", "blocked"));
      if (searchParameterPrefillSummary.status === "safe") badges.push(badge("search_prefill_safe", "预填边界安全", "info"));
      if (searchParameterPrefillSummary.status === "needs_review") badges.push(badge("search_prefill_review", "预填边界仍需复核", "warning"));
      if (searchParameterPrefillSummary.status === "blocked") badges.push(badge("search_prefill_blocked", "预填边界已阻断", "blocked"));
      if (jumpToPlatformHandoffPreviewSummary.status === "ready") badges.push(badge("handoff_preview_ready", "跳转至平台查看", "info"));
      if (jumpToPlatformHandoffPreviewSummary.status === "needs_review") badges.push(badge("handoff_preview_review", "跳转预览仍需复核", "warning"));
      if (jumpToPlatformHandoffPreviewSummary.status === "blocked") badges.push(badge("handoff_preview_blocked", "跳转预览已阻断", "blocked"));
      if (jumpToPlatformHandoffPreviewSummary.status) badges.push(badge("handoff_prefill_copy", "可带入搜索条件", "info"));
      if (jumpToPlatformHandoffPreviewSummary.status) badges.push(badge("handoff_self_checkout", "平台自行下单", "info"));
      if (externalDeepLinkSafetySummary.status || searchParameterPrefillSummary.status) badges.push(badge("handoff_no_platform_account_storage", "不保存平台账号", "info"));
      if (externalDeepLinkSafetySummary.status || searchParameterPrefillSummary.status) badges.push(badge("handoff_no_identity_bank_storage", "不保存证件银行卡", "info"));
      if (jumpToPlatformHandoffPreviewSummary.status) badges.push(badge("handoff_preview_not_ordering", "跳转预览不代表下单能力", "warning"));
      if (userFacingManualReviewFlowSummary.status === "ready") badges.push(badge("user_manual_review_flow_ready", "用户手动复核流程已准备", "info"));
      if (platformVerificationProgressTrackerSummary.status === "ready") badges.push(badge("platform_verification_progress_ready", "平台核对进度已准备", "info"));
      if (safeNextActionPanelSummary.status === "ready") badges.push(badge("safe_next_action_ready", "安全下一步已准备", "info"));
      if (platformVerificationProgressTrackerSummary.status) badges.push(badge("platform_verification_no_persist", "平台核对进度不保存勾选", "info"));
      if (safeNextActionPanelSummary.status) badges.push(badge("safe_next_action_no_open", "安全下一步不打开平台", "info"));
      if (safeNextActionPanelSummary.status) badges.push(badge("safe_next_action_no_buy", "下一步不包含购买、下单、付款或出票", "warning"));
      if (userManualReviewViewModelSummary.status) badges.push(badge("user_manual_decision_required", "用户必须自行完成最终平台判断", "warning"));
      if (manualPlatformVisitPreparationCenterSummary.status === "ready") badges.push(badge("manual_platform_visit_preparation_ready", "手动访问平台准备已完成", "info"));
      if (externalPlatformBoundaryBriefSummary.status === "ready") badges.push(badge("external_platform_boundary_ready", "外部平台边界说明已准备", "info"));
      if (finalUserSafetyChecklistSummary.status === "ready") badges.push(badge("final_user_safety_checklist_ready", "最终用户安全清单已准备", "info"));
      if (externalPlatformBoundaryBriefSummary.status) badges.push(badge("weishan_not_platform", "Weishan 不代表外部平台", "warning"));
      if (platformVisitPreparationViewModelSummary.status || externalPlatformBoundaryBriefSummary.status) badges.push(badge("platform_final_authority", "平台页面为最终依据", "info"));
      if (finalUserSafetyChecklistSummary.status) badges.push(badge("final_checklist_no_persist", "最终安全清单不保存用户勾选", "info"));
      if (platformVisitPreparationViewModelSummary.status) badges.push(badge("leave_weishan_user_decision", "离开 Weishan 后由用户自行判断", "warning"));
      if (externalPlatformExitRampPreviewSummary.status === "ready") badges.push(badge("external_platform_exit_ramp_ready", "外部平台退出坡道已准备", "info"));
      if (manualVisitSafetyBriefSummary.status === "ready") badges.push(badge("manual_visit_safety_brief_ready", "手动访问安全简报已准备", "info"));
      if (readOnlySessionClosurePackSummary.status === "ready") badges.push(badge("read_only_session_closure_pack_ready", "只读会话关闭包已准备", "info"));
      if (externalPlatformExitRampPreviewSummary.status || externalPlatformExitViewModelSummary.status) badges.push(badge("exit_ramp_no_open", "退出坡道不打开平台", "info"));
      if (manualVisitSafetyBriefSummary.status) badges.push(badge("manual_visit_safety_brief_no_persist", "安全简报不保存确认", "info"));
      if (readOnlySessionClosurePackSummary.status) badges.push(badge("read_only_session_closure_pack_no_export", "会话关闭包不导出、不下载", "info"));
      if (readOnlySessionClosurePackSummary.status || externalPlatformExitViewModelSummary.status) badges.push(badge("read_only_session_closure_not_contract", "关闭包不是合同、订单或付款授权", "warning"));
      if (readOnlyCommerceSessionRecapCenterSummary.status === "ready") badges.push(badge("commerce_session_recap_center_ready", "只读全球购会话总结已准备", "info"));
      if (userTrustClosureSummarySummary.status === "ready") badges.push(badge("user_trust_closure_summary_ready", "用户信任闭环摘要已准备", "info"));
      if (nextFeatureReadinessGateSummary.status === "ready") badges.push(badge("next_feature_readiness_gate_ready", "下一功能准备闸门已准备", "info"));
      if (commerceSessionRecapViewModelSummary.status === "ready") badges.push(badge("commerce_session_recap_view_model_ready", "只读全球购会话总结与下一步准备已准备", "info"));
      if (readOnlyCommerceSessionRecapCenterSummary.status) badges.push(badge("commerce_session_recap_no_export", "会话总结不保存、不导出", "info"));
      if (userTrustClosureSummarySummary.status) badges.push(badge("user_trust_closure_not_confirmation", "信任闭环不构成平台确认", "warning"));
      if (nextFeatureReadinessGateSummary.status) badges.push(badge("next_feature_readiness_no_provider", "下一功能闸门不接真实 provider", "info"));
      if (commerceSessionRecapViewModelSummary.status || nextFeatureReadinessGateSummary.status) badges.push(badge("next_step_human_approval_required", "下一步仍需人工审批", "warning"));
      if (readOnlySandboxProviderIntegrationBlueprintSummary.status === "ready" || safe.sandboxProviderIntegrationBlueprintStatus === "ready") badges.push(badge("sandbox_provider_blueprint_ready", "只读 Sandbox Provider 接入蓝图已准备", "info"));
      if (credentialIsolationReadinessBoardSummary.status === "ready" || safe.credentialIsolationReadinessStatus === "ready") badges.push(badge("credential_isolation_ready", "凭证隔离准备度已通过", "info"));
      if (providerContractSelectionBoardSummary.status === "ready" || safe.providerContractSelectionStatus === "ready") badges.push(badge("provider_contract_selection_ready", "Provider 合同/授权选择板已准备", "info"));
      if (readOnlySandboxProviderIntegrationBlueprintSummary.status || credentialIsolationReadinessBoardSummary.status || providerContractSelectionBoardSummary.status || sandboxProviderPlanningViewModelSummary.status) badges.push(badge("sandbox_provider_blueprint_boundary", "接入蓝图不启动真实接入", "info"));
      if (readOnlySandboxProviderIntegrationBlueprintSummary.status || credentialIsolationReadinessBoardSummary.status || providerContractSelectionBoardSummary.status || sandboxProviderPlanningViewModelSummary.status) badges.push(badge("sandbox_provider_credentials_boundary", "凭证隔离不读取真实密钥", "info"));
      if (readOnlySandboxProviderIntegrationBlueprintSummary.status || credentialIsolationReadinessBoardSummary.status || providerContractSelectionBoardSummary.status || sandboxProviderPlanningViewModelSummary.status) badges.push(badge("sandbox_provider_contract_boundary", "Provider 选择不代表已合作或已授权", "warning"));
      if (safe.safeToProceedWithProviderLegalAndCredentialReview === true) badges.push(badge("sandbox_provider_human_review", "下一步仍需人工法务与安全审批", "warning"));
      if (providerLegalReviewDossierSummary.status === "ready" || safe.providerLegalReviewStatus === "ready") badges.push(badge("provider_legal_review_ready", "Provider 法务审查档案已准备", "info"));
      if (credentialVaultInterfaceStubSummary.status === "ready" || safe.credentialVaultInterfaceStatus === "ready") badges.push(badge("credential_vault_stub_ready", "凭证保险箱接口桩已准备", "info"));
      if (sandboxAdapterContractTestbedSummary.status === "ready" || safe.sandboxAdapterContractStatus === "ready") badges.push(badge("sandbox_adapter_contract_ready", "Sandbox Adapter 合同测试台已准备", "info"));
      if (providerLegalReviewDossierSummary.status || providerIntegrationPrepViewModelSummary.status) badges.push(badge("provider_legal_review_boundary", "法务审查不代表已合作或已授权", "warning"));
      if (credentialVaultInterfaceStubSummary.status || providerIntegrationPrepViewModelSummary.status) badges.push(badge("credential_vault_stub_boundary", "凭证接口桩不读取真实密钥", "info"));
      if (sandboxAdapterContractTestbedSummary.status || providerIntegrationPrepViewModelSummary.status) badges.push(badge("sandbox_adapter_contract_boundary", "Adapter 合同测试不请求真实 provider", "info"));
      if (safe.safeToProceedWithProviderSandboxContractImplementation === true) badges.push(badge("provider_integration_prep_human_review", "下一步仍需人工安全审批", "warning"));
      if (obj(safe.sandboxProviderMockRuntimeSummary).status === "ready" || safe.sandboxProviderMockRuntimeStatus === "ready") badges.push(badge("sandbox_provider_mock_runtime_ready", "Sandbox Provider Mock Runtime 已准备", "info"));
      if (obj(safe.vaultBoundaryContractSummary).status === "ready" || safe.vaultBoundaryContractStatus === "ready") badges.push(badge("vault_boundary_contract_ready", "Vault 边界合同已准备", "info"));
      if (obj(safe.legalApprovalWorkflowBoardSummary).status === "ready" || safe.legalApprovalWorkflowStatus === "ready") badges.push(badge("legal_approval_workflow_ready", "法务审批流程板已准备", "info"));
      if (obj(safe.sandboxProviderMockRuntimeSummary).status || obj(safe.providerMockRuntimeViewModelSummary).status) badges.push(badge("sandbox_provider_mock_runtime_boundary", "Mock Runtime 不接真实 provider", "info"));
      if (obj(safe.vaultBoundaryContractSummary).status || obj(safe.providerMockRuntimeViewModelSummary).status) badges.push(badge("vault_boundary_contract_boundary", "Vault 边界不读取或保存真实密钥", "info"));
      if (obj(safe.legalApprovalWorkflowBoardSummary).status || obj(safe.providerMockRuntimeViewModelSummary).status) badges.push(badge("legal_approval_workflow_boundary", "审批流程不创建任务、不发邮件", "warning"));
      if (safe.safeToProceedWithMockAdapterRuntimeHardening === true) badges.push(badge("provider_mock_runtime_human_review", "下一步仍需人工审批", "warning"));
      if (obj(safe.mockProviderAdapterRegistryRuntimeSummary).status === "ready" || safe.mockProviderAdapterRegistryStatus === "ready") badges.push(badge("mock_provider_adapter_registry_runtime_ready", "Mock Provider Adapter 注册运行时已准备", "info"));
      if (obj(safe.providerContractReplayHarnessSummary).status === "ready" || safe.providerContractReplayStatus === "ready") badges.push(badge("provider_contract_replay_harness_ready", "Provider 合同回放器已准备", "info"));
      if (obj(safe.providerLaunchReadinessBoardSummary).status === "ready" || safe.providerLaunchReadinessStatus === "ready") badges.push(badge("provider_launch_readiness_board_ready", "Provider 启动准备总闸门已准备", "info"));
      if (obj(safe.mockProviderAdapterRegistryRuntimeSummary).status || obj(safe.providerLaunchReadinessViewModelSummary).status) badges.push(badge("mock_provider_adapter_registry_runtime_boundary", "Mock Adapter 注册不接真实 provider", "info"));
      if (obj(safe.providerContractReplayHarnessSummary).status || obj(safe.providerLaunchReadinessViewModelSummary).status) badges.push(badge("provider_contract_replay_harness_boundary", "合同回放不回放 raw request 或 raw response", "info"));
      if (obj(safe.providerLaunchReadinessBoardSummary).status || obj(safe.providerLaunchReadinessViewModelSummary).status) badges.push(badge("provider_launch_readiness_board_boundary", "启动准备不读取密钥、不联网", "warning"));
      if (safe.safeToProceedWithHumanProviderSandboxApproval === true) badges.push(badge("provider_launch_readiness_human_review", "真实 sandbox provider 仍需人工审批", "warning"));
      if (obj(safe.humanApprovalSimulationGateSummary).status === "ready" || safe.humanApprovalSimulationStatus === "ready") badges.push(badge("human_approval_simulation_gate_ready", "人工审批模拟闸门已准备", "info"));
      if (obj(safe.mockProviderLaunchDrillSummary).status === "ready" || safe.mockProviderLaunchDrillStatus === "ready") badges.push(badge("mock_provider_launch_drill_ready", "Mock Provider 启动演练已准备", "info"));
      if (obj(safe.sandboxProviderRollbackPlanSummary).status === "ready" || safe.sandboxProviderRollbackPlanStatus === "ready") badges.push(badge("sandbox_provider_rollback_plan_ready", "Sandbox Provider 回滚预案已准备", "info"));
      if (obj(safe.humanApprovalSimulationGateSummary).status || obj(safe.providerLaunchSimulationViewModelSummary).status) badges.push(badge("human_approval_simulation_boundary", "审批模拟不代表真实审批完成", "warning"));
      if (obj(safe.mockProviderLaunchDrillSummary).status || obj(safe.providerLaunchSimulationViewModelSummary).status) badges.push(badge("mock_provider_launch_boundary", "Mock 启动不启动真实 provider", "info"));
      if (obj(safe.sandboxProviderRollbackPlanSummary).status || obj(safe.providerLaunchSimulationViewModelSummary).status) badges.push(badge("sandbox_provider_rollback_boundary", "回滚预案不执行回滚", "warning"));
      if (safe.safeToProceedWithHumanControlledSandboxProviderPilot === true) badges.push(badge("human_controlled_sandbox_provider_pilot", "真实 sandbox provider pilot 仍需人工控制", "warning"));
      if (obj(safe.providerSandboxPilotControlRoomSummary).status === "ready" || safe.providerSandboxPilotControlStatus === "ready") badges.push(badge("provider_sandbox_pilot_control_room_ready", "Provider Sandbox Pilot 控制室已准备", "info"));
      if (obj(safe.mockProviderIncidentDrillSummary).status === "ready" || safe.mockProviderIncidentDrillStatus === "ready") badges.push(badge("mock_provider_incident_drill_ready", "Mock Provider 事故演练已准备", "info"));
      if (obj(safe.productionBlockerMatrixSummary).status === "ready" || safe.productionBlockerMatrixStatus === "ready") badges.push(badge("production_blocker_matrix_ready", "Production 阻断矩阵已准备", "info"));
      if (obj(safe.providerSandboxPilotControlRoomSummary).status || obj(safe.providerPilotControlViewModelSummary).status) badges.push(badge("provider_sandbox_pilot_control_room_boundary", "Pilot 控制室不启动真实 provider", "info"));
      if (obj(safe.mockProviderIncidentDrillSummary).status || obj(safe.providerPilotControlViewModelSummary).status) badges.push(badge("mock_provider_incident_drill_boundary", "事故演练不触发真实告警或回滚", "warning"));
      if (obj(safe.productionBlockerMatrixSummary).status || obj(safe.providerPilotControlViewModelSummary).status) badges.push(badge("production_blocker_matrix_boundary", "阻断矩阵不修改运行配置", "info"));
      if (safe.safeToProceedWithHumanControlledSandboxProviderPilotPlan === true) badges.push(badge("human_controlled_pilot_plan_human_review", "Human-controlled pilot 仍需人工审批", "warning"));
      if (obj(safe.humanControlledSandboxProviderPilotPlannerSummary).status === "ready" || safe.humanControlledSandboxProviderPilotPlannerStatus === "ready") badges.push(badge("human_controlled_pilot_planner_ready", "人工控制 Sandbox Provider Pilot 计划器已准备", "info"));
      if (obj(safe.providerKillSwitchDrillSummary).status === "ready" || safe.providerKillSwitchDrillStatus === "ready") badges.push(badge("provider_kill_switch_drill_ready", "Provider Kill Switch 演练已准备", "info"));
      if (obj(safe.complianceEvidencePackSummary).status === "ready" || safe.complianceEvidencePackStatus === "ready") badges.push(badge("compliance_evidence_pack_ready", "合规证据包已准备", "info"));
      if (obj(safe.providerGovernanceConsoleSummary).consoleStatus === "sandbox_ready" || safe.providerGovernanceConsoleStatus === "sandbox_ready") badges.push(badge("provider_governance_console_sandbox_ready", "Provider Governance Console 已达到 sandbox-ready", "info"));
      if (obj(safe.providerGovernanceConsoleSummary).consoleStatus === "ready_for_human_approval" || safe.providerGovernanceConsoleStatus === "ready_for_human_approval") badges.push(badge("provider_governance_console_human_approval", "Provider Governance Console 等待人工最终确认", "warning"));
      if (obj(safe.providerGovernanceConsoleSummary).consoleStatus === "needs_evidence" || safe.providerGovernanceConsoleStatus === "needs_evidence") badges.push(badge("provider_governance_console_needs_evidence", "Provider Governance Console 仍需补充证据", "warning"));
      if (obj(safe.providerOperatorReviewLoopSummary).status === "sandbox_ready" || safe.providerOperatorReviewLoopStatus === "sandbox_ready") badges.push(badge("provider_operator_review_loop_sandbox_ready", "运营复核循环允许继续 sandbox 复核", "info"));
      if (obj(safe.providerOperatorReviewLoopSummary).status === "blocked" || safe.providerOperatorReviewLoopStatus === "blocked") badges.push(badge("provider_operator_review_loop_blocked", "运营复核循环要求暂停", "blocked"));
      if (obj(safe.humanControlledSandboxProviderPilotPlannerSummary).status || obj(safe.providerPilotGovernanceViewModelSummary).status) badges.push(badge("pilot_planner_not_start_real_provider", "Pilot 计划不启动真实 provider", "info"));
      if (obj(safe.providerKillSwitchDrillSummary).status || obj(safe.providerPilotGovernanceViewModelSummary).status) badges.push(badge("kill_switch_not_disable_real_provider", "Kill Switch 演练不禁用真实 provider", "info"));
      if (obj(safe.complianceEvidencePackSummary).status || obj(safe.providerPilotGovernanceViewModelSummary).status) badges.push(badge("compliance_evidence_no_export", "合规证据包不写文件、不导出", "info"));
      if (safe.safeToProceedWithHumanAuditSandboxPilotReadinessReview === true || obj(safe.providerPilotGovernanceViewModelSummary).status === "ready") badges.push(badge("human_audit_review_required", "Human audit 仍需人工复核", "warning"));
      if (obj(safe.providerGovernanceAuditConsoleSummary).status === "ready" || safe.providerGovernanceAuditConsoleStatus === "ready") badges.push(badge("provider_governance_audit_console_ready", "Provider Governance 审计控制台已准备", "info"));
      if (obj(safe.humanPilotReadinessLedgerSummary).status === "ready" || safe.humanPilotReadinessLedgerStatus === "ready") badges.push(badge("human_pilot_readiness_ledger_ready", "Human Pilot 准备台账已准备", "info"));
      if (obj(safe.sandboxProviderReleaseFreezeGateSummary).status === "ready" || safe.sandboxProviderReleaseFreezeGateStatus === "ready") badges.push(badge("sandbox_provider_release_freeze_gate_ready", "Sandbox Provider Release Freeze Gate 已准备", "info"));
      if (obj(safe.providerGovernanceAuditConsoleSummary).status || obj(safe.providerGovernanceReleaseViewModelSummary).status) badges.push(badge("provider_governance_audit_console_boundary", "治理审计不写文件、不上传", "info"));
      if (obj(safe.humanPilotReadinessLedgerSummary).status || obj(safe.providerGovernanceReleaseViewModelSummary).status) badges.push(badge("human_pilot_ledger_boundary", "Human Pilot 台账不持久化审批结果", "info"));
      if (obj(safe.sandboxProviderReleaseFreezeGateSummary).status || obj(safe.providerGovernanceReleaseViewModelSummary).status) badges.push(badge("provider_release_freeze_boundary", "Release Freeze Gate 不改 git、不 push", "warning"));
      if ((obj(safe.providerGovernanceReleaseViewModelSummary).status && obj(safe.providerGovernanceReleaseViewModelSummary).status !== "blocked") || safe.safeToProceedWithManualGovernanceReleaseDecision === false) badges.push(badge("manual_governance_release_decision_required", "Manual governance release decision 仍需人工确认", "warning"));
      if (obj(safe.manualGovernanceReleaseDecisionRoomSummary).status === "ready" || safe.manualGovernanceReleaseDecisionRoomStatus === "ready") badges.push(badge("manual_governance_release_decision_room_ready", "Manual Governance Release 决策室已准备", "info"));
      if (obj(safe.sandboxPilotExceptionRegisterSummary).status === "ready" || safe.sandboxPilotExceptionRegisterStatus === "ready") badges.push(badge("sandbox_pilot_exception_register_ready", "Sandbox Pilot 例外登记簿已准备", "info"));
      if (obj(safe.providerReadinessSignOffPacketSummary).status === "ready" || safe.providerReadinessSignOffPacketStatus === "ready") badges.push(badge("provider_readiness_signoff_packet_ready", "Provider 准备签核包已准备", "info"));
      if (obj(safe.manualGovernanceReleaseDecisionRoomSummary).status || obj(safe.providerManualReleaseViewModelSummary).status) badges.push(badge("manual_provider_release_no_release_push", "人工发布决策不创建 release、不 push", "info"));
      if (obj(safe.sandboxPilotExceptionRegisterSummary).status || obj(safe.providerManualReleaseViewModelSummary).status) badges.push(badge("sandbox_exception_register_no_persistence", "例外登记不持久化审批结果", "info"));
      if (obj(safe.providerReadinessSignOffPacketSummary).status || obj(safe.providerManualReleaseViewModelSummary).status) badges.push(badge("provider_signoff_packet_no_export", "准备签核包不写文件、不导出", "info"));
      if ((obj(safe.providerManualReleaseViewModelSummary).status && obj(safe.providerManualReleaseViewModelSummary).status !== "blocked") || safe.safeToProceedWithManualProviderSignOffReview === false) badges.push(badge("manual_provider_signoff_required", "Manual provider sign-off 仍需人工复核", "warning"));
      if (obj(safe.readOnlySandboxActivationReadinessCenterSummary).status === "ready" || safe.readOnlySandboxActivationReadinessCenterStatus === "ready") badges.push(badge("sandbox_activation_readiness_center_ready", "只读 Sandbox 激活准备中心已准备", "info"));
      if (obj(safe.offlineMockSandboxSessionRunnerSummary).status === "ready" || safe.offlineMockSandboxSessionRunnerStatus === "ready") badges.push(badge("offline_mock_sandbox_session_runner_ready", "离线 Mock Sandbox 会话运行器已准备", "info"));
      if (obj(safe.manualProviderActivationHandoffPacketSummary).status === "ready" || safe.manualProviderActivationHandoffPacketStatus === "ready") badges.push(badge("manual_provider_activation_handoff_packet_ready", "人工 Provider 激活交接包已准备", "info"));
      if (obj(safe.readOnlySandboxActivationReadinessCenterSummary).status || obj(safe.providerSandboxActivationViewModelSummary).status) badges.push(badge("sandbox_activation_readiness_no_activation", "Sandbox 激活准备不执行激活", "info"));
      if (obj(safe.offlineMockSandboxSessionRunnerSummary).status || obj(safe.providerSandboxActivationViewModelSummary).status) badges.push(badge("offline_mock_sandbox_session_no_network_key", "离线 Mock 会话不联网、不读密钥", "info"));
      if (obj(safe.manualProviderActivationHandoffPacketSummary).status || obj(safe.providerSandboxActivationViewModelSummary).status) badges.push(badge("manual_activation_handoff_no_release_push", "人工激活交接包不创建 release、不 push", "info"));
      if ((obj(safe.providerSandboxActivationViewModelSummary).status && obj(safe.providerSandboxActivationViewModelSummary).status !== "blocked") || safe.safeToProceedWithManualSandboxActivationReview === false) badges.push(badge("manual_sandbox_activation_review_required", "Manual sandbox activation 仍需人工复核", "warning"));
      if (sandboxDeepLinkCandidateSummary.status === "ready") badges.push(badge("sandbox_deep_link_candidate_ready", "Sandbox 跳转候选已准备", "info"));
      if (sandboxDeepLinkCandidateSummary.status === "needs_review") badges.push(badge("sandbox_deep_link_candidate_review", "Sandbox 跳转候选仍需复核", "warning"));
      if (sandboxDeepLinkCandidateSummary.status === "blocked") badges.push(badge("sandbox_deep_link_candidate_blocked", "Sandbox 跳转候选已阻断", "blocked"));
      if (platformAvailabilitySummary.status === "available") badges.push(badge("platform_availability_ready", "平台候选可展示", "info"));
      if (platformAvailabilitySummary.status === "needs_review") badges.push(badge("platform_availability_review", "平台可用性仍需复核", "warning"));
      if (platformAvailabilitySummary.status === "blocked") badges.push(badge("platform_availability_blocked", "平台可用性已阻断", "blocked"));
      if (partnerLinkPolicySummary.status === "compliant") badges.push(badge("partner_link_policy_ready", "合作链接政策合规", "info"));
      if (partnerLinkPolicySummary.status === "needs_review") badges.push(badge("partner_link_policy_review", "合作链接政策仍需复核", "warning"));
      if (partnerLinkPolicySummary.status === "blocked") badges.push(badge("partner_link_policy_blocked", "合作链接政策已阻断", "blocked"));
      if (partnerLinkPolicySummary.status) badges.push(badge("partner_link_not_lowest", "合作链接不代表最低价", "warning"));
      if (platformAvailabilitySummary.status) badges.push(badge("platform_realtime_truth", "平台页面为实时价格准绳", "info"));
      if (sandboxDeepLinkCandidateSummary.status) badges.push(badge("sandbox_link_no_open", "Sandbox 跳转不打开真实平台", "info"));
      if (platformAvailabilitySummary.status) badges.push(badge("platform_no_endorsement", "平台可用不代表官方背书", "warning"));
      if (readOnlyProviderSandboxConnectorSummary.status === "ready") badges.push(badge("readonly_provider_connector_ready", "只读 Provider Connector 已准备", "info"));
      if (readOnlyProviderSandboxConnectorSummary.status === "needs_review") badges.push(badge("readonly_provider_connector_review", "只读 Provider Connector 仍需复核", "warning"));
      if (readOnlyProviderSandboxConnectorSummary.status === "blocked") badges.push(badge("readonly_provider_connector_blocked", "只读 Provider Connector 已阻断", "blocked"));
      if (fixtureReplayConsoleSummary.status === "ready") badges.push(badge("fixture_replay_ready", "Fixture 回放已准备", "info"));
      if (fixtureReplayConsoleSummary.status === "needs_review") badges.push(badge("fixture_replay_review", "Fixture 回放仍需复核", "warning"));
      if (fixtureReplayConsoleSummary.status === "blocked") badges.push(badge("fixture_replay_blocked", "Fixture 回放已阻断", "blocked"));
      if (normalizedPriceCandidateBoardSummary.status === "ready") badges.push(badge("normalized_price_candidate_board_ready", "归一化价格候选板已准备", "info"));
      if (normalizedPriceCandidateBoardSummary.status === "needs_review") badges.push(badge("normalized_price_candidate_board_review", "归一化价格候选板仍需复核", "warning"));
      if (normalizedPriceCandidateBoardSummary.status === "blocked") badges.push(badge("normalized_price_candidate_board_blocked", "归一化价格候选板已阻断", "blocked"));
      if (realProviderSandboxGateSummary.status === "ready") badges.push(badge("real_provider_sandbox_gate_ready", "真实只读 Provider Sandbox 闸门已准备", "info"));
      if (realProviderSandboxGateSummary.status === "needs_review") badges.push(badge("real_provider_sandbox_gate_review", "真实只读 Provider Sandbox 闸门仍需复核", "warning"));
      if (realProviderSandboxGateSummary.status === "blocked") badges.push(badge("real_provider_sandbox_gate_blocked", "真实只读 Provider Sandbox 闸门已阻断", "blocked"));
      if (providerRequestEnvelopeSummary.status === "ready") badges.push(badge("provider_request_envelope_ready", "Provider 请求封装已准备", "info"));
      if (providerRequestEnvelopeSummary.status === "needs_review") badges.push(badge("provider_request_envelope_review", "Provider 请求封装仍需复核", "warning"));
      if (providerRequestEnvelopeSummary.status === "blocked") badges.push(badge("provider_request_envelope_blocked", "Provider 请求封装已阻断", "blocked"));
      if (providerCallAuditLedgerSummary.status === "ready") badges.push(badge("provider_call_audit_ledger_ready", "Provider 调用审计台账已准备", "info"));
      if (providerCallAuditLedgerSummary.status === "needs_review") badges.push(badge("provider_call_audit_ledger_review", "Provider 调用审计台账仍需复核", "warning"));
      if (providerCallAuditLedgerSummary.status === "blocked") badges.push(badge("provider_call_audit_ledger_blocked", "Provider 调用审计台账已阻断", "blocked"));
      if (providerRequestEnvelopeSummary.status) badges.push(badge("provider_request_envelope_not_send", "请求封装不发送真实请求", "info"));
      if (providerCallAuditLedgerSummary.status) badges.push(badge("provider_call_audit_no_raw_response", "调用审计不保存 raw response", "info"));
      if (providerSandboxReadinessViewModelSummary.status) badges.push(badge("provider_sandbox_readiness_not_real_price", "Sandbox 准备不代表真实价格", "warning"));
      if (providerSandboxReadinessViewModelSummary.status) badges.push(badge("provider_sandbox_readiness_not_ordering", "Sandbox 准备不代表下单能力", "warning"));
      if (providerSandboxDryRunHarnessSummary.status === "ready") badges.push(badge("provider_sandbox_dry_run_ready", "Provider Sandbox 干跑框架已准备", "info"));
      if (providerSandboxDryRunHarnessSummary.status === "needs_review") badges.push(badge("provider_sandbox_dry_run_review", "Provider Sandbox 干跑框架仍需复核", "warning"));
      if (providerSandboxDryRunHarnessSummary.status === "blocked") badges.push(badge("provider_sandbox_dry_run_blocked", "Provider Sandbox 干跑框架已阻断", "blocked"));
      if (firstReadOnlyProviderAdapterShellSummary.status === "ready") badges.push(badge("provider_adapter_shell_ready", "第一个只读 Provider Adapter 外壳已准备", "info"));
      if (firstReadOnlyProviderAdapterShellSummary.status === "needs_review") badges.push(badge("provider_adapter_shell_review", "第一个只读 Provider Adapter 外壳仍需复核", "warning"));
      if (firstReadOnlyProviderAdapterShellSummary.status === "blocked") badges.push(badge("provider_adapter_shell_blocked", "第一个只读 Provider Adapter 外壳已阻断", "blocked"));
      if (providerSandboxSafetyKillSwitchSummary.status === "clear") badges.push(badge("provider_kill_switch_clear", "Provider Sandbox 安全熔断器未触发", "info"));
      if (providerSandboxSafetyKillSwitchSummary.status === "blocked") badges.push(badge("provider_kill_switch_blocked", "安全熔断器阻断真实 provider 风险", "blocked"));
      if (obj(safe.offlineSandboxTraceInspectorSummary).status === "ready" || safe.offlineSandboxTraceInspectorStatus === "ready") badges.push(badge("offline_sandbox_trace_inspector_ready", "离线 Sandbox Trace 检查器已准备", "info"));
      if (obj(safe.mockProviderResultNormalizerSummary).status === "ready" || safe.mockProviderResultNormalizerStatus === "ready") badges.push(badge("mock_provider_result_normalizer_ready", "Mock Provider 结果归一化器已准备", "info"));
      if (obj(safe.manualActivationDryRunChecklistSummary).status === "ready" || safe.manualActivationDryRunChecklistStatus === "ready") badges.push(badge("manual_activation_dry_run_checklist_ready", "人工激活 Dry-run 检查清单已准备", "info"));
      if (providerSandboxDryRunViewModelSummary.status === "ready") badges.push(badge("provider_dry_run_view_ready", "Provider Sandbox 离线 Dry-run", "info"));
      if (obj(safe.offlineSandboxTraceInspectorSummary).status || providerSandboxDryRunViewModelSummary.status) badges.push(badge("offline_trace_no_raw_trace", "离线 Trace 检查不保存 raw trace", "info"));
      if (obj(safe.mockProviderResultNormalizerSummary).status || providerSandboxDryRunViewModelSummary.status) badges.push(badge("mock_result_normalizer_no_real_response", "Mock 结果归一化不处理真实 provider response", "info"));
      if (obj(safe.manualActivationDryRunChecklistSummary).status || providerSandboxDryRunViewModelSummary.status) badges.push(badge("manual_activation_dry_run_no_activation", "激活 Dry-run 不激活 sandbox、不创建 release", "info"));
      if ((providerSandboxDryRunViewModelSummary.status && providerSandboxDryRunViewModelSummary.status !== "blocked") || safe.safeToProceedWithManualSandboxDryRunReview === false) badges.push(badge("manual_sandbox_dry_run_review_required", "Manual sandbox dry-run 仍需人工复核", "warning"));
      if (providerSandboxDryRunHarnessSummary.status || firstReadOnlyProviderAdapterShellSummary.status || providerSandboxSafetyKillSwitchSummary.status) badges.push(badge("provider_dry_run_no_request", "干跑不发送真实请求", "info"));
      if (firstReadOnlyProviderAdapterShellSummary.status) badges.push(badge("provider_adapter_no_endpoint", "Adapter 外壳不包含真实 endpoint", "info"));
      if (providerSandboxDryRunViewModelSummary.status) badges.push(badge("provider_dry_run_not_real_price", "干跑不代表真实价格或下单能力", "warning"));
      if (providerSandboxReadinessWorkbenchSummary.status === "ready" || safe.providerSandboxReadinessWorkbenchStatus === "ready") badges.push(badge("provider_sandbox_readiness_workbench_ready", "Provider Sandbox Readiness Workbench 已准备", "info"));
      if (offlineProviderScenarioLabSummary.status === "ready" || safe.offlineProviderScenarioLabStatus === "ready") badges.push(badge("offline_provider_scenario_lab_ready", "Offline Provider Scenario Lab 已准备", "info"));
      if (readOnlyProviderAdapterSdkSkeletonSummary.status === "ready" || safe.readOnlyProviderAdapterSdkSkeletonStatus === "ready") badges.push(badge("read_only_provider_adapter_sdk_skeleton_ready", "Read-Only Provider Adapter SDK Skeleton 已准备", "info"));
      if (manualActivationCommandCenterSummary.status === "ready" || safe.manualActivationCommandCenterStatus === "ready") badges.push(badge("manual_activation_command_center_ready", "Manual Activation Command Center 已准备", "info"));
      if (providerSandboxReadinessWorkbenchSummary.status || providerSandboxMilestoneViewModelSummary.status) badges.push(badge("readiness_workbench_no_activation", "Readiness Workbench 不激活 sandbox", "info"));
      if (offlineProviderScenarioLabSummary.status || providerSandboxMilestoneViewModelSummary.status) badges.push(badge("offline_scenario_lab_no_network_key", "Offline Scenario Lab 不联网、不读密钥", "info"));
      if (readOnlyProviderAdapterSdkSkeletonSummary.status || providerSandboxMilestoneViewModelSummary.status) badges.push(badge("adapter_sdk_skeleton_no_endpoint", "Adapter SDK Skeleton 不生成 endpoint、不导入真实 SDK", "info"));
      if (manualActivationCommandCenterSummary.status || providerSandboxMilestoneViewModelSummary.status) badges.push(badge("command_center_no_release_push", "Command Center 不创建 release、不 push", "info"));
      if ((providerSandboxMilestoneViewModelSummary.status && providerSandboxMilestoneViewModelSummary.status !== "blocked") || safe.safeToProceedWithHumanSandboxMilestoneReview === true) badges.push(badge("human_sandbox_milestone_review_required", "Human sandbox milestone review 仍需人工复核", "warning"));
      if (offlineProviderAdapterContractKitSummary.status === "ready" || safe.offlineProviderAdapterContractKitStatus === "ready") badges.push(badge("offline_provider_adapter_contract_kit_ready", "Offline Provider Adapter Contract Kit 已准备", "info"));
      if (mockSandboxQaMatrixSummary.status === "ready" || safe.mockSandboxQaMatrixStatus === "ready") badges.push(badge("mock_sandbox_qa_matrix_ready", "Mock Sandbox QA Matrix 已准备", "info"));
      if (humanActivationRunbookCenterSummary.status === "ready" || safe.humanActivationRunbookCenterStatus === "ready") badges.push(badge("human_activation_runbook_center_ready", "Human Activation Runbook Center 已准备", "info"));
      if (providerAdapterComplianceChecklistSummary.status === "ready" || safe.providerAdapterComplianceChecklistStatus === "ready") badges.push(badge("provider_adapter_compliance_checklist_ready", "Provider Adapter Compliance Checklist 已准备", "info"));
      if (offlineProviderAdapterContractKitSummary.status || providerSandboxReleaseCandidateViewModelSummary.status) badges.push(badge("adapter_contract_kit_no_real_sdk", "Adapter Contract Kit 不生成真实 SDK", "info"));
      if (mockSandboxQaMatrixSummary.status || providerSandboxReleaseCandidateViewModelSummary.status) badges.push(badge("mock_qa_matrix_no_real_provider", "Mock QA Matrix 不运行真实 provider", "info"));
      if (humanActivationRunbookCenterSummary.status || providerSandboxReleaseCandidateViewModelSummary.status) badges.push(badge("human_runbook_no_task_activation", "Human Runbook 不创建任务、不激活 sandbox", "info"));
      if (providerAdapterComplianceChecklistSummary.status || providerSandboxReleaseCandidateViewModelSummary.status) badges.push(badge("adapter_compliance_no_provider_client", "Adapter Compliance 不创建 provider client", "info"));
      if ((providerSandboxReleaseCandidateViewModelSummary.status && providerSandboxReleaseCandidateViewModelSummary.status !== "blocked") || safe.safeToProceedWithManualReleaseCandidateReview === true) badges.push(badge("manual_release_candidate_review_required", "Manual release candidate review 仍需人工复核", "warning"));
      if (offlineProviderCertificationCenterSummary.status === "ready" || safe.offlineProviderCertificationCenterStatus === "ready") badges.push(badge("offline_provider_certification_center_ready", "Offline Provider Certification Center 已准备", "info"));
      if (mockIntegrationRegressionLabSummary.status === "ready" || safe.mockIntegrationRegressionLabStatus === "ready") badges.push(badge("mock_integration_regression_lab_ready", "Mock Integration Regression Lab 已准备", "info"));
      if (humanApprovalEvidenceBinderSummary.status === "ready" || safe.humanApprovalEvidenceBinderStatus === "ready") badges.push(badge("human_approval_evidence_binder_ready", "Human Approval Evidence Binder 已准备", "info"));
      if (adapterBoundaryLockSummary.status === "ready" || safe.adapterBoundaryLockStatus === "ready") badges.push(badge("adapter_boundary_lock_ready", "Adapter Boundary Lock 已准备", "info"));
      if (offlineProviderCertificationCenterSummary.status || providerCertificationViewModelSummary.status) badges.push(badge("provider_certification_no_real_certification", "Certification Center 不生成真实认证文件", "info"));
      if (mockIntegrationRegressionLabSummary.status || providerCertificationViewModelSummary.status) badges.push(badge("provider_regression_no_real_provider", "Regression Lab 不运行真实 provider", "info"));
      if (humanApprovalEvidenceBinderSummary.status || providerCertificationViewModelSummary.status) badges.push(badge("provider_evidence_binder_no_file_upload", "Evidence Binder 不写文件、不上传", "info"));
      if (adapterBoundaryLockSummary.status || providerCertificationViewModelSummary.status) badges.push(badge("provider_boundary_lock_no_config_mutation", "Boundary Lock 不修改配置、不启用 provider", "info"));
      if ((providerCertificationViewModelSummary.status && providerCertificationViewModelSummary.status !== "blocked") || safe.safeToProceedWithHumanCertificationReview === true) badges.push(badge("human_certification_review_required", "Human certification review 仍需人工复核", "warning"));
      if (providerOfflineReleaseGateSummary.status === "ready" || safe.providerOfflineReleaseGateStatus === "ready") badges.push(badge("provider_offline_release_gate_ready", "Provider Offline Release Gate 已准备", "info"));
      if (providerCertificationFreezeLedgerSummary.status === "ready" || safe.providerCertificationFreezeLedgerStatus === "ready") badges.push(badge("provider_certification_freeze_ledger_ready", "Provider Certification Freeze Ledger 已准备", "info"));
      if (sandboxActivationReviewPacketSummary.status === "ready" || safe.sandboxActivationReviewPacketStatus === "ready") badges.push(badge("sandbox_activation_review_packet_ready", "Sandbox Activation Review Packet 已准备", "info"));
      if (adapterBoundaryDiffInspectorSummary.status === "ready" || safe.adapterBoundaryDiffInspectorStatus === "ready") badges.push(badge("adapter_boundary_diff_inspector_ready", "Adapter Boundary Diff Inspector 已准备", "info"));
      if (providerOfflineReleaseGateSummary.status || providerOfflineReleaseViewModelSummary.status) badges.push(badge("provider_offline_release_gate_no_release_push", "Offline Release Gate 不创建 release、不 push", "info"));
      if (providerCertificationFreezeLedgerSummary.status || providerOfflineReleaseViewModelSummary.status) badges.push(badge("provider_certification_freeze_ledger_no_persistence", "Certification Freeze Ledger 不持久化台账", "info"));
      if (sandboxActivationReviewPacketSummary.status || providerOfflineReleaseViewModelSummary.status) badges.push(badge("sandbox_activation_review_packet_no_activation", "Activation Review Packet 不激活 sandbox", "info"));
      if (adapterBoundaryDiffInspectorSummary.status || providerOfflineReleaseViewModelSummary.status) badges.push(badge("adapter_boundary_diff_inspector_no_config_mutation", "Boundary Diff Inspector 不修改配置、不启用 provider", "info"));
      if ((providerOfflineReleaseViewModelSummary.status && providerOfflineReleaseViewModelSummary.status !== "blocked") || safe.safeToProceedWithManualOfflineReleaseReview === true) badges.push(badge("manual_offline_release_review_required", "Manual offline release review 仍需人工复核", "warning"));
      if (offlineLaunchDecisionSimulatorSummary.status === "ready" || safe.offlineLaunchDecisionSimulatorStatus === "ready") badges.push(badge("offline_launch_decision_simulator_ready", "Offline Launch Decision Simulator 已准备", "info"));
      if (sandboxActivationReceiptLedgerSummary.status === "ready" || safe.sandboxActivationReceiptLedgerStatus === "ready") badges.push(badge("sandbox_activation_receipt_ledger_ready", "Sandbox Activation Receipt Ledger 已准备", "info"));
      if (adapterSecurityRegressionGuardSummary.status === "ready" || safe.adapterSecurityRegressionGuardStatus === "ready") badges.push(badge("adapter_security_regression_guard_ready", "Adapter Security Regression Guard 已准备", "info"));
      if (providerOfflineLaunchChecklistSummary.status === "ready" || safe.providerOfflineLaunchChecklistStatus === "ready") badges.push(badge("provider_offline_launch_checklist_ready", "Provider Offline Launch Checklist 已准备", "info"));
      if (offlineLaunchDecisionSimulatorSummary.status || providerOfflineLaunchViewModelSummary.status) badges.push(badge("offline_launch_decision_simulator_no_real_decision", "Launch Decision 不保存真实决策", "info"));
      if (sandboxActivationReceiptLedgerSummary.status || providerOfflineLaunchViewModelSummary.status) badges.push(badge("sandbox_activation_receipt_ledger_no_real_receipt", "Activation Receipt Ledger 不保存真实回执", "info"));
      if (adapterSecurityRegressionGuardSummary.status || providerOfflineLaunchViewModelSummary.status) badges.push(badge("adapter_security_regression_guard_no_config_mutation", "Security Guard 不修改配置、不启用 provider", "info"));
      if (providerOfflineLaunchChecklistSummary.status || providerOfflineLaunchViewModelSummary.status) badges.push(badge("provider_offline_launch_checklist_no_release_push", "Launch Checklist 不创建 release、不 push", "info"));
      if ((providerOfflineLaunchViewModelSummary.status && providerOfflineLaunchViewModelSummary.status !== "blocked") || safe.safeToProceedWithManualOfflineLaunchDecisionReview === true) badges.push(badge("manual_offline_launch_decision_review_required", "Manual offline launch decision 仍需人工复核", "warning"));
      if (providerAdapterRegistrySummary.status === "ready") badges.push(badge("provider_adapter_registry_ready", "Adapter 注册表已准备", "info"));
      if (providerAdapterRegistrySummary.status === "needs_review") badges.push(badge("provider_adapter_registry_review", "Adapter 注册表仍需复核", "warning"));
      if (providerAdapterRegistrySummary.status === "blocked") badges.push(badge("provider_adapter_registry_blocked", "Adapter 注册表已阻断", "blocked"));
      if (dryRunProviderResponseNormalizerSummary.status === "ready") badges.push(badge("dry_run_response_normalizer_ready", "Dry-run 响应归一化已准备", "info"));
      if (dryRunProviderResponseNormalizerSummary.status === "needs_review") badges.push(badge("dry_run_response_normalizer_review", "Dry-run 响应归一化仍需复核", "warning"));
      if (dryRunProviderResponseNormalizerSummary.status === "blocked") badges.push(badge("dry_run_response_normalizer_blocked", "Dry-run 响应归一化已阻断", "blocked"));
      if (sandboxProviderRunbookSummary.status === "ready") badges.push(badge("sandbox_provider_runbook_ready", "Sandbox Provider 接入手册已准备", "info"));
      if (sandboxProviderRunbookSummary.status === "needs_review") badges.push(badge("sandbox_provider_runbook_review", "Sandbox Provider 接入手册仍需复核", "warning"));
      if (sandboxProviderRunbookSummary.status === "blocked") badges.push(badge("sandbox_provider_runbook_blocked", "Sandbox Provider 接入手册已阻断", "blocked"));
      if (providerAdapterRegistrySummary.status) badges.push(badge("provider_adapter_registry_read_only", "只允许只读 adapter 注册", "info"));
      if (dryRunProviderResponseNormalizerSummary.status) badges.push(badge("dry_run_response_normalizer_no_raw", "不接收 raw provider response", "info"));
      if (sandboxProviderRunbookSummary.status) badges.push(badge("sandbox_provider_runbook_no_execution", "接入手册不执行真实接入", "warning"));
      if (providerAdapterRegistryViewModelSummary.status || providerAdapterRegistrySummary.status) badges.push(badge("provider_adapter_registry_not_connected", "Adapter 注册不代表真实 provider 接通", "warning"));
      if (readOnlyProviderSandboxConnectorSummary.status || fixtureReplayConsoleSummary.status || normalizedPriceCandidateBoardSummary.status) badges.push(badge("fixture_replay_not_real_provider", "Replay 不代表真实 provider 调用", "warning"));
      if (readOnlyProviderSandboxConnectorSummary.status || legalProviderFixtureSummary.status || providerCredentialSafetySummary.status) badges.push(badge("connector_no_prod_key", "Connector 不读取生产密钥", "info"));
      if (readOnlyProviderSandboxIntegrationGateSummary.status === "ready") badges.push(badge("provider_sandbox_integration_gate_ready", "只读 Provider Sandbox 接入闸门已准备", "info"));
      if (readOnlyProviderSandboxIntegrationGateSummary.status === "needs_review") badges.push(badge("provider_sandbox_integration_gate_review", "只读 Provider Sandbox 接入闸门仍需复核", "warning"));
      if (readOnlyProviderSandboxIntegrationGateSummary.status === "blocked") badges.push(badge("provider_sandbox_integration_gate_blocked", "只读 Provider Sandbox 接入闸门已阻断", "blocked"));
      if (sandboxPriceCandidateSessionSummary.status === "ready") badges.push(badge("sandbox_price_candidate_session_ready", "Sandbox 价格候选会话已准备", "info"));
      if (sandboxPriceCandidateSessionSummary.status === "needs_review") badges.push(badge("sandbox_price_candidate_session_review", "Sandbox 价格候选会话仍需复核", "warning"));
      if (sandboxPriceCandidateSessionSummary.status === "blocked") badges.push(badge("sandbox_price_candidate_session_blocked", "Sandbox 价格候选会话已阻断", "blocked"));
      if (sandboxPriceCandidateResultBoardSummary.status === "ready") badges.push(badge("sandbox_price_candidate_result_ready", "Sandbox 价格候选结果已准备", "info"));
      if (sandboxPriceCandidateResultBoardSummary.status === "needs_review") badges.push(badge("sandbox_price_candidate_result_review", "Sandbox 价格候选结果仍需复核", "warning"));
      if (sandboxPriceCandidateResultBoardSummary.status === "blocked") badges.push(badge("sandbox_price_candidate_result_blocked", "Sandbox 价格候选结果已阻断", "blocked"));
      if (sandboxPriceCandidateResultBoardSummary.status || sandboxPriceCandidateSessionSummary.status) badges.push(badge("sandbox_result_not_real_price", "Sandbox 结果不代表真实价格", "warning"));
      if (sandboxPriceCandidateResultBoardSummary.status || sandboxPriceCandidateSessionSummary.status) badges.push(badge("sandbox_result_not_lowest", "候选结果不代表全网最低", "warning"));
      if (sandboxPriceCandidateResultBoardSummary.status || sandboxPriceCandidateSessionSummary.status) badges.push(badge("sandbox_result_not_ordering", "候选结果不代表下单能力", "warning"));
      if (sandboxPriceCandidateResultBoardSummary.status || readOnlyProviderSandboxIntegrationGateSummary.status) badges.push(badge("sandbox_result_platform_truth", "价格以未来平台实时页面为准", "info"));
      if (sandboxSessionReplayCenterSummary.status === "ready") badges.push(badge("sandbox_session_replay_ready", "Sandbox 会话回放已准备", "info"));
      if (providerEvidenceTraceSummary.status === "ready") badges.push(badge("provider_evidence_trace_ready", "Provider 证据链已准备", "info"));
      if (candidateConfidenceExplainerSummary.status === "ready") badges.push(badge("candidate_confidence_ready", "候选价可信度解释已准备", "info"));
      if (sandboxSessionReplayCenterSummary.status || sandboxReplayViewModelSummary.status) badges.push(badge("sandbox_replay_not_real_query", "回放不代表真实平台查询", "warning"));
      if (providerEvidenceTraceSummary.status) badges.push(badge("provider_trace_no_raw_response", "证据链不包含 raw response", "info"));
      if (candidateConfidenceExplainerSummary.status) badges.push(badge("confidence_not_lowest_guarantee", "可信度不代表最低价保证", "warning"));
      if (candidateConfidenceExplainerSummary.status) badges.push(badge("confidence_not_ordering", "可信度不代表可订或可下单", "warning"));
      if (sandboxCandidateComparisonWorkbenchSummary.status === "ready") badges.push(badge("sandbox_candidate_comparison_ready", "Sandbox 候选对比已准备", "info"));
      if (providerEvidenceComparisonMatrixSummary.status === "ready") badges.push(badge("provider_evidence_matrix_ready", "Provider 证据矩阵已准备", "info"));
      if (readOnlyHandoffReadinessDrillSummary.status === "ready") badges.push(badge("handoff_readiness_drill_ready", "只读交接演练已准备", "info"));
      if (sandboxCandidateComparisonWorkbenchSummary.status) badges.push(badge("candidate_recommendation_not_lowest", "候选推荐不代表最低价保证", "warning"));
      if (readOnlyHandoffReadinessDrillSummary.status) badges.push(badge("handoff_drill_no_open", "交接演练不打开平台", "info"));
      if (readOnlyHandoffReadinessDrillSummary.status) badges.push(badge("handoff_params_no_identity_payment", "参数预览不包含身份或支付信息", "info"));
      if (sandboxDecisionReviewViewModelSummary.status) badges.push(badge("decision_review_not_ordering", "决策复核不代表下单能力", "warning"));
      if (readOnlyPlatformHandoffSimulatorSummary.status === "ready") badges.push(badge("handoff_simulator_ready", "只读平台交接模拟已准备", "info"));
      if (redactedSearchParameterPackSummary.status === "ready") badges.push(badge("redacted_parameter_pack_ready", "脱敏搜索参数包已准备", "info"));
      if (userConfirmationChecklistSummary.status === "ready") badges.push(badge("user_confirmation_checklist_ready", "用户确认清单已准备", "info"));
      if (redactedSearchParameterPackSummary.status) badges.push(badge("redacted_parameter_pack_no_identity_payment", "搜索参数包不包含身份或支付信息", "info"));
      if (userConfirmationChecklistSummary.status) badges.push(badge("user_confirms_realtime_price", "用户必须在平台自行确认实时价格", "warning"));
      if (platformHandoffSimulationViewModelSummary.status || readOnlyPlatformHandoffSimulatorSummary.status) badges.push(badge("handoff_no_login_payment_order_ticket", "Weishan 不替用户登录、付款、下单或出票", "warning"));
      if (readOnlyPlatformHandoffSimulatorSummary.status || platformHandoffSimulationViewModelSummary.status) badges.push(badge("handoff_simulator_no_open", "交接模拟不打开平台", "info"));
      if (safe.readOnlyHandoffPacketPreviewSummary && safe.readOnlyHandoffPacketPreviewSummary.status === "ready") badges.push(badge("handoff_packet_preview_ready", "只读交接包预览已准备", "info"));
      if (safe.platformPreflightSafetyGateSummary && safe.platformPreflightSafetyGateSummary.status === "clear") badges.push(badge("platform_preflight_gate_clear", "平台跳转前安全预检未触发阻断", "info"));
      if (safe.userActionBoundaryReceiptSummary && safe.userActionBoundaryReceiptSummary.status === "ready") badges.push(badge("user_action_boundary_receipt_ready", "用户行动边界回执已准备", "info"));
      if (safe.handoffPacketViewModelSummary && safe.handoffPacketViewModelSummary.status) badges.push(badge("handoff_packet_no_export", "交接包不导出、不下载、不上传", "warning"));
      if (safe.platformPreflightSafetyGateSummary && safe.platformPreflightSafetyGateSummary.status) badges.push(badge("preflight_no_open", "安全预检不打开平台", "info"));
      if (safe.userActionBoundaryReceiptSummary && safe.userActionBoundaryReceiptSummary.status) badges.push(badge("boundary_receipt_not_order", "回执不是订单、合同或付款授权", "warning"));
      if (safe.handoffPacketViewModelSummary && safe.handoffPacketViewModelSummary.status) badges.push(badge("user_final_confirmation_required", "用户必须在平台自行完成最终确认", "warning"));
      if (safe.manualPlatformReviewCockpitSummary && safe.manualPlatformReviewCockpitSummary.status === "ready") badges.push(badge("manual_platform_review_cockpit_ready", "手动平台复核驾驶舱已准备", "info"));
      if (safe.handoffAcceptanceWalkthroughSummary && safe.handoffAcceptanceWalkthroughSummary.status === "ready") badges.push(badge("handoff_acceptance_walkthrough_ready", "交接包接受演练已准备", "info"));
      if (safe.platformRealityCheckBoardSummary && safe.platformRealityCheckBoardSummary.status === "ready") badges.push(badge("platform_reality_check_ready", "平台真实页面复核清单已准备", "info"));
      if (safe.manualPlatformReviewViewModelSummary && safe.manualPlatformReviewViewModelSummary.status) badges.push(badge("handoff_acceptance_no_persistence", "接受演练不保存用户确认", "info"));
      if (safe.manualPlatformReviewViewModelSummary && safe.manualPlatformReviewViewModelSummary.status) badges.push(badge("platform_page_final_truth", "平台页面才是最终依据", "warning"));
      if (safe.manualPlatformReviewViewModelSummary && safe.manualPlatformReviewViewModelSummary.status) badges.push(badge("manual_review_not_ordering", "手动复核不代表下单能力", "warning"));
      if (safe.safeToProceedWithManualPlatformUserEducation === true) badges.push(badge("manual_platform_user_education_ready", "手动平台复核教育已准备", "info"));
      if (normalizedPriceCandidateBoardSummary.status || pricePipelineOrchestratorSummary.status) badges.push(badge("normalized_candidate_not_real_price", "归一化候选不代表真实价格", "warning"));
      if (normalizedPriceCandidateBoardSummary.status || readOnlyCandidateJourneySummary.status) badges.push(badge("normalized_candidate_not_ordering", "价格候选板不代表下单能力", "warning"));
      if (sandboxHandoffViewModelSummary.status === "ready") badges.push(badge("sandbox_handoff_ready", "Sandbox 跳转候选与平台可用性已准备", "info"));
      if (legalProviderFixtureSummary.status === "ready") badges.push(badge("legal_provider_fixture_ready", "Provider fixture 已准备", "info"));
      if (legalProviderFixtureSummary.status === "needs_review") badges.push(badge("legal_provider_fixture_review", "Provider fixture 仍需复核", "warning"));
      if (legalProviderFixtureSummary.status === "blocked") badges.push(badge("legal_provider_fixture_blocked", "Provider fixture 已阻断", "blocked"));
      if (providerCredentialSafetySummary.status === "ready") badges.push(badge("provider_credential_safety_ready", "Provider 凭据边界安全", "info"));
      if (providerCredentialSafetySummary.status === "needs_review") badges.push(badge("provider_credential_safety_review", "Provider 凭据边界仍需复核", "warning"));
      if (providerCredentialSafetySummary.status === "blocked") badges.push(badge("provider_credential_safety_blocked", "Provider 凭据边界已阻断", "blocked"));
      if (sandboxPriceFeedSummary.status === "ready") badges.push(badge("sandbox_price_feed_ready", "Sandbox 价格 Feed 已准备", "info"));
      if (sandboxPriceFeedSummary.status === "needs_review") badges.push(badge("sandbox_price_feed_review", "Sandbox 价格 Feed 仍需复核", "warning"));
      if (sandboxPriceFeedSummary.status === "blocked") badges.push(badge("sandbox_price_feed_blocked", "Sandbox 价格 Feed 已阻断", "blocked"));
      if (sandboxProviderResponseContractSummary.status === "ready") badges.push(badge("sandbox_provider_response_contract_ready", "Provider 响应合同已准备", "info"));
      if (sandboxProviderResponseContractSummary.status === "needs_review") badges.push(badge("sandbox_provider_response_contract_review", "Provider 响应合同仍需复核", "warning"));
      if (sandboxProviderResponseContractSummary.status === "blocked") badges.push(badge("sandbox_provider_response_contract_blocked", "Provider 响应合同已阻断", "blocked"));
      if (pricePipelineOrchestratorSummary.status === "ready") badges.push(badge("price_pipeline_ready", "只读价格流水线已准备", "info"));
      if (pricePipelineOrchestratorSummary.status === "needs_review") badges.push(badge("price_pipeline_review", "只读价格流水线仍需复核", "warning"));
      if (pricePipelineOrchestratorSummary.status === "blocked") badges.push(badge("price_pipeline_blocked", "只读价格流水线已阻断", "blocked"));
      if (readOnlyCandidateJourneySummary.status === "ready") badges.push(badge("candidate_journey_ready", "全球购只读候选旅程已准备", "info"));
      if (readOnlyCandidateJourneySummary.status === "needs_review") badges.push(badge("candidate_journey_review", "全球购只读候选旅程仍需复核", "warning"));
      if (readOnlyCandidateJourneySummary.status === "blocked") badges.push(badge("candidate_journey_blocked", "全球购只读候选旅程已阻断", "blocked"));
      if (providerCredentialSafetySummary.status || sandboxPriceFeedSummary.status) badges.push(badge("provider_no_prod_key", "不读取生产密钥", "info"));
      if (legalProviderFixtureSummary.status || providerCredentialSafetySummary.status || sandboxPriceFeedSummary.status) badges.push(badge("provider_no_raw_response", "不保存 raw provider response", "info"));
      if (sandboxPriceFeedSummary.status) badges.push(badge("sandbox_feed_normalization_ready", "Fixture feed 可进入价格归一化", "info"));
      if (providerFixtureViewModelSummary.status || legalProviderFixtureSummary.status) badges.push(badge("provider_fixture_not_real_price", "Provider fixture 不代表真实价格", "warning"));
      if (sandboxProviderResponseContractSummary.status || pricePipelineOrchestratorSummary.status) badges.push(badge("provider_response_not_persisted", "Raw provider response 不持久化", "info"));
      if (pricePipelineOrchestratorSummary.status || readOnlyCandidateJourneySummary.status) badges.push(badge("fixture_enters_candidate_journey", "Fixture 数据进入候选旅程", "info"));
      if (pricePipelineOrchestratorSummary.status) badges.push(badge("price_pipeline_not_real_price", "价格流水线不代表真实价格", "warning"));
      if (readOnlyCandidateJourneySummary.status) badges.push(badge("candidate_journey_not_ordering", "候选旅程不代表下单能力", "warning"));
      if (safe.safeToProceedWithPartnerFixtureAdapter === true || sandboxHandoffViewModelSummary.safeToProceedWithPartnerFixtureAdapter === true) badges.push(badge("partner_fixture_adapter_ready", "合作/联盟链接可继续只读接入", "info"));
      if (safe.safeToProceedWithSandboxCandidateUserPreview === true) badges.push(badge("sandbox_candidate_user_preview_ready", "可继续只读 Sandbox 候选展示", "info"));
      if (cohortProgress.status === "ready" || safe.cohortProgressStatus === "ready") badges.push(badge("cohort_progress_ready", "测试批次进度正常", "info"));
      if (cohortProgress.status === "needs_review" || safe.cohortProgressStatus === "needs_review") badges.push(badge("cohort_progress_in_progress", "测试批次仍在进行", "warning"));
      if (cohortProgress.status === "needs_more_testers" || safe.cohortProgressStatus === "needs_more_testers") badges.push(badge("cohort_progress_needs_more", "仍需更多测试者", "warning"));
      if (trialMilestone.status === "ready" || safe.trialMilestoneStatus === "ready") badges.push(badge("trial_milestone_ready", "下一批测试已准备", "info"));
      if (trialMilestone.status === "needs_review" || safe.trialMilestoneStatus === "needs_review") badges.push(badge("trial_milestone_review", "测试批次仍在进行", "warning"));
      if (trialMilestone.status === "blocked" || safe.trialMilestoneStatus === "blocked") badges.push(badge("trial_milestone_blocked", "测试批次已阻断", "blocked"));
      const rolloutControl = obj(safe.rolloutControlSummary);
      const cohortHealthDashboard = obj(safe.cohortHealthSummary);
      if (rolloutControl.status === "ready" || safe.rolloutDecisionStatus === "ready") badges.push(badge("rollout_control_ready", "发布控制正常", "info"));
      if (obj(rolloutControl.decision).decisionId === "advance_next_cohort") badges.push(badge("rollout_next_cohort_ready", "可以进入下一批只读测试", "info"));
      if (rolloutControl.status === "continue_current_batch" || safe.rolloutDecisionStatus === "continue_current_batch") badges.push(badge("rollout_continue_current", "继续当前小范围试点", "warning"));
      if (rolloutControl.status === "pause_expansion" || safe.rolloutDecisionStatus === "pause_expansion") badges.push(badge("rollout_pause_expansion", "暂停扩大测试", "warning"));
      if (rolloutControl.status === "blocked") badges.push(badge("rollout_blocked", "发布控制已阻断", "blocked"));
      if (cohortHealthDashboard.status === "healthy" || safe.cohortHealthStatus === "healthy") badges.push(badge("cohort_health_healthy", "批次健康", "info"));
      if (cohortHealthDashboard.status === "needs_review" || safe.cohortHealthStatus === "needs_review") badges.push(badge("cohort_health_review", "批次需要复核", "warning"));
      if (cohortHealthDashboard.status === "blocked") badges.push(badge("cohort_health_blocked", "批次已阻断", "blocked"));
      const pilotOpsSummary = safe.pilotOpsSummary || safe.readOnlyPilotOpsSummary || {};
      const nextCohortDecision = safe.nextCohortDecisionSummary || safe.nextCohortDecisionBoard || {};
      if (pilotOpsSummary.status === "healthy" || safe.pilotOpsStatus === "healthy") badges.push(badge("pilot_ops_healthy", "试点运行健康", "info"));
      if (pilotOpsSummary.status === "continue_current_batch" || safe.pilotOpsStatus === "continue_current_batch") badges.push(badge("pilot_ops_continue_current", "继续当前批次", "warning"));
      if (pilotOpsSummary.status === "pause_expansion" || safe.pilotOpsStatus === "pause_expansion") badges.push(badge("pilot_ops_pause_expansion", "暂停扩大测试", "warning"));
      if (pilotOpsSummary.status === "needs_review" || safe.pilotOpsStatus === "needs_review") badges.push(badge("pilot_ops_needs_review", "运营需要复核", "warning"));
      if (pilotOpsSummary.status === "blocked" || safe.pilotOpsStatus === "blocked") badges.push(badge("pilot_ops_blocked", "试点运营已阻断", "blocked"));
      if (obj(nextCohortDecision.decision).decisionId === "advance_next_cohort" || nextCohortDecision.status === "advance") badges.push(badge("next_cohort_advance", "下一批可推进", "info"));
      if (nextCohortDecision.status === "continue_current" || safe.nextCohortDecisionStatus === "continue_current") badges.push(badge("next_cohort_continue", "继续当前批次", "warning"));
      if (nextCohortDecision.status === "pause" || safe.nextCohortDecisionStatus === "pause") badges.push(badge("next_cohort_pause", "暂停扩大测试", "warning"));
      if (nextCohortDecision.status === "needs_review" || safe.nextCohortDecisionStatus === "needs_review") badges.push(badge("next_cohort_needs_review", "运营需要复核", "warning"));
      if (nextCohortDecision.status === "blocked" || safe.nextCohortDecisionStatus === "blocked") badges.push(badge("next_cohort_blocked", "试点运营已阻断", "blocked"));
      if (beta.status === "blocked" || guided.status === "blocked" || guided.status === "failed_safe") badges.push(badge("beta_acceptance_blocked", "Beta 验收被阻断", "blocked"));
      if (copyStatus === "pass" || releaseReadiness.copyValidationStatus === "pass") badges.push(badge("safety_copy_unified", "安全文案已统一", "info"));
      badges.push(badge("not_exportable", "不可导出", "warning"));
      return clone({ builderName:BUILDER_NAME, appVersion:FLIGHT_WORKFLOW_RISK_BADGE_BUILDER_VERSION, status:health.overall === "blocked" ? "blocked" : "ready", badges:badges, summaryLabel:summarizeFlightWorkflowRiskBadges(badges).summaryLabel, safety:safety(), bookingUrl:null, redacted:true });
    } catch (error) {
      return clone({ builderName:BUILDER_NAME, appVersion:FLIGHT_WORKFLOW_RISK_BADGE_BUILDER_VERSION, status:"failed_safe", badges:[badge("read_only_safe", "只读安全", "info"), badge("not_exportable", "不可导出", "warning")], summaryLabel:"只读安全 / 不可导出", safety:safety(), bookingUrl:null, redacted:true });
    }
  }
  function summarizeFlightWorkflowRiskBadges(badges) {
    const list = Array.isArray(badges) ? badges : [];
    return clone({ builderName:BUILDER_NAME, appVersion:FLIGHT_WORKFLOW_RISK_BADGE_BUILDER_VERSION, badgeCount:list.length, summaryLabel:list.map(function (item) { return safeText(item && item.label || ""); }).filter(Boolean).join(" / ") || "只读安全", safety:safety(), bookingUrl:null, redacted:true });
  }
  function buildFlightWorkflowRiskBadgeBuilderAuditDraft(input) {
    const model = buildFlightWorkflowRiskBadges(input || {});
    return clone({ eventType:"FLIGHT_WORKFLOW_RISK_BADGE_BUILDER_AUDIT_DRAFT", builderName:BUILDER_NAME, appVersion:FLIGHT_WORKFLOW_RISK_BADGE_BUILDER_VERSION, status:model.status, badgeCount:model.badges.length, summaryLabel:model.summaryLabel, bookingUrl:null, payment:false, order:false, ticketing:false, identityUpload:false, secretStored:false, redacted:true });
  }
  window.WeishanFlightWorkflowRiskBadgeBuilder = { FLIGHT_WORKFLOW_RISK_BADGE_BUILDER_VERSION, BUILDER_NAME, buildFlightWorkflowRiskBadges, summarizeFlightWorkflowRiskBadges, buildFlightWorkflowRiskBadgeBuilderAuditDraft };
})();
