;(function () {
  "use strict";

  const FLIGHT_WORKFLOW_BETA_COHORT_VIEW_MODEL_VERSION = "4.2.0";
  const VIEW_MODEL_NAME = "flight_workflow_beta_cohort_view_model_v1";
  const SENSITIVE_RE = /https?:\/\/\S+|(?:token|apiKey|key|secret|password|credential|cardNumber)\s*[:=]?\s*\S+|身份证|护照|银行卡|passport|raw feedback|rawUserText/ig;
  function clone(value) { return value && typeof value === "object" ? JSON.parse(JSON.stringify(value)) : value; }
  function text(value) { return String(value == null ? "" : value).trim(); }
  function safeText(value) { return text(value).replace(SENSITIVE_RE, "redacted"); }
  function toArray(value) { return Array.isArray(value) ? value.slice() : []; }
  function safety() { return { bookingUrl:null, checkoutUrl:null, paymentUrl:null, orderUrl:null, payment:false, order:false, ticketing:false, identityUpload:false, credentialInput:false, rawResponseStored:false, rawUserTextStored:false, secretStored:false, fileWrite:false, download:false, redacted:true }; }
  function boardOf(input) { const safe = input && typeof input === "object" ? input : {}; if (safe.betaCohortSummary) return safe.betaCohortSummary; const api = window.WeishanFlightWorkflowBetaCohortReviewBoard || {}; return typeof api.buildFlightWorkflowBetaCohortReviewBoard === "function" ? api.buildFlightWorkflowBetaCohortReviewBoard(safe) : { status:"needs_more_feedback", cohortHealth:{ sessionCount:0, usableFeedbackCount:0, safeToExpandBeta:false }, rows:[], findings:[], userFacingSummary:{ resultLabel:"仍需更多反馈", redacted:true }, redacted:true }; }
  function radarOf(input) { const safe = input && typeof input === "object" ? input : {}; if (safe.feedbackTrendSummary) return safe.feedbackTrendSummary; const api = window.WeishanFlightWorkflowFeedbackTrendRadar || {}; return typeof api.buildFlightWorkflowFeedbackTrendRadar === "function" ? api.buildFlightWorkflowFeedbackTrendRadar(safe) : { status:"insufficient_data", trends:{ overallTrend:"unknown" }, signals:[], recommendation:{ label:"仍需更多反馈", redacted:true }, redacted:true }; }
  function card(cardId, label, value) { return { cardId:cardId, label:label, value:safeText(value), redacted:true }; }
  function buildFlightWorkflowBetaCohortCards(input) { const board = boardOf(input || {}); const radar = radarOf(input || {}); const h = board.cohortHealth || {}; return clone([ card("sessions", "验收会话", String(h.sessionCount || 0)), card("feedback", "可用反馈", String(h.usableFeedbackCount || 0)), card("trend", "反馈趋势", radar.trends && radar.trends.overallTrend || "unknown"), card("recommendation", "下一步建议", radar.recommendation && radar.recommendation.label || board.userFacingSummary && board.userFacingSummary.resultLabel || "仍需更多反馈") ]); }
  function buildFlightWorkflowBetaCohortRows(input) { const board = boardOf(input || {}); return clone(toArray(board.rows).map(function (item) { return { rowId:safeText(item.rowId || "row"), label:safeText(item.label || ""), value:safeText(item.value || ""), status:safeText(item.status || "warning"), redacted:true }; })); }
  function buildFlightWorkflowFeedbackTrendRows(input) { const radar = radarOf(input || {}); return clone(toArray(radar.signals).map(function (item) { return { rowId:safeText(item.signalId || "signal"), label:safeText(item.label || ""), value:safeText(item.value || ""), status:safeText(item.status || "warning"), redacted:true }; })); }
  function buildFlightWorkflowBetaCohortViewModel(input) { const board = boardOf(input || {}); const radar = radarOf(input || {}); return clone({ viewModelName:VIEW_MODEL_NAME, appVersion:FLIGHT_WORKFLOW_BETA_COHORT_VIEW_MODEL_VERSION, status:board.status === "ready" && radar.status === "ready" ? "ready" : (board.status === "blocked" || radar.status === "blocked" ? "blocked" : "needs_review"), title:"Beta 反馈复核板", cards:buildFlightWorkflowBetaCohortCards({ betaCohortSummary:board, feedbackTrendSummary:radar }), rows:buildFlightWorkflowBetaCohortRows({ betaCohortSummary:board }), trendRows:buildFlightWorkflowFeedbackTrendRows({ feedbackTrendSummary:radar }), findings:toArray(board.findings).map(function (item) { return { findingId:safeText(item.findingId || "finding"), severity:safeText(item.severity || "warning"), title:safeText(item.title || ""), message:safeText(item.message || ""), redacted:true }; }), caveat:"Beta 反馈只用于改进只读候选证据流程，不代表真实票价、库存或可出票。", safety:safety(), bookingUrl:null, checkoutUrl:null, paymentUrl:null, orderUrl:null, rawUserTextStored:false, rawResponseStored:false, secretStored:false, fileWrite:false, download:false, redacted:true }); }
  function buildFlightWorkflowBetaCohortViewModelAuditDraft(input) { const vm = buildFlightWorkflowBetaCohortViewModel(input || {}); return clone({ eventType:"FLIGHT_WORKFLOW_BETA_COHORT_VIEW_MODEL_AUDIT_DRAFT", viewModelName:VIEW_MODEL_NAME, appVersion:FLIGHT_WORKFLOW_BETA_COHORT_VIEW_MODEL_VERSION, status:vm.status, cardCount:vm.cards.length, rowCount:vm.rows.length, trendRowCount:vm.trendRows.length, rawUserTextStored:false, secretStored:false, bookingUrl:null, paymentUrl:null, orderUrl:null, fileWrite:false, download:false, redacted:true }); }
  window.WeishanFlightWorkflowBetaCohortViewModel = { FLIGHT_WORKFLOW_BETA_COHORT_VIEW_MODEL_VERSION, VIEW_MODEL_NAME, buildFlightWorkflowBetaCohortViewModel, buildFlightWorkflowBetaCohortCards, buildFlightWorkflowBetaCohortRows, buildFlightWorkflowFeedbackTrendRows, buildFlightWorkflowBetaCohortViewModelAuditDraft };
})();
