;(function () {
  "use strict";
  const FLIGHT_WORKFLOW_OPERATOR_CONSOLE_VIEW_MODEL_VERSION = "2.4.1";
  const VIEW_MODEL_NAME = "flight_workflow_operator_console_view_model_v1";
  const FORBIDDEN_TEXT_RE = /https?:\/\/\S+|token|apiKey|secret|password|身份证|护照|银行卡|credential|passport|cardNumber/ig;
  function clone(value) { return value && typeof value === "object" ? JSON.parse(JSON.stringify(value)) : value; }
  function text(value) { return String(value == null ? "" : value).trim(); }
  function safeText(value) { return text(value).replace(FORBIDDEN_TEXT_RE, "redacted"); }
  function toArray(value) { return Array.isArray(value) ? value.slice() : []; }
  function statusValue(status, ready, warning) { if (status === "blocked" || status === "fail") return "已阻断"; if (status === "warning" || warning) return "需复核"; return ready || status === "ready" || status === "pass" ? "正常" : "需复核"; }
  function consoleOf(input) { const safe = input && typeof input === "object" ? input : {}; if (safe.operatorConsoleSummary) return safe.operatorConsoleSummary; const api = window.WeishanFlightWorkflowOperatorConsole || {}; return typeof api.buildFlightWorkflowOperatorConsole === "function" ? api.buildFlightWorkflowOperatorConsole(safe) : safe; }
  function buildOperatorConsoleStatusCards(input) { const c = consoleOf(input); const readiness = c.readiness || {}; const sentinel = c.safetyRegressionSummary || input && input.safetyRegressionSummary || {}; return clone([{ cardId:"workflow", label:"工作流", value:statusValue(c.status, readiness.workflowReady, c.status === "warning"), redacted:true }, { cardId:"safety", label:"安全回归", value:sentinel.status === "fail" ? "失败" : (sentinel.status === "warning" ? "警告" : "通过"), redacted:true }, { cardId:"handoff", label:"平台确认", value:c.status === "blocked" ? "已阻断" : (readiness.handoffPacketReady ? "准备完成" : "仍需复核"), redacted:true }]); }
  function rowsFromSections(sections, sectionId) { const section = toArray(sections).filter(function (item) { return item && item.sectionId === sectionId; })[0] || {}; return toArray(section.rows).map(function (row) { return { label:safeText(row.label || ""), value:safeText(row.value || ""), redacted:true }; }); }
  function buildOperatorConsoleSafetyRows(input) { const c = consoleOf(input); const sentinel = c.safetyRegressionSummary || {}; const checks = toArray(sentinel.checks); return clone(checks.length ? checks.map(function (check) { return { label:safeText(check.label || "安全回归"), value:safeText(check.status === "fail" ? "失败" : "通过"), redacted:true }; }) : rowsFromSections(c.sections, "safety_status")); }
  function buildFlightWorkflowOperatorConsoleViewModel(input) { const c = consoleOf(input || {}); const statusCards = buildOperatorConsoleStatusCards(c); return clone({ viewModelName:VIEW_MODEL_NAME, appVersion:FLIGHT_WORKFLOW_OPERATOR_CONSOLE_VIEW_MODEL_VERSION, status:c.status || "failed_safe", title:"机票工作流运营控制台", statusCards:statusCards, safetyRows:buildOperatorConsoleSafetyRows(c), recentEventRows:rowsFromSections(c.sections, "recent_events"), blockedActionRows:rowsFromSections(c.sections, "blocked_actions"), nextActionLabel:safeText(c.nextOperatorAction && c.nextOperatorAction.label || "继续只读流程"), caveat:"唯珊只提供只读候选证据，不付款、不下单、不出票。", bookingUrl:null, checkoutUrl:null, paymentUrl:null, orderUrl:null, redacted:true }); }
  function buildOperatorConsoleViewModelAuditDraft(input) { const vm = buildFlightWorkflowOperatorConsoleViewModel(input || {}); return clone({ eventType:"FLIGHT_WORKFLOW_OPERATOR_CONSOLE_VIEW_MODEL_AUDIT_DRAFT", viewModelName:VIEW_MODEL_NAME, appVersion:FLIGHT_WORKFLOW_OPERATOR_CONSOLE_VIEW_MODEL_VERSION, status:vm.status, title:vm.title, statusCardCount:vm.statusCards.length, safetyRowCount:vm.safetyRows.length, bookingUrl:null, checkoutUrl:null, paymentUrl:null, orderUrl:null, payment:false, order:false, ticketing:false, rawResponseStored:false, rawUserTextStored:false, secretStored:false, redacted:true }); }
  window.WeishanFlightWorkflowOperatorConsoleViewModel = { FLIGHT_WORKFLOW_OPERATOR_CONSOLE_VIEW_MODEL_VERSION, VIEW_MODEL_NAME, buildFlightWorkflowOperatorConsoleViewModel, buildOperatorConsoleStatusCards, buildOperatorConsoleSafetyRows, buildOperatorConsoleViewModelAuditDraft };
})();
