;(function () {
  "use strict";

  const FLIGHT_WORKFLOW_FEEDBACK_TREND_RADAR_VERSION = "3.3.0";
  const RADAR_NAME = "flight_workflow_feedback_trend_radar_v1";
  const SENSITIVE_RE = /https?:\/\/\S+|(?:token|apiKey|key|secret|password|credential|cardNumber)\s*[:=]?\s*\S+|身份证|护照|银行卡|passport|raw feedback|rawUserText/ig;
  const TRADING_RE = /"(bookingUrl|checkoutUrl|paymentUrl|orderUrl)"\s*:\s*"https?:\/\//i;
  function clone(value) { return value && typeof value === "object" ? JSON.parse(JSON.stringify(value)) : value; }
  function text(value) { return String(value == null ? "" : value).trim(); }
  function safeText(value) { return text(value).replace(SENSITIVE_RE, "redacted"); }
  function toArray(value) { return Array.isArray(value) ? value.slice() : []; }
  function safety() { return { rawUserTextStored:false, rawResponseStored:false, secretStored:false, identityUpload:false, credentialInput:false, bookingUrl:null, checkoutUrl:null, paymentUrl:null, orderUrl:null, payment:false, order:false, ticketing:false, fileWrite:false, download:false, redacted:true }; }
  function itemsOf(input) { const safe = input && typeof input === "object" ? input : {}; return Array.isArray(safe.feedback) ? safe.feedback : (Array.isArray(safe.sessions) ? safe.sessions : (Array.isArray(safe.items) ? safe.items : [])); }
  function normalized(item) { const safe = item && typeof item === "object" ? item : {}; const review = safe.feedbackReviewSummary || (safe.reviewCenterName === "flight_workflow_beta_feedback_review_center_v1" ? safe : {}); const rating = review.ratingSummary || safe.redactedFeedback || safe.feedbackSummary || safe; const health = review.feedbackHealth || {}; return { status:review.status || safe.status || "unknown", usability:rating.usabilityRating || safe.usabilityRating || "unknown", clarity:rating.clarityRating || safe.clarityRating || "unknown", safetyCopyUnderstood:typeof health.safetyCopyUnderstood === "boolean" ? health.safetyCopyUnderstood : (typeof rating.safetyCopyUnderstood === "boolean" ? rating.safetyCopyUnderstood : safe.safetyCopyUnderstood), sensitive:review.status === "redacted" || safe.status === "redacted" || safe.sensitiveDetected === true, blocked:review.status === "blocked" || safe.status === "blocked" || safe.blocked === true }; }
  function blockedInput(input) { const source = JSON.stringify(input && typeof input === "object" ? input : {}); return /rawUserTextStored"?\s*:?\s*true/i.test(source) || /secretStored"?\s*:?\s*true/i.test(source) || TRADING_RE.test(source); }
  function trend(good, bad, total) { if (!total) return "unknown"; if (bad / total > 0.5) return "negative"; if (good / total >= 0.6) return "positive"; return "mixed"; }
  function evaluateFlightWorkflowFeedbackTrends(input) {
    const items = itemsOf(input || {}).map(normalized);
    let goodU = 0, badU = 0, goodC = 0, badC = 0, understood = 0, notUnderstood = 0, redacted = 0, blocked = 0;
    items.forEach(function (item) { if (item.usability === "good") goodU += 1; if (item.usability === "bad") badU += 1; if (item.clarity === "good") goodC += 1; if (item.clarity === "bad") badC += 1; if (item.safetyCopyUnderstood === true) understood += 1; if (item.safetyCopyUnderstood === false) notUnderstood += 1; if (item.sensitive) redacted += 1; if (item.blocked) blocked += 1; });
    const count = items.length;
    const usabilityTrend = trend(goodU, badU, count);
    const clarityTrend = trend(goodC, badC, count);
    const safetyCopyTrend = !count ? "unknown" : (notUnderstood / count > 0.5 ? "not_understood" : (understood / count >= 0.7 ? "understood" : "mixed"));
    const sensitiveInputTrend = blocked || blockedInput(input || {}) ? "blocked" : (redacted ? "redacted" : (count ? "none" : "unknown"));
    const overallTrend = sensitiveInputTrend === "blocked" || usabilityTrend === "negative" || clarityTrend === "negative" || safetyCopyTrend === "not_understood" ? "negative" : (usabilityTrend === "positive" && clarityTrend === "positive" && safetyCopyTrend === "understood" ? "positive" : (count ? "mixed" : "unknown"));
    return clone({ usabilityTrend:usabilityTrend, clarityTrend:clarityTrend, safetyCopyTrend:safetyCopyTrend, sensitiveInputTrend:sensitiveInputTrend, overallTrend:overallTrend, feedbackCount:count, redacted:true });
  }
  function statusFor(trends) { if (trends.sensitiveInputTrend === "blocked") return "blocked"; if (trends.feedbackCount < 3) return "insufficient_data"; if (trends.overallTrend === "negative" || trends.usabilityTrend === "negative" || trends.clarityTrend === "negative" || trends.safetyCopyTrend === "not_understood") return "needs_review"; return "ready"; }
  function signal(signalId, label, value, status) { return { signalId:signalId, label:safeText(label), value:safeText(value), status:/^(pass|warning|blocked)$/.test(status) ? status : "warning", redacted:true }; }
  function buildFlightWorkflowFeedbackTrendSignals(input) { const t = evaluateFlightWorkflowFeedbackTrends(input || {}); return clone([ signal("usability", "可用性评分", t.usabilityTrend, t.usabilityTrend === "positive" ? "pass" : (t.usabilityTrend === "negative" ? "warning" : "warning")), signal("clarity", "清晰度评分", t.clarityTrend, t.clarityTrend === "positive" ? "pass" : (t.clarityTrend === "negative" ? "warning" : "warning")), signal("safety_copy", "安全文案理解", t.safetyCopyTrend, t.safetyCopyTrend === "understood" ? "pass" : "warning"), signal("sensitive", "敏感输入", t.sensitiveInputTrend, t.sensitiveInputTrend === "blocked" ? "blocked" : (t.sensitiveInputTrend === "none" ? "pass" : "warning")) ]); }
  function recommendationFor(status, trends) { if (status === "blocked") return { recommendationId:"blocked", label:"已阻断", message:"趋势中存在禁止的安全风险。", redacted:true }; if (status === "insufficient_data") return { recommendationId:"continue_small_batch", label:"仍需更多反馈", message:"继续小批次只读测试。", redacted:true }; if (trends.safetyCopyTrend === "not_understood" || trends.clarityTrend === "negative") return { recommendationId:"improve_copy", label:"改进安全文案", message:"优先改进安全提示和可读性。", redacted:true }; if (status === "ready") return { recommendationId:"expand_read_only_beta", label:"可以扩大只读测试", message:"反馈趋势正向，可扩大只读 Beta。", redacted:true }; return { recommendationId:"continue_small_batch", label:"仍需复核", message:"继续观察脱敏反馈趋势。", redacted:true }; }
  function sanitizeFlightWorkflowFeedbackTrendRadar(radar) { const safe = radar && typeof radar === "object" ? radar : {}; return clone({ radarName:RADAR_NAME, appVersion:FLIGHT_WORKFLOW_FEEDBACK_TREND_RADAR_VERSION, status:safeText(safe.status || "failed_safe"), trends:clone(safe.trends || evaluateFlightWorkflowFeedbackTrends({})), signals:toArray(safe.signals).map(function (item) { return signal(item.signalId || "signal", item.label || "", item.value || "", item.status || "warning"); }), recommendation:Object.assign({ recommendationId:"continue_small_batch", label:"仍需更多反馈", message:"继续小批次只读测试。", redacted:true }, safe.recommendation || {}), safety:safety(), rawUserTextStored:false, rawResponseStored:false, secretStored:false, bookingUrl:null, checkoutUrl:null, paymentUrl:null, orderUrl:null, redacted:true }); }
  function buildFlightWorkflowFeedbackTrendRadar(input) { try { if (!input || typeof input !== "object" || Array.isArray(input)) return sanitizeFlightWorkflowFeedbackTrendRadar({ status:"failed_safe" }); const trends = evaluateFlightWorkflowFeedbackTrends(input); const status = statusFor(trends); return sanitizeFlightWorkflowFeedbackTrendRadar({ status:status, trends:trends, signals:buildFlightWorkflowFeedbackTrendSignals(input), recommendation:recommendationFor(status, trends) }); } catch (error) { return sanitizeFlightWorkflowFeedbackTrendRadar({ status:"failed_safe" }); } }
  function buildFlightWorkflowFeedbackTrendRadarAuditDraft(input) { const radar = buildFlightWorkflowFeedbackTrendRadar(input || {}); return clone({ eventType:"FLIGHT_WORKFLOW_FEEDBACK_TREND_RADAR_AUDIT_DRAFT", radarName:RADAR_NAME, appVersion:FLIGHT_WORKFLOW_FEEDBACK_TREND_RADAR_VERSION, status:radar.status, recommendationId:radar.recommendation.recommendationId, rawUserTextStored:false, secretStored:false, bookingUrl:null, paymentUrl:null, orderUrl:null, fileWrite:false, download:false, redacted:true }); }
  window.WeishanFlightWorkflowFeedbackTrendRadar = { FLIGHT_WORKFLOW_FEEDBACK_TREND_RADAR_VERSION, RADAR_NAME, buildFlightWorkflowFeedbackTrendRadar, evaluateFlightWorkflowFeedbackTrends, buildFlightWorkflowFeedbackTrendSignals, buildFlightWorkflowFeedbackTrendRadarAuditDraft, sanitizeFlightWorkflowFeedbackTrendRadar };
})();
