;(function () {
  "use strict";

  const FLIGHT_WORKFLOW_PILOT_READINESS_VIEW_MODEL_VERSION = "2.2.8";
  const VIEW_MODEL_NAME = "flight_workflow_pilot_readiness_view_model_v1";
  const SENSITIVE_RE = /https?:\/\/\S+|(?:token|apiKey|key|secret|password|credential|cardNumber)\s*[:=]?\s*\S+|身份证|护照|银行卡|passport|raw feedback|rawUserText/ig;
  function clone(value) { return value && typeof value === "object" ? JSON.parse(JSON.stringify(value)) : value; }
  function text(value) { return String(value == null ? "" : value).trim(); }
  function safeText(value) { return text(value).replace(SENSITIVE_RE, "redacted"); }
  function toArray(value) { return Array.isArray(value) ? value.slice() : []; }
  function safety() { return { bookingUrl:null, checkoutUrl:null, paymentUrl:null, orderUrl:null, autoOpen:false, autoRefresh:false, payment:false, order:false, ticketing:false, identityUpload:false, credentialInput:false, rawResponseStored:false, rawUserTextStored:false, secretStored:false, fileWrite:false, download:false, redacted:true }; }
  function gateOf(input) { const safe = input && typeof input === "object" ? input : {}; if (safe.betaExpansionGateSummary) return safe.betaExpansionGateSummary; const api = window.WeishanFlightWorkflowBetaExpansionGate || {}; return typeof api.buildFlightWorkflowBetaExpansionGate === "function" ? api.buildFlightWorkflowBetaExpansionGate(safe) : { status:"continue_internal_testing", decision:{ label:"继续内部测试", safeToExpandReadOnlyBeta:false }, unmetCriteria:[], riskNotes:[], userFacingSummary:{ resultLabel:"继续内部测试", redacted:true }, redacted:true }; }
  function checklistOf(input) { const safe = input && typeof input === "object" ? input : {}; if (safe.publicPilotChecklistSummary) return safe.publicPilotChecklistSummary; const api = window.WeishanFlightWorkflowReadOnlyPublicPilotChecklist || {}; return typeof api.buildFlightWorkflowReadOnlyPublicPilotChecklist === "function" ? api.buildFlightWorkflowReadOnlyPublicPilotChecklist(safe) : { status:"needs_internal_testing", readiness:{ safeForSmallPublicPilot:false }, checklistItems:[], blockedItems:[], userFacingSummary:{ resultLabel:"继续内部测试", redacted:true }, redacted:true }; }
  function card(cardId, label, value) { return { cardId:cardId, label:safeText(label), value:safeText(value), redacted:true }; }
  function buildFlightWorkflowPilotReadinessCards(input) { const gate = gateOf(input || {}); const checklist = checklistOf(input || {}); return clone([ card("expansion_gate", "扩大测试闸门", gate.userFacingSummary && gate.userFacingSummary.resultLabel || gate.decision && gate.decision.label || "继续内部测试"), card("pilot_checklist", "试点检查清单", checklist.userFacingSummary && checklist.userFacingSummary.resultLabel || checklist.status || "needs_review"), card("safety", "安全边界", checklist.readiness && checklist.readiness.safeForSmallPublicPilot ? "公开试点仍为只读" : "继续内部测试"), card("next_step", "下一步", gate.status === "approved" && checklist.status === "ready" ? "可以小范围只读试点" : (gate.status === "blocked" || checklist.status === "blocked" ? "暂停扩大测试" : "继续内部测试")) ]); }
  function buildFlightWorkflowPilotChecklistRows(input) { const checklist = checklistOf(input || {}); return clone(toArray(checklist.checklistItems).map(function (entry) { return { rowId:safeText(entry.itemId || "item"), label:safeText(entry.label || ""), value:safeText(entry.message || entry.status || ""), status:safeText(entry.status || "needs_review"), redacted:true }; })); }
  function buildFlightWorkflowPilotRiskRows(input) { const gate = gateOf(input || {}); const checklist = checklistOf(input || {}); const risks = toArray(gate.riskNotes).concat(toArray(gate.unmetCriteria).map(function (id) { return "未满足项: " + id; })).concat(toArray(checklist.blockedItems).map(function (entry) { return entry.label || entry.itemId || "blocked"; })); return clone((risks.length ? risks : ["公开试点仍然只覆盖只读候选证据流程"]).map(function (value, index) { return { rowId:"risk_" + index, label:index === 0 ? "风险说明" : "未满足项", value:safeText(value), status:risks.length ? "needs_review" : "checked", redacted:true }; })); }
  function buildFlightWorkflowPilotReadinessViewModel(input) { const gate = gateOf(input || {}); const checklist = checklistOf(Object.assign({}, input || {}, { betaExpansionGateSummary:gate })); const status = gate.status === "blocked" || checklist.status === "blocked" ? "blocked" : (gate.status === "approved" && checklist.status === "ready" ? "ready" : (gate.status === "needs_review" || checklist.status === "needs_review" ? "needs_review" : "needs_internal_testing")); return clone({ viewModelName:VIEW_MODEL_NAME, appVersion:FLIGHT_WORKFLOW_PILOT_READINESS_VIEW_MODEL_VERSION, status:status, title:"只读公开试点准备状态", cards:buildFlightWorkflowPilotReadinessCards({ betaExpansionGateSummary:gate, publicPilotChecklistSummary:checklist }), checklistRows:buildFlightWorkflowPilotChecklistRows({ publicPilotChecklistSummary:checklist }), riskRows:buildFlightWorkflowPilotRiskRows({ betaExpansionGateSummary:gate, publicPilotChecklistSummary:checklist }), pilotOnboardingSummary:clone((input && input.pilotOnboardingSummary) || null), readOnlyConsentSummary:clone((input && input.readOnlyConsentSummary) || null), pilotEntryStatus:safeText((input && input.pilotEntryStatus) || ""), canEnterReadOnlyPilot:input && input.canEnterReadOnlyPilot === true, pilotConsentRequired:input && input.pilotConsentRequired === true, caveat:"公开试点仍然只覆盖只读候选证据流程，不代表真实票价、库存或可出票。", safety:safety(), bookingUrl:null, checkoutUrl:null, paymentUrl:null, orderUrl:null, rawUserTextStored:false, rawResponseStored:false, secretStored:false, fileWrite:false, download:false, redacted:true }); }
  function buildFlightWorkflowPilotReadinessViewModelAuditDraft(input) { const vm = buildFlightWorkflowPilotReadinessViewModel(input || {}); return clone({ eventType:"FLIGHT_WORKFLOW_PILOT_READINESS_VIEW_MODEL_AUDIT_DRAFT", viewModelName:VIEW_MODEL_NAME, appVersion:FLIGHT_WORKFLOW_PILOT_READINESS_VIEW_MODEL_VERSION, status:vm.status, cardCount:vm.cards.length, checklistRowCount:vm.checklistRows.length, riskRowCount:vm.riskRows.length, bookingUrl:null, checkoutUrl:null, paymentUrl:null, orderUrl:null, autoOpen:false, autoRefresh:false, payment:false, order:false, ticketing:false, identityUpload:false, rawResponseStored:false, rawUserTextStored:false, secretStored:false, fileWrite:false, download:false, redacted:true }); }
  window.WeishanFlightWorkflowPilotReadinessViewModel = { FLIGHT_WORKFLOW_PILOT_READINESS_VIEW_MODEL_VERSION, VIEW_MODEL_NAME, buildFlightWorkflowPilotReadinessViewModel, buildFlightWorkflowPilotReadinessCards, buildFlightWorkflowPilotChecklistRows, buildFlightWorkflowPilotRiskRows, buildFlightWorkflowPilotReadinessViewModelAuditDraft };
})();
