;(function () {
  "use strict";
  const FLIGHT_WORKFLOW_FINAL_SAFE_HANDOFF_PACKET_VERSION = "4.0.9";
  const PACKET_NAME = "flight_workflow_final_safe_handoff_packet_v1";
  const FORBIDDEN_NAME_RE = /(rawText|rawUserText|rawInput|rawProviderResponse|rawResponse|rawPayload|token|apiKey|secret|password|auth|credential|bookingUrl|checkoutUrl|paymentUrl|orderUrl|identity|passport|bank|card|idNumber|passportNumber)/i;
  const FORBIDDEN_TEXT_RE = /https?:\/\/\S+|token|apiKey|secret|password|身份证|护照|银行卡|credential|passport|cardNumber/ig;
  function clone(value) { return value && typeof value === "object" ? JSON.parse(JSON.stringify(value)) : value; }
  function text(value) { return String(value == null ? "" : value).trim(); }
  function safeText(value) { return text(value).replace(FORBIDDEN_TEXT_RE, "redacted"); }
  function toArray(value) { return Array.isArray(value) ? value.slice() : []; }
  function stripUnsafe(value) { if (Array.isArray(value)) return value.map(stripUnsafe).filter(function (item) { return item !== undefined; }); if (!value || typeof value !== "object") return typeof value === "string" ? safeText(value) : value; const result = {}; Object.keys(value).forEach(function (name) { const raw = value[name]; const allowedNullUrl = /Url$/.test(name) && raw === null; const allowedFalse = /(Stored|Included|Allowed|Enabled|Upload|Input|Open|Refresh|Payment|Order|Ticketing)$/i.test(name) && raw === false; if (FORBIDDEN_NAME_RE.test(name) && !allowedNullUrl && !allowedFalse) return; const next = stripUnsafe(raw); if (next !== undefined) result[name] = next; }); return result; }
  function safety() { return { bookingUrl:null, checkoutUrl:null, paymentUrl:null, orderUrl:null, canOpenExternalPlatform:false, payment:false, order:false, ticketing:false, identityUpload:false, credentialInput:false, rawResponseStored:false, rawUserTextStored:false, secretStored:false, redacted:true }; }
  function hasUnsafe(value) { let blocked = false; function visit(item, key){ if (blocked || item == null) return; const name = String(key || ""); if (/rawProviderResponse|rawResponse|rawPayload|rawText|rawUserText|rawInput|token|apiKey|secret|password|credential|identity|passport|bank|card|idNumber|passportNumber/i.test(name) && item) blocked = true; if (/bookingUrl|checkoutUrl|paymentUrl|orderUrl/i.test(name) && item !== null && item !== false && item !== "") blocked = true; if (/(payment|order|ticketing|identityUpload|credentialInput)/i.test(name) && item === true) blocked = true; if (typeof item === "string" && (/token|apiKey|secret|password|sk-|pk-|live_|prod_|身份证|护照|银行卡|https?:\/\//i.test(item))) blocked = true; if (Array.isArray(item)) item.forEach(function (child){ visit(child, name); }); else if (item && typeof item === "object") Object.keys(item).forEach(function (childKey){ visit(item[childKey], childKey); }); } visit(value, ""); return blocked; }
  function checklistOf(input){ const safe = input && typeof input === "object" ? input : {}; if (safe.humanReviewChecklistSummary) return safe.humanReviewChecklistSummary; const api = window.WeishanFlightWorkflowHumanReviewChecklist || {}; return typeof api.buildFlightWorkflowHumanReviewChecklist === "function" ? api.buildFlightWorkflowHumanReviewChecklist(safe) : null; }
  function evaluateFinalSafeHandoffPacketReadiness(input) { if (!input || typeof input !== "object" || Array.isArray(input)) return clone({ status:"failed_safe", checklistReady:false, safeToPrepare:false, blockedReasons:["malformed_input"], needsReviewReasons:["malformed_input"], redacted:true }); const checklist = checklistOf(input) || {}; const sentinel = input.safetyRegressionSummary || input.sentinelReport || {}; const blocked = hasUnsafe(input) || checklist.status === "blocked" || input.auditReviewSummary && input.auditReviewSummary.status === "blocked" || sentinel.status === "fail" || sentinel.status === "failed_safe"; const needs = checklist.status !== "ready"; return clone({ status:blocked ? "blocked" : (needs ? "needs_review" : "ready"), checklistReady:checklist.status === "ready", safeToPrepare:!blocked && !needs, blockedReasons:blocked ? ["handoff_packet_blocked"] : [], needsReviewReasons:(!blocked && needs) ? ["human_review_checklist_not_ready"] : [], redacted:true }); }
  function row(label, value) { return { label:safeText(label), value:safeText(value), redacted:true }; }
  function buildFinalSafeHandoffPacketSections(input) { const safe = input && typeof input === "object" ? input : {}; const checklist = checklistOf(safe) || {}; return clone([{ sectionId:"trip_summary", title:"行程摘要", rows:[row("路线", safe.routeSummary || safe.workflowStateSummary && safe.workflowStateSummary.routeSummary || "已脱敏行程"), row("日期", safe.departureDate || safe.dateDisplay || "待人工核对")] }, { sectionId:"candidate_summary", title:"候选证据摘要", rows:[row("候选", safe.selectedCandidateSummary && safe.selectedCandidateSummary.line || safe.selectedCandidate && safe.selectedCandidate.providerName || "只读候选证据"), row("说明", "非最低价保证，非锁价，非可出票承诺")] }, { sectionId:"manual_check_summary", title:"平台核对摘要", rows:[row("复核状态", checklist.status === "ready" ? "人工复核完成" : "仍需复核"), row("平台页面", "平台页面结果为准")] }, { sectionId:"safety_summary", title:"安全限制摘要", rows:[row("限制", "唯珊不会付款、不会下单、不会出票"), row("外部打开", "需要用户确认，不自动打开")]}]); }
  function buildFlightWorkflowFinalSafeHandoffPacket(input) { if (!input || typeof input !== "object" || Array.isArray(input)) return sanitizeFinalSafeHandoffPacket({ packetName:PACKET_NAME, appVersion:FLIGHT_WORKFLOW_FINAL_SAFE_HANDOFF_PACKET_VERSION, status:"failed_safe", packetType:"redacted_platform_confirmation_packet", canOpenExternalPlatform:false, requiresUserConfirmation:true, readiness:evaluateFinalSafeHandoffPacketReadiness(null), sections:[], handoffInstructions:["交接包已阻断"], safety:safety(), redacted:true }); try { const readiness = evaluateFinalSafeHandoffPacketReadiness(input || {}); return sanitizeFinalSafeHandoffPacket({ packetName:PACKET_NAME, appVersion:FLIGHT_WORKFLOW_FINAL_SAFE_HANDOFF_PACKET_VERSION, status:readiness.status, packetType:"redacted_platform_confirmation_packet", canOpenExternalPlatform:false, requiresUserConfirmation:true, readiness:readiness, sections:buildFinalSafeHandoffPacketSections(input || {}), handoffInstructions:["前往平台前请人工复核", "平台页面结果为准", "唯珊不会付款、不会下单、不会出票"], userFacingSummary:{ title:"最终安全交接包", line:readiness.status === "ready" ? "可以进入平台确认" : (readiness.status === "blocked" ? "交接包已阻断" : "仍需补充复核"), redacted:true }, safety:safety(), redacted:true }); } catch (error) { return sanitizeFinalSafeHandoffPacket({ packetName:PACKET_NAME, appVersion:FLIGHT_WORKFLOW_FINAL_SAFE_HANDOFF_PACKET_VERSION, status:"failed_safe", packetType:"redacted_platform_confirmation_packet", canOpenExternalPlatform:false, requiresUserConfirmation:true, readiness:evaluateFinalSafeHandoffPacketReadiness(null), sections:[], handoffInstructions:["交接包已阻断"], safety:safety(), redacted:true }); } }
  function sanitizeFinalSafeHandoffPacket(input) { const safe = stripUnsafe(input && typeof input === "object" ? input : {}) || {}; safe.packetName = PACKET_NAME; safe.appVersion = FLIGHT_WORKFLOW_FINAL_SAFE_HANDOFF_PACKET_VERSION; safe.packetType = "redacted_platform_confirmation_packet"; safe.canOpenExternalPlatform = false; safe.requiresUserConfirmation = true; safe.sections = toArray(safe.sections).map(stripUnsafe); safe.handoffInstructions = toArray(safe.handoffInstructions).map(safeText); safe.userFacingSummary = Object.assign({ title:"最终安全交接包", line:"仍需补充复核" }, stripUnsafe(safe.userFacingSummary || {})); safe.operatorConsoleSummary = stripUnsafe(safe.operatorConsoleSummary || null); safe.safetyRegressionSummary = stripUnsafe(safe.safetyRegressionSummary || null); safe.sentinelStatus = safeText(safe.sentinelStatus || safe.safetyRegressionSummary && safe.safetyRegressionSummary.status || ""); safe.operatorReadiness = stripUnsafe(safe.operatorReadiness || null); safe.nextOperatorAction = stripUnsafe(safe.nextOperatorAction || null); safe.safety = Object.assign(safety(), stripUnsafe(safe.safety || {})); safe.bookingUrl = null; safe.checkoutUrl = null; safe.paymentUrl = null; safe.orderUrl = null; safe.payment = false; safe.order = false; safe.ticketing = false; safe.identityUpload = false; safe.credentialInput = false; safe.rawResponseStored = false; safe.rawUserTextStored = false; safe.secretStored = false; safe.redacted = true; return clone(safe); }
  function buildFlightWorkflowFinalSafeHandoffPacketAuditDraft(input) { const packet = buildFlightWorkflowFinalSafeHandoffPacket(input || {}); return clone({ eventType:"FLIGHT_WORKFLOW_FINAL_SAFE_HANDOFF_PACKET_AUDIT_DRAFT", packetName:PACKET_NAME, appVersion:FLIGHT_WORKFLOW_FINAL_SAFE_HANDOFF_PACKET_VERSION, status:packet.status, packetType:packet.packetType, sectionCount:packet.sections.length, canOpenExternalPlatform:false, requiresUserConfirmation:true, bookingUrl:null, checkoutUrl:null, paymentUrl:null, orderUrl:null, payment:false, order:false, ticketing:false, identityUpload:false, rawResponseStored:false, rawUserTextStored:false, secretStored:false, redacted:true }); }
  window.WeishanFlightWorkflowFinalSafeHandoffPacket = { FLIGHT_WORKFLOW_FINAL_SAFE_HANDOFF_PACKET_VERSION, PACKET_NAME, buildFlightWorkflowFinalSafeHandoffPacket, evaluateFinalSafeHandoffPacketReadiness, buildFinalSafeHandoffPacketSections, buildFlightWorkflowFinalSafeHandoffPacketAuditDraft, sanitizeFinalSafeHandoffPacket };
})();
