;(function () {
  "use strict";
  const BLOCKED_KEYS=Object.freeze(["__proto__","prototype","constructor"]), AUTHORITY_KEYS=Object.freeze(["trusted","validated","isadmin","authorizesexecution","productiontraffic","safeurl","exact","exacthandoff","trustedurl","recommended","current","live","sendallowed","autoreply"]), SENSITIVE=/^(token|secret|credential|password|passwd|apikey|api_key|authorization|cookie|session|endpoint|privatekey|accesskey|clientsecret|cardnumber|cvv)$/i;
  function result(valid,code){return Object.freeze({valid:valid,code:code||"SAFE"});}
  function validateGlobalDiscoveryInput(input){const seen=new Set(),nodes={count:0};function walk(value,depth){if(depth>8)return result(false,"MAX_DEPTH_EXCEEDED");if(value===null||typeof value==="string"||typeof value==="boolean")return result(true);if(typeof value==="number")return Number.isFinite(value)?result(true):result(false,"INVALID_NUMBER");if(typeof value==="function"||typeof value==="symbol"||typeof value==="bigint"||typeof value==="undefined")return result(false,"UNSUPPORTED_VALUE_TYPE");if(typeof value!=="object"||seen.has(value))return seen.has(value)?result(false,"CIRCULAR_REFERENCE"):result(false,"UNSUPPORTED_VALUE_TYPE");const proto=Object.getPrototypeOf(value),constructor=proto&&Object.getOwnPropertyDescriptor(proto,"constructor");if(proto!==null&&!Array.isArray(value)&&(!constructor||typeof constructor.value!=="function"||constructor.value.name!=="Object"))return result(false,"UNSUPPORTED_VALUE_TYPE");seen.add(value);nodes.count+=1;if(nodes.count>400)return result(false,"MAX_NODES_EXCEEDED");const names=Object.getOwnPropertyNames(value),symbols=Object.getOwnPropertySymbols(value);if(symbols.length)return result(false,"UNSUPPORTED_VALUE_TYPE");if(Array.isArray(value)&&names.filter(k=>k!=="length").length>100)return result(false,"MAX_NODES_EXCEEDED");for(const key of names){if(Array.isArray(value)&&/^\d+$/.test(key)){}else if(key!=="length"){if(BLOCKED_KEYS.indexOf(key)>=0)return result(false,"PROTOTYPE_POLLUTION_KEY");if(SENSITIVE.test(key))return result(false,"SENSITIVE_FIELD");const normalizedAuthorityKey=String(key).replace(/[^a-z0-9]/gi,"").toLowerCase();const boundary=window.WeishanSecurityCoreTrustBoundary;if(AUTHORITY_KEYS.indexOf(normalizedAuthorityKey)>=0||(boundary&&boundary.isAuthorityKey&&boundary.isAuthorityKey(key)))return result(false,"AUTHORITY_FIELD");}const descriptor=Object.getOwnPropertyDescriptor(value,key);if(descriptor.get)return result(false,"UNSAFE_GETTER");if(descriptor.set)return result(false,"UNSAFE_SETTER");const next=walk(descriptor.value,depth+1);if(!next.valid)return next;}seen.delete(value);return result(true);}return walk(input,0);}
  function cloneValidatedInput(input){function copy(value){if(value===null||typeof value!=="object")return value;if(Array.isArray(value))return Object.freeze(value.map(copy));const out={};Object.getOwnPropertyNames(value).forEach(function(key){out[key]=copy(Object.getOwnPropertyDescriptor(value,key).value);});return Object.freeze(out);}return copy(input);}
  function guardAndCloneInput(input){const validation=validateGlobalDiscoveryInput(input);return validation.valid?Object.freeze({valid:true,code:"SAFE",value:cloneValidatedInput(input)}):Object.freeze({valid:false,code:validation.code,value:null});}
  window.WeishanGlobalDiscoveryInputGuard={BLOCKED_KEYS,AUTHORITY_KEYS,validateGlobalDiscoveryInput,guardAndCloneInput};
})();
