;(function () {
  "use strict";
  const READ_ONLY_PROVIDER_ADAPTER_CONTRACT_VERSION = "2.2.2";
  const ALLOWED_METHODS = ["getAdapterMetadata", "validateCredentialScope", "validateReadinessGates", "runOfflineFixtureSearch", "normalizeProviderResult", "validateResultSchema", "attachSourceLabel", "validateSandboxResponseSchema", "validateRealProviderResultSchema", "attachProviderSourceLabel", "evaluateResultForConsoleOnlyDisplay", "runDryRun"];
  const BLOCKED_METHODS = ["connect", "fetch", "request", "post", "createOrder", "pay", "checkout", "uploadIdentity", "revealCredential", "exportCredential", "testEndpoint"];
  function clone(value) { return JSON.parse(JSON.stringify(value)); }
  function blockedStub(methodName) { return function blockedProviderAdapterMethod() { return clone({ methodName, status:"blocked", blockedReason:"real provider adapter action disabled", networkAttemptCount:0, realProviderCallCount:0, realCredentialReadCount:0, realEndpointConnectCount:0, realPriceDisplayedCount:0, bookingUrlDisplayedCount:0, paymentAttemptCount:0, orderAttemptCount:0, identityUploadAttemptCount:0, redacted:true }); }; }
  function getAdapterMetadata(input) { const raw = input && typeof input === "object" ? input : {}; return clone({ version: READ_ONLY_PROVIDER_ADAPTER_CONTRACT_VERSION, adapterId: raw.adapterId || "readonly_provider_adapter_contract_v1", providerCategory: raw.providerCategory || "generic_provider", providerName: raw.providerName || "Read-Only Provider Adapter Contract", mode: "offline_fixture_only", networkPolicy: "disabled", credentialPolicy: "metadata_only", endpointPolicy: "disabled", resultPolicy: "normalized_draft_only", sandboxResponseSchemaGate:"draft-ready", realProviderResultSchemaValidation:"draft-ready", providerResultSourceLabelGate:"draft-ready", ordinaryResultExposure:"disabled", priceExposure:"disabled", availabilityExposure:"disabled", bookingUrlPolicy: "disabled", paymentPolicy: "disabled", orderPolicy: "disabled", identityUploadPolicy: "disabled", redacted: true }); }
  function validateCredentialScope(consentState) { const state = consentState && typeof consentState === "object" ? consentState : {}; return clone({ status: state.consentState === "draft_ready" ? "draft-ready" : "missing", finalDecision:"no-go", realCredentialRead:false, realCredentialUsed:false, redacted:true }); }
  function validateReadinessGates(readinessState) { const state = readinessState && typeof readinessState === "object" ? readinessState : {}; return clone({ status:"draft-ready", endpointAllowlist:state.endpointAllowlist || "missing", sandboxGate:state.sandboxGate || "missing", manualProviderReview:state.manualProviderReview || "missing", finalDecision:"no-go", redacted:true }); }
  function runOfflineFixtureSearch(query) { return clone({ status:"PASS", mode:"offline_fixture_only", query:query || {}, fixtureOnly:true, realProvider:false, realNetwork:false, networkAttemptCount:0, redacted:true }); }
  function normalizeProviderResult(fixtureResult) { return clone(Object.assign({ resultSchemaVersion:"provider_result_schema_v1", fixtureOnly:true, realProvider:false, realNetwork:false, realPrice:false, availability:false, bookingUrl:null, payment:false, order:false, identityUpload:false, redacted:true }, fixtureResult || {})); }
  function validateResultSchema(normalizedResult) { const result = normalizedResult || {}; if (result.fixtureOnly !== true) throw new Error("adapter result must stay fixtureOnly"); if (result.realProvider !== false || result.realNetwork !== false || result.realPrice !== false) throw new Error("adapter result must not be real provider/network/price"); if (result.bookingUrl !== null) throw new Error("adapter result must not include bookingUrl"); return true; }
  function attachSourceLabel(normalizedResult) { const result = normalizeProviderResult(normalizedResult); result.sourceLabel = result.sourceLabel || "offline fixture / no real provider"; return result; }
  function runDryRun(query) { const fixture = runOfflineFixtureSearch(query); const normalized = attachSourceLabel(normalizeProviderResult(fixture)); validateResultSchema(normalized); return normalized; }
  function buildReadOnlyProviderAdapterAuditDraft(metadata) { const meta = getAdapterMetadata(metadata || {}); return clone({ eventType:"READ_ONLY_PROVIDER_ADAPTER_V1_DRAFT", adapterId:meta.adapterId, providerCategory:meta.providerCategory, mode:"offline_fixture_only", fixtureRunCount:0, realProviderCallCount:0, realProviderResultCount:0, networkAttemptCount:0, realCredentialReadCount:0, realApiKeyReadCount:0, realEndpointConnectCount:0, realPriceDisplayedCount:0, realPriceReturnCount:0, bookingUrlDisplayedCount:0, bookingUrlReturnCount:0, paymentAttemptCount:0, orderAttemptCount:0, identityUploadAttemptCount:0, redacted:true }); }
  function buildAdapterContract(input) { const metadata = getAdapterMetadata(input); return clone({ version:READ_ONLY_PROVIDER_ADAPTER_CONTRACT_VERSION, contractVersion:READ_ONLY_PROVIDER_ADAPTER_CONTRACT_VERSION, phase:"read_only_provider_adapter_contract_v1", status:"adapter contract draft-ready", mode:"offline_fixture_only", networkPolicy:"disabled", credentialPolicy:"metadata_only", endpointPolicy:"disabled", resultPolicy:"normalized_draft_only", realProviderConnection:"disabled", realNetwork:"disabled", realEndpoint:"disabled", realPrice:"disabled", availability:"disabled", bookingUrl:"disabled", payment:"disabled", order:"disabled", identityUpload:"disabled", metadata, allowedMethods:ALLOWED_METHODS, blockedMethods:BLOCKED_METHODS, auditDraft:buildReadOnlyProviderAdapterAuditDraft(metadata), finalDecision:"no-go", redacted:true }); }
  function assertReadOnlyProviderAdapterContractSafe(contract) { const safe = contract && contract.metadata ? contract : buildAdapterContract(contract || {}); const meta = safe.metadata || safe; if (meta.networkPolicy !== "disabled" || safe.networkPolicy !== "disabled") throw new Error("networkPolicy must stay disabled"); if (meta.credentialPolicy !== "metadata_only" || safe.credentialPolicy !== "metadata_only") throw new Error("credentialPolicy must stay metadata_only"); if (meta.endpointPolicy !== "disabled" || safe.endpointPolicy !== "disabled") throw new Error("endpointPolicy must stay disabled"); if (meta.bookingUrlPolicy !== "disabled" || meta.paymentPolicy !== "disabled" || meta.orderPolicy !== "disabled" || meta.identityUploadPolicy !== "disabled") throw new Error("write policies must stay disabled"); for (const method of BLOCKED_METHODS) if (!safe.blockedMethods.includes(method)) throw new Error("missing blocked method " + method); const audit = safe.auditDraft || buildReadOnlyProviderAdapterAuditDraft(meta); ["realProviderCallCount", "realProviderResultCount", "networkAttemptCount", "realCredentialReadCount", "realApiKeyReadCount", "realEndpointConnectCount", "realPriceDisplayedCount", "realPriceReturnCount", "bookingUrlDisplayedCount", "bookingUrlReturnCount", "paymentAttemptCount", "orderAttemptCount", "identityUploadAttemptCount"].forEach((key) => { if (audit[key] !== 0) throw new Error(key + " must stay zero"); }); if (safe.redacted !== true || audit.redacted !== true || meta.redacted !== true) throw new Error("adapter contract must stay redacted"); return true; }
  const api = { READ_ONLY_PROVIDER_ADAPTER_CONTRACT_VERSION, ALLOWED_METHODS, BLOCKED_METHODS, getAdapterMetadata, validateCredentialScope, validateReadinessGates, runOfflineFixtureSearch, normalizeProviderResult, validateResultSchema, attachSourceLabel, runDryRun, buildAdapterContract, buildReadOnlyProviderAdapterAuditDraft, assertReadOnlyProviderAdapterContractSafe };
  BLOCKED_METHODS.forEach((method) => { api[method] = blockedStub(method); });
  window.WeishanReadOnlyProviderAdapterContract = api;
})();
