(function(){
  const C=window.WeishanVideoProviderCapabilities,T=window.WeishanVideoProviderTaskMapper,A=window.WeishanVideoProviderArtifacts,E=window.WeishanVideoProviderErrors,FORBIDDEN=["__proto__","prototype","constructor"];
  function plain(value){if(!value||typeof value!=="object"||Array.isArray(value))return false;const proto=Object.getPrototypeOf(value);if(proto===null)return true;const constructor=Object.getOwnPropertyDescriptor(proto,"constructor");return!!constructor&&typeof constructor.value==="function"&&Object.getPrototypeOf(proto)===null;}
  function safe(value,seen){if(value===null||["string","number","boolean"].includes(typeof value))return true;if(typeof value!=="object"||ArrayBuffer.isView(value)||value instanceof ArrayBuffer)return false;const visited=seen||new Set();if(visited.has(value))return false;visited.add(value);if(Array.isArray(value))return value.every((item)=>safe(item,visited));if(!plain(value))return false;return Object.getOwnPropertyNames(value).every((key)=>{const descriptor=Object.getOwnPropertyDescriptor(value,key);return !FORBIDDEN.includes(key)&&!!descriptor&&!descriptor.get&&!descriptor.set&&safe(descriptor.value,visited);});}
  function only(value,keys){return plain(value)&&safe(value)&&Object.getOwnPropertyNames(value).every((key)=>keys.includes(key));}
  function invalid(){return{ok:false,error:E.createVideoProviderError()};}
  function validateVideoProviderEnvelope(value,kind){if(!only(value,["ok","data","error"])||typeof value.ok!=="boolean")return invalid();if(!value.ok)return only(value.error,["code"])?{ok:false,error:E.createVideoProviderError(value.error)}:invalid();if(kind==="task"){if(!only(value.data,["taskId","title","status","progress","resultTypes","createdAt","updatedAt"]))return invalid();return{ok:true,data:T.mapVideoProviderTask(value.data)};}if(kind==="artifacts"){const list=Array.isArray(value.data)?value.data:null;if(!list||!safe(list)||!list.every((item)=>only(item,["type","mimeType","sizeBytes","availability","previewMode","displayName","name"])))return invalid();return{ok:true,data:A.createVideoProviderArtifacts(list)};}if(kind==="capabilities"){const source=value.data;if(!only(source,["available","capabilities","limits"])||!plain(source.capabilities)||!plain(source.limits)||!safe(source.capabilities)||!safe(source.limits))return invalid();return{ok:true,data:{available:source.available===true,capabilities:C.createVideoProviderCapabilities(source.capabilities),limits:source.limits}};}if(kind==="status"){const source=value.data;if(!only(source,["available","mode","runtimeReady","providerHostReady","activeTaskCount"]))return invalid();return{ok:true,data:{available:source.available===true,mode:typeof source.mode==="string"?source.mode:"unavailable",runtimeReady:source.runtimeReady===true,providerHostReady:source.providerHostReady===true,activeTaskCount:Number.isInteger(source.activeTaskCount)&&source.activeTaskCount>=0?source.activeTaskCount:0}};}if(kind==="tasks"){const list=Array.isArray(value.data)?value.data:null;if(!list||!safe(list)||!list.every((item)=>only(item,["taskId","title","status","progress","resultTypes","createdAt","updatedAt"])))return invalid();return{ok:true,data:list.map(T.mapVideoProviderTask)};}return invalid();}
  window.WeishanVideoProviderValidator={validateVideoProviderEnvelope};
})();
