(function(){
  const KEYS=["type","mimeType","sizeBytes","availability","previewMode","displayName"];
  function plain(value){const proto=Object.getPrototypeOf(value);if(proto===null)return true;const descriptor=Object.getOwnPropertyDescriptor(proto,"constructor");return !!descriptor&&typeof descriptor.value==="function"&&Object.getPrototypeOf(proto)===null;}
  function descriptor(value){if(!value||typeof value!=="object"||Array.isArray(value)||Object.getOwnPropertySymbols(value).length||!plain(value))return false;const names=Object.getOwnPropertyNames(value);if(names.length!==KEYS.length||names.some((key)=>!KEYS.includes(key)))return false;for(const key of names){const property=Object.getOwnPropertyDescriptor(value,key);if(!property||property.get||property.set)return false;}return typeof value.type==="string"&&value.type.length>0&&value.type.length<=40&&typeof value.mimeType==="string"&&/^[-\w]+\/[-\w.+]+$/.test(value.mimeType)&&Number.isSafeInteger(value.sizeBytes)&&value.sizeBytes>=0&&typeof value.availability==="boolean"&&typeof value.previewMode==="string"&&value.previewMode.length<=40&&typeof value.displayName==="string"&&value.displayName.length>0&&value.displayName.length<=120;}
  function certifyVideoProviderArtifacts(list){const valid=Array.isArray(list)&&Object.getOwnPropertySymbols(list).length===0&&list.every(descriptor);return Object.freeze({status:valid?"passed":"failed",code:valid?"ARTIFACTS_OK":"ARTIFACTS_INVALID",message:valid?"结果验证通过":"结果验证未通过"});}
  const STATES=["QUEUED","GENERATING","POST_PROCESSING","COMPLETED","FAILED","CANCELLED","UNKNOWN_TASK"];
  async function certifyVideoProviderArtifactScenarios(createSandbox){const scenarios=[];if(typeof createSandbox!=="function")return Object.freeze({status:"failed",code:"ARTIFACTS_INVALID",message:"结果验证未通过",scenarios:Object.freeze(scenarios)});for(const scenario of STATES){let sandbox;try{sandbox=createSandbox();const taskId=scenario==="UNKNOWN_TASK"?"unknown-certification-task":(await sandbox.createTask({certificationState:scenario})).data.taskId,first=await sandbox.downloadArtifacts({taskId}),second=scenario==="COMPLETED"?await sandbox.downloadArtifacts({taskId}):first,count=first.ok&&Array.isArray(first.data)?first.data.length:0,completed=scenario==="COMPLETED",passed=completed?first.ok&&count>0&&descriptor(first.data[0])&&second.ok&&JSON.stringify(first.data)===JSON.stringify(second.data):scenario==="UNKNOWN_TASK"?!first.ok&&first.error&&first.error.code==="TASK_NOT_FOUND":first.ok&&count===0;scenarios.push(Object.freeze({scenario,taskStatus:scenario,outcome:first.ok?"safe":"rejected",artifactCount:count,errorCode:first.ok?null:first.error&&first.error.code||null,immutable:completed&&first.ok, repeatedReadStable:completed&&first.ok&&second.ok&&JSON.stringify(first.data)===JSON.stringify(second.data),passed}));}catch(_){scenarios.push(Object.freeze({scenario,taskStatus:scenario,outcome:"rejected",artifactCount:0,errorCode:"INTERNAL_ERROR",immutable:false,repeatedReadStable:false,passed:false}));}finally{if(sandbox)await sandbox.dispose();}}const passed=scenarios.length===STATES.length&&new Set(scenarios.map(x=>x.scenario)).size===STATES.length&&scenarios.every(x=>x.passed);return Object.freeze({status:passed?"passed":"failed",code:passed?"ARTIFACTS_OK":"ARTIFACTS_INVALID",message:passed?"结果验证通过":"结果验证未通过",scenarios:Object.freeze(scenarios)});}
  window.WeishanVideoProviderArtifactCertification={KEYS,STATES,certifyVideoProviderArtifacts,certifyVideoProviderArtifactScenarios};
})();
