(function(){
  const Manifest=window.WeishanVideoProviderManifest,Contracts=window.WeishanVideoProviderContracts,Sandbox=window.WeishanVideoProviderSandbox,Matrix=window.WeishanVideoProviderComplianceMatrix,Capabilities=window.WeishanVideoProviderCapabilityMatrix,Lifecycle=window.WeishanVideoProviderLifecycleCertification,Errors=window.WeishanVideoProviderErrorCertification,Security=window.WeishanVideoProviderSecurityCertification,Determinism=window.WeishanVideoProviderDeterminismCertification,Concurrency=window.WeishanVideoProviderConcurrencyCertification,Cancellation=window.WeishanVideoProviderCancellationCertification,Artifacts=window.WeishanVideoProviderArtifactCertification,Reports=window.WeishanVideoProviderCertificationReport;
  const FIXTURE=Object.freeze({title:"认证视频任务",unknownTaskId:"certification-unknown-task"});
  function row(status,code,message){return{status,code,message};}
  function failed(entries,key,code,message){entries[key]=row("failed",code,message);}
  function createSandbox(factory){const adapter=factory();if(!Contracts.validateVideoProviderContract(adapter).valid)throw new Error("contract");return Sandbox.createVideoProviderSandbox({adapter});}
  async function scenario(factory,manifest){const sandbox=createSandbox(factory),timeline=[];try{const status=await sandbox.getStatus({}),capabilities=await sandbox.getCapabilities({}),created=await sandbox.createTask(FIXTURE);if(!created.ok)throw new Error("create");timeline.push(created.data.status+":"+created.data.progress);const queries=[];for(let index=0;index<4;index+=1){const query=await sandbox.queryTask({taskId:created.data.taskId});if(!query.ok)throw new Error("query");queries.push(query.data);timeline.push(query.data.status+":"+query.data.progress);}const listed=await sandbox.listTasks({}),unknown=await sandbox.queryTask({taskId:FIXTURE.unknownTaskId}),artifact=await sandbox.downloadArtifacts({taskId:created.data.taskId}),progress=queries.map((task)=>task.progress),last=queries[queries.length-1],terminal={status:last.status,progress:last.progress};const compatibility=Capabilities.createVideoProviderCapabilityMatrix({capabilities:manifest.capabilities,limits:{}},capabilities.ok?capabilities.data:{});const monotonic=progress.every((value,index)=>Number.isInteger(value)&&value>=0&&value<=100&&(index===0||value>=progress[index-1]));return Object.freeze({status,capabilities,created,queries,listed,unknown,artifact,compatibility,timeline,terminal,monotonic});}finally{await sandbox.dispose();}}
  function report(manifest,profile,entries,compatibility){const matrix=Matrix.createVideoProviderComplianceMatrix(entries),rejected=Matrix.KEYS.some((key)=>matrix[key].status!=="passed"&&matrix[key].status!=="skipped");return Reports.createVideoProviderCertificationReport({manifest,profile,matrix,capabilityCompatibility:compatibility||{},overallStatus:rejected?"rejected":"certified"});}
  async function certifyVideoProviderAdapter(options){const source=options&&typeof options==="object"?options:{},raw=source.manifest,validation=Manifest.validateVideoProviderManifest(raw),manifest=Manifest.createVideoProviderManifest(raw),profile=source.profile==="strict"?"strict":manifest.certificationProfile,entries={};if(!validation.valid){failed(entries,"manifest",validation.code,"适配器声明无效");return report(manifest,profile,entries,{});}entries.manifest=row("passed","MANIFEST_OK","适配器声明通过");if(typeof source.adapterFactory!=="function"){failed(entries,"contract","ADAPTER_FACTORY_REQUIRED","适配器接口不符合要求");return report(manifest,profile,entries,{});}try{const result=await scenario(source.adapterFactory,manifest),task=result.created.data;entries.contract=row("passed","CONTRACT_OK","适配器接口通过");entries.capabilities=row(result.compatibility.valid?"passed":"failed",result.compatibility.valid?"CAPABILITY_OK":"CAPABILITY_REJECTED",result.compatibility.valid?"能力声明通过":"能力声明未通过");entries.lifecycle=Lifecycle.certifyVideoProviderLifecycle({dispose(){}});entries.taskMapping=row(result.created.ok&&result.queries.every((query)=>query.taskId===task.taskId)?"passed":"failed","TASK_MAPPING","任务映射验证");entries.errors=Errors.certifyVideoProviderErrors();const artifactCertification=await Artifacts.certifyVideoProviderArtifactScenarios(()=>createSandbox(source.adapterFactory));entries.artifacts={status:artifactCertification.status,code:artifactCertification.code,message:artifactCertification.message};entries.security=Security.certifyVideoProviderSecurity({manifest,capabilities:result.capabilities.ok?result.capabilities.data:{},status:result.status.ok?result.status.data:{}});entries.cancellation=await Cancellation.certifyVideoProviderCancellation(()=>createSandbox(source.adapterFactory));entries.concurrency=await Concurrency.certifyVideoProviderConcurrency(()=>createSandbox(source.adapterFactory));entries.determinism=await Determinism.certifyVideoProviderDeterminism(profile,()=>scenario(source.adapterFactory,manifest));const completed=result.terminal.status==="COMPLETED"&&result.terminal.progress===100&&result.monotonic&&result.listed.ok&&result.unknown.ok===false;entries.disposal=row(completed?"passed":"failed",completed?"DISPOSAL_OK":"LIFECYCLE_REJECTED",completed?"终态与释放验证通过":"终态与释放验证未通过");return report(manifest,profile,entries,result.compatibility.matrix);}catch(_){failed(entries,"contract","CERTIFICATION_REJECTED","认证过程未完成");return report(manifest,profile,entries,{});}}
  window.WeishanVideoProviderCertification={FIXTURE,certifyVideoProviderAdapter};
})();
