(function(){
  const SENSITIVE = /token|secret|password|authorization|cookie|endpoint|credential|header|session|bearer/i;
  function clone(value){ return JSON.parse(JSON.stringify(value)); }
  function plain(value){ return !!value && Object.prototype.toString.call(value) === "[object Object]"; }
  function text(value, max){ return typeof value === "string" ? value.trim().slice(0, max || 160) : ""; }
  function error(code, field){ return { code:code || "INVALID_REQUEST", message:code === "CONTROLLER_DISPOSED" ? "服务已关闭" : "失败，请重试", retryable:false, field:field || null }; }
  function statusText(status, mode){ return mode === "disabled" ? "视频功能即将上线" : ({ CREATED:"准备中……", PREPARING:"准备中……", QUEUED:"准备中……", GENERATING:"正在生成……", POST_PROCESSING:"处理中……", COMPLETED:"已完成", CANCELLED:"已取消", FAILED:"失败，请重试" })[status] || "视频服务暂不可用"; }
  function task(value){ const data = plain(value) ? value : {}; return { taskId:text(data.taskId,80), title:text(data.title,160), status:text(data.status,32), progress:Number.isFinite(data.progress) ? data.progress : null, resultType:Array.isArray(data.resultTypes) ? text(data.resultTypes[0],32) : "", createdAt:text(data.createdAt,80), updatedAt:text(data.updatedAt,80) }; }
  function createVideoWorkspaceController(options){
    const config = plain(options) ? options : {}; let api = config.videoRuntimeApi || null; let disposed = false; const listeners = new Set();
    let state = { mode:"disabled", available:false, initialized:false, busy:false, statusText:"视频功能即将上线", draft:{ title:"", prompt:"", negativePrompt:"", duration:null, resolution:"", fps:null }, activeTask:null, tasks:[], capabilities:{}, artifacts:[], error:null };
    function snapshot(){ return clone(state); } function publish(){ const value=snapshot(); listeners.forEach((listener)=>{ try { listener(clone(value)); } catch (_) {} }); return value; }
    function guard(){ if (disposed) throw Object.assign(new Error("CONTROLLER_DISPOSED"), { code:"CONTROLLER_DISPOSED" }); }
    function set(patch){ state=Object.assign({},state,patch); return publish(); }
    function safeEnvelope(value){ if (!plain(value) || typeof value.ok !== "boolean") return { ok:false,error:error("INVALID_REQUEST") }; return value.ok ? { ok:true,data:value.data } : { ok:false,error:{ code:text(value.error && value.error.code,48)||"INTERNAL_ERROR", message:text(value.error && value.error.message,160)||"失败，请重试", retryable:value.error && value.error.retryable===true, field:text(value.error && value.error.field,64)||null } }; }
    function normalizeDraft(input){ if (!plain(input) || Object.keys(input).some((key)=>SENSITIVE.test(key))) throw Object.assign(new Error("INVALID_REQUEST"),{code:"INVALID_REQUEST"}); const draft={ title:text(input.title,160), prompt:text(input.prompt,4000), negativePrompt:text(input.negativePrompt,2000), duration:input.duration == null ? null : Number(input.duration), resolution:text(input.resolution,32), fps:input.fps == null ? null : Number(input.fps) }; if (!draft.prompt || (draft.duration != null && (!Number.isFinite(draft.duration)||draft.duration<1)) || (draft.fps != null && (!Number.isFinite(draft.fps)||draft.fps<1))) throw Object.assign(new Error("INVALID_REQUEST"),{code:"INVALID_REQUEST"}); return draft; }
    async function initialize(){ guard(); if (!api) return set({ initialized:true }); const status=safeEnvelope(await api.getStatus({requestId:"workspace-status"})); const capabilities=safeEnvelope(await api.getCapabilities({requestId:"workspace-capabilities"})); const available=!!(status.ok&&status.data&&status.data.available&&capabilities.ok&&capabilities.data&&capabilities.data.available); set({ mode:status.ok&&status.data?text(status.data.mode,32)||"unavailable":"unavailable", available, initialized:true, capabilities:capabilities.ok?clone(capabilities.data):{}, statusText:available?"准备中……":"视频功能即将上线", error:status.ok?null:status.error }); if (available) await refreshTaskList(); return snapshot(); }
    async function createTask(input){ guard(); if (!state.initialized||!state.available||state.busy) throw Object.assign(new Error("RUNTIME_DISABLED"),{code:"RUNTIME_DISABLED"}); const draft=normalizeDraft(input); set({busy:true,error:null,statusText:"正在创建任务……",draft}); try { const result=safeEnvelope(await api.createTask(Object.assign({requestId:"workspace-create"},draft))); if(!result.ok) throw Object.assign(new Error(result.error.code),result.error); const next=task(result.data); set({activeTask:next,tasks:[next].concat(state.tasks.filter((row)=>row.taskId!==next.taskId)),statusText:statusText(next.status,state.mode)}); return snapshot(); } catch (cause) { set({error:error(cause.code),statusText:"失败，请重试"}); throw cause; } finally { set({busy:false}); } }
    async function refreshTask(taskId){ guard(); const result=safeEnvelope(await api.queryTask({requestId:"workspace-query",taskId:text(taskId,80)})); if(!result.ok) { set({error:result.error}); throw Object.assign(new Error(result.error.code),result.error); } const next=task(result.data); set({activeTask:next,tasks:state.tasks.map((row)=>row.taskId===next.taskId?next:row),statusText:statusText(next.status,state.mode)}); if(next.status==="COMPLETED") { const artifacts=safeEnvelope(await api.downloadArtifacts({requestId:"workspace-artifacts",taskId:next.taskId})); if(artifacts.ok) set({artifacts:(Array.isArray(artifacts.data)?artifacts.data:[]).map((item)=>({type:text(item.type,32),name:text(item.name,160),mimeType:text(item.mimeType,80)||null,sizeBytes:Number.isFinite(item.sizeBytes)?item.sizeBytes:null,availability:item.availability===true,downloadMode:text(item.downloadMode,32)||"unavailable",placeholderRef:null}))}); } return snapshot(); }
    async function cancelTask(taskId){ guard(); const current=state.tasks.find((row)=>row.taskId===text(taskId,80)); if(current&&["COMPLETED","FAILED","CANCELLED"].includes(current.status)) throw Object.assign(new Error("TASK_NOT_ACTIVE"),{code:"TASK_NOT_ACTIVE"}); const result=safeEnvelope(await api.cancelTask({requestId:"workspace-cancel",taskId:text(taskId,80)})); if(!result.ok) throw Object.assign(new Error(result.error.code),result.error); const next=task(result.data); set({activeTask:next,tasks:state.tasks.map((row)=>row.taskId===next.taskId?next:row),statusText:statusText(next.status,state.mode)}); return snapshot(); }
    async function refreshTaskList(){ guard(); if(!state.available) return snapshot(); const result=safeEnvelope(await api.listTasks({requestId:"workspace-list",limit:20})); if(!result.ok) { set({error:result.error}); return snapshot(); } const tasks=(Array.isArray(result.data)?result.data:[]).map(task); return set({tasks,activeTask:state.activeTask?tasks.find((row)=>row.taskId===state.activeTask.taskId)||state.activeTask:null}); }
    async function loadCapabilities(){ guard(); return initialize(); } async function loadRuntimeStatus(){ guard(); return initialize(); }
    function getState(){ return snapshot(); } function subscribe(listener){ guard(); if(typeof listener!=="function") throw new Error("invalid_listener"); listeners.add(listener); return ()=>listeners.delete(listener); } function dispose(){ if(disposed)return; listeners.clear(); api=null; state=Object.assign({},state,{activeTask:null,tasks:[],artifacts:[]}); disposed=true; }
    return { initialize,getState,subscribe,createTask,refreshTask,cancelTask,refreshTaskList,loadCapabilities,loadRuntimeStatus,dispose };
  }
  window.WeishanVideoWorkspaceController={createVideoWorkspaceController};
})();
