(function(){
  const STATUSES=["PREPARING","QUEUED","GENERATING","POST_PROCESSING","COMPLETED","FAILED","CANCELLED"];
  function plain(value){ return !!value && Object.prototype.toString.call(value)==="[object Object]"; }
  function text(value,max){ return typeof value==="string"?value.trim().slice(0,max):""; }
  function safeError(value){ const code=text(value&&value.code,48)||"INTERNAL_ERROR"; const messages={INVALID_DRAFT:"请检查创作信息",OPERATION_IN_PROGRESS:"操作正在进行中",RUNTIME_DISABLED:"视频服务暂不可用",VIDEO_SERVICE_UNAVAILABLE:"视频服务暂不可用",TASK_NOT_FOUND:"未找到任务",TASK_NOT_ACTIVE:"任务当前不能取消",ARTIFACT_UNAVAILABLE:"结果暂不可用",CONTROLLER_DISPOSED:"服务已关闭",INTERNAL_ERROR:"失败，请重试"}; return {code,message:messages[code]||"失败，请重试",retryable:["VIDEO_SERVICE_UNAVAILABLE","INTERNAL_ERROR"].includes(code),field:text(value&&value.field,32)||null}; }
  function task(value){ const source=plain(value)?value:{}; const status=STATUSES.includes(text(source.status,32))?text(source.status,32):"FAILED"; return {taskId:text(source.taskId,80),title:text(source.title,80),status,progress:Number.isFinite(source.progress)&&source.progress>=0&&source.progress<=100?source.progress:null,resultType:Array.isArray(source.resultTypes)?text(source.resultTypes[0],32):text(source.resultType,32),createdAt:text(source.createdAt,80),updatedAt:text(source.updatedAt,80),error:source.error?safeError(source.error):null,artifactCount:Number.isInteger(source.artifactCount)&&source.artifactCount>=0?source.artifactCount:0}; }
  function artifact(value){ const source=plain(value)?value:{}; return {type:text(source.type,32),name:text(source.name,160),mimeType:text(source.mimeType,80),sizeBytes:Number.isFinite(source.sizeBytes)&&source.sizeBytes>=0?source.sizeBytes:null,availability:source.availability===true,downloadMode:text(source.downloadMode,32)||"unavailable"}; }
  function envelope(value){ if(!plain(value)||typeof value.ok!=="boolean") return {ok:false,error:safeError({code:"INTERNAL_ERROR"})}; return value.ok?{ok:true,data:value.data}:{ok:false,error:safeError(value.error)}; }
  window.WeishanVideoWorkspaceSanitizers={STATUSES,safeError,sanitizeTask:task,sanitizeArtifact:artifact,sanitizeEnvelope:envelope,isPlainObject:plain};
})();
