(function(){
  const V=window.WeishanVideoWorkspaceValidation;
  const S=window.WeishanVideoWorkspaceSanitizers;
  const R=window.WeishanVideoWorkspaceState;
  const Q=window.WeishanVideoWorkspaceSelectors;
  const E=window.WeishanVideoWorkspaceEvents;
  function plain(value){ return S.isPlainObject(value); }
  function copy(value){ return Object.assign({},value); }
  function failure(code,field){ return S.safeError({code:code||"INTERNAL_ERROR",field}); }
  function createVideoWorkspaceController(options){
    const config=plain(options)?options:{}; let api=config.videoRuntimeApi||null; const eventBus=config.eventBus&&typeof config.eventBus.emit==="function"?config.eventBus:E&&E.createVideoWorkspaceEventBus&&E.createVideoWorkspaceEventBus(); let state=R.createVideoWorkspaceInitialState(); let disposed=false; let sequence=0; const listeners=new Set(); const guards=new Set(); let limits={};
    function snapshot(){ const output=copy(state); output.draft=copy(state.draft); output.validation={valid:state.validation.valid,fields:copy(state.validation.fields),summary:state.validation.summary}; output.operations=copy(state.operations); output.tasks=copy(state.tasks); output.taskOrder=state.taskOrder.slice(); output.filters=copy(state.filters); output.sort=copy(state.sort); output.capabilities=copy(state.capabilities); output.runtimeStatus=copy(state.runtimeStatus); output.artifactsByTaskId=copy(state.artifactsByTaskId); output.error=state.error&&copy(state.error); return output; }
    function publish(){ const value=snapshot(); listeners.forEach((listener)=>{try{listener(snapshot());}catch(_){}}); return value; }
    function dispatch(action){ state=R.reduceVideoWorkspaceState(state,action); const types={INITIALIZE_SUCCEEDED:"WorkspaceInitialized",DRAFT_UPDATED:"DraftChanged",TASK_CREATE_SUCCEEDED:"TaskCreated",TASK_REFRESH_SUCCEEDED:"TaskUpdated",TASK_CANCEL_SUCCEEDED:"TaskCancelled",TASK_SELECTED:"TaskSelected",ARTIFACTS_SUCCEEDED:"ArtifactsLoaded",STATUS_SUCCEEDED:"RuntimeStatusChanged",CAPABILITIES_SUCCEEDED:"CapabilitiesChanged",ERROR_CLEARED:"ErrorCleared",DISPOSED:"WorkspaceDisposed"}; const failed=/_FAILED$/.test(action.type); if(eventBus){ if(types[action.type])eventBus.emit(types[action.type],{taskId:action.task&&action.task.taskId||action.taskId||"",status:action.task&&action.task.status||""}); if(action.type==="DRAFT_UPDATED")eventBus.emit("ValidationChanged",{valid:state.validation.valid}); if(failed)eventBus.emit("ErrorRaised",{code:state.error&&state.error.code||"INTERNAL_ERROR"}); if(action.type==="TASK_REFRESH_SUCCEEDED"&&action.task&&action.task.status==="COMPLETED")eventBus.emit("TaskCompleted",{taskId:action.task.taskId}); if(action.type==="TASK_REFRESH_SUCCEEDED"&&action.task&&action.task.status==="FAILED")eventBus.emit("TaskFailed",{taskId:action.task.taskId}); } return publish(); }
    function active(){ if(disposed) throw Object.assign(new Error("CONTROLLER_DISPOSED"),{code:"CONTROLLER_DISPOSED"}); }
    function requestId(){ sequence+=1; return "video-workspace-request-"+String(sequence).padStart(6,"0"); }
    function run(key,action,fn){ active(); if(guards.has(key)){ const err=Object.assign(new Error("OPERATION_IN_PROGRESS"),{code:"OPERATION_IN_PROGRESS"}); dispatch({type:action+"_FAILED",error:failure(err.code)}); return Promise.reject(err); } guards.add(key); dispatch({type:action+"_STARTED"}); return Promise.resolve().then(fn).catch((cause)=>{ const err=failure(cause&&cause.code); dispatch({type:action+"_FAILED",error:err}); throw Object.assign(new Error(err.code),err); }).finally(()=>guards.delete(key)); }
    function normalizeRuntimeStatus(value){ const source=plain(value)?value:{}; return {available:source.available===true,mode:typeof source.mode==="string"?source.mode:"unavailable",runtimeReady:source.runtimeReady===true,providerHostReady:source.providerHostReady===true,activeTaskCount:Number.isInteger(source.activeTaskCount)&&source.activeTaskCount>=0?source.activeTaskCount:0}; }
    function statusText(taskStatus){ return state.mode==="disabled"?"视频功能即将上线":taskStatus?Q.statusLabel(taskStatus):state.available?"准备中……":"视频功能即将上线"; }
    function validTaskId(taskId){ return typeof taskId==="string"&&taskId.trim().length>0&&taskId.trim().length<=80; }
    function apiCall(name,payload){ if(!api||typeof api[name]!=="function") throw Object.assign(new Error("RUNTIME_DISABLED"),{code:"RUNTIME_DISABLED"}); return api[name](payload); }
    async function initialize(){ return run("initialize","INITIALIZE",async()=>{ if(!api){ dispatch({type:"INITIALIZE_SUCCEEDED",mode:"disabled",available:false,capabilities:{},runtimeStatus:normalizeRuntimeStatus({})}); return snapshot(); } const [statusRaw,capabilitiesRaw]=await Promise.all([apiCall("getStatus",{requestId:requestId()}),apiCall("getCapabilities",{requestId:requestId()})]); const status=S.sanitizeEnvelope(statusRaw), capabilities=S.sanitizeEnvelope(capabilitiesRaw); if(!status.ok||!capabilities.ok) throw Object.assign(new Error(!status.ok?status.error.code:capabilities.error.code),{code:!status.ok?status.error.code:capabilities.error.code}); const runtimeStatus=normalizeRuntimeStatus(status.data); const data=plain(capabilities.data)?capabilities.data:{}; limits=V.mergeLimits(data.limits); const available=runtimeStatus.available&&data.available===true; dispatch({type:"STATUS_SUCCEEDED",runtimeStatus}); dispatch({type:"CAPABILITIES_SUCCEEDED",capabilities:data}); dispatch({type:"INITIALIZE_SUCCEEDED",mode:runtimeStatus.mode,available,capabilities:data,runtimeStatus,statusText:available?"准备中……":"视频功能即将上线"}); if(available) await refreshTaskList(); return snapshot(); }); }
    function updateDraft(patch){ active(); if(!plain(patch)) return dispatch({type:"TASK_CREATE_FAILED",error:failure("INVALID_DRAFT")}); const allowed={}; V.FIELDS.forEach((key)=>{if(Object.prototype.hasOwnProperty.call(patch,key))allowed[key]=patch[key];}); return dispatch({type:"DRAFT_UPDATED",patch:allowed,limits}); }
    function resetDraft(){ active(); return dispatch({type:"DRAFT_RESET"}); }
    async function createTask(draftOverride){ active(); if(!state.initialized||!state.available) return Promise.reject(Object.assign(new Error("RUNTIME_DISABLED"),{code:"RUNTIME_DISABLED"})); const source=draftOverride===undefined?state.draft:draftOverride; const validation=V.validateVideoDraft(source,limits); if(!validation.valid){ dispatch({type:"DRAFT_UPDATED",patch:plain(source)?source:{},limits}); return Promise.reject(Object.assign(new Error("INVALID_DRAFT"),{code:"INVALID_DRAFT"})); } return run("create","TASK_CREATE",async()=>{ const input=validation.normalizedDraft; const result=S.sanitizeEnvelope(await apiCall("createTask",Object.assign({requestId:requestId()},input))); if(!result.ok) throw Object.assign(new Error(result.error.code),{code:result.error.code}); const row=S.sanitizeTask(result.data); if(!row.taskId) throw Object.assign(new Error("INTERNAL_ERROR"),{code:"INTERNAL_ERROR"}); dispatch({type:"TASK_CREATE_SUCCEEDED",task:row,statusText:statusText(row.status)}); return snapshot(); }); }
    async function refreshTask(taskId){ active(); if(!validTaskId(taskId)) return Promise.reject(Object.assign(new Error("TASK_NOT_FOUND"),{code:"TASK_NOT_FOUND"})); const current=state.tasks[taskId]; if(!current) return Promise.reject(Object.assign(new Error("TASK_NOT_FOUND"),{code:"TASK_NOT_FOUND"})); if(Q.terminal(current.status)) return snapshot(); return run("refresh:"+taskId,"TASK_REFRESH",async()=>{ const result=S.sanitizeEnvelope(await apiCall("queryTask",{requestId:requestId(),taskId})); if(!result.ok) throw Object.assign(new Error(result.error.code),{code:result.error.code}); const row=S.sanitizeTask(result.data); if(!row.taskId) throw Object.assign(new Error("INTERNAL_ERROR"),{code:"INTERNAL_ERROR"}); dispatch({type:"TASK_REFRESH_SUCCEEDED",task:row,statusText:statusText(row.status)}); return snapshot(); }); }
    async function cancelTask(taskId){ active(); if(!validTaskId(taskId)||!state.tasks[taskId]) return Promise.reject(Object.assign(new Error("TASK_NOT_FOUND"),{code:"TASK_NOT_FOUND"})); if(Q.terminal(state.tasks[taskId].status)) return Promise.reject(Object.assign(new Error("TASK_NOT_ACTIVE"),{code:"TASK_NOT_ACTIVE"})); return run("cancel:"+taskId,"TASK_CANCEL",async()=>{ const result=S.sanitizeEnvelope(await apiCall("cancelTask",{requestId:requestId(),taskId})); if(!result.ok) throw Object.assign(new Error(result.error.code),{code:result.error.code}); const row=S.sanitizeTask(result.data); if(!row.taskId) throw Object.assign(new Error("INTERNAL_ERROR"),{code:"INTERNAL_ERROR"}); dispatch({type:"TASK_CANCEL_SUCCEEDED",task:row,statusText:statusText(row.status)}); return snapshot(); }); }
    async function refreshTaskList(options){ active(); if(!state.available) return snapshot(); const config=plain(options)?options:{}; const limit=Number.isInteger(config.limit)&&config.limit>=1&&config.limit<=100?config.limit:50; const status=typeof config.status==="string"?config.status:""; return run("list","TASK_LIST",async()=>{ const result=S.sanitizeEnvelope(await apiCall("listTasks",{requestId:requestId(),limit,status})); if(!result.ok) throw Object.assign(new Error(result.error.code),{code:result.error.code}); dispatch({type:"TASK_LIST_SUCCEEDED",tasks:Array.isArray(result.data)?result.data:[]}); return snapshot(); }); }
    async function loadCapabilities(){ active(); return run("capabilities","CAPABILITIES",async()=>{ const result=S.sanitizeEnvelope(await apiCall("getCapabilities",{requestId:requestId()})); if(!result.ok) throw Object.assign(new Error(result.error.code),{code:result.error.code}); const data=plain(result.data)?result.data:{}; limits=V.mergeLimits(data.limits); dispatch({type:"CAPABILITIES_SUCCEEDED",capabilities:data}); dispatch({type:"DRAFT_UPDATED",patch:state.draft,limits}); return snapshot(); }); }
    async function loadRuntimeStatus(){ active(); return run("status","STATUS",async()=>{ const result=S.sanitizeEnvelope(await apiCall("getStatus",{requestId:requestId()})); if(!result.ok) throw Object.assign(new Error(result.error.code),{code:result.error.code}); dispatch({type:"STATUS_SUCCEEDED",runtimeStatus:normalizeRuntimeStatus(result.data)}); return snapshot(); }); }
    async function loadArtifacts(taskId){ active(); if(!validTaskId(taskId)||!state.tasks[taskId]||state.tasks[taskId].status!=="COMPLETED") return Promise.reject(Object.assign(new Error("ARTIFACT_UNAVAILABLE"),{code:"ARTIFACT_UNAVAILABLE"})); return run("artifacts:"+taskId,"ARTIFACTS",async()=>{ const result=S.sanitizeEnvelope(await apiCall("downloadArtifacts",{requestId:requestId(),taskId})); if(!result.ok) throw Object.assign(new Error(result.error.code),{code:result.error.code}); dispatch({type:"ARTIFACTS_SUCCEEDED",taskId,artifacts:Array.isArray(result.data)?result.data:[]}); return snapshot(); }); }
    function selectTask(taskId){ active(); return dispatch({type:"TASK_SELECTED",taskId:validTaskId(taskId)&&state.tasks[taskId]?taskId:""}); }
    function updateFilter(filters){ active(); return dispatch({type:"FILTER_UPDATED",filters:plain(filters)?{status:typeof filters.status==="string"?filters.status:state.filters.status,search:typeof filters.search==="string"?filters.search:state.filters.search}:{}}); }
    function updateSort(sort){ active(); return dispatch({type:"SORT_UPDATED",sort:plain(sort)?{field:typeof sort.field==="string"?sort.field:state.sort.field,direction:sort.direction==="asc"?"asc":"desc"}:{}}); }
    function clearError(){ active(); return dispatch({type:"ERROR_CLEARED"}); }
    function getState(){ return snapshot(); }
    function subscribe(listener){ active(); if(typeof listener!=="function") throw new Error("invalid_listener"); listeners.add(listener); return ()=>listeners.delete(listener); }
    function dispose(){ if(disposed)return; guards.clear(); listeners.clear(); api=null; disposed=true; dispatch({type:"DISPOSED"}); }
    return {initialize,getState,subscribe,updateDraft,resetDraft,createTask,refreshTask,cancelTask,refreshTaskList,loadCapabilities,loadRuntimeStatus,loadArtifacts,selectTask,updateFilter,updateSort,clearError,dispose};
  }
  window.WeishanVideoWorkspaceController={createVideoWorkspaceController};
})();
