(function(){
  const FIELDS=["title","prompt","negativePrompt","duration","resolution","fps","style","camera","motion"];
  const LOCAL_LIMITS={title:80,prompt:4000,negativePrompt:2000,style:80,camera:80,motion:80,duration:{min:1,max:30},resolution:["854x480","1280x720","1920x1080"],fps:[24,25,30]};
  function plain(value){ return !!value && Object.prototype.toString.call(value)==="[object Object]"; }
  function copy(value){ const output={}; FIELDS.forEach((key)=>{ output[key]=value && value[key]; }); return output; }
  function createVideoDraft(){ return {title:"",prompt:"",negativePrompt:"",duration:5,resolution:"1280x720",fps:24,style:"",camera:"",motion:""}; }
  function mergeLimits(provider){ const source=plain(provider)?provider:{}; const result={title:LOCAL_LIMITS.title,prompt:LOCAL_LIMITS.prompt,negativePrompt:LOCAL_LIMITS.negativePrompt,style:LOCAL_LIMITS.style,camera:LOCAL_LIMITS.camera,motion:LOCAL_LIMITS.motion,duration:{min:LOCAL_LIMITS.duration.min,max:LOCAL_LIMITS.duration.max},resolution:LOCAL_LIMITS.resolution.slice(),fps:LOCAL_LIMITS.fps.slice()}; ["title","prompt","negativePrompt","style","camera","motion"].forEach((key)=>{ if(Number.isInteger(source[key])&&source[key]>0) result[key]=Math.min(result[key],source[key]); }); if(plain(source.duration)){ if(Number.isInteger(source.duration.min)) result.duration.min=Math.max(result.duration.min,source.duration.min); if(Number.isInteger(source.duration.max)) result.duration.max=Math.min(result.duration.max,source.duration.max); } if(Array.isArray(source.resolution)) result.resolution=result.resolution.filter((value)=>source.resolution.includes(value)); if(Array.isArray(source.fps)) result.fps=result.fps.filter((value)=>source.fps.includes(value)); return result; }
  function fieldError(fields,key,code,message){ fields[key]={code,message}; }
  function validateVideoDraft(input,providerLimits){ const fields={}; if(!plain(input)) return {valid:false,fields:{draft:{code:"INVALID_DRAFT",message:"请检查创作信息"}},summary:"请检查创作信息",normalizedDraft:createVideoDraft()}; const limits=mergeLimits(providerLimits); const raw=copy(input); const value=createVideoDraft(); ["title","prompt","negativePrompt","style","camera","motion","resolution"].forEach((key)=>{ value[key]=typeof raw[key]==="string"?raw[key].trim():""; }); value.duration=Number(raw.duration); value.fps=Number(raw.fps); if(value.title.length<1||value.title.length>limits.title) fieldError(fields,"title","INVALID_TITLE","请填写 1–"+limits.title+" 个字符的标题"); if(value.prompt.length<1||value.prompt.length>limits.prompt) fieldError(fields,"prompt","INVALID_PROMPT","请填写 1–"+limits.prompt+" 个字符的提示词"); ["negativePrompt","style","camera","motion"].forEach((key)=>{ if(value[key].length>limits[key]) fieldError(fields,key,"INVALID_"+key.toUpperCase(),"内容过长"); }); if(!Number.isInteger(value.duration)||value.duration<limits.duration.min||value.duration>limits.duration.max) fieldError(fields,"duration","INVALID_DURATION","时长需为 "+limits.duration.min+"–"+limits.duration.max+" 秒的整数"); if(!limits.resolution.includes(value.resolution)) fieldError(fields,"resolution","INVALID_RESOLUTION","请选择支持的分辨率"); if(!limits.fps.includes(value.fps)) fieldError(fields,"fps","INVALID_FPS","请选择支持的帧率"); return {valid:Object.keys(fields).length===0,fields,summary:Object.keys(fields).length?"请检查创作信息":"",normalizedDraft:value}; }
  window.WeishanVideoWorkspaceValidation={FIELDS,LOCAL_LIMITS,createVideoDraft,mergeLimits,validateVideoDraft};
})();
