;(function () {
  "use strict";
  const FLIGHT_READONLY_PROVIDER_ADAPTER_V1_VERSION = "2.1.89";
  const ADAPTER_ID = "flight_readonly_provider_adapter_v1";
  function clone(value) { return JSON.parse(JSON.stringify(value)); }
  function metadata() { return clone({ version:FLIGHT_READONLY_PROVIDER_ADAPTER_V1_VERSION, adapterId:ADAPTER_ID, providerCategory:"flight", providerName:"flight_provider", mode:"offline_fixture_only", networkPolicy:"disabled", credentialPolicy:"metadata_only", endpointPolicy:"disabled", resultPolicy:"normalized_draft_only", sandboxResponseSchemaGate:"draft-ready", realProviderResultSchemaValidation:"draft-ready", providerResultSourceLabelGate:"draft-ready", priceIntegrityTaxesFeesGate:"draft-ready", realPriceDisplayGate:"guarded-display-ready", ordinaryResultExposure:"guarded_price_card_only", priceExposure:"guarded_sandbox_test_price", availabilityExposure:"provider_reported_only", bookingUrlPolicy:"disabled", paymentPolicy:"disabled", orderPolicy:"disabled", identityUploadPolicy:"disabled", redacted:true }); }
  function querySummary(query) { const raw = query && typeof query === "object" ? query : {}; const text = String(typeof query === "string" ? query : (raw.text || raw.query || "")); const from = raw.from || raw.origin || (text.includes("上海") ? "上海" : "待补充"); const to = raw.to || raw.destination || (text.includes("成都") ? "成都" : "待补充"); const date = raw.date || (text.includes("7") && text.includes("15") ? "7 月 15 日" : "待补充"); return { from, to, origin:from, destination:to, date, sort:"低价优先" }; }
  function runOfflineFixtureSearch(query) { return clone({ resultType:"flight_provider_offline_fixture_result", providerCategory:"flight", adapterId:ADAPTER_ID, sourceLabel:"offline fixture / no real provider", resultSchemaVersion:"provider_result_schema_v1", querySummary:querySummary(query), candidateSummary:[{ label:"低价优先方案", priceStatus:"real price disabled", availabilityStatus:"availability disabled", bookingUrl:null, notes:["仅为离线结构验证，不代表真实航班"] }], fixtureOnly:true, realProvider:false, realNetwork:false, realPrice:false, availability:false, bookingUrl:null, payment:false, order:false, identityUpload:false, redacted:true }); }
  function normalizeProviderResult(fixtureResult) { const result = Object.assign(runOfflineFixtureSearch({}), fixtureResult || {}); result.resultType = "flight_provider_offline_fixture_result"; result.adapterId = ADAPTER_ID; result.sourceLabel = "offline fixture / no real provider"; result.resultSchemaVersion = "provider_result_schema_v1"; result.fixtureOnly = true; result.realProvider = false; result.realNetwork = false; result.realPrice = false; result.availability = false; result.bookingUrl = null; result.payment = false; result.order = false; result.identityUpload = false; result.redacted = true; return clone(result); }
  function validateResultSchema(result) { const safe = result || {}; if (safe.adapterId !== ADAPTER_ID) throw new Error("adapterId mismatch"); if (safe.sourceLabel !== "offline fixture / no real provider") throw new Error("sourceLabel required"); if (safe.fixtureOnly !== true) throw new Error("fixtureOnly required"); if (safe.realProvider !== false || safe.realNetwork !== false || safe.realPrice !== false || safe.availability !== false) throw new Error("real provider/network/price/availability must stay false"); if (safe.bookingUrl !== null) throw new Error("bookingUrl must stay null"); if (safe.payment !== false || safe.order !== false || safe.identityUpload !== false) throw new Error("write actions must stay false"); return true; }
  function attachSourceLabel(result) { const next = normalizeProviderResult(result); next.sourceLabel = "offline fixture / no real provider"; next.providerId = next.providerId || "flight_provider"; next.providerName = next.providerName || "Flight Provider Sandbox"; next.providerCategory = next.providerCategory || "flight"; next.resultType = next.resultType === "flight_provider_offline_fixture_result" ? "flight_offer" : (next.resultType || "flight_offer"); next.sourceType = next.sourceType || "sandbox_provider"; next.sourceUrlHost = next.sourceUrlHost || "provider-sandbox.invalid"; next.sourceHostDisplayName = next.sourceHostDisplayName || "Provider Sandbox"; next.providerRegion = next.providerRegion || "sandbox"; next.updatedAt = next.updatedAt || "2026-06-20T00:00:00.000Z"; next.resultObservedAt = next.resultObservedAt || next.updatedAt; next.readonlyEvidence = next.readonlyEvidence || "offline fixture / simulated sandbox only"; next.evidenceType = next.evidenceType || "sandbox_fixture"; next.sourceTrustState = next.sourceTrustState || "sandbox_verified"; next.sandboxOnly = true; next.redacted = true; return next; }
  function schemaSafeResult(result) { const next = attachSourceLabel(result || runOfflineFixtureSearch({})); ["bookingUrl", "checkoutUrl", "paymentUrl", "orderUrl", "createOrderUrl", "holdBookingUrl", "passengerIdentity", "passportNumber", "identityNumber", "bankCardNumber", "paymentToken", "rawApiKey", "rawSecret", "rawToken", "rawHeaders", "rawRequest", "rawResponse", "rawProviderPayload", "rawProviderPayloadWithSecrets", "providerAuth", "authorizationHeader", "credentialQueryParams", "payment", "order", "identityUpload"].forEach(function(field){ delete next[field]; }); next.availability = "withheld"; next.price = 0; next.currency = "CNY"; return next; }
  function validateEndpointAllowlist(endpointCandidate) { const api = window.WeishanProviderEndpointAllowlistEnforcement; if (api && typeof api.validateEndpointCandidate === "function") return api.validateEndpointCandidate({ providerId:"flight_provider", endpointCandidate }); return { finalDecision:"blocked", blockedReason:"endpoint_allowlist_missing", networkAttemptCount:0, realEndpointConnectCount:0, redacted:true }; }
  function validateSandboxResponseSchema(response) { const api = window.WeishanProviderSandboxResponseSchemaGate; const next = schemaSafeResult(response || runOfflineFixtureSearch({})); if (api && typeof api.validateSandboxResponseSchema === "function") return api.validateSandboxResponseSchema(next); return { validationDecision:"blocked", blockedReasons:["sandbox response schema gate missing"], ordinaryResultExposure:"disabled", priceExposure:"disabled", availabilityExposure:"disabled", bookingUrlExposure:"disabled", rawPayloadExposure:"forbidden", redacted:true }; }
  function validateRealProviderResultSchema(result) { const api = window.WeishanRealProviderResultSchemaValidation; const next = schemaSafeResult(result || runOfflineFixtureSearch({})); if (api && typeof api.validateRealProviderResultSchema === "function") return api.validateRealProviderResultSchema(next); return { validationDecision:"blocked", resultDisplayDecision:"blocked", blockedReasons:["real provider result schema validation missing"], ordinaryResultExposure:"disabled", priceExposure:"disabled", availabilityExposure:"disabled", bookingUrlExposure:"disabled", rawPayloadExposure:"forbidden", redacted:true }; }
  function attachProviderSourceLabel(result) { const next = attachSourceLabel(result); const api = window.WeishanProviderResultSourceLabelGate; const baseLabel = { providerId:next.providerId, providerName:next.providerName, providerCategory:next.providerCategory, sourceType:next.sourceType, sourceUrlHost:next.sourceUrlHost, sourceHostDisplayName:next.sourceHostDisplayName, providerRegion:next.providerRegion, updatedAt:next.updatedAt, resultObservedAt:next.resultObservedAt, readonlyEvidence:next.readonlyEvidence, evidenceType:next.evidenceType, sourceTrustState:next.sourceTrustState, redacted:true }; const label = api && typeof api.buildValidSandboxSourceLabel === "function" ? api.buildValidSandboxSourceLabel(baseLabel) : baseLabel; next.sourceLabelValidation = api && typeof api.validateProviderResultSourceLabel === "function" ? api.validateProviderResultSourceLabel(label).validationDecision : "blocked"; next.sourceLabelObject = label; return next; }
  function evaluateResultForConsoleOnlyDisplay(result) { const next = attachProviderSourceLabel(result || runOfflineFixtureSearch({})); const sandboxSchema = validateSandboxResponseSchema(next); const realSchema = validateRealProviderResultSchema(next); const displayDecision = sandboxSchema.validationDecision === "pass" && next.sourceLabelValidation === "pass" ? "console-only" : "blocked"; return clone({ adapterId:ADAPTER_ID, sandboxResponseSchemaValidation:sandboxSchema.validationDecision === "pass" ? "pass" : "blocked", realProviderResultSchemaValidation:realSchema.validationDecision || "blocked", sourceLabelValidation:next.sourceLabelValidation === "pass" ? "pass" : "blocked", ordinaryResultExposure:"disabled", priceExposure:"disabled", availabilityExposure:"disabled", bookingUrlExposure:"disabled", rawPayloadExposure:"forbidden", resultDisplayDecision:displayDecision, resultDisplayReason:displayDecision === "console-only" ? "validated sandbox-shaped result remains withheld from ordinary result surface" : "schema or source label blocked", redacted:true }); }
  function buildSandboxVerifiedPriceCandidate(overrides) {
    const priceApi = window.WeishanPriceIntegrityTaxesFeesGateV1;
    const base = priceApi && typeof priceApi.buildSandboxVerifiedPriceCandidate === "function"
      ? priceApi.buildSandboxVerifiedPriceCandidate()
      : { providerId:"flight_provider", providerName:"Flight Provider Sandbox", providerCategory:"flight", sourceUrlHost:"provider-sandbox.invalid", sourceHostDisplayName:"Provider Sandbox", sourceType:"sandbox_provider", sourceTrustState:"sandbox_verified", resultSchemaValidationDecision:"pass", sourceLabelValidationDecision:"pass", currency:"CNY", baseFare:860, taxes:120, fees:30, total:1010, taxIncluded:true, feesIncluded:true, shippingIncluded:"not_applicable", inventoryStatus:"provider_reported", inventoryReliability:"provider_reported", priceObservedAt:"2026-06-20T00:00:00.000Z", updatedAt:"2026-06-20T00:00:00.000Z", readonlyEvidence:"sandbox/test provider response shape validation only", quoteType:"sandbox_verified_price", priceDisplayMode:"guarded_price_card", finalPageDisclaimer:"最终价格、税费、库存/余票、退改签和行李规则，以平台页面为准。", redacted:true };
    return clone(Object.assign({}, base, overrides || {}));
  }
  function validatePriceIntegrity(candidate) {
    const api = window.WeishanPriceIntegrityTaxesFeesGateV1;
    const next = candidate || buildSandboxVerifiedPriceCandidate();
    return api && typeof api.validatePriceIntegrityTaxesFees === "function"
      ? api.validatePriceIntegrityTaxesFees(next)
      : { gateName:"price_integrity_taxes_fees_gate_v1", validationDecision:"blocked", displayEligibility:"blocked", blockedReasons:["price integrity gate missing"], redacted:true };
  }
  function evaluateRealPriceDisplay(candidate, surface) {
    const displayApi = window.WeishanRealPriceDisplayGate;
    const next = candidate || buildSandboxVerifiedPriceCandidate();
    const integrity = validatePriceIntegrity(next);
    return displayApi && typeof displayApi.evaluateRealPriceDisplay === "function"
      ? displayApi.evaluateRealPriceDisplay({ candidate:next, normalizedProviderResult:next, priceIntegrityValidation:integrity, displaySurface:surface || "ordinary_result_card" })
      : { gateName:"real_price_display_gate", displayDecision:"blocked", displaySurface:surface || "ordinary_result_card", blockedReasons:["real price display gate missing"], redacted:true };
  }
  function buildGuardedPriceCard(candidate) {
    const displayApi = window.WeishanRealPriceDisplayGate;
    const next = candidate || buildSandboxVerifiedPriceCandidate();
    const decision = evaluateRealPriceDisplay(next, "ordinary_result_card");
    return displayApi && typeof displayApi.buildGuardedPriceCard === "function"
      ? displayApi.buildGuardedPriceCard(next, decision)
      : { visible:false, title:"价格结果已阻断", reasons:["real price display gate missing"], redacted:true };
  }
  function prepareSandboxDryRun(dryRunGateState) { const gateApi = window.WeishanProviderSandboxRealKeyDryRunGate; const state = dryRunGateState && typeof dryRunGateState === "object" ? dryRunGateState : {}; const next = Object.assign({ providerCategory:"flight", providerId:"flight_provider", adapterId:ADAPTER_ID, endpointCandidate:"https://provider-sandbox.invalid/sandbox/dry-run" }, state); return gateApi && typeof gateApi.evaluateSandboxRealKeyDryRunGate === "function" ? gateApi.evaluateSandboxRealKeyDryRunGate(next) : { status:"sandbox real-key dry-run gate only", dryRunDecision:"blocked", realNetwork:false, networkAttemptCount:0, redacted:true }; }
  function runSandboxDryRunWithSimulatedTransport(dryRunGateState) { const gateApi = window.WeishanProviderSandboxRealKeyDryRunGate; const state = Object.assign({ providerCategory:"flight", providerId:"flight_provider", adapterId:ADAPTER_ID, endpointCandidate:"https://provider-sandbox.invalid/sandbox/dry-run", credentialScopeConsent:true, sandboxKey:"WEISHAN_SANDBOX_TEST_KEY_000000" }, dryRunGateState || {}); const result = gateApi && typeof gateApi.runSandboxDryRunGateWithSimulatedTransport === "function" ? gateApi.runSandboxDryRunGateWithSimulatedTransport(state) : { dryRunDecision:"blocked", dryRunTransport:"simulated", realNetwork:false, networkAttemptCount:0, realEndpointConnectCount:0, redacted:true }; const evaluation = evaluateResultForConsoleOnlyDisplay(runOfflineFixtureSearch({ text:"7 月 15 日上海到成都最便宜的机票" })); const priceCandidate = buildSandboxVerifiedPriceCandidate(); const priceIntegrityValidation = validatePriceIntegrity(priceCandidate); const realPriceDisplayDecision = evaluateRealPriceDisplay(priceCandidate, "sandbox_console"); const guardedPriceCard = buildGuardedPriceCard(priceCandidate); return Object.assign(result, { adapterId:ADAPTER_ID, schemaValidation:evaluation.sandboxResponseSchemaValidation || result.schemaValidation || "pass", sandboxResponseSchemaValidation:evaluation.sandboxResponseSchemaValidation, realProviderResultSchemaValidation:evaluation.realProviderResultSchemaValidation, sourceLabelValidation:evaluation.sourceLabelValidation, resultDisplayDecision:evaluation.resultDisplayDecision, resultDisplayReason:evaluation.resultDisplayReason, resultExposure:result.resultExposure || "console-only", ordinaryResultExposure:"guarded_price_card_only", priceExposure:"guarded_sandbox_test_price", availabilityExposure:"provider_reported_only", bookingUrlExposure:"disabled", priceIntegrityValidation, realPriceDisplayDecision, guardedPriceCard, redacted:true }); }
  function runDryRun(query) { const result = attachSourceLabel(runOfflineFixtureSearch(query)); validateResultSchema(result); return result; }
  function buildAuditDraft(fixtureRunCount) { return { eventType:"READ_ONLY_PROVIDER_ADAPTER_V1_DRAFT", adapterId:ADAPTER_ID, providerCategory:"flight", mode:"offline_fixture_only", fixtureRunCount:fixtureRunCount || 0, realProviderCallCount:0, realProviderResultCount:0, networkAttemptCount:0, realCredentialReadCount:0, realApiKeyReadCount:0, realEndpointConnectCount:0, realPriceDisplayedCount:0, realPriceReturnCount:0, bookingUrlDisplayedCount:0, bookingUrlReturnCount:0, paymentAttemptCount:0, orderAttemptCount:0, identityUploadAttemptCount:0, redacted:true }; }
  function assertFlightReadOnlyProviderAdapterV1Safe(result) { validateResultSchema(result || runDryRun({ text:"7 月 15 日上海到成都最便宜的机票" })); const audit = buildAuditDraft(1); ["realProviderCallCount", "realProviderResultCount", "networkAttemptCount", "realCredentialReadCount", "realApiKeyReadCount", "realEndpointConnectCount", "realPriceDisplayedCount", "realPriceReturnCount", "bookingUrlDisplayedCount", "bookingUrlReturnCount", "paymentAttemptCount", "orderAttemptCount", "identityUploadAttemptCount"].forEach(function(key){ if (audit[key] !== 0) throw new Error(key + " must stay zero"); }); return true; }
  const blocked = function(methodName){ return function(){ return { methodName, status:"blocked", blockedReason:"real provider adapter action disabled", redacted:true }; }; };
  window.WeishanFlightReadOnlyProviderAdapterV1 = { FLIGHT_READONLY_PROVIDER_ADAPTER_V1_VERSION, ADAPTER_ID, getAdapterMetadata:metadata, validateCredentialScope:function(){ return { status:"draft-ready", finalDecision:"no-go", realCredentialRead:false, redacted:true }; }, validateReadinessGates:function(){ return { status:"draft-ready", finalDecision:"no-go", redacted:true }; }, runOfflineFixtureSearch, normalizeProviderResult, validateResultSchema, attachSourceLabel, validateEndpointAllowlist, validateSandboxResponseSchema, validateRealProviderResultSchema, attachProviderSourceLabel, evaluateResultForConsoleOnlyDisplay, buildSandboxVerifiedPriceCandidate, validatePriceIntegrity, evaluateRealPriceDisplay, buildGuardedPriceCard, prepareSandboxDryRun, runSandboxDryRunWithSimulatedTransport, runDryRun, buildAuditDraft, assertFlightReadOnlyProviderAdapterV1Safe, connect:blocked("connect"), fetch:blocked("fetch"), request:blocked("request"), post:blocked("post"), createOrder:blocked("createOrder"), pay:blocked("pay"), checkout:blocked("checkout"), uploadIdentity:blocked("uploadIdentity"), revealCredential:blocked("revealCredential"), exportCredential:blocked("exportCredential"), testEndpoint:blocked("testEndpoint") };
})();
