;(function () {
  "use strict";
  const FLIGHT_READONLY_PROVIDER_ADAPTER_V1_VERSION = "2.1.26";
  const ADAPTER_ID = "flight_readonly_provider_adapter_v1";
  function clone(value) { return JSON.parse(JSON.stringify(value)); }
  function metadata() { return clone({ version:FLIGHT_READONLY_PROVIDER_ADAPTER_V1_VERSION, adapterId:ADAPTER_ID, providerCategory:"flight", providerName:"flight_provider", mode:"offline_fixture_only", networkPolicy:"disabled", credentialPolicy:"metadata_only", endpointPolicy:"disabled", resultPolicy:"normalized_draft_only", bookingUrlPolicy:"disabled", paymentPolicy:"disabled", orderPolicy:"disabled", identityUploadPolicy:"disabled", redacted:true }); }
  function querySummary(query) { const raw = query && typeof query === "object" ? query : {}; const text = String(typeof query === "string" ? query : (raw.text || raw.query || "")); const from = raw.from || raw.origin || (text.includes("上海") ? "上海" : "待补充"); const to = raw.to || raw.destination || (text.includes("成都") ? "成都" : "待补充"); const date = raw.date || (text.includes("7") && text.includes("15") ? "7 月 15 日" : "待补充"); return { from, to, origin:from, destination:to, date, sort:"低价优先" }; }
  function runOfflineFixtureSearch(query) { return clone({ resultType:"flight_provider_offline_fixture_result", providerCategory:"flight", adapterId:ADAPTER_ID, sourceLabel:"offline fixture / no real provider", resultSchemaVersion:"provider_result_schema_v1", querySummary:querySummary(query), candidateSummary:[{ label:"低价优先方案", priceStatus:"real price disabled", availabilityStatus:"availability disabled", bookingUrl:null, notes:["仅为离线结构验证，不代表真实航班"] }], fixtureOnly:true, realProvider:false, realNetwork:false, realPrice:false, availability:false, bookingUrl:null, payment:false, order:false, identityUpload:false, redacted:true }); }
  function normalizeProviderResult(fixtureResult) { const result = Object.assign(runOfflineFixtureSearch({}), fixtureResult || {}); result.resultType = "flight_provider_offline_fixture_result"; result.adapterId = ADAPTER_ID; result.sourceLabel = "offline fixture / no real provider"; result.resultSchemaVersion = "provider_result_schema_v1"; result.fixtureOnly = true; result.realProvider = false; result.realNetwork = false; result.realPrice = false; result.availability = false; result.bookingUrl = null; result.payment = false; result.order = false; result.identityUpload = false; result.redacted = true; return clone(result); }
  function validateResultSchema(result) { const safe = result || {}; if (safe.adapterId !== ADAPTER_ID) throw new Error("adapterId mismatch"); if (safe.sourceLabel !== "offline fixture / no real provider") throw new Error("sourceLabel required"); if (safe.fixtureOnly !== true) throw new Error("fixtureOnly required"); if (safe.realProvider !== false || safe.realNetwork !== false || safe.realPrice !== false || safe.availability !== false) throw new Error("real provider/network/price/availability must stay false"); if (safe.bookingUrl !== null) throw new Error("bookingUrl must stay null"); if (safe.payment !== false || safe.order !== false || safe.identityUpload !== false) throw new Error("write actions must stay false"); return true; }
  function attachSourceLabel(result) { const next = normalizeProviderResult(result); next.sourceLabel = "offline fixture / no real provider"; return next; }
  function runDryRun(query) { const result = attachSourceLabel(runOfflineFixtureSearch(query)); validateResultSchema(result); return result; }
  function buildAuditDraft(fixtureRunCount) { return { eventType:"READ_ONLY_PROVIDER_ADAPTER_V1_DRAFT", adapterId:ADAPTER_ID, providerCategory:"flight", mode:"offline_fixture_only", fixtureRunCount:fixtureRunCount || 0, realProviderCallCount:0, realProviderResultCount:0, networkAttemptCount:0, realCredentialReadCount:0, realApiKeyReadCount:0, realEndpointConnectCount:0, realPriceDisplayedCount:0, realPriceReturnCount:0, bookingUrlDisplayedCount:0, bookingUrlReturnCount:0, paymentAttemptCount:0, orderAttemptCount:0, identityUploadAttemptCount:0, redacted:true }; }
  function assertFlightReadOnlyProviderAdapterV1Safe(result) { validateResultSchema(result || runDryRun({ text:"7 月 15 日上海到成都最便宜的机票" })); const audit = buildAuditDraft(1); ["realProviderCallCount", "realProviderResultCount", "networkAttemptCount", "realCredentialReadCount", "realApiKeyReadCount", "realEndpointConnectCount", "realPriceDisplayedCount", "realPriceReturnCount", "bookingUrlDisplayedCount", "bookingUrlReturnCount", "paymentAttemptCount", "orderAttemptCount", "identityUploadAttemptCount"].forEach(function(key){ if (audit[key] !== 0) throw new Error(key + " must stay zero"); }); return true; }
  const blocked = function(methodName){ return function(){ return { methodName, status:"blocked", blockedReason:"real provider adapter action disabled", redacted:true }; }; };
  window.WeishanFlightReadOnlyProviderAdapterV1 = { FLIGHT_READONLY_PROVIDER_ADAPTER_V1_VERSION, ADAPTER_ID, getAdapterMetadata:metadata, validateCredentialScope:function(){ return { status:"draft-ready", finalDecision:"no-go", realCredentialRead:false, redacted:true }; }, validateReadinessGates:function(){ return { status:"draft-ready", finalDecision:"no-go", redacted:true }; }, runOfflineFixtureSearch, normalizeProviderResult, validateResultSchema, attachSourceLabel, runDryRun, buildAuditDraft, assertFlightReadOnlyProviderAdapterV1Safe, connect:blocked("connect"), fetch:blocked("fetch"), request:blocked("request"), post:blocked("post"), createOrder:blocked("createOrder"), pay:blocked("pay"), checkout:blocked("checkout"), uploadIdentity:blocked("uploadIdentity"), revealCredential:blocked("revealCredential"), exportCredential:blocked("exportCredential"), testEndpoint:blocked("testEndpoint") };
})();
