"use strict";
const A=require("assert");
const F=require("fs");
const P=require("path");
const M=require("vm");
const w={};
const c=M.createContext({window:w,Object,Array,Set,Number,String,RegExp,JSON,Error});
const root=P.join(__dirname,"..");
["intentTaxonomy.js","intentValidation.js"].forEach(n=>M.runInContext(F.readFileSync(P.join(root,"intent",n),"utf8"),c));
["conversationAuthorityDefinition.js","conversationAuthorityEvidence.js","conversationAuthorityMatrix.js"].forEach(n=>M.runInContext(F.readFileSync(P.join(__dirname,n),"utf8"),c));
const definition=w.WeishanConversationAuthorityDefinition.define();
const evidence=w.WeishanConversationAuthorityEvidence.collect();
const matrix=w.WeishanConversationAuthorityMatrix.build(definition,evidence);
const command=F.readFileSync(P.join(root,"..","modules","command","commandApi.js"),"utf8");
const home=F.readFileSync(P.join(root,"..","routes","HomePage.js"),"utf8");
const history=F.readFileSync(P.join(root,"..","modules","history","historyApi.js"),"utf8");
const tests=[];
const test=(name,fn)=>tests.push([name,fn]);
test("partial authority",()=>A.equal(definition.outcome,"CONVERSATION_AUTHORITY_PARTIALLY_FOUND"));
test("human pending",()=>A.equal(evidence.humanReviewStatus,"PENDING"));
test("not ready",()=>A.equal(matrix.readyForHumanReview,false));
test("closed",()=>A.equal(matrix.executionGate,"CLOSED"));
test("no authority",()=>A.equal(matrix.authorizesExecution,false));
test("home submit",()=>A.ok(home.includes("function submit()")));
test("classifier",()=>A.ok(command.includes("function classify(text)")));
test("enqueue",()=>A.ok(command.includes("function enqueue(text, options)")));
test("process",()=>A.ok(command.includes("async function processQueue()")));
test("run",()=>A.ok(command.includes("async function runTask(task)")));
test("gateway",()=>A.ok(command.includes("answerChatWithGateway")));
test("display",()=>A.ok(home.includes("function displayAnswer(task)")));
test("history writer",()=>A.ok(history.includes("function record(type, payload)")));
test("history clear",()=>A.ok(history.includes("function clearPersonal()")));
test("memory",()=>A.ok(command.includes("async function saveMemory(text)")));
test("workspace",()=>A.ok(command.includes("attachSubPlanCompletionWorkspace")));
test("commerce",()=>A.ok(command.includes("function commerceAgentAnswer")));
test("failure",()=>A.ok(command.includes('transitionTask(t, "failed"')));
definition.nodes.forEach(node=>{for(let index=0;index<10;index++)test(node.node+" class "+index,()=>A.ok(w.WeishanConversationAuthorityDefinition.NODE_CLASSES.includes(node.classification)));});
evidence.items.forEach(item=>["area","status","facts"].forEach(key=>test(item.area+" "+key,()=>A.ok(Object.prototype.hasOwnProperty.call(item,key)))));
test("three proven",()=>A.equal(matrix.counts.proven,4));
test("four partial",()=>A.equal(matrix.counts.partiallyProven,4));
test("two not proven",()=>A.equal(matrix.counts.notProven,2));
test("history disclosed",()=>A.equal(evidence.persistence.historyMayPersist,true));
test("answer readonly",()=>A.equal(evidence.persistence.answerIsReadOnly,true));
test("history clear scope",()=>A.equal(evidence.persistence.canDelete,"CLEAR_ALL_PERSONAL_HISTORY_ONLY"));
test("no disable proof",()=>A.equal(evidence.persistence.canDisable,"UNKNOWN"));
for(let index=0;index<10;index++)test("deterministic "+index,()=>{
  const first=JSON.parse(JSON.stringify(w.WeishanConversationAuthorityMatrix.build(definition,evidence)));
  const second=JSON.parse(JSON.stringify(matrix));
  A.deepEqual(first,second);
});
tests.forEach(([,fn])=>fn());
if(tests.length<140)throw new Error("insufficient tests");
console.log("CONVERSATION_AUTHORITY_TESTS PASS "+tests.length);

