(function () {
  "use strict";

  const Shared=window.WeishanCommerceShadowContractValidation,Types=window.WeishanRecommendationTypes;
  function fail(code){Shared.fail(code);}function text(value){return Shared.text(value);}function exact(value,keys){return Shared.exact(value,keys);}function enumValue(values,value){return values.indexOf(value)>=0;}function array(value){return Array.isArray(value);}
  function normalizedPriceReference(input){const value=Shared.safeClone(input),keys=Types.INTERFACES.normalizedPriceReference.required;if(!exact(value,keys)||!keys.every(function(key){return text(value[key]);}))fail("invalid_normalized_price_reference");return Shared.freeze(value);}
  function factor(input){const value=Shared.safeClone(input),keys=Types.INTERFACES.recommendationFactor.required;if(!exact(value,keys)||!enumValue(Types.ENUMS.FACTOR_TYPE,value.factorType)||!enumValue(Types.ENUMS.VALUE_STATE,value.valueState)||!enumValue(Types.ENUMS.EVIDENCE_TYPE,value.evidenceType)||!enumValue(Types.ENUMS.CONFIDENCE,value.confidence)||!text(value.explanation)||!array(value.limitations))fail("invalid_recommendation_factor");return Shared.freeze(value);}
  function risk(input){const value=Shared.safeClone(input),keys=Types.INTERFACES.recommendationRisk.required;if(!exact(value,keys)||!text(value.riskType)||!enumValue(Types.ENUMS.VALUE_STATE,value.valueState)||!enumValue(Types.ENUMS.EVIDENCE_TYPE,value.evidenceType)||!enumValue(Types.ENUMS.CONFIDENCE,value.confidence)||!text(value.explanation)||!array(value.limitations))fail("invalid_recommendation_risk");return Shared.freeze(value);}
  function explanationReference(input){const value=Shared.safeClone(input),keys=Types.INTERFACES.recommendationExplanationReference.required;if(!exact(value,keys)||!text(value.referenceId)||!enumValue(Types.ENUMS.EVIDENCE_TYPE,value.evidenceType)||!array(value.limitations))fail("invalid_recommendation_explanation_reference");return Shared.freeze(value);}
  function candidate(input){const value=Shared.safeClone(input),keys=Types.INTERFACES.recommendationCandidate.required;if(!exact(value,keys)||!text(value.candidateId)||!text(value.sourceReference)||!text(value.providerReference)||!enumValue(Types.ENUMS.AVAILABILITY_STATE,value.availabilityState)||!array(value.advantages)||!array(value.disadvantages)||!array(value.risks)||!enumValue(Types.ENUMS.CONFIDENCE,value.confidence)||!enumValue(Types.ENUMS.EVIDENCE_TYPE,value.evidenceState)||!array(value.limitations)||!enumValue(Types.ENUMS.SELECTION_STATUS,value.selectionStatus))fail("invalid_recommendation_candidate");value.normalizedPriceReference=normalizedPriceReference(value.normalizedPriceReference);value.risks=value.risks.map(risk);return Shared.freeze(value);}
  function request(input){const value=Shared.safeClone(input),keys=Types.INTERFACES.recommendationRequest.required;if(!exact(value,keys)||value.schemaVersion!==Types.CONTRACT_VERSION||!text(value.requestId)||!enumValue(Types.ENUMS.DOMAIN,value.domain)||!text(value.marketContextId)||!array(value.normalizedPrices)||!array(value.userPreferences)||!array(value.constraints)||!enumValue(Types.ENUMS.COMPARISON_MODE,value.comparisonMode)||!enumValue(Types.ENUMS.REQUESTED_GOAL,value.requestedGoal)||!array(value.limitations))fail("invalid_recommendation_request");value.normalizedPrices=value.normalizedPrices.map(normalizedPriceReference);return Shared.freeze(value);}
  function dependencies(input){if(!input||typeof input.clock!=="function"||typeof input.idGenerator!=="function")fail("invalid_recommendation_dependencies");return input;}
  function result(input){const value=Shared.safeClone(input),keys=Types.INTERFACES.recommendationResult.required;if(!exact(value,keys)||value.schemaVersion!==Types.CONTRACT_VERSION||!text(value.resultId)||!text(value.requestId)||!array(value.candidates)||!array(value.factors)||!array(value.risks)||!array(value.explanationReferences)||!array(value.limitations)||!enumValue(Types.ENUMS.RESULT_STATUS,value.status)||value.userDecisionRequired!==true||value.executed!==false||value.productionAffected!==false||!text(value.createdAt))fail("invalid_recommendation_result");value.candidates=value.candidates.map(candidate);value.factors=value.factors.map(factor);value.risks=value.risks.map(risk);value.explanationReferences=value.explanationReferences.map(explanationReference);return Shared.freeze(value);}
  function compatibility(version){return Shared.compatibility(version,Types.CONTRACT_VERSION);}
  window.WeishanRecommendationValidation=Object.freeze({fail,text,exact,normalizedPriceReference,factor,risk,explanationReference,candidate,request,dependencies,result,compatibility,freeze:Shared.freeze,safeClone:Shared.safeClone});
})();
