(function(){
  const T=window.WeishanIntentTaxonomy,V=window.WeishanIntentValidation,E=window.WeishanIntentEnvelope,R=window.WeishanIntentRules;
  const INPUT_FIELDS=["rawInput","source","requestId","createdAt","capabilities","context"],CAPABILITY_FIELDS=["capabilityId","status","reasonCode","supportedIntents","requiresPermission","requiresExecutionConfirmation","enabled"];
  const own=(value,fields,code)=>{if(!value||typeof value!=="object"||Object.keys(value).some(key=>!fields.includes(key)))V.fail(code);return value;};
  const textHas=(text,expression)=>R.has(text,expression);
  function snapshot(value){if(value===undefined)return Object.freeze([]);const items=V.json(value,true);if(!Array.isArray(items))V.fail("invalid_capability_snapshot");return Object.freeze(items.map(item=>{own(item,CAPABILITY_FIELDS,"invalid_capability_snapshot");if(typeof item.capabilityId!=="string"||!item.capabilityId)V.fail("invalid_capability_snapshot");if(item.enabled!==undefined&&typeof item.enabled!=="boolean")V.fail("invalid_capability_snapshot");if(item.status!==undefined&&!T.AVAILABILITY_STATUS.includes(item.status))V.fail("invalid_capability_snapshot");if(item.reasonCode!==undefined&&!T.AVAILABILITY_REASON_CODES.includes(item.reasonCode))V.fail("invalid_capability_snapshot");if(item.supportedIntents!==undefined&&(!Array.isArray(item.supportedIntents)||item.supportedIntents.some(intent=>!T.INTENTS.includes(intent))))V.fail("invalid_capability_snapshot");if(item.requiresPermission!==undefined&&typeof item.requiresPermission!=="boolean")V.fail("invalid_capability_snapshot");if(item.requiresExecutionConfirmation!==undefined&&typeof item.requiresExecutionConfirmation!=="boolean")V.fail("invalid_capability_snapshot");return V.freeze(item)}));}
  function availability(capabilities,capabilityId){const item=capabilities.find(candidate=>candidate.capabilityId===capabilityId);if(!item)return {status:"UNKNOWN",capabilityId:capabilityId||"",reasonCode:"UNKNOWN",requiresPermission:false};let status=item.enabled===false?"DISABLED":(item.status||"UNKNOWN"),reason=item.enabled===false?"DISABLED_BY_DEFAULT":(item.reasonCode||(status==="AVAILABLE"?"NONE":"UNKNOWN"));return {status,capabilityId:item.capabilityId,reasonCode:reason,requiresPermission:item.requiresPermission===true};}
  function classifyIntent(input,options){const x=V.json(input,true);own(x,INPUT_FIELDS,"invalid_classifier_input");if(typeof x.rawInput!=="string"||!T.INTENT_SOURCES.includes(x.source))V.fail("invalid_classifier_input");if(x.context!==undefined)V.json(x.context,true);const normalized=V.norm(x.rawInput),matches=R.match(normalized),capabilities=snapshot(x.capabilities),empty=!normalized;let selected=empty?[]:matches.slice(),clarification=[],reasons=[],confirmation=[],workspace=textHas(normalized,/保存|创建.*工作区|create.*workspace/i),external=textHas(normalized,/打开.*网站|跳转|open.*(site|website)|external navigation/i),purchase=textHas(normalized,/买|购买|purchase|buy/i),payment=textHas(normalized,/支付|付款|payment/i),checkout=textHas(normalized,/结账|checkout/i),order=textHas(normalized,/下单|订单|order/i);
    if(!selected.length){selected=[{intent:"UNKNOWN",destination:"NONE",capability:"",confirmation:""}];clarification=["请说明希望解决的问题。"] ;reasons=["INSUFFICIENT_INPUT"]}
    const primary=selected[0],primaryAvailability=availability(capabilities,primary.capability);
    if(primary.intent==="COMMERCE"&&purchase&&!textHas(normalized,/iphone|手机|电脑|酒店|机票|商品|product|hotel|flight/i)){clarification=["你想比较或购买什么？"];if(!reasons.includes("MISSING_REQUIRED_CONTEXT"))reasons.push("MISSING_REQUIRED_CONTEXT")}
    if(primary.intent==="PLUGIN"&&primaryAvailability.status!=="AVAILABLE"){if(!reasons.includes("UNSUPPORTED_CAPABILITY"))reasons.push("UNSUPPORTED_CAPABILITY")}
    if(selected.length>1&&!reasons.includes("CONFLICTING_SIGNALS"))reasons.push("CONFLICTING_SIGNALS");
    if(selected.some(item=>item.intent==="AUTOMATION"))confirmation.push("AUTOMATION");
    if(selected.some(item=>item.intent==="PLUGIN"))confirmation.push("EXECUTION");
    if(purchase)confirmation.push("PURCHASE");if(payment)confirmation.push("PAYMENT");if(checkout)confirmation.push("CHECKOUT");if(order)confirmation.push("ORDER");if(external)confirmation.push("EXTERNAL_NAVIGATION");if(workspace)confirmation.push("PERSISTENT_STATE");
    confirmation=[...new Set(confirmation)];const needsConfirmation=confirmation.length>0,ambiguous=reasons.length>0||selected.length>1,competing=selected.map(item=>item.intent),candidateAvailability=primaryAvailability;
    const candidates=selected.map((item,index)=>{return {intent:item.intent,confidenceCategory:ambiguous?(index===0?"MEDIUM":"LOW"):"HIGH",evidence:["input:"+item.intent.toLowerCase()+"_signal"],suggestedCapability:item.capability,requiresClarification:clarification.length>0,requiresUserConfirmation:item.intent==="PLUGIN"||item.intent==="AUTOMATION"||(item.intent==="COMMERCE"&&needsConfirmation)||(item.intent==="DECISION"&&workspace)};});
    const createdAt=x.createdAt===undefined?(options&&typeof options.clock==="function"?options.clock():"1970-01-01T00:00:00.000Z"):x.createdAt;
    return E.createIntentEnvelope({schemaVersion:T.INTENT_SCHEMA_VERSION,requestId:x.requestId||"shadow-request",source:x.source,rawInput:x.rawInput,normalizedInput:normalized,candidates,ambiguity:{isAmbiguous:ambiguous,reasonCodes:reasons.length?reasons:[],competingIntents:ambiguous?competing:[]},clarification:{required:clarification.length>0,questions:clarification.slice(0,3),missingFields:clarification.length?["required_context"]:[]},suggestedDestination:primary.destination,requiresUserConfirmation:needsConfirmation,confirmationReasons:confirmation,capabilityAvailability:{status:candidateAvailability.status,capabilityId:candidateAvailability.capabilityId,reasonCode:candidateAvailability.reasonCode},safety:{defaultDeny:true,externalEffectsAllowed:false,containsSensitiveInference:false,requiresPermissionReview:candidateAvailability.requiresPermission===true},metadata:{},createdAt},{clock:options&&options.clock});}
  window.WeishanIntentClassifier=Object.freeze({classifyIntent});
})();
