(function(){
  const T=window.WeishanIntentTaxonomy,V=window.WeishanIntentValidation,E=window.WeishanIntentEnvelope,C=window.WeishanIntentClassifier;
  const LABEL_FIELDS=["requestId","primaryIntent","suggestedDestination","requiresUserConfirmation","isAmbiguous","capabilityStatus"];
  function optionsOf(value){if(value===undefined)return {};if(!value||Object.prototype.toString.call(value)!=="[object Object]"||Object.getOwnPropertySymbols(value).length)V.fail("invalid_observer_options");const descriptors=Object.getOwnPropertyDescriptors(value),allowed=["authoritative","clock","failureHandler"];Object.keys(descriptors).forEach(key=>{if(!allowed.includes(key)||descriptors[key].get||descriptors[key].set)V.fail("invalid_observer_options")});return value;}
  function label(value){if(!value)return null;const copy=V.json(value,true);if(E.isIntentEnvelope(copy)){return {requestId:copy.requestId,primaryIntent:copy.candidates[0].intent,suggestedDestination:copy.suggestedDestination,requiresUserConfirmation:copy.requiresUserConfirmation,isAmbiguous:copy.ambiguity.isAmbiguous,capabilityStatus:copy.capabilityAvailability.status};}if(Object.keys(copy).some(key=>!LABEL_FIELDS.includes(key))||typeof copy.primaryIntent!=="string"||!T.INTENTS.includes(copy.primaryIntent)||typeof copy.suggestedDestination!=="string"||!T.DESTINATIONS.includes(copy.suggestedDestination)||typeof copy.requiresUserConfirmation!=="boolean"||typeof copy.isAmbiguous!=="boolean"||typeof copy.capabilityStatus!=="string"||!T.AVAILABILITY_STATUS.includes(copy.capabilityStatus))return null;return {requestId:typeof copy.requestId==="string"?copy.requestId:"",primaryIntent:copy.primaryIntent,suggestedDestination:copy.suggestedDestination,requiresUserConfirmation:copy.requiresUserConfirmation,isAmbiguous:copy.isAmbiguous,capabilityStatus:copy.capabilityStatus};}
  function record(authoritative,shadow,codes,createdAt){const a=label(authoritative),s=label(shadow),differences=[...new Set(codes||[])],agreement=!a||!s?"NOT_COMPARABLE":differences.includes("PRIMARY_INTENT_DIFFERENT")?"MISMATCH":differences.length?"PARTIAL_MATCH":"MATCH";return V.freeze({schemaVersion:T.INTENT_SCHEMA_VERSION,requestId:(s&&s.requestId)||(a&&a.requestId)||"shadow-request",authoritative:a?{primaryIntent:a.primaryIntent,suggestedDestination:a.suggestedDestination,requiresUserConfirmation:a.requiresUserConfirmation,isAmbiguous:a.isAmbiguous,capabilityStatus:a.capabilityStatus}:null,shadow:s?{primaryIntent:s.primaryIntent,suggestedDestination:s.suggestedDestination,requiresUserConfirmation:s.requiresUserConfirmation,isAmbiguous:s.isAmbiguous,capabilityStatus:s.capabilityStatus}:null,agreement,differenceCodes:differences,safeSummary:agreement==="MATCH"?"Shadow outcome matches the supplied authoritative outcome.":agreement==="NOT_COMPARABLE"?"Comparison is unavailable without a valid supplied outcome.":"Shadow outcome differs from the supplied authoritative outcome.",createdAt:createdAt||"1970-01-01T00:00:00.000Z"});}
  function compareIntentOutcomes(authoritative,shadow){let a;let s;try{a=label(authoritative)}catch(error){a=null}try{s=label(shadow)}catch(error){s=null}if(!a)return record(null,s,["AUTHORITATIVE_RESULT_MISSING"],s&&s.createdAt);if(!s)return record(a,null,["SHADOW_RESULT_INVALID"],"1970-01-01T00:00:00.000Z");const codes=[];if(a.primaryIntent!==s.primaryIntent)codes.push("PRIMARY_INTENT_DIFFERENT");if(a.suggestedDestination!==s.suggestedDestination)codes.push("DESTINATION_DIFFERENT");if(a.requiresUserConfirmation!==s.requiresUserConfirmation)codes.push("CONFIRMATION_DIFFERENT");if(a.isAmbiguous!==s.isAmbiguous)codes.push("AMBIGUITY_DIFFERENT");if(a.capabilityStatus!==s.capabilityStatus)codes.push("CAPABILITY_STATUS_DIFFERENT");return record(a,s,codes,"1970-01-01T00:00:00.000Z");}
  function observeShadowIntent(input,options){let o;try{o=optionsOf(options);const shadow=C.classifyIntent(input,{clock:o.clock});return compareIntentOutcomes(o.authoritative,shadow)}catch(error){try{if(o&&typeof o.failureHandler==="function")o.failureHandler(Object.freeze({code:error&&error.code||"shadow_classification_failed"}));}catch(ignored){}return record(null,null,["SHADOW_RESULT_INVALID"],"1970-01-01T00:00:00.000Z");}}
  window.WeishanShadowIntentObserver=Object.freeze({observeShadowIntent,compareIntentOutcomes});
})();
